const guess = (q, a) => ({ q, a });

const EMOJI_GUESS_CATEGORIES = {
  movie_show_emoji: {
    label: "Movie or Show By Emoji",
    icon: "🎬",
    color: "#EF4444",
    isEmojiGuess: true,
    emojiPrompt: "Guess the movie or show from the emoji clue",
    200: [
      guess("🦁 👑 🌅", "The Lion King"),
      guess("❄️ 👭 👑", "Frozen"),
      guess("🕷️ 🧑 🏙️", "Spider-Man"),
      guess("🚢 💎 🌊", "Titanic"),
      guess("🤠 🚀 🧸", "Toy Story"),
      guess("🦖 🏝️ ⚡", "Jurassic Park"),
      guess("🧙 ⚡ 🦉", "Harry Potter"),
      guess("🦈 🏖️ 🌊", "Jaws"),
      guess("🐀 👨‍🍳 🍝", "Ratatouille"),
      guess("🐠 🔍 🌊", "Finding Nemo"),
      guess("👻 🚫 🚒", "Ghostbusters"),
      guess("🏹 🔥 🍞", "The Hunger Games"),
      guess("👬 ☕ 🛋️", "Friends"),
      guess("🏢 📎 😐", "The Office"),
      guess("👨‍🏫 🧪 💀", "Breaking Bad"),
      guess("👧 🧇 🔬", "Stranger Things"),
      guess("🦇 🌃 🃏", "Batman"),
      guess("🛡️ 🔨 🦸", "The Avengers"),
      guess("🚀 ⭐ ⚔️", "Star Wars"),
      guess("🧅 👹 👸", "Shrek"),
      guess("🏠 👦 🎄", "Home Alone"),
      guess("🚗 🏁 ⚡", "Cars"),
      guess("🌊 ⛵ 🌺", "Moana"),
      guess("🧽 🍍 🌊", "SpongeBob SquarePants"),
      guess("🧟‍♂️ 🏹 👮", "The Walking Dead"),
      guess("🐉 👑 🗡️", "Game of Thrones"),
      guess("⚡ 🏃 ⏱️", "The Flash"),
      guess("💊 🕶️ 🖥️", "The Matrix"),
      guess("🏴‍☠️ 🧭 🌊", "Pirates of the Caribbean"),
      guess("👨‍👩‍👧‍👦 🍩 🟡", "The Simpsons"),
    ],
    400: [
      guess("🏛️ ⚔️ 👑", "Gladiator"),
      guess("✈️ 😎 🎯", "Top Gun"),
      guess("🚗 ⚡ 🕒", "Back to the Future"),
      guess("🃏 🦇 🌃", "The Dark Knight"),
      guess("🌍 💙 🌿", "Avatar"),
      guess("🧜‍♀️ 🐚 🎤", "The Little Mermaid"),
      guess("🦸‍♂️ 👨‍👩‍👧‍👦 🔥", "The Incredibles"),
      guess("🐾 👑 ⚫", "Black Panther"),
      guess("🚀 🦝 🌌", "Guardians of the Galaxy"),
      guess("🐶 🔫 🕴️", "John Wick"),
      guess("🔪 🍩 🕵️", "Knives Out"),
      guess("🎰 🤵 🔫", "Casino Royale"),
      guess("🎩 🪄 ⚡", "The Prestige"),
      guess("🤖 🔥 🕶️", "Terminator 2: Judgment Day"),
      guess("🧱 🗺️ 🏃", "Prison Break"),
      guess("👨‍🔬 👨‍🔬 🛋️", "The Big Bang Theory"),
      guess("💼 ⚖️ 👔", "Suits"),
      guess("🩸 🔬 🌴", "Dexter"),
      guess("🪓 ⛵ 👑", "Vikings"),
      guess("👮 9️⃣9️⃣ 😎", "Brooklyn Nine-Nine"),
      guess("💍 🌋 🧝", "The Lord of the Rings"),
      guess("👶 🛸 🪖", "The Mandalorian"),
      guess("🚬 🧢 🔪", "Peaky Blinders"),
      guess("🕵️ 🎻 🔎", "Sherlock"),
      guess("✈️ 🏝️ ❓", "Lost"),
      guess("🏥 ❤️ 👩‍⚕️", "Grey's Anatomy"),
      guess("🦸‍♂️ 🧪 😈", "The Boys"),
      guess("👦 🦸 🩸", "Invincible"),
      guess("⚔️ 🐺 🧙", "The Witcher"),
      guess("🚀 🪐 ⌛", "Interstellar"),
    ],
    600: [
      guess("🥁 👨‍🏫 😤", "Whiplash"),
      guess("🏥 🏝️ 🧠", "Shutter Island"),
      guess("👦 👻 🤫", "The Sixth Sense"),
      guess("📺 🌍 🚪", "The Truman Show"),
      guess("🎹 🌃 💃", "La La Land"),
      guess("⛵ ✈️ 🔥", "Dunkirk"),
      guess("🪖 🏃 🌫️", "1917"),
      guess("🐻 ❄️ 🏹", "The Revenant"),
      guess("💍 📓 🕵️", "Gone Girl"),
      guess("🏎️ 🐎 🔧", "Ford v Ferrari"),
      guess("🧠 🔐 💻", "The Imitation Game"),
      guess("⛏️ 🌧️ 🧱", "The Shawshank Redemption"),
      guess("🚚 🔥 🏜️", "Mad Max: Fury Road"),
      guess("⏱️ 👽 🔁", "Edge of Tomorrow"),
      guess("🩰 🦢 🩸", "Black Swan"),
      guess("💼 🌵 🔫", "No Country for Old Men"),
      guess("🤖 🌆 🦄", "Blade Runner 2049"),
      guess("🏨 🧳 🍰", "The Grand Budapest Hotel"),
      guess("⚖️ 📞 💼", "Better Call Saul"),
      guess("👨‍⚕️ 🩼 🏥", "House"),
      guess("🤖 🤠 🎢", "Westworld"),
      guess("📱 📺 ⚫", "Black Mirror"),
      guess("🍝 🦆 👔", "The Sopranos"),
      guess("👨‍🍳 🐻 🍽️", "The Bear"),
      guess("🧠 🕵️ 🔪", "Mindhunter"),
      guess("👨‍👦 💼 💰", "Succession"),
      guess("🐉 🔥 👑", "House of the Dragon"),
      guess("🍄 🌎 👧", "The Last of Us"),
      guess("🌴 🏨 💀", "The White Lotus"),
      guess("🌵 🪱 👑", "Dune"),
    ],
  },
  country_emoji: {
    label: "Country By Emoji",
    icon: "🌍",
    color: "#10B981",
    isEmojiGuess: true,
    emojiPrompt: "Guess the country from the emoji clue",
    200: [
      guess("🍁 🏒 🧊", "Canada"),
      guess("🦅 🗽 🍔", "United States"),
      guess("🌮 🌵 🎸", "Mexico"),
      guess("⚽ 🎉 🌴", "Brazil"),
      guess("🥩 ⚽ 💃", "Argentina"),
      guess("🗼 🥖 🧀", "France"),
      guess("🍕 🍝 🏛️", "Italy"),
      guess("🍺 🥨 🚗", "Germany"),
      guess("💃 🐂 ☀️", "Spain"),
      guess("👑 ☕ 🌧️", "United Kingdom"),
      guess("☘️ 🍺 🎻", "Ireland"),
      guess("🦘 🏄 ☀️", "Australia"),
      guess("🥝 🐑 🏉", "New Zealand"),
      guess("🍣 🗻 🌸", "Japan"),
      guess("🐉 🥢 🏯", "China"),
      guess("🕌 🍛 🪷", "India"),
      guess("📱 🎤 💄", "South Korea"),
      guess("🐪 🔺 ☀️", "Egypt"),
      guess("🏛️ 🏺 🌊", "Greece"),
      guess("🕌 🐪 🛢️", "Saudi Arabia"),
      guess("🏙️ 🏎️ 🛍️", "United Arab Emirates"),
      guess("🦁 🏉 🌈", "South Africa"),
      guess("🦁 🏃 🦒", "Kenya"),
      guess("🎶 🛢️ 🌍", "Nigeria"),
      guess("🧿 🐪 🫖", "Morocco"),
      guess("🏖️ 🥊 🐘", "Thailand"),
      guess("🪑 🎵 ❄️", "Sweden"),
      guess("⛷️ ❄️ 🌊", "Norway"),
      guess("⚽ 🍷 🌊", "Portugal"),
      guess("🐻 ❄️ ⛪", "Russia"),
    ],
    400: [
      guess("🧀 ⌚ ⛰️", "Switzerland"),
      guess("🎻 ☕ ⛰️", "Austria"),
      guess("🚲 🌷 🌬️", "Netherlands"),
      guess("🍫 🍟 🧇", "Belgium"),
      guess("🥟 🏰 🎻", "Poland"),
      guess("🍺 🏰 🌉", "Czechia"),
      guess("🌶️ 🛁 🎻", "Hungary"),
      guess("🧛 ⛰️ 🏰", "Romania"),
      guess("📱 🌲 ❄️", "Finland"),
      guess("🧜‍♀️ 🚲 👑", "Denmark"),
      guess("🌋 ♨️ ❄️", "Iceland"),
      guess("✡️ 🥙 🌊", "Israel"),
      guess("🏔️ 🏏 🍛", "Pakistan"),
      guess("🧵 🌊 👕", "Bangladesh"),
      guess("🌋 🏝️ 🐉", "Indonesia"),
      guess("🛵 🍜 🌾", "Vietnam"),
      guess("🏝️ 🎤 🥭", "Philippines"),
      guess("🏙️ 🌴 🛕", "Malaysia"),
      guess("🦁 🏙️ 💰", "Singapore"),
      guess("☕ ⛰️ 💃", "Colombia"),
      guess("🌶️ 🏔️ 🌊", "Chile"),
      guess("🦙 🏔️ 🥔", "Peru"),
      guess("✈️ 🏟️ 🐪", "Qatar"),
      guess("☕ 🏃 ⛰️", "Ethiopia"),
      guess("🦓 🐘 🌋", "Tanzania"),
      guess("🌴 🎶 🏃", "Jamaica"),
      guess("🚬 🚗 🎺", "Cuba"),
      guess("⚽ 🌊 🏰", "Croatia"),
      guess("🎾 🏀 🏰", "Serbia"),
      guess("🏞️ ⛰️ 🚣", "Slovenia"),
    ],
    600: [
      guess("🐉 ⛰️ 🙏", "Bhutan"),
      guess("🏔️ 🥾 🛕", "Nepal"),
      guess("🦁 🍵 🏝️", "Sri Lanka"),
      guess("🐎 🏹 ⛰️", "Mongolia"),
      guess("🕌 🍉 ☀️", "Uzbekistan"),
      guess("⛰️ 🏇 🦅", "Kyrgyzstan"),
      guess("🏀 🌲 🌊", "Lithuania"),
      guess("🌲 🏒 🌊", "Latvia"),
      guess("💻 🌲 ❄️", "Estonia"),
      guess("⛰️ 🏰 🚗", "Slovakia"),
      guess("🌲 🧆 🌊", "Lebanon"),
      guess("🏜️ 🧿 🏛️", "Jordan"),
      guess("🏜️ ⛵ 🕌", "Oman"),
      guess("🏎️ 🏝️ 🛢️", "Bahrain"),
      guess("🏙️ 🛢️ 🌊", "Kuwait"),
      guess("🏔️ 🦙 🧂", "Bolivia"),
      guess("⚽ 🌿 ☀️", "Paraguay"),
      guess("⚽ 🌿 🌊", "Uruguay"),
      guess("🌋 🐢 🍌", "Ecuador"),
      guess("⚾ 🏝️ 🎶", "Dominican Republic"),
      guess("🏜️ 🦊 🕌", "Algeria"),
      guess("🏛️ 🏖️ 🌶️", "Tunisia"),
      guess("💎 🦓 ☀️", "Botswana"),
      guess("🦎 🌴 🐒", "Madagascar"),
      guess("🏝️ 🐠 ☀️", "Maldives"),
      guess("🏰 ⛵ ☀️", "Malta"),
      guess("💶 🏰 🌲", "Luxembourg"),
      guess("👑 ⛰️ 🏦", "Liechtenstein"),
      guess("🍷 ⛰️ 🥟", "Georgia"),
      guess("🚀 🐎 ⛰️", "Kazakhstan"),
    ],
  },
  general_emoji: {
    label: "General Stuff By Emoji",
    icon: "🧩",
    color: "#8B5CF6",
    isEmojiGuess: true,
    emojiPrompt: "Guess the item or phrase from the emoji clue",
    200: [
      guess("🎈 ☁️", "Hot air balloon"),
      guess("🎂 🎉", "Birthday party"),
      guess("📽️ 🍿", "Movie theater"),
      guess("🗺️ 💰 📦", "Treasure chest"),
      guess("🔥 🪵", "Campfire"),
      guess("🧳 📘", "Passport"),
      guess("🌞 🌚", "Solar eclipse"),
      guess("🎤 📰", "News reporter"),
      guess("🧠 ❄️", "Brain freeze"),
      guess("☕ ⏸️", "Coffee break"),
      guess("🚗 🛣️", "Road trip"),
      guess("📱 🎥 👋", "Video call"),
      guess("🌙 🦉", "Night owl"),
      guess("📚 🪱", "Bookworm"),
      guess("❄️ 🌍", "Snow globe"),
      guess("🌊 💡 🏠", "Lighthouse"),
      guess("👨‍👩‍👧‍👦 ✈️ 🏖️", "Family vacation"),
      guess("🏦 🔫", "Bank robbery"),
      guess("🏗️ 👷", "Construction worker"),
      guess("🐠 🤿", "Scuba diving"),
      guess("🧪 ⚗️ 👨‍🔬", "Science experiment"),
      guess("🧠 ⛈️", "Brainstorm"),
      guess("🏖️ 🏰", "Sandcastle"),
      guess("🚗 🔧", "Car mechanic"),
      guess("💌 📬", "Mailbox"),
    ],
    400: [
      guess("🚗 🚗 🚗 ⛔", "Traffic jam"),
      guess("💡 ❌", "Power outage"),
      guess("🌦️ 📱", "Weather forecast"),
      guess("🏔️ 🧗", "Mountain climber"),
      guess("🎤 😰", "Stage fright"),
      guess("🛋️ 🥔", "Couch potato"),
      guess("🎓 🎤 📊", "Class presentation"),
      guess("🧳 🛂 ✈️", "Airport security"),
      guess("⛺ 🌧️ 😩", "Camping disaster"),
      guess("🪂 🌬️", "Parachuting"),
      guess("🎧 🎶 🔊", "Noise-canceling headphones"),
      guess("🍔 🚗 🪟", "Drive-thru"),
      guess("📸 🤳 👥", "Group selfie"),
      guess("🎮 😡", "Rage quit"),
      guess("🛒 🧾", "Grocery shopping"),
      guess("🕵️ 🧩", "Private investigator"),
      guess("🧑‍🍳 🔥 😱", "Kitchen fire"),
      guess("💍 💒", "Wedding ceremony"),
      guess("🏊 ⏱️", "Swimming race"),
      guess("🏃 🏅 🏁", "Marathon"),
      guess("🎤 🕺 💃", "Dance battle"),
      guess("📦 🚚 🏠", "House move"),
      guess("🐶 🦴 🐕‍🦺", "Dog training"),
      guess("🛏️ ⏰ 😴", "Oversleeping"),
      guess("🎁 🎄", "Christmas present"),
      guess("🧼 🫧 🚗", "Car wash"),
      guess("💳 🛍️ 🧾", "Online shopping"),
      guess("🔒 📱 😬", "Forgot phone password"),
      guess("🧽 🍽️", "Doing the dishes"),
      guess("☔ 🌬️ 😖", "Umbrella in the wind"),
    ],
    600: [
      guess("🧊 🤝", "Break the ice"),
      guess("🍵 🫗", "Spill the tea"),
      guess("☁️ 9️⃣", "On cloud nine"),
      guess("🔵 🌙", "Once in a blue moon"),
      guess("🎂 🥄", "Piece of cake"),
      guess("🚪 🛣️", "Hit the road"),
      guess("🐘 🏠", "The elephant in the room"),
      guess("🌧️ 🐈 🐕", "Raining cats and dogs"),
      guess("🧺 🥚", "Don't put all your eggs in one basket"),
      guess("🪡 🌾", "Needle in a haystack"),
      guess("🪑 🪑 🪑", "Musical chairs"),
      guess("🪞 😈", "Face your demons"),
      guess("🌙 🛢️ 🔥", "Burning the midnight oil"),
      guess("🧊 🌦️", "Under the weather"),
      guess("🐕 🌳 ❌", "Bark up the wrong tree"),
      guess("🏳️ 🧻", "Throw in the towel"),
      guess("🧍 🪵", "Sitting on the fence"),
      guess("🐦 🪨 2️⃣", "Kill two birds with one stone"),
      guess("🍎 👁️", "Apple of my eye"),
      guess("📖 ❤️", "Open book"),
      guess("🥶 👤", "Cold shoulder"),
      guess("🦴 🐶", "Bone to pick"),
      guess("🧵 💭", "Train of thought"),
      guess("🌪️ ☕", "Storm in a teacup"),
      guess("💀 🚪", "Skeleton in the closet"),
      guess("🐴 🚫", "Hold your horses"),
      guess("🧱 🪨", "Between a rock and a hard place"),
      guess("🥤 1️⃣", "The last straw"),
      guess("🐈 🎒 🚪", "Let the cat out of the bag"),
      guess("⛽ 🔥", "Add fuel to the fire"),
    ],
  },
};

export default EMOJI_GUESS_CATEGORIES;
