const guess = (q, a) => ({ q, a });

// All rebus answers read LEFT-TO-RIGHT: first emoji's sound + second emoji's sound.
const EMOJI_GUESS_CATEGORIES = {
general_emoji: {
    label: "General By Emoji",
    icon: "🧩",
    color: "#8B5CF6",
    isEmojiGuess: true,
    emojiPrompt: "",
    200: [
      guess("🔑 🪨", "Keystone"),
      guess("☀️ 🌸", "Sunflower"),
      guess("🧈 🪰", "Butterfly"),
      guess("❄️ 👨", "Snowman"),
      guess("🌙 🚶", "Moonwalk"),
      guess("🍯 🌙", "Honeymoon"),
      guess("💡 🏠", "Lighthouse"),
      guess("🐱 🐟", "Catfish"),
      guess("🐕 🏠", "Doghouse"),
      guess("🐦 🏠", "Birdhouse"),
      guess("☀️ 🕶️", "Sunglasses"),
      guess("☀️ 🌅", "Sunset"),
      guess("❄️ ⚽", "Snowball"),
      guess("🔥 🪰", "Firefly"),
      guess("🔥 👨", "Fireman"),
      guess("🎂 🚶", "Cakewalk"),
      guess("🌽 🍞", "Cornbread"),
      guess("🐮 👦", "Cowboy"),
      guess("🐴 👞", "Horseshoe"),
      guess("🐴 ⚡", "Horsepower"),
      guess("🧠 🌊", "Brainwave"),
      guess("👁️ ⚽", "Eyeball"),
      guess("🔦 💡", "Flashlight"),
      guess("🍳 🎂", "Pancake"),
      guess("🔙 🦴", "Backbone"),
      guess("🧠 📦", "Brainbox"),
      guess("🐕 🪵", "Dogwood"),
      guess("🔔 💐", "Bellflower"),
      guess("🌧️ 🎀", "Rainbow"),
      guess("🌧️ 💧", "Raindrop"),
    ],
    400: [
      guess("🐝 🕳️", "Beehive"),
      guess("🌊 🐎", "Seahorse"),
      guess("🗡️ 🐟", "Swordfish"),
      guess("⭐ 🐠", "Starfish"),
      guess("🪰 🎣", "Flytrap"),
      guess("🧱 🏠", "Brickhouse"),
      guess("🚪 🛎️", "Doorbell"),
      guess("✉️ 📦", "Mailbox"),
      guess("🐌 📬", "Snail mail"),
      guess("🌱 🐰", "Grasshopper"),
      guess("🪵 🔨", "Woodwork"),
      guess("🐦 👁️", "Birdseye"),
      guess("👑 🐝", "Queen bee"),
      guess("🐟 🪝", "Fishhook"),
      guess("🔑 🕳️", "Keyhole"),
      guess("🎓 🎒", "Schoolbag"),
      guess("🦷 🖌️", "Toothbrush"),
      guess("🌽 🌾", "Cornfield"),
      guess("☕ 🏠", "Coffeehouse"),
      guess("🐕 🐟", "Dogfish"),
      guess("🍎 🥧", "Apple Pie"),
      guess("🧊 🍦", "Ice Cream"),
      guess("🐴 🎀", "Horsebow"),
      guess("🧠 🌩️", "Brainstorm"),
      guess("🔥 👨", "Fireman"),
      guess("🌞 🌕", "Sunmoon"),
      guess("🌊 🐠", "Seafish"),
      guess("🪵 🏠", "Woodhouse"),
      guess("🐦 🎵", "Birdsong"),
      guess("🧊 🧊", "Iceberg"),
    ],
    600: [
      guess("🔑 📝", "Keynote"),
      guess("🕯️ 💡", "Candlelight"),
      guess("⛵ 👨", "Sailor"),
      guess("🪵 🪓", "Woodchop"),
      guess("🪵 🚶", "Boardwalk"),
      guess("🦷 🧚", "Tooth fairy"),
      guess("🐖 🏦", "Piggy bank"),
      guess("🌊 🪵", "Driftwood"),
      guess("🌊 👁️", "Seaside"),
      guess("🐢 🦢", "Turtleneck"),
      guess("🐴 🍎", "Horse apple"),
      guess("🔔 🏠", "Bellhouse"),
      guess("🕷️ 🕸️", "Spiderweb"),
      guess("🦊 🕳️", "Foxhole"),
      guess("🔙 🚪", "Backdoor"),
      guess("🔙 🛝", "Backslide"),
      guess("🐟 👑", "Kingfish"),
      guess("🪶 💡", "Featherlight"),
      guess("🌾 🔥", "Hayfire"),
      guess("🥜 🧠", "Nuthead"),
      guess("🌊 🎺", "Seahorn"),
      guess("🌲 🏠", "Treehouse"),
      guess("🌞 🌻", "Sunflower"),
      guess("🪵 🐛", "Wormwood"),
      guess("🌊 🌊", "Seasea"),
      guess("🐦 🏡", "Birdhome"),
      guess("🏠 🐱", "Housecat"),
      guess("🥛 🧔", "Milkman"),
      guess("🌲 🔥", "Wildfire"),
      guess("🌧️ 💦", "Rainfall"),
    ],
  },
};

export default EMOJI_GUESS_CATEGORIES;
