const logo = (rows) => rows.map(([q, a]) => ({ q, a }));

const LOGO_CATEGORIES_BANK = {
  logos: {
    label: "Logos",
    icon: "\u{1F3AF}",
    color: "#F59E0B",
    isLogoGuess: true,
    200: logo([["apple","Apple"],["google","Google"],["youtube","YouTube"],["instagram","Instagram"],["tiktok","TikTok"],["whatsapp","WhatsApp"],["facebook","Facebook"],["netflix","Netflix"],["spotify","Spotify"],["nike","Nike"],["adidas","Adidas"],["mcdonald-s","McDonald's"],["x","X"],["snapchat","Snapchat"],["playstation","PlayStation"],["tesla","Tesla"],["ferrari","Ferrari"],["airbnb","Airbnb"],["discord","Discord"],["twitch","Twitch"],["reddit","Reddit"],["pinterest","Pinterest"],["paypal","PayPal"],["github","GitHub"],["dropbox","Dropbox"],["telegram","Telegram"],["firefox","Firefox"],["android","Android"],["steam","Steam"],["roblox","Roblox"],["fortnite","Fortnite"],["mitsubishi","Mitsubishi"],["chevrolet","Chevrolet"],["puma","Puma"],["jordan","Jordan"],["nba","NBA"],["mlb","MLB"],["wwe","WWE"],["tumblr","Tumblr"],["threads","Threads"],["bluesky","Bluesky"],["opera","Opera"],["valorant","Valorant"],["unity","Unity"],["mongodb","MongoDB"],["square-enix","Square Enix"],["shazam","Shazam"],["pandora","Pandora"],["crunchyroll","Crunchyroll"],["vimeo","Vimeo"],["under-armour","Under Armour"],["polestar","Polestar"],["renault","Renault"],["suzuki","Suzuki"],["riot-games","Riot Games"],["rockstar-games","Rockstar Games"]]),
    400: logo([["unreal-engine","Unreal Engine"],["flutter","Flutter"],["kotlin","Kotlin"],["blender","Blender"],["stripe","Stripe"],["webflow","Webflow"],["framer","Framer"],["kirby","Kirby"],["british-airways","British Airways"],["lufthansa","Lufthansa"],["turkish-airlines","Turkish Airlines"],["qantas","Qantas"],["singapore-airlines","Singapore Airlines"],["american-airlines","American Airlines"],["southwest-airlines","Southwest Airlines"],["air-france","Air France"],["air-china","Air China"],["air-india","Air India"],["airasia","AirAsia"],["iberia","Iberia"],["ethiopian-airlines","Ethiopian Airlines"],["air-transat","Air Transat"],["s7-airlines","S7 Airlines"],["cbs","CBS"],["rotten-tomatoes","Rotten Tomatoes"],["letterboxd","Letterboxd"],["metacritic","Metacritic"],["genius","Genius"],["myanimelist","MyAnimeList"],["deviantart","DeviantArt"],["artstation","ArtStation"],["fandom","Fandom"],["fandango","Fandango"],["substack","Substack"],["patreon","Patreon"],["kickstarter","Kickstarter"],["premier-league","Premier League"],["rumble","Rumble"],["kick","Kick"],["wattpad","Wattpad"],["bandcamp","Bandcamp"],["product-hunt","Product Hunt"],["quora","Quora"],["glassdoor","Glassdoor"],["battle-net","Battle.net"],["confluence","Confluence"],["jira","Jira"],["trello","Trello"],["asana","Asana"],["bitbucket","Bitbucket"],["gitlab","GitLab"],["atlassian","Atlassian"],["bitwarden","Bitwarden"],["1password","1Password"],["proton","Proton"],["expressvpn","ExpressVPN"]]),
    600: logo([["nordvpn","NordVPN"],["vivaldi","Vivaldi"],["arch-linux","Arch Linux"],["fedora","Fedora"],["red-hat","Red Hat"],["hashicorp","HashiCorp"],["ansible","Ansible"],["cloudflare","Cloudflare"],["vercel","Vercel"],["digitalocean","DigitalOcean"],["supabase","Supabase"],["planetscale","PlanetScale"],["neo4j","Neo4j"],["redis","Redis"],["rabbitmq","RabbitMQ"],["deno","Deno"],["vite","Vite"],["eslint","ESLint"],["next-js","Next.js"],["vue-js","Vue.js"],["tensorflow","TensorFlow"],["pytorch","PyTorch"],["bitly","Bitly"],["linktree","Linktree"],["hubspot","HubSpot"],["clickup","ClickUp"],["miro","Miro"],["loom","Loom"],["todoist","Todoist"],["hotjar","Hotjar"],["okta","Okta"],["render","Render"],["storybook","Storybook"],["spring","Spring"],["flask","Flask"],["ionic","Ionic"],["ifood","iFood"],["deliveroo","Deliveroo"],["doordash","DoorDash"],["swiggy","Swiggy"],["surveymonkey","SurveyMonkey"],["unsplash","Unsplash"],["pexels","Pexels"],["pixiv","pixiv"],["flickr","Flickr"],["giphy","GIPHY"],["buffer","Buffer"],["mastodon","Mastodon"],["strava","Strava"],["upwork","Upwork"],["toptal","Toptal"],["humble-bundle","Humble Bundle"],["infiniti","INFINITI"],["tidal","TIDAL"],["anilist","AniList"]]),
  },
};

export default LOGO_CATEGORIES_BANK;
