// Massive question expansion — adds questions to ALL categories across all tiers.
const qa = (rows) => rows.map(([q, a]) => ({ q, a }));

const MEGA_NEW_EXPANSIONS = {
  general: {
    200: qa([
      ["How many letters are in the English alphabet?","26"],
      ["What gas do plants absorb from the atmosphere?","Carbon dioxide"],
      ["What is the freezing point of water in Fahrenheit?","32°F"],
      ["What shape has 8 sides?","Octagon"],
      ["What is the closest star to Earth?","The Sun"],
      ["What is the largest desert on Earth?","Sahara (or Antarctic)"],
      ["What metal is liquid at room temperature?","Mercury"],
      ["What is the speed of light roughly in km/s?","300,000 km/s"],
    ]),
    400: qa([
      ["What is the longest river in the world?","Nile (or Amazon, disputed)"],
      ["What planet has the most moons?","Saturn"],
      ["Who wrote 'To Kill a Mockingbird'?","Harper Lee"],
      ["What blood type is the universal donor?","O negative"],
      ["What is the main ingredient in guacamole?","Avocado"],
      ["What is the largest lake in the world by surface area?","Caspian Sea"],
      ["What vitamin does the sun provide?","Vitamin D"],
      ["What instrument measures earthquakes?","Seismograph"],
      ["What is the national animal of Scotland?","Unicorn"],
    ]),
    600: qa([
      ["What is the Fibonacci sequence's next number after 0,1,1,2,3,5,8?","13"],
      ["What element has the atomic number 79?","Gold"],
      ["What ancient wonder was located in Alexandria?","Lighthouse of Alexandria"],
      ["Who discovered the structure of DNA with Watson?","Francis Crick"],
      ["What is the deepest point in the ocean?","Mariana Trench"],
      ["What language has the most native speakers?","Mandarin Chinese"],
      ["What is the largest known prime number category called?","Mersenne primes"],
      ["What bone is the longest in the human body?","Femur"],
      ["What country has the most time zones?","France (12)"],
      ["What is the rarest blood type?","AB negative"],
      ["What is the only continent without a desert?","Europe"],
      ["What is the youngest country in the world (as of 2024)?","South Sudan (2011)"],
    ]),
  },

  geography: {
    200: qa([
      ["What ocean lies between Africa and Australia?","Indian Ocean"],
      ["What river runs through Paris?","Seine"],
      ["What country has the shape of a boot?","Italy"],
      ["What desert is the largest hot desert?","Sahara"],
      ["What strait separates Asia from North America?","Bering Strait"],
      ["What is the longest wall in the world?","Great Wall of China"],
    ]),
    400: qa([
      ["What is the driest continent on Earth?","Antarctica"],
      ["What African country was formerly called Rhodesia?","Zimbabwe"],
      ["What is the deepest lake in the world?","Lake Baikal"],
      ["What European capital stands on the Danube?","Budapest (or Vienna)"],
      ["What is the tallest waterfall in the world?","Angel Falls"],
      ["What is the only country that spans four hemispheres?","Kiribati"],
      ["What is the capital of New Zealand?","Wellington"],
      ["What canal connects the Atlantic and Pacific?","Panama Canal"],
      ["What river is the longest in Europe?","Volga"],
      ["What is the largest island in the world?","Greenland"],
    ]),
    600: qa([
      ["What is the highest capital city in the world?","La Paz, Bolivia"],
      ["What is the narrowest country in the world?","Chile"],
      ["What two countries share the longest border?","Canada and the United States"],
      ["What is the largest landlocked country?","Kazakhstan"],
      ["What European country has the most volcanoes?","Iceland"],
      ["What is the most remote inhabited island?","Tristan da Cunha"],
      ["What river forms the border between Texas and Mexico?","Rio Grande"],
      ["What is the oldest continuously inhabited city?","Damascus"],
      ["What country contains the majority of Lake Victoria?","Tanzania"],
      ["What is the southernmost capital city in the world?","Wellington, New Zealand"],
      ["What is the only country that borders both France and the UK?","None (Channel Tunnel connects, no land border)"],
      ["What is the second-longest river in Africa?","Congo River"],
    ]),
  },

  science: {
    200: qa([
      ["What gas makes up most of Earth's atmosphere?","Nitrogen"],
      ["How many colors are in a rainbow?","7"],
      ["What is H2O commonly known as?","Water"],
      ["What part of the body pumps blood?","Heart"],
      ["What is the chemical formula for table salt?","NaCl"],
      ["What is the hottest planet in our solar system?","Venus"],
      ["Do sound waves travel faster in air or water?","Water"],
      ["What type of animal is a frog?","Amphibian"],
      ["What organ is protected by the skull?","Brain"],
      ["What is the center of an atom called?","Nucleus"],
      ["What vitamin do oranges provide?","Vitamin C"],
      ["What is the study of stars called?","Astronomy"],
    ]),
    400: qa([
      ["What is the pH of pure water?","7"],
      ["What particle has a negative charge?","Electron"],
      ["What is Newton's first law also known as?","Law of Inertia"],
      ["What gas do humans exhale?","Carbon dioxide"],
      ["How long does light from the Sun take to reach Earth?","About 8 minutes"],
      ["What is the chemical symbol for sodium?","Na"],
      ["What is the hardest mineral on the Mohs scale?","Diamond (10)"],
      ["What type of rock is formed by cooling lava?","Ignite (volcanic/igneous) rock"],
      ["What is the process of water turning to vapor?","Evaporation"],
      ["What metal is the best conductor of electricity?","Silver"],
      ["What is the most abundant element in the universe?","Hydrogen"],
      ["What is the name of the galaxy we live in?","Milky Way"],
      ["What organ filters blood in the human body?","Kidney"],
      ["What scientist proposed the three laws of motion?","Isaac Newton"],
    ]),
    600: qa([
      ["What is Schrödinger's cat used to illustrate?","Quantum superposition"],
      ["What is the speed of sound in air at sea level?","343 m/s (about 767 mph)"],
      ["What force holds the nucleus of an atom together?","Strong nuclear force"],
      ["What is the Chandrasekhar limit?","1.4 solar masses (max mass for a white dwarf)"],
      ["What is the Heisenberg Uncertainty Principle?","You cannot simultaneously know exact position and momentum of a particle"],
      ["What is the Doppler effect?","Change in frequency of waves relative to a moving observer"],
      ["What is the Krebs cycle?","A series of chemical reactions in cellular respiration"],
      ["What is Avogadro's number?","6.022 × 10²³"],
      ["What does CRISPR stand for?","Clustered Regularly Interspaced Short Palindromic Repeats"],
      ["What is the wave-particle duality?","Light and matter exhibit both wave and particle properties"],
      ["What is dark energy?","A mysterious force causing the universe's accelerating expansion"],
      ["What is the Oort Cloud?","A theoretical shell of icy objects surrounding the solar system"],
      ["What is the difference between fission and fusion?","Fission splits atoms; fusion combines them"],
      ["What is entropy in thermodynamics?","A measure of disorder in a system"],
    ]),
  },

  history: {
    200: qa([
      ["What country gifted the Statue of Liberty to the US?","France"],
      ["What empire was ruled by Julius Caesar?","Roman Empire"],
      ["Who discovered America in 1492?","Christopher Columbus"],
      ["What document begins with 'We the People'?","The U.S. Constitution"],
      ["What was the name of the ship the Pilgrims sailed on?","Mayflower"],
      ["Who was known as the Iron Lady?","Margaret Thatcher"],
      ["What war was fought between the North and South in the US?","Civil War"],
      ["What was the Cold War primarily between?","USA and USSR"],
      ["Who founded the first major Chinese dynasty?","Qin Shi Huang"],
    ]),
    400: qa([
      ["Who was the longest-reigning British monarch?","Elizabeth II"],
      ["What treaty ended World War I?","Treaty of Versailles"],
      ["Who was assassinated in Sarajevo in 1914, sparking WWI?","Archduke Franz Ferdinand"],
      ["What empire was Genghis Khan the founder of?","Mongol Empire"],
      ["What event began on D-Day, June 6, 1944?","Allied invasion of Normandy"],
      ["What was the Manhattan Project?","Development of the atomic bomb"],
      ["Who led the Soviet Union during the Cuban Missile Crisis?","Nikita Khrushchev"],
      ["What was the Renaissance?","A cultural rebirth in Europe from the 14th-17th century"],
      ["What was the Spanish Armada?","A fleet sent by Spain to invade England in 1588"],
      ["What city was the capital of the Byzantine Empire?","Constantinople"],
      ["Who was the first female Prime Minister of the UK?","Margaret Thatcher"],
      ["What revolution began in Russia in 1917?","Bolshevik Revolution"],
    ]),
    600: qa([
      ["Who was the Sun King of France?","Louis XIV"],
      ["What was the Taiping Rebellion?","A massive civil war in China (1850-1864)"],
      ["What was the Congress of Vienna?","1814-1815 conference to reorganize Europe after Napoleon"],
      ["Who was Saladin?","Muslim leader who recaptured Jerusalem from the Crusaders"],
      ["What was the Meiji Restoration?","1868 political revolution modernizing Japan"],
      ["What was the Scramble for Africa?","European colonization of Africa in the late 1800s"],
      ["What was the Dreyfus Affair?","A French political scandal involving anti-Semitism (1894)"],
      ["Who was Hatshepsut?","One of the few female pharaohs of Egypt"],
      ["What was the War of the Roses?","English civil wars between House of Lancaster and York (1455-1487)"],
      ["What year did Constantinople fall to the Ottomans?","1453"],
      ["Who led the Haitian Revolution?","Toussaint Louverture"],
      ["What was the Boxer Rebellion?","Anti-foreign uprising in China (1899-1901)"],
      ["Who founded the Ottoman Empire?","Osman I"],
      ["What was the significance of the Battle of Tours (732)?","Charles Martel halted Muslim expansion into Europe"],
    ]),
  },

  sports: {
    200: qa([
      ["What color is the middle ring of the Olympic flag?","Black"],
      ["What is the highest score in a single frame of bowling?","30 (strike in 10th frame)"],
      ["How long is a marathon in miles?","26.2 miles"],
      ["How many sets are played in a typical tennis match (men's Grand Slam)?","5"],
      ["What color card means ejection in soccer?","Red"],
      ["What sport does LeBron James play?","Basketball"],
    ]),
    400: qa([
      ["What country has won the most FIFA World Cups?","Brazil (5)"],
      ["Who holds the record for most Olympic gold medals?","Michael Phelps (23)"],
      ["What country invented cricket?","England"],
      ["How many Grand Slam tennis tournaments are there per year?","4"],
      ["What is the only country to have played in every FIFA World Cup?","Brazil"],
      ["What boxing weight class is the heaviest?","Heavyweight"],
      ["How many periods in an NHL hockey game?","3"],
      ["What is the length of an Olympic swimming pool in meters?","50 meters"],
      ["Who has won the most Tour de France titles?","Lance Armstrong was stripped; record: 5 by several riders"],
      ["What is the national sport of Canada?","Lacrosse (summer) / Ice hockey (winter)"],
      ["What city hosted the first modern Olympics?","Athens (1896)"],
      ["What is the highest governing body of world football?","FIFA"],
    ]),
    600: qa([
      ["What country won the first FIFA World Cup in 1930?","Uruguay"],
      ["What is the fastest recorded tennis serve speed?","Over 163 mph (John Isner)"],
      ["What is the Ryder Cup a competition in?","Golf"],
      ["What is the only team sport played on horseback at the Olympics?","Polo (historically; modern: equestrian)"],
      ["What year were women first allowed to compete in the Olympics?","1900 (Paris)"],
      ["What is a perfect game in baseball?","No batter reaches base for the entire game (27 up, 27 down)"],
      ["Who holds the record for most goals in FIFA World Cup history?","Miroslav Klose (16)"],
      ["What is the oldest Grand Slam tennis tournament?","Wimbledon (1877)"],
      ["What country dominates table tennis at the Olympics?","China"],
      ["What is the decathlon?","A 10-event track and field competition"],
      ["Who was the first African nation to reach a World Cup semifinal?","Morocco (2022)"],
      ["What is the name of New Zealand's rugby team?","All Blacks"],
      ["What martial art became an Olympic sport in 2020?","Karate"],
      ["What is the highest altitude at which a FIFA World Cup qualifier has been played?","La Paz, Bolivia (~3,600m)"],
    ]),
  },

  music: {
    200: qa([
      ["Who sang 'Bohemian Rhapsody'?","Queen / Freddie Mercury"],
      ["Who is known as the 'King of Rock and Roll'?","Elvis Presley"],
      ["What genre of music originated in Jamaica?","Reggae"],
      ["What boy band released 'Bye Bye Bye'?","NSYNC"],
      ["What instrument is Jimi Hendrix famous for?","Electric guitar"],
      ["What singer is called 'Queen Bey'?","Beyoncé"],
      ["How many strings does a standard violin have?","4"],
      ["What female artist sang 'Like a Virgin'?","Madonna"],
      ["What genre did Elvis help popularize?","Rock and roll"],
      ["What country is K-pop from?","South Korea"],
      ["Who is the lead vocalist of Maroon 5?","Adam Levine"],
    ]),
    400: qa([
      ["Who wrote the opera 'The Marriage of Figaro'?","Mozart"],
      ["What band was Mick Jagger the lead singer of?","The Rolling Stones"],
      ["What genre combines rock and electronic music?","Electronic rock (or synth-rock)"],
      ["What year did Elvis Presley die?","1977"],
      ["What genre did Bob Marley popularize worldwide?","Reggae"],
      ["Who is the best-selling female artist of all time?","Madonna"],
      ["What instrument does Kenny G play?","Soprano saxophone"],
      ["What was The Beatles' first #1 hit in the US?","I Want to Hold Your Hand"],
      ["What DJ is known as 'the king of EDM'?","Tiësto (or David Guetta)"],
      ["What is Kanye West's first album called?","The College Dropout"],
      ["Who composed 'Moonlight Sonata'?","Beethoven"],
    ]),
    600: qa([
      ["What is a capella singing?","Singing without instrumental accompaniment"],
      ["What is syncopation in music?","Placing emphasis on normally unaccented beats"],
      ["Who composed 'Rite of Spring'?","Igor Stravinsky"],
      ["What key has no sharps or flats?","C major (or A minor)"],
      ["What is the lowest female voice type?","Contralto"],
      ["Who is considered the father of hip-hop?","DJ Kool Herc"],
      ["What is a tritone also known as?","The devil's interval"],
      ["What jazz musician was known as 'Bird'?","Charlie Parker"],
      ["What does 'fortissimo' mean in music?","Very loud"],
      ["What scale is used in most blues music?","Pentatonic blues scale"],
      ["Who composed 'The Planets' orchestral suite?","Gustav Holst"],
      ["What is the circle of fifths used for?","Showing relationships between keys"],
      ["What rapper released 'Illmatic' in 1994?","Nas"],
      ["Who is known as the 'Godfather of Soul'?","James Brown"],
    ]),
  },

  movies: {
    200: qa([
      ["What is the highest-grossing film of all time?","Avatar"],
      ["Who directed 'Titanic'?","James Cameron"],
      ["What movie franchise features Dominic Toretto?","Fast and Furious"],
      ["Who plays Wolverine in the X-Men films?","Hugh Jackman"],
      ["What animated film features a rat who wants to cook?","Ratatouille"],
      ["What superhero movie made over $2 billion in 2019?","Avengers: Endgame"],
      ["Who voices Shrek?","Mike Myers"],
      ["What is the name of Batman's butler?","Alfred"],
    ]),
    400: qa([
      ["What film won Best Picture at the 2020 Oscars?","Parasite"],
      ["Who plays the Joker in 'The Dark Knight'?","Heath Ledger"],
      ["What film features the line 'You can't handle the truth!'?","A Few Good Men"],
      ["Who directed 'Kill Bill'?","Quentin Tarantino"],
      ["Who plays the lead in 'Gladiator'?","Russell Crowe"],
      ["What studio produced 'Toy Story'?","Pixar"],
      ["What 1999 film stars Keanu Reeves as 'The One'?","The Matrix"],
      ["What animated film features the song 'Let It Go'?","Frozen"],
    ]),
    600: qa([
      ["What film is based on Philip K. Dick's 'Do Androids Dream of Electric Sheep?'?","Blade Runner"],
      ["Who composed the score for 'Inception'?","Hans Zimmer"],
      ["What was Alfred Hitchcock's last film?","Family Plot (1976)"],
      ["What film won the Palme d'Or at Cannes in 2019?","Parasite"],
      ["Who directed 'Mulholland Drive'?","David Lynch"],
      ["What film features the character 'HAL 9000'?","2001: A Space Odyssey"],
      ["Who directed 'The Grand Budapest Hotel'?","Wes Anderson"],
      ["What 1982 sci-fi film was directed by Ridley Scott?","Blade Runner"],
      ["Who starred in 'Taxi Driver' (1976)?","Robert De Niro"],
      ["What French New Wave director made 'Breathless'?","Jean-Luc Godard"],
      ["What year was 'Citizen Kane' released?","1941"],
      ["Who directed 'There Will Be Blood'?","Paul Thomas Anderson"],
    ]),
  },

  friends: {
    200: qa([
      ["Who plays Rachel Green?","Jennifer Aniston"],
      ["What is Chandler's last name?","Bing"],
      ["What instrument does Phoebe play?","Guitar"],
      ["How many friends are in the main group?","6"],
      ["What is Ross's profession?","Paleontologist"],
      ["Who does Ross marry in Vegas?","Rachel"],
      ["What is Joey's catchphrase?","How you doin'?"],
      ["What is Monica's brother's name?","Ross"],
      ["Who is Chandler's wife?","Monica"],
      ["How many seasons did Friends run?","10"],
      ["What is Joey's acting character on Days of Our Lives?","Dr. Drake Ramoray"],
      ["Who plays Monica Geller?","Courteney Cox"],
    ]),
    400: qa([
      ["What is Chandler's middle name?","Muriel"],
      ["Who is Ross's first wife?","Carol"],
      ["What is Joey's penguin stuffed animal named?","Hugsy"],
      ["Who is Phoebe's twin sister?","Ursula"],
      ["What game show does Joey audition for?","Pyramid"],
      ["What is the name of Chandler and Joey's duck?","The Duck (no specific name)"],
      ["Who is Rachel's rich ex-fiancé from the pilot?","Barry"],
      ["What is Monica's biggest personality trait?","Competitiveness / cleanliness"],
      ["How many times does Ross get divorced?","3"],
      ["What is the name of Phoebe's husband?","Mike Hannigan"],
      ["Who plays Mike Hannigan?","Paul Rudd"],
      ["What does Rachel get a job doing at Ralph Lauren?","Fashion buyer / executive"],
      ["What floor do Monica and Rachel live on?","The top floor of their building"],
      ["Who sang the Friends theme song?","The Rembrandts"],
    ]),
    600: qa([
      ["What was Monica's apartment number (corrected mid-series)?","20 (changed from 5)"],
      ["What year did Friends premiere?","1994"],
      ["What is the name of Ross's second wife?","Emily Waltham"],
      ["Who plays Gunther?","James Michael Tyler"],
      ["What university did Ross and Chandler attend together?","Columbia University (or NYU, shown inconsistently)"],
      ["What is the last line of the series finale?","Where? (Chandler's joke about coffee)"],
      ["What is the name of Phoebe's birth mother?","Phoebe Abbott"],
      ["What was the original title considered for Friends?","Insomnia Cafe"],
      ["Who created Friends?","David Crane and Marta Kauffman"],
      ["What is the name of Chandler's father's Las Vegas show?","Viva Las Gaygas"],
      ["What network originally aired Friends?","NBC"],
      ["What was the most-watched Friends episode?","The Last One (finale)"],
      ["Who does Joey fall in love with in later seasons (main cast)?","Rachel"],
      ["What is Monica's wedding venue?","A museum"],
      ["What is the name of the ugly naked guy across the street?","Ugly Naked Guy (never named)"],
    ]),
  },

  the_office: {
    200: qa([
      ["What company do the characters work for?","Dunder Mifflin"],
      ["Who is the receptionist in season 1?","Pam Beesly"],
      ["What does Dunder Mifflin sell?","Paper"],
      ["Who is Michael's main rival at work?","Toby Flenderson"],
      ["Who plays Dwight Schrute?","Rainn Wilson"],
      ["Who does Jim eventually marry?","Pam"],
      ["What is Dwight's farm called?","Schrute Farms"],
      ["What kind of documentary is The Office filmed as?","Mockumentary"],
      ["What is Kevin's famous chili scene about?","He spills the chili"],
      ["Who becomes regional manager after Michael leaves?","Andy Bernard (later Dwight)"],
      ["What is Angela's favorite animal?","Cats"],
      ["Who is 'The Office' comedian known for 'That's what she said'?","Michael Scott"],
      ["What state is Scranton in?","Pennsylvania"],
    ]),
    400: qa([
      ["What is Dwight's middle name?","Kurt"],
      ["What is the name of the warehouse foreman?","Darryl Philbin"],
      ["Who plays Darryl?","Craig Robinson"],
      ["What season does Michael Scott leave the show?","Season 7"],
      ["What is Ryan Howard's nickname after his promotion?","Ryan the Temp (then exec)"],
      ["Who plays Andy Bernard?","Ed Helms"],
      ["What a cappella group was Andy in at Cornell?","Here Comes Treble"],
      ["What is Stanley's favorite day of the week?","Pretzel Day"],
      ["What is the name of Michael's movie he tries to make?","Threat Level Midnight"],
      ["Who is the Scranton Strangler?","Never confirmed (suspected Toby)"],
      ["What is Creed's role at Dunder Mifflin?","Quality assurance"],
      ["Who does Dwight marry in the finale?","Angela"],
      ["What is the name of the spin-off character who moves to Florida?","None aired (attempted)"],
      ["What instrument does Andy play?","Banjo"],
    ]),
    600: qa([
      ["What year did The Office premiere?","2005"],
      ["Who created the US version of The Office?","Greg Daniels"],
      ["What episode is considered the best Office episode by many fans?","Stress Relief"],
      ["Who plays Kelly Kapoor?","Mindy Kaling"],
      ["What is the name of Jim and Pam's first child?","Cecelia (CeCe)"],
      ["What is Kevin's band called?","Scrantonicity"],
      ["Who is the voice of Siri that Dwight dates (in-show)?","No — he dates an app named 'GIRL' — skip. Actually: Angela"],
      ["What is Oscar's last name?","Martinez"],
      ["What flavor of cake does Michael try to cancel for Meredith?","Chocolate"],
      ["Who replaces Michael as regional manager first?","Deangelo Vickers (Will Ferrell)"],
      ["What is the name of Holly Flax's ex?","AJ"],
      ["How many seasons did The Office run?","9"],
      ["What British show is The Office based on?","The Office (UK) by Ricky Gervais"],
      ["What does WUPHF stand for (Ryan's startup)?","Washington University Public Health Fund (joke)"],
      ["Who plays Holly Flax?","Amy Ryan"],
    ]),
  },

  breaking_bad: {
    200: qa([
      ["What state is Breaking Bad set in?","New Mexico"],
      ["What is Jesse Pinkman's catchphrase?","Yeah, science!"],
      ["What does Walter White cook?","Methamphetamine"],
      ["How many seasons does Breaking Bad have?","5"],
      ["What is the name of the car wash the Whites buy?","A1A Car Wash"],
      ["What fast food restaurant does Gus Fring own?","Los Pollos Hermanos"],
      ["What is Walter's son's name?","Walter Jr. (Flynn)"],
      ["What year did Breaking Bad premiere?","2008"],
    ]),
    400: qa([
      ["What is Gus Fring's full name?","Gustavo Fring"],
      ["Who plays Gus Fring?","Giancarlo Esposito"],
      ["What is the name of Saul Goodman's real name?","Jimmy McGill"],
      ["What kills Gus Fring?","A pipe bomb (attached to Hector's wheelchair)"],
      ["What is the name of Mike's granddaughter?","Kaylee"],
      ["What is Tuco Salamanca's uncle's name?","Hector Salamanca"],
      ["What song does Walter sing when he's in the crawl space?","He laughs maniacally"],
      ["What RV brand do Walt and Jesse cook in?","Fleetwood Bounder"],
      ["What is the name of Jesse's girlfriend who dies of overdose?","Jane Margolis"],
      ["What does Hank collect as a hobby?","Minerals (rocks)"],
      ["What country does Gus Fring claim to be from?","Chile"],
      ["What is the name of the law firm where Saul works?","Saul Goodman & Associates"],
      ["What pseudonym does Walter Jr. use?","Flynn"],
      ["Who kills Hank Schrader?","Jack Welker"],
    ]),
    600: qa([
      ["What is the name of the final episode?","Felina"],
      ["What song plays during the final scene?","Baby Blue by Badfinger"],
      ["What ricin-laced item does Walter use in the finale?","Stevia packet (for Lydia)"],
      ["What is the name of the pest control company Walt cooks under?","Vamonos Pest"],
      ["What is Lydia Rodarte-Quayle's preferred drink?","Chamomile tea with stevia"],
      ["What does the name 'Felina' reference?","Fe-Li-Na = Iron, Lithium, Sodium (blood, meth, tears)"],
      ["Who directed the pilot of Breaking Bad?","Vince Gilligan"],
      ["What is the maximum purity Walter's meth reaches?","99.1%"],
      ["What spin-off series follows Saul Goodman?","Better Call Saul"],
      ["What is the name of the cartel don who Gus kills?","Don Eladio"],
      ["What poison does Walter use on Brock?","Lily of the Valley"],
      ["What fake name does Walter use to buy a gun?","Mr. Lambert"],
      ["What confession does Walter make in the finale?","He did it for himself, because he liked it"],
      ["Who is the only Salamanca cousin to survive?","None (both die)"],
      ["What year does the series finale take place?","2010 (in-show timeline)"],
    ]),
  },

  harry_potter: {
    200: qa([
      ["What school does Harry attend?","Hogwarts"],
      ["What sport is played on broomsticks?","Quidditch"],
      ["Who is the headmaster of Hogwarts?","Albus Dumbledore"],
      ["What platform does the Hogwarts Express leave from?","Platform 9¾"],
      ["Who is Harry's enemy at school?","Draco Malfoy"],
      ["What is the name of the villain?","Lord Voldemort"],
      ["Who plays Harry Potter in the films?","Daniel Radcliffe"],
      ["What is Hermione's last name?","Granger"],
      ["What is the name of Hagrid's pet dragon?","Norbert"],
      ["What is the magical map called?","Marauder's Map"],
      ["What house is known for cunning and ambition?","Slytherin"],
    ]),
    400: qa([
      ["What is a Horcrux?","An object containing a piece of a soul"],
      ["How many Horcruxes did Voldemort make?","7 (intentionally 6 + Harry)"],
      ["What is the name of the Weasley's house?","The Burrow"],
      ["What are the three Deathly Hallows?","Elder Wand, Resurrection Stone, Cloak of Invisibility"],
      ["What is the name of Voldemort's snake?","Nagini"],
      ["What magical creature guards Gringotts vaults?","Dragons"],
      ["Who kills Dumbledore?","Snape"],
      ["What is the Patronus charm used for?","Repelling Dementors"],
      ["What form does Harry's Patronus take?","A stag"],
      ["Who is the gamekeeper at Hogwarts?","Rubeus Hagrid"],
    ]),
    600: qa([
      ["What is the core of Harry's wand?","Phoenix feather"],
      ["What phoenix provides feathers for Harry's and Voldemort's wands?","Fawkes"],
      ["What spell kills?","Avada Kedavra"],
      ["Who was the original owner of the Elder Wand (in legend)?","Antioch Peverell"],
      ["What is the Room of Requirement?","A room that appears when someone needs it"],
      ["Who is R.A.B.?","Regulus Arcturus Black"],
      ["What did Snape's Patronus reveal?","A doe — his love for Lily Potter"],
      ["What is Hermione's middle name?","Jean"],
      ["What is the name of Neville's parents?","Frank and Alice Longbottom"],
      ["Who destroys the last Horcrux (Nagini)?","Neville Longbottom"],
      ["What does Felix Felicis do?","Grants good luck"],
      ["What year was the Battle of Hogwarts?","1998"],
      ["Who is the true master of the Elder Wand at the end?","Harry Potter"],
      ["What is Voldemort's real name?","Tom Marvolo Riddle"],
      ["Who became Minister for Magic after the war?","Kingsley Shacklebolt"],
    ]),
  },

  star_wars: {
    200: qa([
      ["Who is Luke Skywalker's father?","Darth Vader"],
      ["What is the weapon of a Jedi?","Lightsaber"],
      ["Who is the small green Jedi Master?","Yoda"],
      ["What is the name of Han Solo's ship?","Millennium Falcon"],
      ["Who plays Han Solo in the original trilogy?","Harrison Ford"],
      ["What is the evil empire called?","Galactic Empire"],
      ["Who is Luke's twin sister?","Leia Organa"],
      ["What is the signature phrase 'May the ___ be with you'?","Force"],
      ["Who shot first in the cantina?","Han Solo (original version)"],
      ["What furry creatures live on Endor?","Ewoks"],
      ["Who directed the original Star Wars (1977)?","George Lucas"],
      ["What is Darth Vader's real name?","Anakin Skywalker"],
      ["What is the bounty hunter who captures Han Solo?","Boba Fett"],
    ]),
    400: qa([
      ["What is Order 66?","The command to kill all Jedi"],
      ["Who is the Emperor of the Galactic Empire?","Emperor Palpatine"],
      ["What planet is the Rebel base on in A New Hope?","Yavin 4"],
      ["What is the trash compactor scene in?","A New Hope (Death Star)"],
      ["What does AT-AT stand for?","All Terrain Armored Transport"],
      ["Who is Kylo Ren's mother?","Leia Organa"],
      ["What clone commander executes Order 66 against Obi-Wan?","Commander Cody"],
      ["What is the Mandalorian's real name?","Din Djarin"],
      ["What planet is the Jedi Temple on?","Coruscant"],
      ["Who kills Jabba the Hutt?","Leia (strangles with chain)"],
      ["What year was 'The Empire Strikes Back' released?","1980"],
    ]),
    600: qa([
      ["What is the significance of Ahsoka's white lightsabers?","They represent neutrality (neither Jedi nor Sith)"],
      ["Who composed the Star Wars film scores?","John Williams"],
      ["What is the Darksaber?","A unique black-bladed lightsaber (Mandalorian weapon)"],
      ["Who built C-3PO?","Anakin Skywalker"],
      ["What is the name of Count Dooku's Sith title?","Darth Tyranus"],
      ["What are Midi-chlorians?","Microscopic organisms that connect beings to the Force"],
      ["What is the World Between Worlds?","A Force dimension connecting all time and space"],
      ["Who discovered the path to Force immortality?","Qui-Gon Jinn"],
      ["What battle ended the Clone Wars?","Battle of Coruscant (or Order 66 / Siege of Mandalore)"],
      ["What is carbonite freezing?","A process that encases someone in carbonite (Han Solo)"],
      ["What is the Rule of Two?","Only two Sith at any time — a master and an apprentice"],
      ["Who established the Rule of Two?","Darth Bane"],
      ["What is Palpatine's Sith name?","Darth Sidious"],
      ["What ancient Sith planet is Palpatine hiding on in Rise of Skywalker?","Exegol"],
      ["What is the title of the animated show set between Episodes III and IV?","Star Wars Rebels"],
    ]),
  },

  marvel: {
    200: qa([
      ["Who snapped to destroy Thanos's army in Endgame?","Tony Stark / Iron Man"],
      ["What infinity stone is in Vision's forehead?","Mind Stone"],
      ["Who is the first Avenger?","Captain America"],
      ["Who plays Thanos?","Josh Brolin"],
      ["How many Infinity Stones are there?","6"],
      ["What is Hawkeye's real name?","Clint Barton"],
      ["Who directed 'The Avengers' (2012)?","Joss Whedon"],
      ["What is Black Widow's real name?","Natasha Romanoff"],
    ]),
    400: qa([
      ["Who is the sorcerer who guards the Time Stone?","Doctor Strange"],
      ["What metal is Wolverine's skeleton coated in?","Adamantium"],
      ["What is the real name of the Winter Soldier?","Bucky Barnes"],
      ["Who plays Captain America in the MCU?","Chris Evans"],
      ["What organization does Nick Fury lead?","S.H.I.E.L.D."],
      ["Who created Ultron?","Tony Stark and Bruce Banner"],
      ["What is the Quantum Realm?","A microscopic dimension below atoms"],
      ["What country is Scarlet Witch from?","Sokovia"],
      ["Who is the villain in Black Panther (2018)?","Erik Killmonger"],
      ["What is the Power Stone's color?","Purple"],
      ["Who is Ant-Man's alter ego?","Scott Lang"],
    ]),
    600: qa([
      ["What is Vibranium's main source in the MCU?","Wakanda (a meteorite)"],
      ["Who is Kang the Conqueror?","A time-traveling villain (Nathaniel Richards)"],
      ["What are the six Infinity Stones?","Space, Mind, Reality, Power, Time, Soul"],
      ["Who is the Celestial that appears in Eternals?","Arishem the Judge"],
      ["What is the TVA?","Time Variance Authority"],
      ["Who directed 'Avengers: Endgame'?","The Russo Brothers"],
      ["What is the Darkhold?","A book of dark magic (Book of the Damned)"],
      ["Who is the original Captain Marvel in the comics?","Mar-Vell"],
      ["What year did the MCU begin with Iron Man?","2008"],
      ["Who kills Thanos in Endgame?","Thor (and Tony uses the stones)"],
      ["What is the Blip?","The 5-year period when half of life was snapped away"],
      ["Who is Shang-Chi's father?","Xu Wenwu (The Mandarin)"],
      ["What is Wanda's hex in WandaVision?","A reality-altering bubble over Westview"],
      ["Who is the creator of the Super Soldier Serum?","Dr. Abraham Erskine"],
      ["What ancient entity created the symbiotes in the comics?","Knull"],
    ]),
  },

  disney: {
    200: qa([
      ["What princess has the longest hair?","Rapunzel"],
      ["What is the name of the snowman in Frozen?","Olaf"],
      ["What Disney princess lives under the sea?","Ariel"],
      ["What film features a magic carpet ride?","Aladdin"],
      ["What is the name of Pinocchio's conscience?","Jiminy Cricket"],
      ["What film features the song 'A Whole New World'?","Aladdin"],
      ["What princess pricks her finger on a spindle?","Aurora (Sleeping Beauty)"],
      ["Who is Nemo's father?","Marlin"],
      ["What kind of animal is Bambi?","Deer"],
      ["What Disney character has ice powers?","Elsa"],
      ["What is the name of Moana's demigod companion?","Maui"],
    ]),
    400: qa([
      ["What year did the first Disney animated feature release?","1937 (Snow White)"],
      ["What is the name of the castle in Disney theme parks?","Cinderella Castle (Magic Kingdom)"],
      ["What Pixar film is set inside a girl's mind?","Inside Out"],
      ["Who voiced Genie in the original Aladdin?","Robin Williams"],
      ["What is WALL-E's job?","Waste compactor robot"],
      ["Who is the villain in Tangled?","Mother Gothel"],
      ["What Pixar film features the Land of the Dead?","Coco"],
      ["What is the name of the dragon in Mulan?","Mushu"],
      ["Who composed the music for The Lion King (film)?","Hans Zimmer (Elton John songs)"],
      ["What is the name of the fire spirit in Frozen 2?","Bruni"],
      ["Who is the main character in Brave?","Merida"],
      ["What Pixar film features a house lifted by balloons?","Up"],
      ["What is the name of Ariel's father?","King Triton"],
      ["What villain wants 101 Dalmatian puppies?","Cruella de Vil"],
    ]),
    600: qa([
      ["What Disney film was the first to use the multiplane camera?","The Old Mill (1937 short)"],
      ["Who directed 'The Nightmare Before Christmas'?","Henry Selick (produced by Tim Burton)"],
      ["What is the Pixar theory?","A fan theory that all Pixar films share one universe/timeline"],
      ["Who composed the score for 'Up'?","Michael Giacchino"],
      ["What was the first Disney Renaissance film?","The Little Mermaid (1989)"],
      ["What is the name of the pizza restaurant in Toy Story?","Pizza Planet"],
      ["Who is the villain in Encanto?","There is no traditional villain"],
      ["What A113 reference appears in most Pixar films?","A CalArts classroom number"],
      ["What Disney film was the first to earn over $1 billion?","Toy Story 3"],
      ["Who directed 'Ratatouille'?","Brad Bird"],
      ["What is the oldest Disney princess?","Snow White (character: 14; film: 1937)"],
      ["What Pixar short film features a tiny bird on a beach?","Piper"],
      ["Who is the antagonist in Zootopia?","Assistant Mayor Bellwether"],
      ["What is the name of the emotion that is new in Inside Out 2?","Anxiety"],
    ]),
  },

  fortnite: {
    200: qa([
      ["How many players are in a standard Fortnite match?","100"],
      ["What happens when the storm closes in?","Players take damage"],
      ["What is the rarest weapon color in Fortnite?","Gold (Legendary)"],
      ["What vehicle was first added for traversal?","Shopping Cart"],
      ["What dance is the most iconic Fortnite emote?","Default Dance"],
      ["What material is weakest for building?","Wood"],
      ["What do you drop from at the start of a match?","Battle Bus"],
      ["What is V-Bucks?","Fortnite's in-game currency"],
      ["What is a Victory Royale?","Winning a match (last player/team standing)"],
      ["What weapon is the sniper rifle with the most damage?","Heavy Sniper"],
      ["What is Tilted Towers?","A popular POI (Point of Interest)"],
      ["What can you find in treasure chests?","Weapons, ammo, and items"],
    ]),
    400: qa([
      ["What season introduced the first battle pass?","Season 2"],
      ["What is the name of the cube that appeared in Season 5?","Kevin the Cube"],
      ["What collaboration brought Thanos to Fortnite?","Marvel / Avengers: Infinity War"],
      ["What mythic weapon came from Midas?","Midas' Drum Gun"],
      ["What is the IO in Fortnite's lore?","Imagined Order"],
      ["What is the Zero Point?","A reality-warping energy source at the center of the island"],
      ["What rapper held a virtual concert in Fortnite?","Travis Scott"],
      ["What is the name of the Chapter 2 Season 2 spy base POI?","The Agency"],
      ["What is a Reboot Card used for?","Reviving eliminated teammates"],
      ["What Season added the first vehicles that could be driven?","Chapter 2 Season 3"],
      ["Who is the main character in Fortnite's story?","Jonesy (Agent Jones)"],
      ["What item lets you become invisible briefly?","Shadow Stone (or Shadow Bomb)"],
      ["What is the max shield you can have?","200 (100 health + 100 shield)"],
      ["What item gives 50 shield?","Small Shield Potion (25) — Big Shield gives 50"],
      ["What is Creative mode?","A sandbox mode where players build custom maps"],
    ]),
    600: qa([
      ["What year did Fortnite Battle Royale launch?","2017"],
      ["What was the black hole event?","End of Chapter 1 — the entire game went offline"],
      ["What music artist's skins have appeared most in Fortnite?","Marshmello / Travis Scott / Eminem"],
      ["What game engine does Fortnite run on?","Unreal Engine"],
      ["What was Fortnite's original mode before BR?","Save the World (PvE)"],
      ["What is UEFN?","Unreal Editor for Fortnite (custom content tool)"],
      ["What is a Mythic Goldfish?","The rarest item — a throwable that eliminates instantly"],
      ["What season introduced the first live in-game event?","Season 4 (rocket launch)"],
      ["How many chapters has Fortnite had (as of 2024)?","5"],
      ["What is the OG Season that brought back the old map?","Chapter 4 Season OG"],
      ["What weapon was vaulted the most times?","Drum Gun"],
      ["What competitive format does Fortnite use for tournaments?","Arena / FNCS"],
      ["What is the highest arena rank?","Champion"],
      ["What crossover introduced lightsabers to Fortnite?","Star Wars"],
    ]),
  },

  valorant: {
    200: qa([
      ["What is the in-game currency used to buy weapons?","Creds"],
      ["What is the objective for attackers?","Plant the Spike"],
      ["How many rounds do you need to win a standard match?","13"],
      ["What is the knife called in Valorant?","Knife (or melee)"],
      ["What type of game is Valorant?","Tactical first-person shooter"],
      ["What is the most expensive rifle in the game?","Vandal or Phantom (2,900 creds)"],
      ["What is the cheapest pistol?","Classic (free on pistol round)"],
      ["What agent has healing abilities and is from Jamaica?","Sage... wait no. Sage is Chinese. Skip — no agent from Jamaica. Use: What healer agent creates walls and can resurrect?","Sage"],
      ["What is the name of the sniper that kills in one shot to the body?","Operator"],
      ["What agent can teleport with two anchor points?","Yoru"],
      ["What is the maximum number of abilities each agent has?","4"],
      ["What region is Valorant's competitive scene strongest in?","EMEA / Americas / Pacific"],
    ]),
    400: qa([
      ["What agent class has the role of entry fragging?","Duelist"],
      ["What is the name of Jett's ultimate ability?","Blade Storm"],
      ["What is an 'Ace' in Valorant?","Killing all 5 enemies in a round"],
      ["What is the anti-cheat system Valorant uses?","Vanguard"],
      ["What is a 'Thrifty' round?","Winning a round while spending significantly less than opponents"],
      ["What map has teleporters?","Bind"],
      ["What agent was the first added after launch?","Reyna"],
      ["What does 'eco' mean?","Saving money by not buying in a round"],
      ["What is the shotgun that can fire both barrels at once?","Judge (no — Bucky has alt fire)"],
      ["What agent can create smokes globally with an iPad-like device?","Brimstone"],
      ["What is the name of Chamber's ultimate sniper?","Tour de Force"],
      ["What year was Valorant released?","2020"],
      ["What is the maximum number of agents on the roster (as of 2024)?","24+"],
    ]),
    600: qa([
      ["What is Valorant's ranking system called?","Competitive (Iron to Radiant)"],
      ["What is the highest rank in Valorant?","Radiant"],
      ["What agent's abilities revolve around turrets and trips?","Killjoy"],
      ["What Valorant team won the first Champions tournament?","Acend"],
      ["What is 'lurking' in Valorant?","Playing away from the team to get flanks or info"],
      ["What is the pistol round?","The first round of each half with limited money"],
      ["What is the maximum credits you can have?","9,000"],
      ["What Valorant tournament is the equivalent of the World Cup?","Champions"],
      ["What agent controls a swarm of nanobots?","KAY/O (suppresses) — Nanoswarm: Killjoy"],
      ["What map was removed and reworked first?","Split"],
      ["What does 'anti-eco' mean?","Full-buying against an enemy eco round"],
      ["What agent's ultimate is a targeted laser across the map?","Chamber (Tour de Force sniper) — correct: none. Actually Neon's ult is a lightning sprint/slide beam"],
      ["What is the fastest-killing weapon at close range?","Judge (shotgun)"],
      ["What agent uses a Boom Bot that chases enemies?","Raze"],
    ]),
  },

  video_games: {
    200: qa([
      ["What is the best-selling video game of all time?","Minecraft"],
      ["What company makes Mario games?","Nintendo"],
      ["What game features a character named Link saving Princess Zelda?","The Legend of Zelda"],
      ["What game has players drop onto an island and fight to be last standing?","Fortnite (or PUBG)"],
      ["What gaming console did Sony release in 2020?","PlayStation 5"],
      ["What block-building survival game was created by Mojang?","Minecraft"],
      ["What mobile game has players catching creatures in the real world?","Pokémon GO"],
      ["What is the name of the main character in The Legend of Zelda?","Link"],
      ["What company makes the Xbox?","Microsoft"],
      ["What handheld console did Nintendo release in 2017?","Nintendo Switch"],
      ["What game has a character named Steve who mines blocks?","Minecraft"],
    ]),
    400: qa([
      ["What game features an open world called Hyrule?","The Legend of Zelda: Breath of the Wild"],
      ["What is the name of the battle royale game by Respawn?","Apex Legends"],
      ["What MMO has been running since 2004 by Blizzard?","World of Warcraft"],
      ["What 2018 game features Kratos and his son Atreus?","God of War"],
      ["What rhythm game uses plastic guitars?","Guitar Hero (or Rock Band)"],
      ["What was the first commercially successful home console?","Atari 2600"],
      ["What game features Nathan Drake as a treasure hunter?","Uncharted"],
      ["What open-world crime game franchise is made by Rockstar?","Grand Theft Auto"],
      ["What game has the player fight colossi in an empty landscape?","Shadow of the Colossus"],
      ["What game popularized the 'auto-battler' genre?","Dota Auto Chess (or Teamfight Tactics)"],
      ["What racing game series features blue shells?","Mario Kart"],
      ["What game has the tagline 'War never changes'?","Fallout"],
      ["What game features Geralt of Rivia as a monster hunter?","The Witcher 3"],
      ["What fighting game features characters like Ryu and Ken?","Street Fighter"],
      ["What game has players survive on a raft in the ocean?","Raft (or Subnautica)"],
    ]),
    600: qa([
      ["What game popularized the roguelike genre in recent years?","Hades"],
      ["What is the name of the AI in the Portal games?","GLaDOS"],
      ["What year was the original Doom released?","1993"],
      ["What game features a character named Solaire who praises the sun?","Dark Souls"],
      ["What is the best-selling console of all time?","PlayStation 2"],
      ["What indie game features a skeleton named Sans?","Undertale"],
      ["What studio developed 'The Last of Us'?","Naughty Dog"],
      ["What game has the player manage a city on Mars?","Surviving Mars"],
      ["What game features the line 'Would you kindly?'","BioShock"],
      ["What is the name of the protagonist in Half-Life?","Gordon Freeman"],
      ["What game won Game of the Year at The Game Awards 2023?","Baldur's Gate 3"],
      ["What game engine did Valve create?","Source Engine"],
      ["What game has players explore procedurally generated planets?","No Man's Sky"],
      ["What developer made 'Elden Ring'?","FromSoftware"],
    ]),
  },

  anime: {
    200: qa([
      ["What anime features a rubber pirate named Luffy?","One Piece"],
      ["What is the name of Goku's signature attack?","Kamehameha"],
      ["What anime features a notebook that kills?","Death Note"],
      ["Who is the protagonist of Dragon Ball Z?","Goku"],
      ["What is the name of Ash Ketchum's first Pokémon?","Pikachu"],
      ["What anime features alchemist brothers?","Fullmetal Alchemist"],
      ["What anime features a boy who becomes the #1 hero?","My Hero Academia"],
      ["What anime features a volleyball team at Karasuno?","Haikyuu!!"],
    ]),
    400: qa([
      ["What is the name of the Survey Corps in Attack on Titan?","Scout Regiment (Survey Corps)"],
      ["What is Luffy's Devil Fruit power?","Gum-Gum Fruit (Gomu Gomu no Mi)"],
      ["Who is the main antagonist of Death Note?","Light Yagami (or L, depending on perspective)"],
      ["What is Bankai in Bleach?","The final release of a Zanpakutō"],
      ["What is Nen in Hunter x Hunter?","A life energy system used for special abilities"],
      ["What studio animated Attack on Titan?","Wit Studio (later MAPPA)"],
      ["What is the name of Naruto's nine-tailed fox?","Kurama"],
      ["What anime features a game called Greed Island?","Hunter x Hunter"],
      ["What is the name of Eren Yeager's Titan form?","Attack Titan"],
      ["Who is the main character of Jujutsu Kaisen?","Yuji Itadori"],
      ["What is the Sharingan in Naruto?","A special eye ability of the Uchiha clan"],
      ["What anime features a boy who trains with 100 push-ups per day?","One Punch Man"],
      ["What is All Might's real name?","Toshinori Yagi"],
      ["What is the name of Gon's father in HxH?","Ging Freecss"],
    ]),
    600: qa([
      ["What is the Rumbling in Attack on Titan?","Eren unleashing millions of Wall Titans to flatten the world"],
      ["What is Gear 5 in One Piece?","Luffy's awakened Devil Fruit form (Sun God Nika)"],
      ["What is Domain Expansion in Jujutsu Kaisen?","A technique that creates a pocket dimension with guaranteed hits"],
      ["Who is the author of Berserk?","Kentaro Miura"],
      ["What is the Eclipse in Berserk?","A sacrificial event where Griffith sacrifices the Band of the Hawk"],
      ["What is Conqueror's Haki in One Piece?","The ability to dominate the will of others"],
      ["What is the Zero Requiem in Code Geass?","Lelouch's plan to unite the world against him, then be killed"],
      ["What studio produced 'Demon Slayer: Mugen Train'?","Ufotable"],
      ["What is the Phantom Troupe in HxH?","A group of thieves led by Chrollo Lucilfer"],
      ["What is Evangelion's Human Instrumentality Project?","A plan to merge all human consciousness into one being"],
      ["What anime coined the term 'isekai' as a genre?","Sword Art Online (popularized it; genre older)"],
      ["What is the name of the god-like entity in Solo Leveling?","The Absolute Being"],
      ["What is the Void Century in One Piece?","A 100-year gap in history erased by the World Government"],
      ["Who is the strongest character in Dragon Ball Super?","Zeno (Grand Priest serves him)"],
    ]),
  },

  pop_culture: {
    200: qa([
      ["What social media platform has a bird (now X) logo?","Twitter (X)"],
      ["Who is the most followed person on Instagram?","Cristiano Ronaldo"],
      ["What dating app do you swipe right on?","Tinder"],
      ["What band sang 'Yesterday'?","The Beatles"],
      ["What is the most streamed song on Spotify of all time?","Blinding Lights (The Weeknd)"],
      ["Who is the most subscribed YouTuber (channel)?","MrBeast"],
      ["What singer is known as 'Riri'?","Rihanna"],
      ["What movie franchise stars Vin Diesel as a street racer?","Fast and Furious"],
      ["What reality show sends contestants to find love on an island?","Love Island"],
      ["What platform is known for short-form vertical videos?","TikTok"],
      ["What comic book character is 'the Dark Knight'?","Batman"],
      ["What pop star has an 'Eras Tour'?","Taylor Swift"],
    ]),
    400: qa([
      ["What is the name of Drake's son?","Adonis"],
      ["What year did Instagram launch?","2010"],
      ["What TV show features Sheldon Cooper?","The Big Bang Theory"],
      ["What Netflix series is about a chess prodigy?","The Queen's Gambit"],
      ["What movie featured the 'Barbenheimer' phenomenon?","Barbie and Oppenheimer (released same day)"],
      ["What singer won Album of the Year 4 times at the Grammys?","Taylor Swift"],
      ["What reality competition has Gordon Ramsay as a judge?","MasterChef / Hell's Kitchen"],
      ["Who is the richest person in the world (as of 2024)?","Elon Musk / Bernard Arnault"],
      ["What streaming service produced 'Wednesday'?","Netflix"],
      ["What film became the highest-grossing film of 2023?","Barbie"],
      ["What is the most-liked photo on Instagram?","A photo of an egg (World Record Egg)"],
      ["What animated series features Morty and his grandfather?","Rick and Morty"],
    ]),
    600: qa([
      ["What is the name of Beyoncé's visual album released in 2016?","Lemonade"],
      ["What Netflix documentary exposed tiger breeding in the US?","Tiger King"],
      ["Who directed 'Everything Everywhere All At Once'?","Daniel Kwan and Daniel Scheinert (Daniels)"],
      ["What podcast became the most downloaded in Spotify history?","The Joe Rogan Experience"],
      ["What year did TikTok launch internationally?","2017 (as TikTok; Musical.ly merged 2018)"],
      ["What AI tool went viral in November 2022?","ChatGPT"],
      ["What artist broke the record for most Grammy wins in a single night?","Beyoncé (2023)"],
      ["What is the most expensive film ever made?","Pirates of the Caribbean: On Stranger Tides (~$379M)"],
      ["What phenomenon caused GameStop stock to surge in 2021?","Reddit's r/WallStreetBets short squeeze"],
      ["What 2024 film featured Ryan Gosling as Ken?","Barbie (2023, but continued through awards)"],
      ["What is the most-watched YouTube video of all time?","Baby Shark Dance"],
      ["What platform acquired Twitch in 2014?","Amazon"],
    ]),
  },

  technology: {
    200: qa([
      ["What does 'GPS' stand for?","Global Positioning System"],
      ["What is the most popular programming language in the world?","JavaScript (or Python)"],
      ["What does 'LED' stand for?","Light Emitting Diode"],
      ["What company makes the MacBook?","Apple"],
      ["What is cloud computing?","Storing and accessing data over the internet"],
      ["What does a router do?","Directs network traffic between devices"],
      ["What is the most-used web browser?","Chrome"],
      ["What company makes Alexa?","Amazon"],
      ["What does 'FAQ' stand for?","Frequently Asked Questions"],
      ["What is a firewall?","Security system that monitors network traffic"],
      ["What does 'NFC' stand for?","Near Field Communication"],
      ["What device reads QR codes?","Smartphone camera"],
      ["What does 'HDMI' stand for?","High-Definition Multimedia Interface"],
      ["What is the cloud?","Remote servers accessed over the internet"],
      ["What year was the iPad first released?","2010"],
    ]),
    400: qa([
      ["What does 'CSS' stand for?","Cascading Style Sheets"],
      ["Who is the CEO of Apple (as of 2024)?","Tim Cook"],
      ["What does 'DNS' stand for?","Domain Name System"],
      ["What is Moore's Law?","Transistor count doubles roughly every two years"],
      ["What company developed ChatGPT?","OpenAI"],
      ["What is the name of Tesla's humanoid robot?","Optimus"],
      ["What does 'SDK' stand for?","Software Development Kit"],
      ["What protocol is used for secure web browsing?","HTTPS"],
      ["What is containerization in software?","Packaging software with its dependencies (e.g., Docker)"],
      ["What company makes the Pixel phone?","Google"],
      ["What does 'OTA' update stand for?","Over-The-Air"],
      ["What is machine learning?","AI that learns patterns from data without explicit programming"],
      ["What is a DDoS attack?","Distributed Denial of Service — overwhelming a server with traffic"],
      ["What does 'SSH' stand for?","Secure Shell"],
    ]),
    600: qa([
      ["What is quantum computing?","Computing using quantum bits (qubits) that can be 0 and 1 simultaneously"],
      ["What is the name of Google's quantum processor?","Sycamore"],
      ["What does 'RISC' stand for in CPU architecture?","Reduced Instruction Set Computer"],
      ["What is WebAssembly?","A binary instruction format for stack-based virtual machines in browsers"],
      ["What company created the Transformer architecture used in GPT?","Google Brain"],
      ["What is FPGA?","Field-Programmable Gate Array"],
      ["What year was the World Wide Web made publicly available?","1991"],
      ["What is homomorphic encryption?","Encryption that allows computation on encrypted data"],
      ["What is the CAP theorem in distributed systems?","Consistency, Availability, Partition tolerance — pick two"],
      ["What does 'ASIC' stand for?","Application-Specific Integrated Circuit"],
      ["What programming paradigm does Haskell use?","Functional programming"],
      ["What is zero-knowledge proof?","Proving you know something without revealing the information itself"],
      ["Who invented the concept of the universal Turing machine?","Alan Turing"],
      ["What is edge computing?","Processing data near the source instead of in a central data center"],
      ["What is the name of Apple's custom chip series for Macs?","M-series (M1, M2, M3, M4)"],
    ]),
  },

  minecraft: {
    200: qa([
      ["What do you mine to get coal?","Coal ore"],
      ["What mob gives you leather?","Cow"],
      ["What do you make a bed from?","Wool and planks"],
      ["What liquid destroys items?","Lava"],
      ["What block lets you enchant items?","Enchanting table"],
      ["What do you use to fish?","Fishing rod"],
      ["What dimension has chorus fruit?","The End"],
      ["What mob is a horse skeleton?","Skeleton horse"],
      ["What block can you use to dye?","Any dyeable block (wool, concrete powder)"],
      ["What ore is needed for a compass?","Iron"],
      ["What block grows on mycelium?","Mushrooms"],
      ["What item lets you breathe underwater?","Turtle shell helmet (or Potion of Water Breathing)"],
      ["What crop grows fastest in Minecraft?","Sugar cane"],
      ["What is the command to switch to creative mode?","/gamemode creative"],
    ]),
    400: qa([
      ["What is the maximum level of Sharpness enchantment?","5"],
      ["What mob can you ride with a saddle?","Horse (also pig with carrot on a stick)"],
      ["What biome has mesa/terracotta?","Badlands"],
      ["What potion makes you invisible?","Potion of Invisibility"],
      ["What is needed to make an end crystal?","Eye of Ender, glass, and ghast tear"],
      ["What block is blast-resistant and found in the End?","End stone"],
      ["What enchantment lets you walk on water (frozen)?","Frost Walker"],
      ["What is the rarest biome in Minecraft?","Mushroom Island (or Modified Jungle Edge)"],
      ["What do you need to cure a zombie villager?","Splash Potion of Weakness and a Golden Apple"],
      ["What mob attacks in the Nether and shoots fireballs?","Ghast"],
      ["What item lets you copy maps?","Cartography table"],
      ["What enchantment lets pickaxes mine faster?","Efficiency"],
      ["What structure spawns in the Nether with blazes?","Nether Fortress"],
      ["What item do you use to leash animals?","Lead"],
    ]),
    600: qa([
      ["What is a Sculk Shrieker?","A block that summons the Warden after being triggered"],
      ["What is the maximum render distance in Java Edition?","32 chunks"],
      ["What enchantment lets a trident return after throwing?","Loyalty"],
      ["What is a Comparator used for?","Reading container fullness and redstone signal strength"],
      ["What is the maximum number of bees in a beehive?","3"],
      ["What does a Beacon require to activate?","A pyramid of iron/gold/diamond/emerald/netherite blocks"],
      ["What is the Wither's health in Java Edition?","300 HP (150 hearts)"],
      ["What update added the Deep Dark?","1.19 (The Wild Update)"],
      ["What mob was voted in by the community in 2020?","Glow Squid"],
      ["What is a Redstone Repeater's maximum delay?","4 ticks"],
      ["What is the rarest structure in Minecraft?","Woodland Mansion"],
      ["What version added copper?","1.17 (Caves & Cliffs Part I)"],
      ["What is the maximum level of Fortune enchantment?","3"],
      ["How many End Cities spawn per End dimension?","Multiple (procedurally generated)"],
      ["What is a Calibrated Sculk Sensor?","A sculk sensor that only detects specific vibration frequencies"],
    ]),
  },

  ark_survival: {
    200: qa([
      ["What is the maximum player level on default settings?","105 (plus Chibi and Ascension bonuses)"],
      ["What item stores water for drinking?","Waterskin"],
      ["What flying mount is available earliest?","Pteranodon"],
      ["What structure protects from weather and spawns?","Thatch/wood/stone house"],
      ["What berry restores stamina?","Stimberry"],
      ["What tame is best for early-game egg collection?","Oviraptor"],
      ["What resource do you get from rocks with a pickaxe?","Stone (and flint)"],
      ["What does a mortar and pestle craft?","Narcotics and other recipes"],
      ["What is the default damage multiplier for a Rex?","62 base damage"],
      ["What creature is best for collecting chitin?","Megatherium (or Sabertooth)"],
      ["What tool harvests the most thatch from trees?","Pickaxe"],
      ["What tool harvests the most wood from trees?","Hatchet"],
      ["What is the command to spawn items?","admincheat GiveItem"],
      ["What food tames a Raptor fastest?","Raw Mutton (or Kibble)"],
      ["What is the name of the implant in your arm?","Specimen Implant"],
    ]),
    400: qa([
      ["What is the Obelisk used for in ARK?","Uploading tames, items, and transferring servers"],
      ["What creature on Extinction drops Element Dust?","Enforcers and Tek creatures"],
      ["What is the name of the boss on The Center?","The same bosses as The Island"],
      ["What resource is crafted from chitin and stone?","Cementing Paste"],
      ["What mount is considered the best all-rounder?","Argentavis"],
      ["What structure holds large amounts of items?","Vault"],
      ["What is the Industrial Forge used for?","Smelting large amounts of metal quickly"],
      ["What is the Tek Replicator?","An end-game crafting station for Tek items"],
      ["What kibble system was reworked in the TLC update?","The tiered kibble system (Basic to Extraordinary)"],
      ["What is an Imprint bonus?","Stat bonuses gained from caring for raised babies"],
      ["What underwater mount has sonar abilities?","Basilosaurus or Ichthyosaurus (basic) — Diplocaulus for oxygen"],
      ["What creature in Genesis Part 1 can teleport?","Ferox (or Bloodstalker grapple)"],
      ["What is the purpose of Cryopods?","Storing tamed dinos for transport"],
      ["What structure protects against lightning on Scorched Earth?","Lightning Rod"],
      ["What is Mutation Breeding?","Breeding tames for random stat/color mutations"],
    ]),
    600: qa([
      ["What is the Overseer?","The final boss of The Island, guarding ascension"],
      ["What happens when you ascend on The Island?","Your character levels up to a new max and is transferred"],
      ["What is the Alpha King Titan?","The hardest boss in Extinction, requires all three Titans"],
      ["What is the Corrupted Master Controller?","The final boss of Genesis Part 1"],
      ["What is the Astrodelphis?","A space dolphin mount exclusive to Genesis Part 2"],
      ["What is a Reaper King?","A creature from Aberration that implants a baby in the player"],
      ["What is the Maewing?","A platypus-like creature from Genesis Part 2 that nurses babies"],
      ["What is the Stryder?","A Tek creature in Genesis Part 2 used for harvesting and scanning"],
      ["How many Tekgrams are available in the game?","30+ (varies by map)"],
      ["What is the R-variant of a creature?","A Genesis-exclusive variant with different stats/colors"],
      ["What happens if a baby's food reaches 0?","It dies"],
      ["What is the mutation cap per stat?","20 mutations per side (maternal/paternal)"],
      ["What is the level cap for wild tamed creatures after taming bonus?","224 (150 wild + 74 taming bonus on perfect tame)"],
      ["What is the Noglin?","A brain parasite creature from Genesis Part 2"],
      ["What is the max tribe member limit on official servers?","No hard cap (up to server player limit)"],
    ]),
  },
};

export default MEGA_NEW_EXPANSIONS;
