const DEFAULT_START = 2;

const scene = (title, videoId, { start = DEFAULT_START, duration, sourceUrl } = {}) => ({
  q: "Clip",
  a: title,
  videoId,
  start,
  duration,
  sourceUrl: sourceUrl || `https://www.youtube.com/watch?v=${videoId}`,
});

const easy = (title, videoId, options = {}) => scene(title, videoId, { duration: 18, ...options });
const medium = (title, videoId, options = {}) => scene(title, videoId, { duration: 16, ...options });
const hard = (title, videoId, options = {}) => scene(title, videoId, { duration: 14, ...options });

const MOVIE_SCENE_BANK = {
  label: "Movie Scenes",
  icon: "🎞️",
  color: "#F97316",
  isMovieScene: true,
  200: [
    easy("Jurassic Park", "E8WaFvwtphY"),
    easy("Frozen", "AiX-WvMNDPc"),
    easy("Harry Potter", "50N2eB0JI80"),
    easy("Spider-Man", "jM7Eou4bV-Q"),
    easy("The Dark Knight Rises", "RBE4fZLqrVQ"),
    easy("The Matrix", "zE7PKRjrid4"),
    easy("Forrest Gump", "bSMxl1V8FSg"),
    easy("Home Alone", "_qu4ZBCU6Fc"),
    easy("Pirates of the Caribbean", "EtgZr_2WM2U"),
    easy("Back to the Future", "qW2syroSQTs"),
    easy("The Hunger Games", "v98Rh9qzmPs"),
    easy("Transformers", "f6L3Ef1JCC8"),
    easy("Jaws", "yrEvK-tv5OI"),
    easy("Independence Day", "vjFG-4Ge668"),
    easy("Die Hard", "I6wRZCV7naE"),
    easy("Despicable Me", "fdrR3NbPARs"),
    easy("Minions", "Ei5IEWld1xw"),
    easy("Madagascar", "kPE7ZCGjw4o"),
    easy("The Godfather", "VC1_tdnZq1A"),
    easy("Wonder Woman", "pJCgeOAKXyg"),
    easy("Aquaman", "UzpeIrvDaGQ"),
    easy("Ice Age", "_LKe8V-h7h8"),
    easy("Kung Fu Panda", "STqJ_Up4iFg"),
    easy("How to Train Your Dragon", "c95YKkIbTGg"),
    easy("Shrek 2", "ZOfisAF09AA"),
    easy("Man of Steel", "hdDFR0nRUcY"),
    easy("Mission Impossible", "sd_I5ez3jwg"),
    easy("The Bourne Identity", "PeGDBR0Ej_0"),
    easy("Taken", "rzIaMCGVw_Y"),
    easy("Rush Hour", "-eIH1jFAGlY"),
    easy("Bad Boys", "nEf2ML7wkBE"),
    easy("The Fast and the Furious", "UmmXGbFASC0"),
    easy("Fast Five", "eFnw_27t9-o"),
    easy("Joker", "4M2WTfCDtyU"),
    easy("Alien", "gEqHJ1tomnk"),
  ],
  400: [
    medium("Predator", "wgzxSr6l9Y4"),
    medium("Mulan", "fO263dPKqns"),
    medium("2012", "YnnxVknsLk0"),
    medium("The Day After Tomorrow", "GmjAp2eRDH0"),
    medium("Pulp Fiction", "x2WK_eWihdU"),
    medium("Fight Club", "CR5Jp_ag2M8"),
    medium("Inception", "i9zjvUywVG8"),
    medium("The Silence of the Lambs", "V5dA92wqmME"),
    medium("Top Gun Maverick", "IXbnzEHZDPg"),
    medium("John Wick", "CdHKXmEn4l8"),
    medium("Rocky", "jK4lxjvrhHs"),
    medium("The Departed", "qVwoeNk9554"),
    medium("Full Metal Jacket", "py_h3yTxcWI"),
    medium("Casino Royale", "iZxNbAwY_rk"),
    medium("The Sixth Sense", "qdzqLQfZIUk"),
    medium("Taxi Driver", "VKE_B4jMF5Q"),
    medium("The Truman Show", "MdwuW8n3JYA"),
    medium("Mad Max Fury Road", "k4Lpr1sqKbQ"),
    medium("Heat", "GpNzlh5ALRA"),
    medium("Seven", "h8m69o_1PoQ"),
    medium("Creed", "1qjRRTjLU4U"),
    medium("American Psycho", "Ruw9fsh3PNY"),
    medium("The Social Network", "8eu9yZ6pWjg"),
    medium("La La Land", "7CVfTd-_qbc"),
    medium("Baby Driver", "_oLBVF_VYRM"),
    medium("No Country for Old Men", "ZY0DG8rUnCA"),
    medium("Black Swan", "dwD4JZsAuew"),
    medium("Good Will Hunting", "-k6JxfX8asc"),
    medium("Argo", "8j4k-10bZC0"),
    medium("Raging Bull", "9yHJcx89XXk"),
    medium("Hacksaw Ridge", "tlNPiSw0AKc"),
    medium("Blade Runner 2049", "bbX5KM0tFVk"),
    medium("The Grand Budapest Hotel", "JN5sqSEXxm4"),
    medium("Hot Fuzz", "faMh6OYfuNE"),
    medium("Scott Pilgrim", "ILwoKfeDJO4"),
    medium("Kick-Ass", "7PcolFECV_k"),
    medium("Snatch", "g7QBS0O7gT0"),
    medium("A Beautiful Mind", "a5e0e_KWwIg"),
    medium("Moneyball", "JXyisZLObHc"),
    medium("American Gangster", "y5RFBLZV-B4"),
    medium("Casino", "-riX6Xbvb8w"),
    medium("Knives Out", "bqAGt9-ByQA"),
    medium("Sicario", "h4HRKN5CZFo"),
    medium("Collateral", "_syPeFclyN8"),
    medium("The Town", "-o1N2unFkSs"),
    medium("Mystic River", "RYlKhpi--QQ"),
    medium("Munich", "0bR6pUOhZo4"),
    medium("Platoon", "PvqQnJ7Fvz4"),
  ],
  600: [
    hard("Donnie Brasco", "e2xiwiWd_sM"),
    hard("The Untouchables", "xPZ6eaL3S2E"),
    hard("The Irishman", "gaa_5m3cmSc"),
    hard("The Pursuit of Happyness", "_-jXE-VvZqw"),
    hard("Lucy", "tsQS1b-fNSs"),
    hard("Atomic Blonde", "q8-xQspXFag"),
    hard("The Wrestler", "7fTnTP49FW0"),
    hard("Steve Jobs", "XS-R1raNESI"),
    hard("Warrior", "LkimMjwfjrQ"),
    hard("The Shawshank Redemption", "hUbIsfzOjk4"),
    hard("Get Out", "kBwVWrBk_uo"),
    hard("Logan", "pCWh64PSr-I"),
    hard("Skyfall", "yV8-IGY64pE"),
    hard("The Batman", "3Q_YQBwG21M"),
    hard("Dunkirk", "X5_GpmLuea4"),
    hard("A Quiet Place", "4CmmKmlXD9I"),
    hard("Ford v Ferrari", "ALXCF2PoYpQ"),
    hard("Shutter Island", "-F1-sTyGvwA"),
    hard("The Conjuring", "wHqQzF4JXdE"),
    hard("Mission Impossible Fallout", "0pUMzDEV-DE"),
    hard("The Bourne Ultimatum", "Mwmy0awMZXY"),
    hard("Eternal Sunshine of the Spotless Mind", "hZdl2FFp0eA"),
    hard("Poor Things", "SEBGdjkPtRo"),
    hard("The Favourite", "w6O6wR44AY4"),
    hard("Boyhood", "iASBdbiKSHU"),
    hard("Lost in Translation", "vGvDCmuDKKE"),
    hard("Memories of Murder", "Smh1_ZKMb-A"),
    hard("Blue Velvet", "BeYx_CBH700"),
    hard("The Tree of Life", "c4Wls5pZlxQ"),
    hard("Blue Valentine", "3ZFLdDFdxW4"),
    hard("Phantom Thread", "URDzGjLruJU"),
    hard("The French Dispatch", "JYZpy6nYa4U"),
    hard("Fantastic Mr Fox", "iuKNXP9LcSg"),
    hard("The Killing of a Sacred Deer", "fC_bPxyhC_8"),
    hard("Inherent Vice", "4RPigjaVctQ"),
    hard("The Virgin Suicides", "3IzkgVtAnuY"),
    hard("Before Sunset", "VhRkUhY8MlQ"),
    hard("Amores Perros", "f48wH7l3c5I"),
  ],
};

export default MOVIE_SCENE_BANK;
