const DEFAULT_START = 2;

const scene = (title, videoId, { start = DEFAULT_START, duration, sourceUrl } = {}) => ({
  q: "Clip",
  a: title,
  videoId,
  start,
  duration,
  sourceUrl: sourceUrl || `https://www.youtube.com/watch?v=${videoId}`,
});

const easy = (title, videoId, options = {}) => scene(title, videoId, { duration: 18, ...options });
const medium = (title, videoId, options = {}) => scene(title, videoId, { duration: 16, ...options });
const hard = (title, videoId, options = {}) => scene(title, videoId, { duration: 14, ...options });

const MOVIE_SCENE_BANK = {
  label: "Movie Scenes",
  icon: "🎞️",
  color: "#F97316",
  isMovieScene: true,
  200: [
    easy("Star Wars: A New Hope", "63HXmKFhi84"),
    easy("Titanic", "_qTZRD1_ybQ"),
    easy("Jurassic Park", "E8WaFvwtphY"),
    easy("The Dark Knight", "SIYkhb2NjfE"),
    easy("Avatar", "nb_fFj_0rq8", { start: 24 }),
    easy("Harry Potter and the Sorcerer's Stone", "thL8QAsPhK0"),
    easy("The Avengers", "Df5a6wapif8"),
    easy("Spider-Man", "zlwaUJzGqns"),
    easy("The Lion King", "C6ATf9ELlkU"),
    easy("Toy Story", "g2IF5NG2vU4"),
    easy("Frozen", "AiX-WvMNDPc"),
    easy("Shrek", "mFl8nzZuExE"),
    easy("The Matrix", "zE7PKRjrid4"),
    easy("Gladiator", "Z2FKji5UeXU"),
    easy("Pirates of the Caribbean: The Curse of the Black Pearl", "LkWQvzrv6gI"),
    easy("Back to the Future", "qW2syroSQTs"),
    easy("The Hunger Games", "mgr2tLYYha4"),
    easy("Finding Nemo", "J6nGQu2fae0", { start: 0, duration: 15 }),
    easy("Home Alone", "S7OWoc-j8qQ"),
    easy("Jaws", "rW23RsUTb2Y"),
  ],
  400: [
    medium("Interstellar", "GIUhpzv47YQ"),
    medium("Inception", "i3-jlhJgU9U"),
    medium("The Truman Show", "6U4-KZSoe6g"),
    medium("Mad Max: Fury Road", "QJX3XvkTJQk"),
    medium("Whiplash", "7d_jQycdQGo", { start: 28 }),
    medium("John Wick", "tM47HMT8GGE"),
    medium("Top Gun: Maverick", "IXbnzEHZDPg"),
    medium("Casino Royale", "iZxNbAwY_rk", { start: 4 }),
    medium("Knives Out", "bqAGt9-ByQA"),
    medium("The Prestige", "J8ZXT2HTxqE", { start: 0, duration: 12 }),
    medium("Alien", "3YTIMGmZUr4"),
    medium("Terminator 2: Judgment Day", "CRRlbK5w8AE", { start: 25 }),
    medium("The Sixth Sense", "9zTRxiG2Rno", { start: 3 }),
    medium("Edge of Tomorrow", "vw61gCe2oqI", { start: 23 }),
    medium("La La Land", "7CVfTd-_qbc", { start: 4 }),
    medium("Black Swan", "dwD4JZsAuew"),
    medium("No Country for Old Men", "ZY0DG8rUnCA", { start: 6 }),
    medium("The Grand Budapest Hotel", "jCk70NdkAkY", { start: 5 }),
    medium("The Departed", "EfjbbuKUqak", { start: 4 }),
    medium("Blade Runner 2049", "I4_AaEazcbk", { start: 4 }),
  ],
  600: [
    hard("1917", "YROAHcWiTpA", { start: 6 }),
    hard("Skyfall", "mGhAT72J2I4", { start: 9 }),
    hard("The Revenant", "lM-Yw_NhoDs", { start: 4 }),
    hard("A Quiet Place", "rwDDgGuCVS0", { start: 4 }),
    hard("The Bourne Ultimatum", "JRLNdcmRcFY", { start: 5 }),
    hard("The Martian", "zWoL_W9mt2c", { start: 4 }),
    hard("Mission: Impossible - Fallout", "wb49-oV0F78", { start: 24 }),
    hard("The Batman", "ZOjtEaZUEuI", { start: 5 }),
    hard("Gravity", "OiTiKOy59o4", { start: 26 }),
    hard("Gone Girl", "msz2G_GFzGw", { start: 3 }),
    hard("Dunkirk", "bgS0GPQhzHg", { start: 4 }),
    hard("Ford v Ferrari", "ALXCF2PoYpQ", { start: 5 }),
    hard("The Wolf of Wall Street", "wM6exo00T5I", { start: 4 }),
    hard("Logan", "Gs5r9PZ_rtc", { start: 5 }),
    hard("Deadpool", "K8mJ_SJH4Jk", { start: 4 }),
    hard("The Imitation Game", "nuPZUUED5uk", { start: 26 }),
    hard("Shutter Island", "v8yrZSkKxTA", { start: 24 }),
    hard("Get Out", "uG_KHjd_PSc", { start: 4 }),
    hard("The Conjuring", "XAwpBIXjQrY", { start: 0, duration: 12 }),
    hard("The Shawshank Redemption", "PLl99DlL6b4", { start: 29 }),
  ],
};

export default MOVIE_SCENE_BANK;
