const DEFAULT_START = 2;

const scene = (title, videoId, { start = DEFAULT_START, duration, sourceUrl } = {}) => ({
  q: "Clip",
  a: title,
  videoId,
  start,
  duration,
  sourceUrl: sourceUrl || `https://www.youtube.com/watch?v=${videoId}`,
});

const easy = (title, videoId, options = {}) => scene(title, videoId, { duration: 18, ...options });
const medium = (title, videoId, options = {}) => scene(title, videoId, { duration: 16, ...options });
const hard = (title, videoId, options = {}) => scene(title, videoId, { duration: 14, ...options });

const MOVIE_SCENE_BANK = {
  label: "Movie Scenes",
  icon: "🎞️",
  color: "#F97316",
  isMovieScene: true,
  200: [
    easy("Star Wars: A New Hope", "63HXmKFhi84"),
    easy("Titanic", "_qTZRD1_ybQ"),
    easy("Jurassic Park", "E8WaFvwtphY"),
    easy("The Dark Knight", "SIYkhb2NjfE"),
    easy("Avatar", "5PSNL1qE6VY", { start: 24 }),
    easy("Harry Potter and the Sorcerer's Stone", "VyHV0BRtdxo"),
    easy("The Avengers", "Df5a6wapif8"),
    easy("Spider-Man", "zlwaUJzGqns"),
    easy("The Lion King", "7TavVZMewpY"),
    easy("Toy Story", "g2IF5NG2vU4"),
    easy("Frozen", "AiX-WvMNDPc"),
    easy("Shrek", "mFl8nzZuExE"),
    easy("The Matrix", "zE7PKRjrid4"),
    easy("Gladiator", "Z2FKji5UeXU"),
    easy("Pirates of the Caribbean: The Curse of the Black Pearl", "naQr0uTrH_s"),
    easy("Back to the Future", "qW2syroSQTs"),
    easy("The Hunger Games", "mgr2tLYYha4"),
    easy("Finding Nemo", "J6nGQu2fae0", { start: 0, duration: 15 }),
    easy("Home Alone", "S7OWoc-j8qQ"),
    easy("Jaws", "rW23RsUTb2Y"),
    easy("Forrest Gump", "bLvqoHBptjg"),
    easy("The Godfather", "UaVTIH8mujA"),
    easy("Pulp Fiction", "s7EdQ4FqbhY"),
    easy("Fight Club", "qtRKdVHc-cE"),
    easy("The Incredibles", "-UaGUdNJdRQ"),
    easy("Finding Dory", "JhvrQeY3doI"),
    easy("Up", "ORFWdXl_zJ4"),
    easy("Moana", "n7f6hlKsxxo"),
    easy("Ratatouille", "NgsQ8mVkN8w"),
    easy("Wall-E", "CZ1CATNbXg0"),
    easy("Zootopia", "Y0c3nKWhlIA"),
    easy("The Secret Life of Pets", "i-80SGWfEjM"),
    easy("Despicable Me", "zzCZ1W_CUoI"),
    easy("Minions", "eisKxhjBnZ0"),
    easy("Kung Fu Panda", "NRc-ze7Wrxw"),
    easy("How to Train Your Dragon", "22w7z_lT6YM"),
    easy("Shrek 2", "xBgSfhp5Fxo"),
    easy("Ice Age", "i4noiCRJRoE"),
    easy("Madagascar", "fq5zU9T_Hl4"),
    easy("Cars", "W_H7_tDHFE8"),
    easy("Monsters Inc", "CGbgaHoapFM"),
    easy("The Little Mermaid", "kpGo2_d3oYE"),
    easy("Beauty and the Beast", "pnkgw6pAKkM"),
    easy("Aladdin", "-G5XI61Y9ms"),
    easy("Cinderella", "LfR8Su4ulX0"),
    easy("Snow White", "iV46TJKL8cU"),
    easy("Peter Pan", "L-o0ufCPANo"),
    easy("101 Dalmatians", "VApVpvcGW1A"),
    easy("Bambi", "j_J2-GafTSQ"),
    easy("Tarzan", "Aj7ty6sViiU"),
    easy("Mulan", "KK8FHdFluOQ"),
    easy("Pocahontas", "5iB82S8rHyg"),
    easy("Hercules", "GFqY089piQ4"),
    easy("The Jungle Book", "wIq1Gufcmeo"),
    easy("The Hunchback of Notre Dame", "O6i3lyx1I_g"),
    easy("Alice in Wonderland", "P_IVeP3i7B0"),
    easy("Sleeping Beauty", "CfsyUyi_FJM"),
    easy("Dumbo", "ocWpGdITSR4"),
    easy("Fantasia", "QsNgdYVAv2w"),
    easy("The Terminator", "nGrW-OR2uDk"),
    easy("Alien", "jQ5lPt9edzQ"),
    easy("Predator", "43R9l7EkJwE"),
    easy("RoboCop", "IqvRDhW-XVA"),
    easy("Total Recall", "pPAy56Otr-E"),
    easy("Aliens", "oSeQQlaCZgU"),
    easy("Starship Troopers", "zPYuV_jGk7M"),
    easy("Independence Day", "B1E7h3SeMDk"),
    easy("Men in Black", "UxUTTrU6PA4"),
    easy("Godzilla", "QFxN2oDKk0E"),
    easy("King Kong", "9extfjDZCts"),
    easy("War of the Worlds", "SM6aEEjc5hA"),
    easy("The Day After Tomorrow", "Ku_IseK3xTc"),
    easy("2012", "sFXGrTng0gQ"),
    easy("San Andreas", "yftHosO0eUo"),
    easy("Taken", "XK9zL0ze9O4"),
    easy("The Bourne Identity", "FpKaB5dvQ4g"),
    easy("Mission Impossible", "fsQgc9pCyDU"),
    easy("Die Hard", "jaJuwKCmJbY"),
    easy("Lethal Weapon", "bKeW-MGu-qQ"),
    easy("Rush Hour", "JMiFsFQcFLE"),
    easy("Bad Boys", "hRFY_Fesa9Q"),
    easy("The Fast and the Furious", "2TAOizOnNPo"),
    easy("Fast Five", "vcn2GOuZCKI"),
    easy("The Rock", "a3qcNyjj9ZQ"),
    easy("Con Air", "vYFU0H1I1i0"),
    easy("Face Off", "S-nDX0BeFoQ"),
    easy("Armageddon", "kg_jH47u480"),
    easy("Pearl Harbor", "oGYcxjywx0o"),
    easy("Transformers", "CbX_SIz_9fk"),
    easy("Iron Man", "8ugaeA-nMTc"),
    easy("Captain America", "qi5UTD7kEr0"),
    easy("Black Panther", "xjDjIWPwcPU"),
    easy("Doctor Strange", "h7gvFravm4A"),
    easy("Guardians of the Galaxy", "d96cjJhvlMA"),
    easy("Avengers Endgame", "TcMBFSGVi1c"),
    easy("Avengers Infinity War", "6ZfuNTqbHE8"),
    easy("Thor Ragnarok", "ue80QwXMRHg"),
    easy("Deadpool 2", "D86RtevtfrA"),
    easy("Wonder Woman", "1Q8fG0TtVAY"),
    easy("Aquaman", "WDkg3h8PCVU"),
    easy("Man of Steel", "T6DJcgm3wNY"),
    easy("Justice League", "3cxixDgHUYw"),
    easy("Suicide Squad", "CmRih_VtVAs"),
    easy("Joker", "zAGVQLHvwOY"),
  ],
  400: [
    medium("Interstellar", "GIUhpzv47YQ"),
    medium("Inception", "i3-jlhJgU9U"),
    medium("The Truman Show", "6U4-KZSoe6g"),
    medium("Mad Max: Fury Road", "QJX3XvkTJQk"),
    medium("Whiplash", "7d_jQycdQGo", { start: 28 }),
    medium("John Wick", "tM47HMT8GGE"),
    medium("Top Gun: Maverick", "IXbnzEHZDPg"),
    medium("Casino Royale", "iZxNbAwY_rk", { start: 4 }),
    medium("Knives Out", "bqAGt9-ByQA"),
    medium("The Prestige", "RLtaA9fFNXU", { start: 0, duration: 12 }),
    medium("Alien", "3YTIMGmZUr4"),
    medium("Terminator 2: Judgment Day", "CRRlbK5w8AE", { start: 25 }),
    medium("The Sixth Sense", "9zTRxiG2Rno", { start: 3 }),
    medium("Edge of Tomorrow", "vw61gCe2oqI", { start: 23 }),
    medium("La La Land", "7CVfTd-_qbc", { start: 4 }),
    medium("Black Swan", "dwD4JZsAuew"),
    medium("No Country for Old Men", "ZY0DG8rUnCA", { start: 6 }),
    medium("The Grand Budapest Hotel", "jCk70NdkAkY", { start: 5 }),
    medium("The Departed", "r-MiSNsCdQ4", { start: 4 }),
    medium("Blade Runner 2049", "I4_AaEazcbk", { start: 4 }),
    medium("Good Will Hunting", "PaZVjZEFkRs"),
    medium("A Beautiful Mind", "EajIlG_OCvw"),
    medium("The Social Network", "lB95KLmpLR4"),
    medium("Moneyball", "-4QPVo0UIzc"),
    medium("The Big Short", "vgqG3ITMv1Q"),
    medium("Wall Street", "NtTkHu8R2_Q"),
    medium("Margin Call", "IjZ-ke1kJrA"),
    medium("Boiler Room", "kgCLG4gCAvI"),
    medium("The Founder", "AX2uz2XYkbo"),
    medium("Steve Jobs", "aEr6K1bwIVs"),
    medium("Rush", "4XA73ni9eVs"),
    medium("Seabiscuit", "a6Zjij_glsI"),
    medium("The Pursuit of Happyness", "DMOBlEcRuw8"),
    medium("Rocky", "-Hk-LYcavrw"),
    medium("Creed", "Uv554B7YHk4"),
    medium("Raging Bull", "F2UKuKxCJqc"),
    medium("The Wrestler", "61-GFxjTyV0"),
    medium("Foxcatcher", "8361stZ8n0w"),
    medium("Million Dollar Baby", "5_RsHRmIRBY"),
    medium("Cinderella Man", "PpdRWplFjG8"),
    medium("Warrior", "I5kzcwcQA1Q"),
    medium("Fury", "q94n3eWOWXM"),
    medium("Saving Private Ryan", "9CiW_DgxCnQ"),
    medium("Full Metal Jacket", "n2i917l5RFc"),
    medium("Platoon", "R8weLPF4qBQ"),
    medium("Apocalypse Now", "9l-ViOOFH-s"),
    medium("Black Hawk Down", "2GfBkC3qs78"),
    medium("Hacksaw Ridge", "s2-1hz1juBI"),
    medium("The Thin Red Line", "mKl5_OxKBn8"),
    medium("Jarhead", "-aBP-c28_1M"),
    medium("Lone Survivor", "yoLFk4JK_RM"),
    medium("American Sniper", "99k3u9ay1gs"),
    medium("Zero Dark Thirty", "LJFra3B9sbA"),
    medium("Argo", "JW3WfSFgrVY"),
    medium("Munich", "feIjYUEWVxk"),
    medium("The Hurt Locker", "AIbFvqFYRT4"),
    medium("Green Zone", "e3KJ21TLKVE"),
    medium("Body of Lies", "bxQW8NGNb60"),
    medium("Syriana", "JvTni7Nggi0"),
    medium("Sicario", "G8tlEcnrGnU"),
    medium("Hell or High Water", "JQoqsKoJVDw"),
    medium("Wind River", "W7V9Fsll5qM"),
    medium("Prisoners", "bpXfcTF6iVk"),
    medium("Nightcrawler", "u1uP_8VJkDQ"),
    medium("Drive", "KBiOF3y1W0Y"),
    medium("Collateral", "JlcX_GXtf40"),
    medium("Heat", "1O3iRdiplB0"),
    medium("The Town", "uAjECYnrYks"),
    medium("Gone Baby Gone", "JyT0_wfQR2Y"),
    medium("Mystic River", "W7NktJhrRYQ"),
    medium("Zodiac", "yNncHPl1UXg"),
    medium("Seven", "KPOuJGkpblk"),
    medium("The Silence of the Lambs", "6iB21hsprAQ"),
    medium("Red Dragon", "zLcI8OFyNUo"),
    medium("Hannibal", "Lr3OavheNu0"),
    medium("Manhunter", "Nbpk0pv60DE"),
    medium("American Psycho", "5YnGhW4UEhc"),
    medium("Filth", "uWGhCLu0fZg"),
    medium("Trainspotting", "8LuxOYIpu-I"),
    medium("Snatch", "9Jar2XkBboo"),
    medium("Lock Stock and Two Smoking Barrels", "HY7mRdQuUSw"),
    medium("The Gentlemen", "2B0RpUGss2c"),
    medium("Baby Driver", "zTvJJnoWIPk"),
    medium("Hot Fuzz", "ayTnvVpj9t4"),
    medium("Shaun of the Dead", "LIfcaZ4pC-4"),
    medium("Scott Pilgrim vs the World", "7wd5KEaOtm4"),
    medium("Kick-Ass", "2rpXHqnGDXo"),
    medium("Atomic Blonde", "yIUube1pSC0"),
    medium("Red Sparrow", "PmUL6wMpMWw"),
    medium("Salt", "QZ40WlshNwU"),
    medium("Anna", "VVhkuL3d_Tc"),
    medium("Lucy", "bN7ksFEVO9U"),
    medium("The Fifth Element", "pqs9ycvKfD8"),
    medium("Leon The Professional", "aNQqoExfQsg"),
    medium("Taxi Driver", "T5IligQP7Fo"),
    medium("Goodfellas", "2ilzidi_J8Q"),
    medium("Casino", "EJXDMwGWhoA"),
    medium("The Irishman", "WHXxVmeGQUc"),
    medium("Public Enemies", "Ee92mDZu_PI"),
    medium("Donnie Brasco", "omIiE9KKj2o"),
    medium("The Untouchables", "2cGat1xI8G8"),
    medium("American Gangster", "BV_nssS6Zkg"),
    medium("Blow", "scWkP1GdnuU"),
    medium("The Departed", "iojhqm0JTW4"),
    medium("Scarface", "cv276Wg3e7I"),
    medium("Carlito's Way", "_ZMd4Baswb4"),
  ],
  600: [
    hard("1917", "YqNYrYUiMfg", { start: 6 }),
    hard("Skyfall", "6kw1UVovByw", { start: 9 }),
    hard("The Revenant", "lM-Yw_NhoDs", { start: 4 }),
    hard("A Quiet Place", "rwDDgGuCVS0", { start: 4 }),
    hard("The Bourne Ultimatum", "JRLNdcmRcFY", { start: 5 }),
    hard("The Martian", "ej3ioOneTy8", { start: 4 }),
    hard("Mission: Impossible - Fallout", "wb49-oV0F78", { start: 24 }),
    hard("The Batman", "mqqft2x_Aa4", { start: 5 }),
    hard("Gravity", "OiTiKOy59o4", { start: 26 }),
    hard("Gone Girl", "2-_-1nJf8Vg", { start: 3 }),
    hard("Dunkirk", "bgS0GPQhzHg", { start: 4 }),
    hard("Ford v Ferrari", "ALXCF2PoYpQ", { start: 5 }),
    hard("The Wolf of Wall Street", "iszwuX1AK6A", { start: 4 }),
    hard("Logan", "Gs5r9PZ_rtc", { start: 5 }),
    hard("Deadpool", "K8mJ_SJH4Jk", { start: 4 }),
    hard("The Imitation Game", "nuPZUUED5uk", { start: 26 }),
    hard("Shutter Island", "v8yrZSkKxTA", { start: 24 }),
    hard("Get Out", "uG_KHjd_PSc", { start: 4 }),
    hard("The Conjuring", "XAwpBIXjQrY", { start: 0, duration: 12 }),
    hard("The Shawshank Redemption", "PLl99DlL6b4", { start: 29 }),
    hard("There Will Be Blood", "FeSLPELpMeM"),
    hard("The Master", "RApl06pYIuU"),
    hard("Phantom Thread", "xNsiQMeSvMk"),
    hard("Licorice Pizza", "ofnXPwUPENo"),
    hard("Magnolia", "KnamcFv_N9Q"),
    hard("Punch-Drunk Love", "KGqn5k227HY"),
    hard("Boogie Nights", "YN7pcEa83dU"),
    hard("Inherent Vice", "wZfs22E7JmI"),
    hard("Hard Eight", "nIOmotayDMY"),
    hard("The Royal Tenenbaums", "caMgokYWboU"),
    hard("Rushmore", "6ZVdXXG3KN8"),
    hard("Moonrise Kingdom", "_eOI3AamSm8"),
    hard("Isle of Dogs", "dt__kig8PVU"),
    hard("The French Dispatch", "TcPk2p0Zaw4"),
    hard("Bottle Rocket", "JJPQ-NnjZR0"),
    hard("The Life Aquatic", "yh401Rmkq0o"),
    hard("The Darjeeling Limited", "B2R7O2IlndM"),
    hard("Fantastic Mr Fox", "n2igjYFojUo"),
    hard("Asteroid City", "9FXCSXuGTF4"),
    hard("Synecdoche New York", "i2q8F0yRmrs"),
    hard("Being John Malkovich", "LEtlqumjXLw"),
    hard("Adaptation", "uougMRq-MSo"),
    hard("Eternal Sunshine of the Spotless Mind", "07-QBnEkgXU"),
    hard("Anomalisa", "WQkHA3fHk_0"),
    hard("I'm Thinking of Ending Things", "cDTg62vsV4U"),
    hard("Her", "dJTU48_yghs"),
    hard("Lost in Translation", "W6iVPCRflQM"),
    hard("Marie Antoinette", "yBWyKRoh98U"),
    hard("The Virgin Suicides", "YRPXQ3XcpKc"),
    hard("Somewhere", "iEga7Hz9a3U"),
    hard("The Beguiled", "iBoLK5z_FHo"),
    hard("On the Rocks", "Xn3sK4WiviA"),
    hard("Priscilla", "DBWk6BohVXk"),
    hard("Melancholia", "6IZGwvxhXvw"),
    hard("Antichrist", "Fo-2fZJfRwY"),
    hard("Dogville", "XhMD80v8uFQ"),
    hard("Breaking the Waves", "dPmWixRLFPQ"),
    hard("Dogtooth", "s0J8Y6McHVI"),
    hard("The Lobster", "LTNZmOJxuAc"),
    hard("The Killing of a Sacred Deer", "CQFdGfwChtw"),
    hard("The Favourite", "SYb-wkehT1g"),
    hard("Poor Things", "RlbR5N6veqw"),
    hard("Kinds of Kindness", "NGOL2_mI9Hw"),
    hard("Holy Motors", "NWu9WjEcdbk"),
    hard("Enter the Void", "HkPMjoUqYXU"),
    hard("Climax", "Hi69nL_VrTE"),
    hard("Irreversible", "ZoDtJjqkfxU"),
    hard("Mandy", "rI054ow6KJk"),
    hard("Color Out of Space", "y4Rn5XAw8YU"),
    hard("Pig", "gH6vhlNTLUk"),
    hard("Dream Scenario", "q3x9iUL-74w"),
    hard("Leaving Las Vegas", "O4HrGa2-RLc"),
    hard("Uncut Gems", "vTfJp2Ts9X8"),
    hard("Good Time", "AVyGCxHZ_Ko"),
    hard("The Rover", "ChM2icbWo9w"),
    hard("Lawless", "HibcC7w5l1g"),
    hard("Killing Them Softly", "xNoSRlOJXm0"),
    hard("Out of the Furnace", "Gw0qH34cbRE"),
    hard("Black Mass", "CE3e3hGF2jc"),
    hard("The Place Beyond the Pines", "KepnbJT5nBw"),
    hard("Blue Valentine", "aILx69WrRhQ"),
    hard("Only God Forgives", "YqAeVosG4zI"),
    hard("The Neon Demon", "cipOTUO0CmU"),
    hard("Bronson", "u2VM7UTy1xw"),
    hard("Valhalla Rising", "Es-CEAWXcfw"),
    hard("Pusher", "A4VKaMrvXgk"),
    hard("Cosmopolis", "PvYyKTZtUG0"),
    hard("The Tree of Life", "RrAz1YLh8nY"),
    hard("A Hidden Life", "qJXmdY4lVR0"),
    hard("Knight of Cups", "SI2j1FHCjtM"),
    hard("To the Wonder", "NTAzcTZTY1g"),
    hard("Song to Song", "XZ-gPv3HpW8"),
    hard("Days of Heaven", "EzZ8phk8yYc"),
    hard("Waking Life", "edrGozs6W_I"),
    hard("A Scanner Darkly", "hkjDUERgCQw"),
    hard("Before Sunrise", "6MUcuqbGTxc"),
    hard("Before Sunset", "oI3UuneLcyU"),
    hard("Before Midnight", "Kv6JWoVKlGY"),
    hard("Boyhood", "B4vhBHY87dg"),
    hard("Paris Texas", "3j8ypqxfiT4"),
    hard("Wings of Desire", "liAOEb5rnbA"),
    hard("The Elephant Man", "AF9gNKJi79g"),
    hard("Mulholland Drive", "jbZJ487oJlY"),
    hard("Lost Highway", "4Y7LpMraInc"),
    hard("Wild at Heart", "dQIdBfrF0Ik"),
    hard("Blue Velvet", "rAA6imfqMYQ"),
    hard("Twin Peaks Fire Walk with Me", "GJdH09lo3DM"),
    hard("Eraserhead", "7WAzFWu2tVw"),
  ],
};

export default MOVIE_SCENE_BANK;
