// Pack 2: new categories — Space, Math, Language.
// Criteria: 30/30/30 minimum, no leaked answers, fact-checked, no duplicates across categories.
const qa = (rows) => rows.map(([q, a]) => ({ q, a }));

const NEW_CATEGORIES_PACK_2 = {
  // ===================== SPACE =====================
  space: {
    label: "Space",
    icon: "\u{1F680}",
    color: "#6366F1",
    200: qa([
      ["Which planet is closest to the Sun?", "Mercury"],
      ["Which planet is known as the Red Planet?", "Mars"],
      ["Which planet has the most visible rings?", "Saturn"],
      ["Which is the largest planet in our solar system?", "Jupiter"],
      ["What star is at the center of our solar system?", "The Sun"],
      ["Which galaxy do we live in?", "The Milky Way"],
      ["Who was the first human to walk on the Moon?", "Neil Armstrong"],
      ["How long does it take light from the Sun to reach Earth?", "About 8 minutes"],
      ["Which planet is famous for its Great Red Spot?", "Jupiter"],
      ["What do we call a collection of stars forming a pattern?", "A constellation"],
      ["Which planet is tilted on its side?", "Uranus"],
      ["What is the name of the North Star?", "Polaris"],
      ["Which is the outermost planet in our solar system?", "Neptune"],
      ["What is a light-year?", "The distance light travels in one year"],
      ["What company founded by Elon Musk runs private space launches?", "SpaceX"],
      ["What was the first artificial satellite?", "Sputnik 1"],
      ["Which planet has a day longer than its year?", "Venus"],
      ["What is a shooting star really?", "A meteor"],
      ["Which celestial body causes ocean tides on Earth?", "The Moon"],
      ["What pulls objects toward the center of a planet?", "Gravity"],
      ["What is Earth's closest planetary neighbor on one side?", "Venus"],
      ["What is Earth's closest planetary neighbor on the other side?", "Mars"],
      ["Which planet rotates the fastest?", "Jupiter"],
      ["How many planets are in our solar system?", "8"],
      ["What is the name of our own moon?", "Luna"],
      ["Which mission first landed humans on the Moon?", "Apollo 11"],
      ["What do astronauts wear to survive outside a spacecraft?", "A spacesuit"],
      ["What is a solar eclipse?", "When the Moon blocks the Sun's light from Earth"],
      ["What is the phase when we see no Moon at all?", "New moon"],
      ["Which U.S. space agency put people on the Moon?", "NASA"],
    ]),
    400: qa([
      ["What is the largest moon of Saturn?", "Titan"],
      ["Who was the second person to walk on the Moon?", "Buzz Aldrin"],
      ["Which asteroid belt lies between two planets?", "Between Mars and Jupiter"],
      ["What is the name of our nearest stellar neighbor beyond the Sun?", "Proxima Centauri"],
      ["What type of matter makes up about 27% of the universe?", "Dark matter"],
      ["Approximately how old is the universe?", "13.8 billion years"],
      ["What space station has been continuously occupied since 2000?", "International Space Station"],
      ["Which NASA rover landed on Mars in 2021?", "Perseverance"],
      ["What is the largest volcano in our solar system?", "Olympus Mons"],
      ["Which galaxy is on a collision course with the Milky Way?", "Andromeda Galaxy"],
      ["What telescope was launched in 2021 to succeed Hubble's role?", "James Webb Space Telescope"],
      ["What is the first probe to leave the solar system called?", "Voyager 1"],
      ["What is the icy region beyond Neptune filled with small bodies?", "The Kuiper Belt"],
      ["Which object was reclassified from planet to dwarf planet in 2006?", "Pluto"],
      ["What is the Sun's outermost atmospheric layer called?", "The corona"],
      ["What type of galaxy is the Milky Way?", "Barred spiral"],
      ["What is a star explosion at the end of a massive star's life?", "Supernova"],
      ["What is the hottest planet in our solar system?", "Venus"],
      ["What causes the aurora borealis?", "Solar wind particles interacting with Earth's magnetic field"],
      ["Which year was the Hubble Space Telescope launched?", "1990"],
      ["Who formulated the laws of planetary motion?", "Johannes Kepler"],
      ["Who described universal gravitation in the 1600s?", "Isaac Newton"],
      ["What is a pulsar?", "A rapidly rotating neutron star that emits beams of radiation"],
      ["What is the remnant of a collapsed massive star with huge density?", "A neutron star"],
      ["Which Apollo mission famously returned safely after an onboard explosion?", "Apollo 13"],
      ["What is the Sun's main fuel source?", "Hydrogen (fused into helium)"],
      ["What is the name of the first space tourist company's suborbital vehicle by Bezos?", "New Shepard"],
      ["Which planet has the most moons currently known?", "Saturn"],
      ["What causes a total solar eclipse?", "The Moon perfectly covering the Sun from Earth's view"],
      ["What spacecraft photographed Pluto closely in 2015?", "New Horizons"],
    ]),
    600: qa([
      ["What is the boundary of a black hole beyond which nothing escapes?", "The event horizon"],
      ["What hypothetical cloud of icy bodies surrounds the outer solar system?", "The Oort Cloud"],
      ["What radiation is theoretically emitted by black holes?", "Hawking radiation"],
      ["What is normal matter made of protons and neutrons called?", "Baryonic matter"],
      ["What is the theory of a rapid early expansion of the universe called?", "Inflationary theory"],
      ["What five special points exist in a two-body orbital system?", "Lagrange points"],
      ["What type of supernova results from a white dwarf exceeding its mass limit?", "Type Ia"],
      ["Whose equation estimates the number of contactable civilizations in our galaxy?", "Frank Drake's equation"],
      ["What brief intense bursts of radio waves come from distant space?", "Fast radio bursts"],
      ["Which crater is linked to the dinosaur extinction event?", "Chicxulub"],
      ["Which triple star system is nearest to the Sun?", "Alpha Centauri"],
      ["Which scale rates civilizations by energy use (Type I, II, III)?", "The Kardashev scale"],
      ["What paradox asks why we haven't found alien civilizations yet?", "The Fermi paradox"],
      ["What is a neutron star with an extremely strong magnetic field called?", "A magnetar"],
      ["What is the habitable zone around a star sometimes nicknamed?", "The Goldilocks Zone"],
      ["What relic radiation from the early universe was discovered in 1964?", "Cosmic microwave background"],
      ["What was the first exoplanet discovered orbiting a Sun-like star?", "51 Pegasi b"],
      ["What is an object too massive to be a planet but too light to fuse hydrogen?", "A brown dwarf"],
      ["In what year was the first direct image of a black hole released?", "2019"],
      ["What bends light from distant objects near a massive body?", "Gravitational lensing"],
      ["What stretching effect happens near a black hole's singularity?", "Spaghettification"],
      ["What rotating disk forms around a compact object as matter falls in?", "An accretion disk"],
      ["What was the largest telescope in the Canaries before being surpassed?", "Gran Telescopio Canarias"],
      ["Which Jovian moon has a subsurface ocean and is a prime target for life?", "Europa"],
      ["Which Saturnian moon shoots water geysers from its south pole?", "Enceladus"],
      ["Which is the fastest spacecraft ever launched?", "Parker Solar Probe"],
      ["Which astronomer discovered four of Jupiter's moons in 1610?", "Galileo Galilei"],
      ["Which theory describes gravity as curvature of spacetime?", "General relativity"],
      ["What is the discovered minimum distance two black holes merge at?", "Schwarzschild radius boundary"],
      ["What is the approximate temperature of the cosmic microwave background?", "2.725 Kelvin"],
    ]),
  },

  // ===================== MATH =====================
  math: {
    label: "Math",
    icon: "\u{1F9EE}",
    color: "#14B8A6",
    200: qa([
      ["What is 12 + 8?", "20"],
      ["What is 15 \u00D7 3?", "45"],
      ["What is 100 \u2212 37?", "63"],
      ["What is 144 \u00F7 12?", "12"],
      ["What is 7 squared?", "49"],
      ["What is the square root of 81?", "9"],
      ["What is 25% of 80?", "20"],
      ["What is 1/2 + 1/4?", "3/4"],
      ["What is 3 \u00D7 7 \u00D7 2?", "42"],
      ["What is 9 \u00D7 11?", "99"],
      ["What is 17 + 23?", "40"],
      ["What is 6 factorial?", "720"],
      ["What is 2 + 2 \u00D7 3 (order of operations)?", "8"],
      ["What is the sum of angles in a triangle?", "180 degrees"],
      ["What is 1000 \u2212 1?", "999"],
      ["What is 8 \u00D7 8?", "64"],
      ["What is half of 100?", "50"],
      ["What is 3 to the power of 4?", "81"],
      ["What is 15 + 25 + 35?", "75"],
      ["What is the perimeter of a square with side 5?", "20"],
      ["What is the area of a rectangle with width 4 and length 7?", "28"],
      ["What is 50 \u00D7 50?", "2500"],
      ["What is 0 factorial?", "1"],
      ["What is 11 \u00D7 12?", "132"],
      ["What is 28 \u00F7 7?", "4"],
      ["What is 10% of 200?", "20"],
      ["What number comes next: 2, 4, 8, 16?", "32"],
      ["What number comes next: 1, 1, 2, 3, 5, 8?", "13"],
      ["How many degrees is a right angle?", "90"],
      ["What is 13 \u00D7 13?", "169"],
    ]),
    400: qa([
      ["What is 7 \u00D7 13?", "91"],
      ["What is the square root of 144?", "12"],
      ["Solve: 2x + 4 = 16, find x.", "6"],
      ["What is the circumference of a circle with radius 7 (use \u03C0 \u2248 3.14)?", "43.96"],
      ["What is the derivative of x squared?", "2x"],
      ["What is sin(90 degrees)?", "1"],
      ["What is cos(0)?", "1"],
      ["What is log base 10 of 100?", "2"],
      ["What is 2^3 \u00D7 2^4?", "128"],
      ["What is 5! / 3!?", "20"],
      ["What is the area of a triangle with base 10 and height 6?", "30"],
      ["What is \u03C0 rounded to 4 decimals?", "3.1416"],
      ["Slope of a line perpendicular to y = 2x + 3?", "\u22121/2"],
      ["Hypotenuse of a right triangle with legs 3 and 4?", "5"],
      ["What is e rounded to 3 decimals?", "2.718"],
      ["What is the volume of a cube with side 4?", "64"],
      ["Probability of rolling a 6 on a fair die?", "1/6"],
      ["What is 40% of 250?", "100"],
      ["What is the mean of 2, 4, 6, 8, 10?", "6"],
      ["What is the median of 1, 3, 5, 7, 9?", "5"],
      ["What is log base 2 of 8?", "3"],
      ["What is the sum of the first 10 natural numbers?", "55"],
      ["How many ways to choose 2 from 12 (12 choose 2)?", "66"],
      ["What is the discriminant of x\u00B2 + 4x + 4?", "0"],
      ["Write the quadratic formula.", "x = (\u2212b \u00B1 \u221A(b\u00B2 \u2212 4ac)) / 2a"],
      ["What is 15% of 80?", "12"],
      ["What is tan(45 degrees)?", "1"],
      ["What is 2^10?", "1024"],
      ["Simplify: 6/9.", "2/3"],
      ["If a triangle has angles 60 and 70, what is the third?", "50 degrees"],
    ]),
    600: qa([
      ["What is the derivative of sin(x)?", "cos(x)"],
      ["What is the integral of 1/x?", "ln|x| + C"],
      ["What is the limit of sin(x)/x as x approaches 0?", "1"],
      ["Write Euler's identity.", "e^(i\u03C0) + 1 = 0"],
      ["What famous conjecture concerns the zeros of the zeta function?", "The Riemann Hypothesis"],
      ["State Fermat's Last Theorem in one sentence.", "No positive integers a, b, c satisfy a^n + b^n = c^n for n > 2"],
      ["Which theorem states any strong formal system has undecidable statements?", "G\u00F6del's Incompleteness Theorem"],
      ["What does the Fundamental Theorem of Calculus connect?", "Differentiation and integration"],
      ["What paradox uses the axiom of choice to split a sphere into two copies?", "Banach\u2013Tarski paradox"],
      ["What is i\u00B2?", "\u22121"],
      ["What is the value of the golden ratio (3 decimals)?", "1.618"],
      ["What is the 10th Fibonacci number?", "55"],
      ["What is the integral of e^x dx?", "e^x + C"],
      ["Give the prime factorization of 84.", "2^2 \u00D7 3 \u00D7 7"],
      ["What is the determinant of the 2\u00D72 matrix [[1,2],[3,4]]?", "\u22122"],
      ["How many permutations of 3 from 5 items (5P3)?", "60"],
      ["What is the limit as x approaches infinity of (1 + 1/x)^x?", "e"],
      ["Best strategy in the Monty Hall problem?", "Always switch (wins 2/3 of the time)"],
      ["What is the cardinality of the real numbers denoted by?", "\u05D0_1 or 2^\u05D0_0"],
      ["What function grows faster than any primitive recursive function?", "The Ackermann function"],
      ["What does Euler's totient function \u03C6(n) count?", "Integers up to n coprime with n"],
      ["What is the integral of cos(x) dx?", "sin(x) + C"],
      ["What is the derivative of ln(x)?", "1/x"],
      ["What is the sum 1 + 1/2 + 1/4 + 1/8 ... to infinity?", "2"],
      ["What are the 3 Pythagorean triples in (3,4,_), (5,12,_), (8,15,_)?", "5, 13, 17"],
      ["Solve for x: log_2(x) = 5.", "32"],
      ["What is the derivative of x^n?", "n \u00B7 x^(n\u22121)"],
      ["What is the sum of interior angles of an n-sided polygon?", "(n \u2212 2) \u00D7 180 degrees"],
      ["What does the Cauchy\u2013Schwarz inequality relate?", "Inner products and norms of vectors"],
      ["What is the volume of a sphere of radius r?", "(4/3) \u03C0 r\u00B3"],
    ]),
  },

  // ===================== LANGUAGE =====================
  language: {
    label: "Language",
    icon: "\u{1F5E3}\uFE0F",
    color: "#EF4444",
    200: qa([
      ["\"Hola, \u00BFc\u00F3mo est\u00E1s?\"", "Spanish"],
      ["\"Bonjour, comment allez-vous?\"", "French"],
      ["\"Guten Tag, wie geht's?\"", "German"],
      ["\"Ciao, come stai?\"", "Italian"],
      ["\"Ol\u00E1, como est\u00E1?\"", "Portuguese"],
      ["\"\u3053\u3093\u306B\u3061\u306F\" (Konnichiwa)", "Japanese"],
      ["\"\u4F60\u597D\" (N\u012D h\u01CEo)", "Mandarin Chinese"],
      ["\"\uC548\uB155\uD558\uC138\uC694\" (Annyeonghaseyo)", "Korean"],
      ["\"Hallo, hoe gaat het?\"", "Dutch"],
      ["\"Hej, hur m\u00E5r du?\"", "Swedish"],
      ["\"Cze\u015B\u0107, jak si\u0119 masz?\"", "Polish"],
      ["\"\u041F\u0440\u0438\u0432\u0435\u0442, \u043A\u0430\u043A \u0434\u0435\u043B\u0430?\" (Privet, kak dela?)", "Russian"],
      ["\"Merhaba, nas\u0131ls\u0131n?\"", "Turkish"],
      ["\"\u0645\u0631\u062D\u0628\u0627\u060C \u0643\u064A\u0641 \u062D\u0627\u0644\u0643\u061F\"", "Arabic"],
      ["\"\u0393\u03B5\u03B9\u03B1 \u03C3\u03B1\u03C2\" (Yia sas)", "Greek"],
      ["\"Hej, hvordan har du det?\"", "Danish"],
      ["\"Hei, hvordan har du det?\"", "Norwegian"],
      ["\"Hei, mit\u00E4 kuuluu?\"", "Finnish"],
      ["\"Au revoir!\"", "French"],
      ["\"Danke sch\u00F6n.\"", "German"],
      ["\"Grazie mille!\"", "Italian"],
      ["\"Obrigado.\"", "Portuguese"],
      ["\"\u3042\u308A\u304C\u3068\u3046\" (Arigatou)", "Japanese"],
      ["\"\u8C22\u8C22\" (Xi\u00E8xie)", "Mandarin Chinese"],
      ["\"\uAC10\uC0AC\uD569\uB2C8\uB2E4\" (Gamsahamnida)", "Korean"],
      ["\"\u0421\u043F\u0430\u0441\u0438\u0431\u043E\" (Spasibo)", "Russian"],
      ["\"Je t'aime.\"", "French"],
      ["\"Te amo.\"", "Spanish"],
      ["\"Ich liebe dich.\"", "German"],
      ["\"\u00A1Buenos d\u00EDas!\"", "Spanish"],
    ]),
    400: qa([
      ["\"Dobrodo\u0161li!\" (welcome)", "Croatian"],
      ["\"D\u011Bkuji\"", "Czech"],
      ["\"K\u00F6sz\u00F6n\u00F6m\"", "Hungarian"],
      ["\"Mul\u021Bumesc\"", "Romanian"],
      ["\"\u0411\u043B\u0430\u0433\u043E\u0434\u0430\u0440\u044F\" (Blagodarya)", "Bulgarian"],
      ["\"Dobrodo\u0161el, \u0161to radi\u0161?\"", "Serbian"],
      ["\"Dobr\u00FD de\u0148\"", "Slovak"],
      ["\"Labas rytas\"", "Lithuanian"],
      ["\"Sveiki\"", "Latvian"],
      ["\"Tere, kuidas sul l\u00E4heb?\"", "Estonian"],
      ["\"\u05E9\u05DC\u05D5\u05DD, \u05DE\u05D4 \u05E0\u05E9\u05DE\u05E2?\" (Shalom, ma nishma?)", "Hebrew"],
      ["\"Sawubona\"", "Zulu"],
      ["\"\u0928\u092E\u0938\u094D\u0924\u0947\" (Namaste)", "Hindi"],
      ["\"Jambo!\"", "Swahili"],
      ["\"\u0E2A\u0E27\u0E31\u0E2A\u0E14\u0E35\u0E04\u0E23\u0E31\u0E1A\" (Sawasdee khrap)", "Thai"],
      ["\"Xin ch\u00E0o\"", "Vietnamese"],
      ["\"Selamat pagi\"", "Indonesian"],
      ["\"Kumusta ka?\"", "Filipino (Tagalog)"],
      ["\"Ma'a as-salaama\"", "Arabic"],
      ["\"Saluton, mia amiko!\"", "Esperanto"],
      ["\"Dia dhuit\"", "Irish"],
      ["\"Bore da\"", "Welsh"],
      ["\"Hola, qu\u00E8 tal?\"", "Catalan"],
      ["\"Kaixo, zer moduz?\"", "Basque"],
      ["\"\u03A0\u03CE\u03C2 \u03C3\u03B5 \u03BB\u03AD\u03BD\u03B5;\" (How are you called?)", "Greek"],
      ["\"Salaam, chetori?\"", "Persian (Farsi)"],
      ["\"Ni hao ma?\"", "Mandarin Chinese"],
      ["\"\u0938\u0941\u092A\u094D\u0930\u092D\u093E\u0924\" (Suprabhat - good morning)", "Hindi"],
      ["\"Jak leci?\" (how's it going?)", "Polish"],
      ["\"\u0E2A\u0E27\u0E31\u0E2A\u0E14\u0E35\u0E04\u0E48\u0E30\" (Sawatdee ka)", "Thai"],
    ]),
    600: qa([
      ["\"Nda woye, nde ghin bo?\"", "Yoruba"],
      ["\"Akwaaba!\" (welcome)", "Twi (Akan)"],
      ["\"Barka da zuwa\"", "Hausa"],
      ["\"Selamat datang\"", "Malay"],
      ["\"M\u00ECngalar b\u00E0\"", "Burmese"],
      ["\"Sawatdee pi mai\" (happy new year)", "Lao"],
      ["\"Ayubowan\"", "Sinhala"],
      ["\"Vanakkam\"", "Tamil"],
      ["\"\u09A8\u09AE\u09B8\u09CD\u0995\u09BE\u09B0\" (Nomoshkar)", "Bengali"],
      ["\"Swastika, namaskar\"", "Nepali"],
      ["\"Minggalarba\"", "Burmese"],
      ["\"Chum reap suor\"", "Khmer (Cambodian)"],
      ["\"Sat sri akal\"", "Punjabi"],
      ["\"Kem cho?\"", "Gujarati"],
      ["\"Halo, apa kabar?\"", "Indonesian"],
      ["\"Kia ora\"", "M\u0101ori"],
      ["\"Aloha\"", "Hawaiian"],
      ["\"Talofa\"", "Samoan"],
      ["\"Malo e lelei\"", "Tongan"],
      ["\"Bul\u00E4!\"", "Fijian"],
      ["\"Goeiedag!\"", "Afrikaans"],
      ["\"Molo\"", "Xhosa"],
      ["\"Sannu\"", "Hausa"],
      ["\"Oo\"", "Oromo"],
      ["\"Selam\"", "Amharic"],
      ["\"Salom, yakhshimisiz?\"", "Uzbek"],
      ["\"Salam, s\u0259nin ad\u0131n n\u0259dir?\"", "Azerbaijani"],
      ["\"Gamardjoba\"", "Georgian"],
      ["\"Barev dzez\"", "Armenian"],
      ["\"S\u0103n\u0103tate!\" (cheers)", "Romanian"],
    ]),
  },
};

export default NEW_CATEGORIES_PACK_2;
