// Pack 2: new categories — Space, Math, Language.
// Criteria: 30/30/30 minimum, no leaked answers, fact-checked, no duplicates across categories.
const qa = (rows) => rows.map(([q, a]) => ({ q, a }));
const qwMovie = (rows) => rows.map(([a, wiki]) => ({ q: "Guess the movie from the image", a, wiki }));
const qwShow = (rows) => rows.map(([a, wiki]) => ({ q: "Guess the TV show from the image", a, wiki }));

const NEW_CATEGORIES_PACK_2 = {
  // ===================== SPACE =====================
  space: {
    label: "Space",
    icon: "\u{1F680}",
    color: "#6366F1",
    200: qa([
      ["Which planet is closest to the Sun?", "Mercury"],
      ["Which planet is known as the Red Planet?", "Mars"],
      ["Which planet has the most visible rings?", "Saturn"],
      ["Which is the largest planet in our solar system?", "Jupiter"],
      ["What star is at the center of our solar system?", "The Sun"],
      ["Which galaxy do we live in?", "The Milky Way"],
      ["Who was the first human to walk on the Moon?", "Neil Armstrong"],
      ["How long does it take light from the Sun to reach Earth?", "About 8 minutes"],
      ["Which planet is famous for its Great Red Spot?", "Jupiter"],
      ["What do we call a collection of stars forming a pattern?", "A constellation"],
      ["Which planet is tilted on its side?", "Uranus"],
      ["What is the name of the North Star?", "Polaris"],
      ["Which is the outermost planet in our solar system?", "Neptune"],
      ["What is a light-year?", "The distance light travels in one year"],
      ["What company founded by Elon Musk runs private space launches?", "SpaceX"],
      ["What was the first artificial satellite?", "Sputnik 1"],
      ["Which planet has a day longer than its year?", "Venus"],
      ["What is a shooting star really?", "A meteor"],
      ["Which celestial body causes ocean tides on Earth?", "The Moon"],
      ["What pulls objects toward the center of a planet?", "Gravity"],
      ["What is Earth's closest planetary neighbor on one side?", "Venus"],
      ["What is Earth's closest planetary neighbor on the other side?", "Mars"],
      ["Which planet rotates the fastest?", "Jupiter"],
      ["How many planets are in our solar system?", "8"],
      ["What is the name of our own moon?", "Luna"],
      ["Which mission first landed humans on the Moon?", "Apollo 11"],
      ["What do astronauts wear to survive outside a spacecraft?", "A spacesuit"],
      ["What is a solar eclipse?", "When the Moon blocks the Sun's light from Earth"],
      ["What is the phase when we see no Moon at all?", "New moon"],
      ["Which U.S. space agency put people on the Moon?", "NASA"],
    ]),
    400: qa([
      ["What is the largest moon of Saturn?", "Titan"],
      ["Who was the second person to walk on the Moon?", "Buzz Aldrin"],
      ["Which asteroid belt lies between two planets?", "Between Mars and Jupiter"],
      ["What is the name of our nearest stellar neighbor beyond the Sun?", "Proxima Centauri"],
      ["What type of matter makes up about 27% of the universe?", "Dark matter"],
      ["Approximately how old is the universe?", "13.8 billion years"],
      ["What space station has been continuously occupied since 2000?", "International Space Station"],
      ["Which NASA rover landed on Mars in 2021?", "Perseverance"],
      ["What is the largest volcano in our solar system?", "Olympus Mons"],
      ["Which galaxy is on a collision course with the Milky Way?", "Andromeda Galaxy"],
      ["What telescope was launched in 2021 to succeed Hubble's role?", "James Webb Space Telescope"],
      ["What is the first probe to leave the solar system called?", "Voyager 1"],
      ["What is the icy region beyond Neptune filled with small bodies?", "The Kuiper Belt"],
      ["Which object was reclassified from planet to dwarf planet in 2006?", "Pluto"],
      ["What is the Sun's outermost atmospheric layer called?", "The corona"],
      ["What type of galaxy is the Milky Way?", "Barred spiral"],
      ["What is a star explosion at the end of a massive star's life?", "Supernova"],
      ["What is the hottest planet in our solar system?", "Venus"],
      ["What causes the aurora borealis?", "Solar wind particles interacting with Earth's magnetic field"],
      ["Which year was the Hubble Space Telescope launched?", "1990"],
      ["Who formulated the laws of planetary motion?", "Johannes Kepler"],
      ["Who described universal gravitation in the 1600s?", "Isaac Newton"],
      ["What is a pulsar?", "A rapidly rotating neutron star that emits beams of radiation"],
      ["What is the remnant of a collapsed massive star with huge density?", "A neutron star"],
      ["Which Apollo mission famously returned safely after an onboard explosion?", "Apollo 13"],
      ["What is the Sun's main fuel source?", "Hydrogen (fused into helium)"],
      ["What is the name of the first space tourist company's suborbital vehicle by Bezos?", "New Shepard"],
      ["Which planet has the most moons currently known?", "Saturn"],
      ["What causes a total solar eclipse?", "The Moon perfectly covering the Sun from Earth's view"],
      ["What spacecraft photographed Pluto closely in 2015?", "New Horizons"],
    ]),
    600: qa([
      ["What is the boundary of a black hole beyond which nothing escapes?", "The event horizon"],
      ["What hypothetical cloud of icy bodies surrounds the outer solar system?", "The Oort Cloud"],
      ["What radiation is theoretically emitted by black holes?", "Hawking radiation"],
      ["What is normal matter made of protons and neutrons called?", "Baryonic matter"],
      ["What is the theory of a rapid early expansion of the universe called?", "Inflationary theory"],
      ["What five special points exist in a two-body orbital system?", "Lagrange points"],
      ["What type of supernova results from a white dwarf exceeding its mass limit?", "Type Ia"],
      ["Whose equation estimates the number of contactable civilizations in our galaxy?", "Frank Drake's equation"],
      ["What brief intense bursts of radio waves come from distant space?", "Fast radio bursts"],
      ["Which crater is linked to the dinosaur extinction event?", "Chicxulub"],
      ["Which triple star system is nearest to the Sun?", "Alpha Centauri"],
      ["Which scale rates civilizations by energy use (Type I, II, III)?", "The Kardashev scale"],
      ["What paradox asks why we haven't found alien civilizations yet?", "The Fermi paradox"],
      ["What is a neutron star with an extremely strong magnetic field called?", "A magnetar"],
      ["What is the habitable zone around a star sometimes nicknamed?", "The Goldilocks Zone"],
      ["What relic radiation from the early universe was discovered in 1964?", "Cosmic microwave background"],
      ["What was the first exoplanet discovered orbiting a Sun-like star?", "51 Pegasi b"],
      ["What is an object too massive to be a planet but too light to fuse hydrogen?", "A brown dwarf"],
      ["In what year was the first direct image of a black hole released?", "2019"],
      ["What bends light from distant objects near a massive body?", "Gravitational lensing"],
      ["What stretching effect happens near a black hole's singularity?", "Spaghettification"],
      ["What rotating disk forms around a compact object as matter falls in?", "An accretion disk"],
      ["What was the largest telescope in the Canaries before being surpassed?", "Gran Telescopio Canarias"],
      ["Which Jovian moon has a subsurface ocean and is a prime target for life?", "Europa"],
      ["Which Saturnian moon shoots water geysers from its south pole?", "Enceladus"],
      ["Which is the fastest spacecraft ever launched?", "Parker Solar Probe"],
      ["Which astronomer discovered four of Jupiter's moons in 1610?", "Galileo Galilei"],
      ["Which theory describes gravity as curvature of spacetime?", "General relativity"],
      ["What is the discovered minimum distance two black holes merge at?", "Schwarzschild radius boundary"],
      ["What is the approximate temperature of the cosmic microwave background?", "2.725 Kelvin"],
    ]),
  },

  // ===================== MATH =====================
  math: {
    label: "Math",
    icon: "\u{1F9EE}",
    color: "#14B8A6",
    200: qa([
      ["What is 12 + 8?", "20"],
      ["What is 15 \u00D7 3?", "45"],
      ["What is 100 \u2212 37?", "63"],
      ["What is 144 \u00F7 12?", "12"],
      ["What is 7 squared?", "49"],
      ["What is the square root of 81?", "9"],
      ["What is 25% of 80?", "20"],
      ["What is 1/2 + 1/4?", "3/4"],
      ["What is 3 \u00D7 7 \u00D7 2?", "42"],
      ["What is 9 \u00D7 11?", "99"],
      ["What is 17 + 23?", "40"],
      ["What is 6 factorial?", "720"],
      ["What is 2 + 2 \u00D7 3 (order of operations)?", "8"],
      ["What is the sum of angles in a triangle?", "180 degrees"],
      ["What is 1000 \u2212 1?", "999"],
      ["What is 8 \u00D7 8?", "64"],
      ["What is half of 100?", "50"],
      ["What is 3 to the power of 4?", "81"],
      ["What is 15 + 25 + 35?", "75"],
      ["What is the perimeter of a square with side 5?", "20"],
      ["What is the area of a rectangle with width 4 and length 7?", "28"],
      ["What is 50 \u00D7 50?", "2500"],
      ["What is 0 factorial?", "1"],
      ["What is 11 \u00D7 12?", "132"],
      ["What is 28 \u00F7 7?", "4"],
      ["What is 10% of 200?", "20"],
      ["What number comes next: 2, 4, 8, 16?", "32"],
      ["What number comes next: 1, 1, 2, 3, 5, 8?", "13"],
      ["How many degrees is a right angle?", "90"],
      ["What is 13 \u00D7 13?", "169"],
    ]),
    400: qa([
      ["What is 7 \u00D7 13?", "91"],
      ["What is the square root of 144?", "12"],
      ["Solve: 2x + 4 = 16, find x.", "6"],
      ["What is the circumference of a circle with radius 7 (use \u03C0 \u2248 3.14)?", "43.96"],
      ["What is the derivative of x squared?", "2x"],
      ["What is sin(90 degrees)?", "1"],
      ["What is cos(0)?", "1"],
      ["What is log base 10 of 100?", "2"],
      ["What is 2^3 \u00D7 2^4?", "128"],
      ["What is 5! / 3!?", "20"],
      ["What is the area of a triangle with base 10 and height 6?", "30"],
      ["What is \u03C0 rounded to 4 decimals?", "3.1416"],
      ["Slope of a line perpendicular to y = 2x + 3?", "\u22121/2"],
      ["Hypotenuse of a right triangle with legs 3 and 4?", "5"],
      ["What is e rounded to 3 decimals?", "2.718"],
      ["What is the volume of a cube with side 4?", "64"],
      ["Probability of rolling a 6 on a fair die?", "1/6"],
      ["What is 40% of 250?", "100"],
      ["What is the mean of 2, 4, 6, 8, 10?", "6"],
      ["What is the median of 1, 3, 5, 7, 9?", "5"],
      ["What is log base 2 of 8?", "3"],
      ["What is the sum of the first 10 natural numbers?", "55"],
      ["How many ways to choose 2 from 12 (12 choose 2)?", "66"],
      ["What is the discriminant of x\u00B2 + 4x + 4?", "0"],
      ["Write the quadratic formula.", "x = (\u2212b \u00B1 \u221A(b\u00B2 \u2212 4ac)) / 2a"],
      ["What is 15% of 80?", "12"],
      ["What is tan(45 degrees)?", "1"],
      ["What is 2^10?", "1024"],
      ["Simplify: 6/9.", "2/3"],
      ["If a triangle has angles 60 and 70, what is the third?", "50 degrees"],
    ]),
    600: qa([
      ["What is the derivative of sin(x)?", "cos(x)"],
      ["What is the integral of 1/x?", "ln|x| + C"],
      ["What is the limit of sin(x)/x as x approaches 0?", "1"],
      ["Write Euler's identity.", "e^(i\u03C0) + 1 = 0"],
      ["What famous conjecture concerns the zeros of the zeta function?", "The Riemann Hypothesis"],
      ["State Fermat's Last Theorem in one sentence.", "No positive integers a, b, c satisfy a^n + b^n = c^n for n > 2"],
      ["Which theorem states any strong formal system has undecidable statements?", "G\u00F6del's Incompleteness Theorem"],
      ["What does the Fundamental Theorem of Calculus connect?", "Differentiation and integration"],
      ["What paradox uses the axiom of choice to split a sphere into two copies?", "Banach\u2013Tarski paradox"],
      ["What is i\u00B2?", "\u22121"],
      ["What is the value of the golden ratio (3 decimals)?", "1.618"],
      ["What is the 10th Fibonacci number?", "55"],
      ["What is the integral of e^x dx?", "e^x + C"],
      ["Give the prime factorization of 84.", "2^2 \u00D7 3 \u00D7 7"],
      ["What is the determinant of the 2\u00D72 matrix [[1,2],[3,4]]?", "\u22122"],
      ["How many permutations of 3 from 5 items (5P3)?", "60"],
      ["What is the limit as x approaches infinity of (1 + 1/x)^x?", "e"],
      ["Best strategy in the Monty Hall problem?", "Always switch (wins 2/3 of the time)"],
      ["What is the cardinality of the real numbers denoted by?", "\u05D0_1 or 2^\u05D0_0"],
      ["What function grows faster than any primitive recursive function?", "The Ackermann function"],
      ["What does Euler's totient function \u03C6(n) count?", "Integers up to n coprime with n"],
      ["What is the integral of cos(x) dx?", "sin(x) + C"],
      ["What is the derivative of ln(x)?", "1/x"],
      ["What is the sum 1 + 1/2 + 1/4 + 1/8 ... to infinity?", "2"],
      ["What are the 3 Pythagorean triples in (3,4,_), (5,12,_), (8,15,_)?", "5, 13, 17"],
      ["Solve for x: log_2(x) = 5.", "32"],
      ["What is the derivative of x^n?", "n \u00B7 x^(n\u22121)"],
      ["What is the sum of interior angles of an n-sided polygon?", "(n \u2212 2) \u00D7 180 degrees"],
      ["What does the Cauchy\u2013Schwarz inequality relate?", "Inner products and norms of vectors"],
      ["What is the volume of a sphere of radius r?", "(4/3) \u03C0 r\u00B3"],
    ]),
  },

  // ===================== LANGUAGE =====================
  language: {
    label: "Language",
    icon: "\u{1F5E3}\uFE0F",
    color: "#EF4444",
    200: qa([
      ["\"Hola, \u00BFc\u00F3mo est\u00E1s?\"", "Spanish"],
      ["\"Bonjour, comment allez-vous?\"", "French"],
      ["\"Guten Tag, wie geht's?\"", "German"],
      ["\"Ciao, come stai?\"", "Italian"],
      ["\"Ol\u00E1, como est\u00E1?\"", "Portuguese"],
      ["\"\u3053\u3093\u306B\u3061\u306F\" (Konnichiwa)", "Japanese"],
      ["\"\u4F60\u597D\" (N\u012D h\u01CEo)", "Mandarin Chinese"],
      ["\"\uC548\uB155\uD558\uC138\uC694\" (Annyeonghaseyo)", "Korean"],
      ["\"Hallo, hoe gaat het?\"", "Dutch"],
      ["\"Hej, hur m\u00E5r du?\"", "Swedish"],
      ["\"Cze\u015B\u0107, jak si\u0119 masz?\"", "Polish"],
      ["\"\u041F\u0440\u0438\u0432\u0435\u0442, \u043A\u0430\u043A \u0434\u0435\u043B\u0430?\" (Privet, kak dela?)", "Russian"],
      ["\"Merhaba, nas\u0131ls\u0131n?\"", "Turkish"],
      ["\"\u0645\u0631\u062D\u0628\u0627\u060C \u0643\u064A\u0641 \u062D\u0627\u0644\u0643\u061F\"", "Arabic"],
      ["\"\u0393\u03B5\u03B9\u03B1 \u03C3\u03B1\u03C2\" (Yia sas)", "Greek"],
      ["\"Hej, hvordan har du det?\"", "Danish"],
      ["\"Hei, hvordan har du det?\"", "Norwegian"],
      ["\"Hei, mit\u00E4 kuuluu?\"", "Finnish"],
      ["\"Au revoir!\"", "French"],
      ["\"Danke sch\u00F6n.\"", "German"],
      ["\"Grazie mille!\"", "Italian"],
      ["\"Obrigado.\"", "Portuguese"],
      ["\"\u3042\u308A\u304C\u3068\u3046\" (Arigatou)", "Japanese"],
      ["\"\u8C22\u8C22\" (Xi\u00E8xie)", "Mandarin Chinese"],
      ["\"\uAC10\uC0AC\uD569\uB2C8\uB2E4\" (Gamsahamnida)", "Korean"],
      ["\"\u0421\u043F\u0430\u0441\u0438\u0431\u043E\" (Spasibo)", "Russian"],
      ["\"Je t'aime.\"", "French"],
      ["\"Te amo.\"", "Spanish"],
      ["\"Ich liebe dich.\"", "German"],
      ["\"\u00A1Buenos d\u00EDas!\"", "Spanish"],
    ]),
    400: qa([
      ["\"Dobrodo\u0161li!\" (welcome)", "Croatian"],
      ["\"D\u011Bkuji\"", "Czech"],
      ["\"K\u00F6sz\u00F6n\u00F6m\"", "Hungarian"],
      ["\"Mul\u021Bumesc\"", "Romanian"],
      ["\"\u0411\u043B\u0430\u0433\u043E\u0434\u0430\u0440\u044F\" (Blagodarya)", "Bulgarian"],
      ["\"Dobrodo\u0161el, \u0161to radi\u0161?\"", "Serbian"],
      ["\"Dobr\u00FD de\u0148\"", "Slovak"],
      ["\"Labas rytas\"", "Lithuanian"],
      ["\"Sveiki\"", "Latvian"],
      ["\"Tere, kuidas sul l\u00E4heb?\"", "Estonian"],
      ["\"\u05E9\u05DC\u05D5\u05DD, \u05DE\u05D4 \u05E0\u05E9\u05DE\u05E2?\" (Shalom, ma nishma?)", "Hebrew"],
      ["\"Sawubona\"", "Zulu"],
      ["\"\u0928\u092E\u0938\u094D\u0924\u0947\" (Namaste)", "Hindi"],
      ["\"Jambo!\"", "Swahili"],
      ["\"\u0E2A\u0E27\u0E31\u0E2A\u0E14\u0E35\u0E04\u0E23\u0E31\u0E1A\" (Sawasdee khrap)", "Thai"],
      ["\"Xin ch\u00E0o\"", "Vietnamese"],
      ["\"Selamat pagi\"", "Indonesian"],
      ["\"Kumusta ka?\"", "Filipino (Tagalog)"],
      ["\"Ma'a as-salaama\"", "Arabic"],
      ["\"Saluton, mia amiko!\"", "Esperanto"],
      ["\"Dia dhuit\"", "Irish"],
      ["\"Bore da\"", "Welsh"],
      ["\"Hola, qu\u00E8 tal?\"", "Catalan"],
      ["\"Kaixo, zer moduz?\"", "Basque"],
      ["\"\u03A0\u03CE\u03C2 \u03C3\u03B5 \u03BB\u03AD\u03BD\u03B5;\" (How are you called?)", "Greek"],
      ["\"Salaam, chetori?\"", "Persian (Farsi)"],
      ["\"Ni hao ma?\"", "Mandarin Chinese"],
      ["\"\u0938\u0941\u092A\u094D\u0930\u092D\u093E\u0924\" (Suprabhat - good morning)", "Hindi"],
      ["\"Jak leci?\" (how's it going?)", "Polish"],
      ["\"\u0E2A\u0E27\u0E31\u0E2A\u0E14\u0E35\u0E04\u0E48\u0E30\" (Sawatdee ka)", "Thai"],
    ]),
    600: qa([
      ["\"Nda woye, nde ghin bo?\"", "Yoruba"],
      ["\"Akwaaba!\" (welcome)", "Twi (Akan)"],
      ["\"Barka da zuwa\"", "Hausa"],
      ["\"Selamat datang\"", "Malay"],
      ["\"M\u00ECngalar b\u00E0\"", "Burmese"],
      ["\"Sawatdee pi mai\" (happy new year)", "Lao"],
      ["\"Ayubowan\"", "Sinhala"],
      ["\"Vanakkam\"", "Tamil"],
      ["\"\u09A8\u09AE\u09B8\u09CD\u0995\u09BE\u09B0\" (Nomoshkar)", "Bengali"],
      ["\"Swastika, namaskar\"", "Nepali"],
      ["\"Minggalarba\"", "Burmese"],
      ["\"Chum reap suor\"", "Khmer (Cambodian)"],
      ["\"Sat sri akal\"", "Punjabi"],
      ["\"Kem cho?\"", "Gujarati"],
      ["\"Halo, apa kabar?\"", "Indonesian"],
      ["\"Kia ora\"", "M\u0101ori"],
      ["\"Aloha\"", "Hawaiian"],
      ["\"Talofa\"", "Samoan"],
      ["\"Malo e lelei\"", "Tongan"],
      ["\"Bul\u00E4!\"", "Fijian"],
      ["\"Goeiedag!\"", "Afrikaans"],
      ["\"Molo\"", "Xhosa"],
      ["\"Sannu\"", "Hausa"],
      ["\"Oo\"", "Oromo"],
      ["\"Selam\"", "Amharic"],
      ["\"Salom, yakhshimisiz?\"", "Uzbek"],
      ["\"Salam, s\u0259nin ad\u0131n n\u0259dir?\"", "Azerbaijani"],
      ["\"Gamardjoba\"", "Georgian"],
      ["\"Barev dzez\"", "Armenian"],
      ["\"S\u0103n\u0103tate!\" (cheers)", "Romanian"],
    ]),
  },

  // ===================== COBRA KAI / KARATE KID =====================
  cobra_kai: {
    label: "Cobra Kai",
    icon: "\u{1F94B}",
    color: "#B91C1C",
    200: qa([
      ["Who is Daniel LaRusso's karate teacher in the original film?", "Mr. Miyagi"],
      ["Who plays Daniel LaRusso in both Karate Kid and Cobra Kai?", "Ralph Macchio"],
      ["Who plays Johnny Lawrence?", "William Zabka"],
      ["What iconic kick wins the 1984 All Valley Tournament?", "Crane kick"],
      ["In what year was the original Karate Kid released?", "1984"],
      ["What Californian valley is the series set in?", "San Fernando Valley"],
      ["Who founded the original Cobra Kai dojo?", "John Kreese"],
      ["Who plays Mr. Miyagi?", "Pat Morita"],
      ["What is Johnny Lawrence's estranged son called?", "Robby Keene"],
      ["Who becomes Johnny's first student in the show?", "Miguel Diaz"],
      ["What dojo does Daniel eventually open?", "Miyagi-Do"],
      ["What is the name of Daniel's daughter?", "Samantha LaRusso"],
      ["What car dealership does Daniel run?", "LaRusso Auto Group"],
      ["In what decade did the original Karate Kid films take place?", "1980s"],
      ["What country does Daniel visit in Karate Kid Part II?", "Japan (Okinawa)"],
      ["What motto emphasizes the Cobra Kai philosophy?", "Strike First, Strike Hard, No Mercy"],
      ["What actor plays John Kreese?", "Martin Kove"],
      ["What is the name of Daniel's wife?", "Amanda LaRusso"],
      ["Who wins the 1984 All Valley against Johnny?", "Daniel LaRusso"],
      ["What is Daniel's first girlfriend's name?", "Ali Mills"],
      ["Who plays Ali Mills?", "Elisabeth Shue"],
      ["Streaming platform that brought Cobra Kai to mainstream after YouTube?", "Netflix"],
      ["What is Miguel's nationality background?", "Ecuadorian"],
      ["What signature move does Mr. Miyagi teach Daniel first?", "Wax on, wax off"],
      ["What does Daniel run as a sideline business devoted to Miyagi?", "Bonsai trees"],
      ["Who paralyzes Miguel at the school fight in Season 2?", "Robby Keene"],
      ["What is Hawk's real first name?", "Eli"],
      ["What martial art style does Miyagi-Do emphasize?", "Okinawan karate (defense first)"],
      ["Who plays Samantha LaRusso?", "Mary Mouser"],
      ["Who plays Miguel Diaz?", "Xolo Marideu\u00F1a"],
    ]),
    400: qa([
      ["Who plays Tory Nichols?", "Peyton List"],
      ["Who plays Robby Keene?", "Tanner Buchanan"],
      ["Who plays Hawk?", "Jacob Bertrand"],
      ["What new dojo does Johnny start after leaving Cobra Kai?", "Eagle Fang Karate"],
      ["Who returns as Kreese's Vietnam friend and main villain?", "Terry Silver"],
      ["Who plays Terry Silver?", "Thomas Ian Griffith"],
      ["In which season does Silver take over Cobra Kai?", "Season 4"],
      ["Where does Miguel travel to in Season 4 searching for his father?", "Ecuador"],
      ["What is Miguel's mother's name?", "Carmen Diaz"],
      ["Who returns as a Miyagi-Do ally from Karate Kid Part II?", "Chozen Toguchi"],
      ["Who plays Chozen Toguchi?", "Yuji Okumoto"],
      ["Who plays Kumiko in Cobra Kai?", "Tamlyn Tomita"],
      ["What is Daniel's son's name?", "Anthony LaRusso"],
      ["Who plays Demetri?", "Gianni DeCenzo"],
      ["Who plays Aisha Robinson?", "Nichole Brown"],
      ["What is the name of Miyagi's truck Daniel restores?", "1947 Ford Super De Luxe"],
      ["What international tournament anchors the final seasons?", "Sekai Taikai"],
      ["What song plays when Daniel wins the 1984 tournament?", "You're the Best"],
      ["What is Johnny Lawrence's stepfather's name?", "Sid Weinberg"],
      ["What sensei teaches Daniel the drum technique in Part II?", "Mr. Miyagi"],
      ["What was the name of Miyagi's wife in Part II backstory?", "Yukie"],
      ["What happened to Miyagi's wife during WWII?", "She died in the Manzanar internment camp"],
      ["What infantry regiment did Miyagi serve in during WWII?", "The 442nd Infantry Regiment"],
      ["Who directed the original 1984 Karate Kid?", "John G. Avildsen"],
      ["Who wrote the original Karate Kid screenplay?", "Robert Mark Kamen"],
      ["What is Kreese's branch of service in flashbacks?", "U.S. Army (Vietnam, Special Forces)"],
      ["What Cobra Kai season opens with the school fight fallout?", "Season 3"],
      ["What platform first premiered Cobra Kai in 2018?", "YouTube Red (later YouTube Premium)"],
      ["What is the name of Johnny's old rival from the first film?", "Daniel LaRusso"],
      ["What bar does Johnny frequent?", "The dive bar shown in early episodes"],
    ]),
    600: qa([
      ["Who played Mike Barnes in Karate Kid Part III?", "Sean Kanan"],
      ["Who is Mike Barnes in the storyline?", "Silver's muscle hired to torment Daniel"],
      ["Who played Julie Pierce in The Next Karate Kid?", "Hilary Swank"],
      ["What year did The Next Karate Kid come out?", "1994"],
      ["Who starred as Dre Parker in the 2010 Karate Kid reboot?", "Jaden Smith"],
      ["Who played Mr. Han in the 2010 Karate Kid?", "Jackie Chan"],
      ["What year was the 2010 Karate Kid released?", "2010"],
      ["What producer has been linked to the franchise as guardian of the IP?", "Jerry Weintraub"],
      ["What was Kreese's cellmate or mentor flashback character called?", "Captain Turner"],
      ["Who played Captain Turner in the Vietnam flashbacks?", "Terry Serpico"],
      ["Who plays Stingray in Cobra Kai?", "Paul Walter Hauser"],
      ["Who plays Kenny Payne?", "Dallas Dupree Young"],
      ["Who plays Devon Lee in later seasons?", "Oona O'Brien"],
      ["What character is Johnny's eventual girlfriend he reconciles with?", "Carmen Diaz"],
      ["Who plays Sam LaRusso's boyfriend Kyler?", "Joe Seo"],
      ["What country-themed tournament caps off the final seasons?", "Barcelona-based Sekai Taikai"],
      ["Who plays young Kreese in flashbacks?", "Barrett Carnahan"],
      ["Who plays young Terry Silver in flashbacks?", "Nick Marini"],
      ["Who plays young Johnny Lawrence in flashbacks?", "Jon Hurwitz is not an actor — it's Colt Henson"],
      ["Who took over as showrunners for Cobra Kai?", "Josh Heald, Jon Hurwitz, Hayden Schlossberg"],
      ["What composer scored both the original film and the series?", "Bill Conti (film), Leo Birenberg & Zach Robinson (series)"],
      ["What 1986 sequel did Mr. Miyagi travel with Daniel to Japan?", "The Karate Kid Part II"],
      ["What is Miyagi's family home village?", "Tomi Village in Okinawa"],
      ["Who plays Sato, Miyagi's rival in Part II?", "Danny Kamekona"],
      ["Who plays Yukie in Part II?", "Nobu McCarthy"],
      ["What karate style does Silver teach recruits in Part III?", "Cobra Kai"],
      ["Who were the three masters of Okinawan karate referenced in Part II?", "Not explicitly named; Miyagi-Do lineage"],
      ["What was the original Karate Kid's budget?", "$8 million"],
      ["How much did the original Karate Kid gross worldwide?", "Over $130 million"],
      ["What was Cobra Kai's final season?", "Season 6"],
    ]),
  },

  // ===================== UAE =====================
  uae: {
    label: "UAE",
    icon: "\u{1F1E6}\u{1F1EA}",
    color: "#059669",
    200: qa([
      ["What is the capital of the UAE?", "Abu Dhabi"],
      ["What is the tallest building in the world, located in Dubai?", "Burj Khalifa"],
      ["What is the national language of the UAE?", "Arabic"],
      ["What currency is used in the UAE?", "Dirham (AED)"],
      ["What is the main religion in the UAE?", "Islam"],
      ["How many emirates make up the UAE?", "7"],
      ["What year was the UAE founded?", "1971"],
      ["What is the name of Dubai's man-made palm-shaped island?", "Palm Jumeirah"],
      ["What iconic sail-shaped luxury hotel is in Dubai?", "Burj Al Arab"],
      ["What is the founding father of the UAE called?", "Sheikh Zayed bin Sultan Al Nahyan"],
      ["Which mega-event did Dubai host from 2021 to 2022?", "Expo 2020"],
      ["Which emirate is the largest by area?", "Abu Dhabi"],
      ["What is the UAE's flagship airline based in Abu Dhabi?", "Etihad Airways"],
      ["What is Dubai's flagship airline called?", "Emirates"],
      ["What body of water borders the UAE on the north?", "Persian Gulf"],
      ["What is the UAE's most important natural resource?", "Oil"],
      ["What is the name of the indoor ski slope in Dubai?", "Ski Dubai"],
      ["What is the name of the largest mall in the UAE?", "Dubai Mall"],
      ["What famous dancing fountain show is at the base of Burj Khalifa?", "The Dubai Fountain"],
      ["What UAE theme park is branded around a car maker?", "Ferrari World"],
      ["Which island hosts both Ferrari World and Yas Marina Circuit?", "Yas Island"],
      ["What is the UAE national sport involving trained birds of prey?", "Falconry"],
      ["What traditional UAE sport involves racing animals through the desert?", "Camel racing"],
      ["What is the UAE's parliamentary body called?", "Federal National Council"],
      ["Which emirate has the Sheikh Zayed Grand Mosque?", "Abu Dhabi"],
      ["What are the four colors of the UAE flag?", "Red, green, white, black"],
      ["What famous bird is the national symbol of the UAE?", "The falcon"],
      ["Who currently serves as President of the UAE (as of 2024)?", "Sheikh Mohamed bin Zayed Al Nahyan"],
      ["What traditional outer garment do Emirati men wear?", "Kandura"],
      ["What traditional black outer cloak do Emirati women wear?", "Abaya"],
    ]),
    400: qa([
      ["What famous art museum opened in Abu Dhabi in 2017 as a partner institution?", "Louvre Abu Dhabi"],
      ["Which emirate sits on the Gulf of Oman coast?", "Fujairah"],
      ["What year was the Burj Khalifa officially opened?", "2010"],
      ["Who was the first UAE astronaut to travel to the ISS?", "Hazza Al Mansouri"],
      ["In which year did Hazza Al Mansouri go to space?", "2019"],
      ["What was Dubai's main economic activity before oil?", "Pearl diving and trade"],
      ["Which UAE city is the cultural capital known for museums?", "Sharjah"],
      ["What archipelago off Dubai's coast is shaped like a world map?", "The World Islands"],
      ["What F1 circuit hosts the season finale in Abu Dhabi?", "Yas Marina Circuit"],
      ["What is the highest mountain peak in the UAE?", "Jebel Jais"],
      ["Which mountain-range emirate is famous for Jebel Jais?", "Ras Al Khaimah"],
      ["What famous photo frame structure opened in Dubai in 2018?", "Dubai Frame"],
      ["What highway connects Abu Dhabi to Dubai?", "Sheikh Zayed Road"],
      ["What is the name of the UAE Mars probe launched in 2020?", "Hope Probe (Al-Amal)"],
      ["What year did the UAE's Hope probe enter Mars orbit?", "2021"],
      ["What major free-trade zone operates near Jebel Ali port?", "JAFZA (Jebel Ali Free Zone)"],
      ["Which island near Abu Dhabi is developed as a cultural destination?", "Saadiyat Island"],
      ["What is the UAE's largest natural oasis?", "Al Ain Oasis"],
      ["Where is the annual Dubai World Cup horse race held?", "Meydan Racecourse"],
      ["In which year was Sheikh Zayed Grand Mosque completed?", "2007"],
      ["What traditional Emirati dance involves chanting and sticks?", "Al-Ayyala"],
      ["What region of Abu Dhabi Emirate is known for date farms and dunes?", "Al Dhafra (Liwa area)"],
      ["Which emirate is the smallest by area?", "Ajman"],
      ["What emirate has Khor Fakkan as an exclave on the east coast?", "Sharjah"],
      ["What global financial district operates within Dubai?", "Dubai International Financial Centre (DIFC)"],
      ["What emirate borders both Saudi Arabia and Oman?", "Abu Dhabi"],
      ["What rail-transit system opened in Dubai in 2009?", "Dubai Metro"],
      ["What is the name of the bridge connecting Abu Dhabi Island to the mainland built by Zaha Hadid?", "Sheikh Zayed Bridge"],
      ["What is the UAE's oldest known mosque?", "Al Bidya Mosque"],
      ["In which emirate is Al Bidya Mosque?", "Fujairah"],
    ]),
    600: qa([
      ["What UNESCO-listed historic fort is in Al Ain?", "Al Jahili Fort"],
      ["Approximately what percentage of UAE residents are foreign nationals?", "About 88%"],
      ["What is the approximate total population of the UAE as of the mid-2020s?", "About 10 million"],
      ["What nuclear power plant began commercial operations in Al Dhafra in 2020?", "Barakah Nuclear Power Plant"],
      ["What is the name of the UAE's main space centre in Dubai?", "Mohammed bin Rashid Space Centre"],
      ["Who was announced in 2021 as the first Arab woman selected for astronaut training?", "Nora Al Matrooshi"],
      ["What financial free-zone operates on Al Maryah Island?", "Abu Dhabi Global Market"],
      ["What ancient archaeological site in Sharjah dates back over 5,000 years?", "Mleiha"],
      ["What mountain range runs through the UAE and Oman?", "The Hajar Mountains"],
      ["What desert region in Abu Dhabi Emirate is known for giant crescent dunes?", "Rub' al Khali (Empty Quarter)"],
      ["What traditional wooden ship is used for pearl diving and trade?", "The dhow"],
      ["What UAE festival features camel beauty contests and falconry?", "Al Dhafra Festival"],
      ["What is the UAE's stock exchange in Abu Dhabi called?", "Abu Dhabi Securities Exchange (ADX)"],
      ["What dish of spiced rice with meat is a UAE national staple?", "Machboos"],
      ["What sticky date-based sweet is served during Ramadan?", "Luqaimat"],
      ["What is the traditional Emirati coffee served from a long-spouted pot?", "Gahwa (Arabic coffee)"],
      ["What was the first settlement of modern Dubai, founded by the Bani Yas tribe?", "Bur Dubai (Shindagha area)"],
      ["What year did Dubai's Metro open Red Line service?", "2009"],
      ["What geological formations in western Abu Dhabi look like stone trees?", "Fossil Dunes"],
      ["Which emirate is home to the historic Hatta enclave?", "Dubai"],
      ["What was the UAE called before unification?", "Trucial States (Trucial Oman)"],
      ["Which treaty ended the Trucial States' maritime truce with Britain?", "The 1971 Treaty of Friendship"],
      ["Who succeeded Sheikh Zayed as UAE president?", "Sheikh Khalifa bin Zayed"],
      ["What year did Sheikh Khalifa become UAE president?", "2004"],
      ["What year did Sheikh Khalifa pass away?", "2022"],
      ["Where is the UAE's oldest archaeological settlement near Jebel Buhais?", "Sharjah Emirate"],
      ["Which emirate's former ruler was Sheikh Sultan bin Mohammed Al Qasimi, a noted historian?", "Sharjah"],
      ["What ancient trade empire was based in UAE's Umm Al Quwain region 2,000 years ago?", "Ed-Dur"],
      ["What Bronze Age culture ruled the Oman Peninsula including UAE?", "Magan civilisation"],
      ["Which emirate produced the famous pearl known as 'La Peregrina'?", "Pearls came from the Gulf generally — no single emirate definitively"],
    ]),
  },

  // ===================== GUESS THE FOOTBALL PLAYER =====================
  guess_footballer: {
    label: "Guess the Footballer",
    icon: "\u26BD",
    color: "#F59E0B",
    200: qa([
      ["Portuguese forward. 5x Ballon d'Or winner. Famous Siuuu celebration. Currently plays for Al-Nassr.", "Cristiano Ronaldo"],
      ["Argentine forward. 8x Ballon d'Or winner. Left-footed dribbler. Lifted the 2022 World Cup.", "Lionel Messi"],
      ["Brazilian forward. Spent time at Barcelona and PSG. Dazzling skill moves. Wears 10 for his country.", "Neymar"],
      ["French forward. Won the World Cup at age 19. Plays for Real Madrid. Explosive sprinting speed.", "Kylian Mbapp\u00E9"],
      ["Norwegian striker. Shattered Premier League goal records. Son of a former Leeds defender. Plays for Manchester City.", "Erling Haaland"],
      ["Egyptian winger. Liverpool's Premier League era top scorer. Left-footed. Known as the Egyptian King.", "Mohamed Salah"],
      ["Belgian playmaker. Manchester City midfielder. Pinpoint crosses and through balls. Famous red hair.", "Kevin De Bruyne"],
      ["French striker. Scored in the 1998 World Cup final. Arsenal's all-time top scorer. Nicknamed Titi.", "Thierry Henry"],
      ["English striker. Former Tottenham captain now at Bayern Munich. Three Lions skipper. England's all-time top scorer.", "Harry Kane"],
      ["Welsh winger. Four Champions League trophies at Real Madrid. Keen golfer. Scored a bicycle kick in the 2018 final.", "Gareth Bale"],
      ["Senegalese forward. Premier League and UCL winner at Liverpool. Later moved to Bayern Munich. Africa Cup of Nations winner.", "Sadio Man\u00E9"],
      ["German goalkeeper. Lifted the 2014 World Cup. Sweeper-keeper pioneer. Longtime Bayern Munich number one.", "Manuel Neuer"],
      ["French midfielder. Head-butted Materazzi in the 2006 final. Won three straight UCLs as Real Madrid coach. Elegant playmaker.", "Zin\u00E9dine Zidane"],
      ["Brazilian striker. Won the 2002 World Cup. Scored twice in that final. Known as R9.", "Ronaldo Naz\u00E1rio"],
      ["Swedish striker. Famous bicycle kick against England. Played for Barca, Milan, and Manchester United. Enormous ego.", "Zlatan Ibrahimovi\u0107"],
      ["English midfielder. Married a Spice Girl. Pinpoint crosses from deep. Wore 7 at Manchester United.", "David Beckham"],
      ["Dutch total-football icon. Won three European Cups with Ajax. Gave his name to a famous turn. Later managed Barcelona.", "Johan Cruyff"],
      ["Italian forward. Roma legend. Nicknamed Il Gladiatore. Spent his entire career at his hometown club.", "Francesco Totti"],
      ["Argentine striker. Manchester City legend. Scored the 93:20 Premier League winner vs QPR. Former partner of Maradona's daughter.", "Sergio Ag\u00FCero"],
      ["Spanish goalkeeper. Real Madrid number one for over a decade. Lifted the 2010 World Cup as captain. Nicknamed San Iker.", "Iker Casillas"],
      ["Croatian midfielder. 2018 Ballon d'Or winner. Six UCL titles at Real Madrid. Small-framed maestro.", "Luka Modri\u0107"],
      ["Portuguese midfielder. Manchester United captain. Long-range shots and leadership. Known for set-piece deliveries.", "Bruno Fernandes"],
      ["Argentine winger. 2022 World Cup winner. Scored in Champions League and Copa America finals. Nicknamed El Fideo.", "\u00C1ngel Di Mar\u00EDa"],
      ["French defender. 2018 World Cup winner. Former Madrid and Manchester United center-back. Shaved head.", "Rapha\u00EBl Varane"],
      ["Spanish striker. Real Madrid legend. All-time club top scorer before a Portuguese passed him. Wore 7 at the Bernabeu.", "Ra\u00FAl"],
      ["Argentine forward. Two World Cup trophies. Scored the Hand of God and the Goal of the Century. Napoli icon.", "Diego Maradona"],
      ["Brazilian forward. Three World Cup titles. Scored over 1,200 career goals. Crowned The King.", "Pel\u00E9"],
      ["English midfielder. Liverpool captain. 2005 Istanbul comeback hero. Slipped vs Chelsea in 2014.", "Steven Gerrard"],
      ["English midfielder. Chelsea's all-time top scorer. Played alongside Terry and Cole. Disallowed goal vs Germany in 2010.", "Frank Lampard"],
      ["Welsh winger. Manchester United legend. Most decorated English league player. Left-footed wing wizard.", "Ryan Giggs"],
    ]),
    400: qa([
      ["German goal machine. Scored 68 times for West Germany. Nicknamed Der Bomber. 1974 World Cup winner.", "Gerd M\u00FCller"],
      ["Dutch striker. Won Euro 1988 for his country. AC Milan legend. Retired early from ankle injuries.", "Marco van Basten"],
      ["Liberian striker. 1995 Ballon d'Or winner. Later elected president of his country. Milan icon of the 1990s.", "George Weah"],
      ["Ivorian midfielder. Barcelona La Liga winner before Manchester City. Powerhouse long-range shots. Three PL titles at City.", "Yaya Tour\u00E9"],
      ["Croatian striker. 2018 World Cup finalist. Juventus trophy winner. Classic volley against France in that final.", "Mario Mand\u017Euki\u0107"],
      ["German midfielder. 2014 World Cup winner. Bayern Munich stalwart. Later married tennis star Ana Ivanovic.", "Bastian Schweinsteiger"],
      ["Spanish defender. Euro 2008 and 2010 World Cup winner. Barcelona captain. Long curly hair.", "Carles Puyol"],
      ["Colombian playmaker. 2014 World Cup Golden Boot. Moved to Real Madrid that summer. Wore number 10.", "James Rodr\u00EDguez"],
      ["Hungarian forward. Real Madrid star of the 1950s. Scored 84 international goals. Nicknamed The Galloping Major.", "Ferenc Pusk\u00E1s"],
      ["Argentine-Spanish forward. Real Madrid legend. Won five straight European Cups. Nicknamed the Blond Arrow.", "Alfredo Di St\u00E9fano"],
      ["Dutch defender. Liverpool captain. Champions League winner in 2019. Ballon d'Or runner-up that year.", "Virgil van Dijk"],
      ["Brazilian right-back. Most decorated player in football history. Played for Barcelona and PSG. Samba celebrations.", "Dani Alves"],
      ["English striker. 2001 Ballon d'Or winner. Liverpool and Real Madrid. Rode racehorses after retiring.", "Michael Owen"],
      ["English striker. Premier League all-time top scorer. Newcastle United legend. Match of the Day pundit.", "Alan Shearer"],
      ["English midfielder. Manchester United midfielder. Famous red-headed long-range shots. Rarely gave interviews.", "Paul Scholes"],
      ["Irish midfielder. Manchester United captain. Fiery temperament. Feuded with Mick McCarthy in 2002.", "Roy Keane"],
      ["English defender. Manchester United and Leeds. Drug-test ban in 2003. Later a TV pundit.", "Rio Ferdinand"],
      ["English defender. Chelsea captain. Slipped taking the 2008 UCL final penalty. Record trophy haul at Stamford Bridge.", "John Terry"],
      ["English defender. Manchester United right-back. Sky Sports pundit. Brother Phil also played for United.", "Gary Neville"],
      ["Italian midfielder. AC Milan's combative enforcer. 2006 World Cup winner. Intimidating glare on the pitch.", "Gennaro Gattuso"],
      ["Ukrainian striker. 2004 Ballon d'Or winner. Dynamo Kyiv and AC Milan. Missed the decisive penalty in the 2005 UCL final.", "Andriy Shevchenko"],
      ["Dutch defender. Scored a famous free kick in the 1992 European Cup final. Later Barcelona and Netherlands coach.", "Ronald Koeman"],
      ["Dutch goalkeeper. Manchester United and Ajax. Won Champions Leagues in 1995 and 2008. Towering reach.", "Edwin van der Sar"],
      ["Italian striker. 1982 World Cup Golden Boot and Golden Ball. Scored a hat trick vs Brazil that tournament. Died in 2020.", "Paolo Rossi"],
      ["Argentine forward. Long flowing blond hair. Scored vs Brazil in 1990 World Cup last 16. Played alongside Maradona.", "Claudio Caniggia"],
      ["Argentine midfielder. Manchester United and Chelsea. Nicknamed La Brujita. Lazio Serie A winner.", "Juan Sebasti\u00E1n Ver\u00F3n"],
      ["Argentine striker. Fiorentina and Roma legend. All-time Argentina top scorer before Messi. Nicknamed Batigol.", "Gabriel Batistuta"],
      ["Argentine striker. Scored twice in the 2005 UCL final for Milan. Parma, Lazio, Inter, Chelsea. Copa America finalist.", "Hern\u00E1n Crespo"],
      ["Portuguese playmaker. Fiorentina and AC Milan. Portuguese Golden Generation. Number 10 elegance.", "Rui Costa"],
      ["Portuguese striker. Benfica legend. Represented his country at multiple Euros. Known for aerial ability.", "Nuno Gomes"],
    ]),
    600: qa([
      ["Argentine midfielder. 1978 World Cup winner. Long Tottenham spell. Later managed the Spurs.", "Osvaldo Ardiles"],
      ["Italian defender. Inter Milan center-back. Provoked a famous head-butt in 2006. Iron-willed enforcer.", "Marco Materazzi"],
      ["Argentine goalkeeper. 2022 World Cup winner. Aston Villa number one. Made an infamous celebration with the Golden Glove.", "Emiliano Mart\u00EDnez"],
      ["Jamaican-born English winger. Liverpool forward of the 1980s. Rapped on the World in Motion song. Solo goal against Brazil in 1984.", "John Barnes"],
      ["Danish goalkeeper. Manchester United record-breaker. 1992 Euros winner. His son Kasper also keeps goal.", "Peter Schmeichel"],
      ["Turkish striker. Galatasaray legend. UEFA Cup winner in 2000. Scored 11 seconds into the 2002 World Cup third-place match.", "Hakan \u015E\u00FCk\u00FCr"],
      ["Japanese midfielder. One of the first Japanese players in Serie A. Roma Scudetto winner. Retired at 29.", "Hidetoshi Nakata"],
      ["Colombian midfielder. Huge blond afro. Three World Cup appearances. Later played in MLS.", "Carlos Valderrama"],
      ["Croatian midfielder. AC Milan Serie A winner. Kicked a policeman at Dinamo Zagreb in 1990. Croatia's 1998 World Cup third-place run.", "Zvonimir Boban"],
      ["Ghanaian midfielder. Chelsea midfielder. Mourinho called him The Bison. 2012 UCL winner.", "Michael Essien"],
      ["Iranian striker. Held the men's international goals record before Ronaldo passed him. Scored 109 for his country. Former national team coach.", "Ali Daei"],
      ["Chilean striker. Wore 1+8 at Inter Milan. Real Madrid Pichichi winner. Played at the 1998 World Cup.", "Iv\u00E1n Zamorano"],
      ["Ghanaian-born French defender. 1998 World Cup and Euro 2000 winner. Milan and Chelsea. Nicknamed The Rock.", "Marcel Desailly"],
      ["English striker. Towering 6'7\" frame. Robot goal celebration. Liverpool and Spurs spells.", "Peter Crouch"],
      ["German libero. 1996 Ballon d'Or winner. Euro 96 champion. Later Borussia Dortmund sporting director.", "Matthias Sammer"],
      ["French defender. 1998 World Cup and Euro 2000 winner. Juventus and Parma. His country's most capped player for years.", "Lilian Thuram"],
      ["French forward. 1958 Ballon d'Or winner. Stade de Reims and Real Madrid. Won three straight European Cups.", "Raymond Kopa"],
      ["French midfielder. Three consecutive Ballons d'Or in the 1980s. Euro 1984 top scorer. Later banned from FIFA.", "Michel Platini"],
      ["Italian striker. Cagliari legend. His country's all-time top scorer for decades. Scored 35 in 42 internationals.", "Luigi Riva"],
      ["German striker. 1980 and 1981 Ballon d'Or winner. Bayern Munich forward. Later Bayern CEO.", "Karl-Heinz Rummenigge"],
      ["Italian goalkeeper. 1982 World Cup winner as captain at age 40. Juventus legend. Later national team coach.", "Dino Zoff"],
      ["Spanish forward. Nicknamed El Buitre. Leader of Real Madrid's Quinta del Buitre. Scored 4 vs Denmark at the 1986 World Cup.", "Emilio Butrague\u00F1o"],
      ["German midfielder. Played for Barcelona, Real Madrid and Atletico Madrid. Euro 1980 winner. Creative playmaker.", "Bernd Schuster"],
      ["English midfielder. Famous tears at Italia 90. Scored a volley against Scotland at Euro 96. Dentist's chair celebration.", "Paul Gascoigne"],
      ["Welsh striker. Liverpool's all-time top scorer. FA Cup final goals specialist. Trademark moustache.", "Ian Rush"],
      ["Scottish forward. Liverpool player and manager. Nicknamed King. Celtic legend before his Anfield move.", "Kenny Dalglish"],
      ["English striker. 1986 World Cup Golden Boot winner. Never booked in his career. Hosts Match of the Day.", "Gary Lineker"],
      ["Nigerian striker. Played for Ajax, Arsenal and Portsmouth. Olympic gold in 1996. Survived a heart condition scare mid-career.", "Nwankwo Kanu"],
      ["Nigerian midfielder. Dazzling skills at Bolton Wanderers. Also turned out for PSG and Fenerbahce. Africa Cup of Nations 1994 winner.", "Jay-Jay Okocha"],
      ["Cameroonian striker. Famous corner-flag dance. Oldest World Cup goalscorer at age 42. Italia 90 star.", "Roger Milla"],
    ]),
  },

};

// ===================== WHICH MOVIE AM I? =====================
NEW_CATEGORIES_PACK_2.who_movie = {
  label: "Which Movie Am I?",
  icon: "\u{1F3A5}",
  color: "#9333EA",
  isWhoAmI: true,
  200: qwMovie([
    ["The Dark Knight", "The_Dark_Knight"],
    ["Avatar: The Way of Water", "Avatar:_The_Way_of_Water"],
    ["Gladiator II", "Gladiator_II"],
    ["Dune", "Dune_(2021_film)"],
    ["Oppenheimer", "Oppenheimer_(film)"],
    ["Everything Everywhere All at Once", "Everything_Everywhere_All_at_Once"],
    ["Top Gun", "Top_Gun"],
    ["The Empire Strikes Back", "The_Empire_Strikes_Back"],
    ["Star Wars: The Force Awakens", "Star_Wars:_The_Force_Awakens"],
    ["Raiders of the Lost Ark", "Raiders_of_the_Lost_Ark"],
    ["E.T. the Extra-Terrestrial", "E.T._the_Extra-Terrestrial"],
    ["The Hangover", "The_Hangover"],
    ["Superbad", "Superbad"],
    ["Mean Girls", "Mean_Girls"],
    ["Legally Blonde", "Legally_Blonde"],
    ["The Devil Wears Prada", "The_Devil_Wears_Prada_(film)"],
    ["The Notebook", "The_Notebook_(film)"],
    ["Love Actually", "Love_Actually"],
    ["Pretty Woman", "Pretty_Woman"],
    ["Twilight", "Twilight_(2008_film)"],
    ["The Hunger Games: Catching Fire", "The_Hunger_Games:_Catching_Fire"],
    ["Inside Out", "Inside_Out_(2015_film)"],
    ["Coco", "Coco_(2017_film)"],
    ["Encanto", "Encanto_(film)"],
    ["Soul", "Soul_(2020_film)"],
    ["Tangled", "Tangled"],
    ["Bohemian Rhapsody", "Bohemian_Rhapsody_(film)"],
    ["Rocketman", "Rocketman_(film)"],
    ["Braveheart", "Braveheart"],
    ["The Wolf of Wall Street", "The_Wolf_of_Wall_Street_(2013_film)"],
  ]),
  400: qwMovie([
    ["Schindler's List", "Schindler%27s_List"],
    ["Django Unchained", "Django_Unchained"],
    ["Inglourious Basterds", "Inglourious_Basterds"],
    ["Reservoir Dogs", "Reservoir_Dogs"],
    ["Kill Bill: Volume 1", "Kill_Bill:_Volume_1"],
    ["Once Upon a Time in Hollywood", "Once_Upon_a_Time_in_Hollywood"],
    ["Saving Private Ryan", "Saving_Private_Ryan"],
    ["Enemy at the Gates", "Enemy_at_the_Gates"],
    ["Black Hawk Down", "Black_Hawk_Down_(film)"],
    ["The Thin Red Line", "The_Thin_Red_Line_(1998_film)"],
    ["The King's Speech", "The_King%27s_Speech"],
    ["12 Years a Slave", "12_Years_a_Slave_(film)"],
    ["Slumdog Millionaire", "Slumdog_Millionaire"],
    ["Spotlight", "Spotlight_(film)"],
    ["The Imitation Game", "The_Imitation_Game"],
    ["The Theory of Everything", "The_Theory_of_Everything_(2014_film)"],
    ["Green Book", "Green_Book_(film)"],
    ["Life of Pi", "Life_of_Pi_(film)"],
    ["Birdman", "Birdman_(film)"],
    ["Moonlight", "Moonlight_(2016_film)"],
    ["Halloween", "Halloween_(1978_film)"],
    ["Scream", "Scream_(1996_film)"],
    ["Saw", "Saw_(2004_film)"],
    ["It", "It_(2017_film)"],
    ["The Lighthouse", "The_Lighthouse_(2019_film)"],
    ["The Exorcist", "The_Exorcist"],
    ["Close Encounters of the Third Kind", "Close_Encounters_of_the_Third_Kind"],
    ["A Clockwork Orange", "A_Clockwork_Orange_(film)"],
    ["Dr. Strangelove", "Dr._Strangelove"],
    ["Am\u00E9lie", "Am%C3%A9lie"],
  ]),
  600: qwMovie([
    ["Eraserhead", "Eraserhead"],
    ["Stalker", "Stalker_(1979_film)"],
    ["Andrei Rublev", "Andrei_Rublev_(film)"],
    ["Persona", "Persona_(1966_film)"],
    ["The Seventh Seal", "The_Seventh_Seal"],
    ["Wild Strawberries", "Wild_Strawberries_(film)"],
    ["8\u00BD", "8%C2%BD"],
    ["Tokyo Story", "Tokyo_Story"],
    ["Seven Samurai", "Seven_Samurai"],
    ["Rashomon", "Rashomon"],
    ["Ran", "Ran_(film)"],
    ["Sunset Boulevard", "Sunset_Boulevard_(film)"],
    ["Psycho", "Psycho_(1960_film)"],
    ["Vertigo", "Vertigo_(film)"],
    ["Rear Window", "Rear_Window"],
    ["12 Angry Men", "12_Angry_Men"],
    ["To Kill a Mockingbird", "To_Kill_a_Mockingbird_(film)"],
    ["Fanny and Alexander", "Fanny_and_Alexander"],
    ["Pan's Labyrinth", "Pan%27s_Labyrinth"],
    ["City of God", "City_of_God_(2002_film)"],
    ["The Intouchables", "The_Intouchables"],
    ["The Lives of Others", "The_Lives_of_Others"],
    ["Belfast", "Belfast_(film)"],
    ["Drive My Car", "Drive_My_Car_(film)"],
    ["Decision to Leave", "Decision_to_Leave"],
    ["The Salesman", "The_Salesman_(2016_film)"],
    ["Oldboy", "Oldboy_(2003_film)"],
    ["In the Mood for Love", "In_the_Mood_for_Love"],
    ["There Will Be Blood", "There_Will_Be_Blood"],
    ["Portrait of a Lady on Fire", "Portrait_of_a_Lady_on_Fire"],
  ]),
};

// ===================== WHICH TV SHOW AM I? =====================
NEW_CATEGORIES_PACK_2.who_tv_show = {
  label: "Which TV Show Am I?",
  icon: "\u{1F4FA}",
  color: "#DC2626",
  isWhoAmI: true,
  200: qwShow([
    ["Breaking Bad", "Breaking_Bad"],
    ["Game of Thrones", "Game_of_Thrones"],
    ["Stranger Things", "Stranger_Things"],
    ["Friends", "Friends"],
    ["The Office", "The_Office_(American_TV_series)"],
    ["Seinfeld", "Seinfeld"],
    ["The Simpsons", "The_Simpsons"],
    ["SpongeBob SquarePants", "SpongeBob_SquarePants"],
    ["South Park", "South_Park"],
    ["The Big Bang Theory", "The_Big_Bang_Theory"],
    ["How I Met Your Mother", "How_I_Met_Your_Mother"],
    ["The Sopranos", "The_Sopranos"],
    ["Lost", "Lost_(TV_series)"],
    ["Prison Break", "Prison_Break"],
    ["Money Heist", "Money_Heist"],
    ["Squid Game", "Squid_Game"],
    ["Peaky Blinders", "Peaky_Blinders_(TV_series)"],
    ["The Walking Dead", "The_Walking_Dead_(TV_series)"],
    ["The Bear", "The_Bear_(TV_series)"],
    ["Narcos", "Narcos"],
    ["Dexter", "Dexter_(TV_series)"],
    ["Suits", "Suits_(American_TV_series)"],
    ["Wednesday", "Wednesday_(TV_series)"],
    ["Westworld", "Westworld_(TV_series)"],
    ["Black Mirror", "Black_Mirror"],
    ["The Last of Us", "The_Last_of_Us_(TV_series)"],
    ["Yellowstone", "Yellowstone_(American_TV_series)"],
    ["Only Murders in the Building", "Only_Murders_in_the_Building"],
    ["Euphoria", "Euphoria_(American_TV_series)"],
    ["The Crown", "The_Crown_(TV_series)"],
  ]),
  400: qwShow([
    ["The Wire", "The_Wire"],
    ["Deadwood", "Deadwood_(TV_series)"],
    ["Six Feet Under", "Six_Feet_Under_(TV_series)"],
    ["The Shield", "The_Shield"],
    ["Band of Brothers", "Band_of_Brothers_(miniseries)"],
    ["Chernobyl", "Chernobyl_(miniseries)"],
    ["Ozark", "Ozark_(TV_series)"],
    ["Fleabag", "Fleabag"],
    ["Succession", "Succession_(TV_series)"],
    ["Shrinking", "Shrinking_(TV_series)"],
    ["Reservation Dogs", "Reservation_Dogs"],
    ["Silicon Valley", "Silicon_Valley_(TV_series)"],
    ["Veep", "Veep"],
    ["Curb Your Enthusiasm", "Curb_Your_Enthusiasm"],
    ["30 Rock", "30_Rock"],
    ["Arrested Development", "Arrested_Development"],
    ["Parks and Recreation", "Parks_and_Recreation"],
    ["Community", "Community_(TV_series)"],
    ["Boardwalk Empire", "Boardwalk_Empire"],
    ["The Americans", "The_Americans"],
    ["Homeland", "Homeland_(American_TV_series)"],
    ["Sons of Anarchy", "Sons_of_Anarchy"],
    ["Grey's Anatomy", "Grey%27s_Anatomy"],
    ["ER", "ER_(TV_series)"],
    ["The West Wing", "The_West_Wing"],
    ["Frasier", "Frasier"],
    ["Cheers", "Cheers"],
    ["Twin Peaks", "Twin_Peaks"],
    ["The X-Files", "The_X-Files"],
    ["Mr. Robot", "Mr._Robot"],
  ]),
  600: qwShow([
    ["Archer", "Archer_(2009_TV_series)"],
    ["Avatar: The Last Airbender", "Avatar:_The_Last_Airbender"],
    ["Samurai Champloo", "Samurai_Champloo"],
    ["Steins;Gate", "Steins;Gate"],
    ["Fullmetal Alchemist: Brotherhood", "Fullmetal_Alchemist:_Brotherhood"],
    ["I May Destroy You", "I_May_Destroy_You"],
    ["The Leftovers", "The_Leftovers_(TV_series)"],
    ["Hannibal", "Hannibal_(TV_series)"],
    ["The Borgias", "The_Borgias"],
    ["Utopia", "Utopia_(British_TV_series)"],
    ["Dark", "Dark_(TV_series)"],
    ["Babylon Berlin", "Babylon_Berlin"],
    ["Gomorrah", "Gomorrah_(TV_series)"],
    ["My Brilliant Friend", "My_Brilliant_Friend_(TV_series)"],
    ["Broadchurch", "Broadchurch"],
    ["Top of the Lake", "Top_of_the_Lake"],
    ["Mare of Easttown", "Mare_of_Easttown"],
    ["Pose", "Pose_(TV_series)"],
    ["Severance", "Severance_(TV_series)"],
    ["The OA", "The_OA"],
    ["Sense8", "Sense8"],
    ["Battlestar Galactica", "Battlestar_Galactica_(2004_TV_series)"],
    ["Firefly", "Firefly_(TV_series)"],
    ["The Expanse", "The_Expanse_(TV_series)"],
    ["Russian Doll", "Russian_Doll_(TV_series)"],
    ["Sharp Objects", "Sharp_Objects_(miniseries)"],
    ["Arcane", "Arcane_(TV_series)"],
    ["True Detective", "True_Detective"],
    ["Fargo", "Fargo_(TV_series)"],
    ["Mad Men", "Mad_Men"],
  ]),
};

// ===================== WHO/WHAT AM I? (RIDDLES) =====================
NEW_CATEGORIES_PACK_2.who_what_am_i = {
  label: "Who/What Am I?",
  icon: "\u{2753}",
  color: "#6366F1",
  200: qa([
    ["I have hands but cannot clap. I have a face but no eyes. What am I?", "A clock"],
    ["I am tall when young and short when old. You burn me to light the dark. What am I?", "A candle"],
    ["I have keys but no locks. I have space but no room. You can enter but not go inside. What am I?", "A keyboard"],
    ["The more you take, the more you leave behind. What am I?", "Footsteps"],
    ["I speak without a mouth and hear without ears. I have no body but I come alive with wind. What am I?", "An echo"],
    ["What has four legs but doesn't walk?", "A table"],
    ["What must be broken before you can use it?", "An egg"],
    ["The more I dry, the wetter I get. What am I?", "A towel"],
    ["What goes up but never comes down?", "Age"],
    ["I have cities but no houses. I have mountains but no trees. I have water but no fish. What am I?", "A map"],
    ["I have an eye but cannot see. I am small and pointy. What am I?", "A needle"],
    ["I follow you all day but disappear when night falls. What am I?", "A shadow"],
    ["I have a head and a tail but no body. What am I?", "A coin"],
    ["I have a neck but no head. I may be filled with drink. What am I?", "A bottle"],
    ["I have many teeth but cannot bite. I help neaten your hair. What am I?", "A comb"],
    ["I can travel around the world while staying in a corner. What am I?", "A stamp"],
    ["I run but never walk. I have a bed but never sleep. What am I?", "A river"],
    ["I have a thumb and four fingers but I am not alive. What am I?", "A glove"],
    ["I am full of holes but still hold water. What am I?", "A sponge"],
    ["I have roots no one sees. I am taller than trees. Up up I go and yet never grow. What am I?", "A mountain"],
    ["I am always in front of you but can never be seen. What am I?", "The future"],
    ["I have branches but no fruit, trunk, or leaves. You visit me to hold your money. What am I?", "A bank"],
    ["The more you have of me, the less you see. What am I?", "Darkness"],
    ["I have one head, one foot, and four legs. Each night you sleep on me. What am I?", "A bed"],
    ["I am so fragile that saying my name breaks me. What am I?", "Silence"],
    ["Until I am measured, I am not known, yet you miss me when I have flown. What am I?", "Time"],
    ["I have teeth but cannot eat. I keep clothes closed. What am I?", "A zipper"],
    ["I can fly without wings and cry without eyes. I drift across the sky. What am I?", "A cloud"],
    ["I have 13 hearts but no organs. I am shuffled and dealt. What am I?", "A deck of cards"],
    ["I grow short the more I am used. I have wood but am not a tree. What am I?", "A pencil"],
  ]),
  400: qa([
    ["I am lighter than a feather, yet the strongest person cannot hold me for long. What am I?", "Breath"],
    ["I can hide a whole city, but I am made of tiny drops. The more of me there is, the less you see. What am I?", "Fog"],
    ["What can you catch but not throw?", "A cold"],
    ["I can be cracked, told, or played. People laugh when they hear me. What am I?", "A joke"],
    ["What 5-letter word becomes shorter when you add two letters to it?", "Short"],
    ["What belongs to you, but other people use it more than you do?", "Your name"],
    ["I have many keys but open no locks. I make music instead. What am I?", "A piano"],
    ["What has four wheels and flies?", "A garbage truck"],
    ["What can two people have without ever touching it?", "A conversation"],
    ["I am the beginning of everything and the end of everywhere. What am I?", "The letter E"],
    ["A five-letter word that sounds the same after removing four of its letters. What is it?", "Queue"],
    ["Give me food and I will live. Give me water and I will die. What am I?", "Fire"],
    ["I have no voice but teach you much. I have spines and hinges but am not a plant or a door. What am I?", "A book"],
    ["What begins with the letter e and ends with the letter e but only contains one letter?", "An envelope"],
    ["What comes once in a minute, twice in a moment, but never in a thousand years?", "The letter M"],
    ["What invention lets you look right through a wall?", "A window"],
    ["You can see me in water, but I never get wet. What am I?", "A reflection"],
    ["I begin and have no end. I am also the ending of all that begins. What am I?", "Death"],
    ["I am a word of 5 letters. People eat me. Remove my first letter and I become a form of energy. What am I?", "Wheat"],
    ["People buy me to eat but never eat me. What am I?", "A plate"],
    ["If you have me, you want to share me. If you share me, you don't have me. What am I?", "A secret"],
    ["What kind of tree can you carry in your hand?", "A palm"],
    ["What room do ghosts avoid?", "The living room"],
    ["I am not a plant but I have leaves. I am not royalty but I have a crown. I am sweet but sugar was never added. What am I?", "A pineapple"],
    ["You can hear me but never see me. I come out when you speak. What am I?", "Your voice"],
    ["I can run but have no legs. I am on your face. What am I?", "Your nose"],
    ["What invention allows you to walk through walls?", "A door"],
    ["One of us breaks yet never falls. The other falls yet never breaks. What are we?", "Day and night"],
    ["I keep ships from drifting. I sink but never drown. What am I?", "An anchor"],
    ["I have an eye but cannot see. I can tear roofs from homes. What am I?", "A hurricane"],
  ]),
  600: qa([
    ["Three lives have I. Gentle enough to soothe the skin, light enough to caress the sky, hard enough to crack rocks. What am I?", "Water"],
    ["Two bodies have I, though both joined in one. The more still I stand, the quicker I run. What am I?", "An hourglass"],
    ["At night they come without being fetched, and by day they are lost without being stolen. What are they?", "Stars"],
    ["The man who makes me does not want me. The man who buys me does not use me. The man who uses me does not know it. What am I?", "A coffin"],
    ["Always old, sometimes new. Never sad, sometimes blue. Never empty, sometimes full. What am I?", "The moon"],
    ["I make you weak at the worst of times. I make your heart pound and hands sweat. I visit the weak but seldom the bold. What am I?", "Fear"],
    ["A cloud is my mother, the wind is my father. A rainbow is my bed, the earth my final resting place. What am I?", "Rain"],
    ["I am the black child of a white father, a wingless bird flying even to the clouds of heaven. What am I?", "Smoke"],
    ["He marries many women but has never been married himself. Who is he?", "A priest"],
    ["Alive without breath, as cold as death. Never thirsty, ever drinking. All in mail, never clinking. What am I?", "A fish"],
    ["I start with T, end with T, and have T in me. What am I?", "A teapot"],
    ["What word in the dictionary is spelled incorrectly?", "Incorrectly"],
    ["Voiceless it cries, wingless flutters, toothless bites, mouthless mutters. What is it?", "The wind"],
    ["I can be long or short. I can be grown or bought. I can be painted or left bare. I can be round or square. What am I?", "Fingernails"],
    ["The sun bakes them, the hand breaks them, the foot treads on them, and the mouth tastes them. What are they?", "Grapes"],
    ["I turn once — that which is outside will not get in. I turn again — that which is inside will not get out. What am I?", "A key"],
    ["I am the fountain from which no one can drink. Like gold to all I am sought. What am I?", "Oil"],
    ["What can fill a room but takes up no space?", "Light"],
    ["I have no life, but I can die. You plug me in to charge. What am I?", "A battery"],
    ["What has three feet but cannot walk?", "A yardstick"],
    ["Poor people have it. Rich people need it. If you eat it, you die. What is it?", "Nothing"],
    ["The more you take away from me, the bigger I grow. What am I?", "A hole"],
    ["I have a tongue but cannot taste, a sole but no soul. What am I?", "A shoe"],
    ["What are the next two letters in the series: O, T, T, F, F, S, S, _, _?", "E, N"],
    ["A man rode into town on Friday, stayed three days, and left on Friday. How?", "His horse was named Friday"],
    ["A mother had three children. The first was named April, the second May. What was the third child's name?", "Johnny"],
    ["What is black when clean and white when dirty?", "A blackboard"],
    ["I get smaller every time I take a bath. What am I?", "A bar of soap"],
    ["I am always coming but never arrive. What am I?", "Tomorrow"],
    ["I have 64 squares, 32 pieces do battle on me. What am I?", "A chessboard"],
  ]),
};

// ===================== BORDERS WHICH COUNTRY? =====================
const qb = (rows) => rows.map(([country, borders]) => ({ q: `What countries border ${country}?`, a: borders }));

NEW_CATEGORIES_PACK_2.borders_country = {
  label: "Borders Which Country?",
  icon: "\u{1F5FA}\uFE0F",
  color: "#059669",
  200: qb([
    ["Canada", "United States"],
    ["Portugal", "Spain"],
    ["Ireland", "United Kingdom"],
    ["Monaco", "France"],
    ["Vatican City", "Italy"],
    ["Denmark", "Germany"],
    ["South Korea", "North Korea"],
    ["Haiti", "Dominican Republic"],
    ["North Korea", "China, Russia, South Korea"],
    ["Mexico", "United States, Guatemala, Belize"],
    ["Spain", "Portugal, France, Andorra"],
    ["United Kingdom", "Ireland"],
    ["Israel", "Lebanon, Syria, Jordan, Egypt"],
    ["Egypt", "Libya, Sudan, Israel"],
    ["Saudi Arabia", "Jordan, Iraq, Kuwait, Qatar, UAE, Oman, Yemen"],
    ["Italy", "France, Switzerland, Austria, Slovenia"],
    ["Netherlands", "Germany, Belgium"],
    ["Belgium", "Netherlands, Germany, Luxembourg, France"],
    ["Sweden", "Norway, Finland"],
    ["Norway", "Sweden, Finland, Russia"],
    ["Finland", "Sweden, Norway, Russia"],
    ["Greece", "Albania, North Macedonia, Bulgaria, Turkey"],
    ["Turkey", "Greece, Bulgaria, Georgia, Armenia, Azerbaijan, Iran, Iraq, Syria"],
    ["India", "Pakistan, China, Nepal, Bhutan, Bangladesh, Myanmar"],
    ["Pakistan", "India, Iran, Afghanistan, China"],
    ["Argentina", "Chile, Bolivia, Paraguay, Brazil, Uruguay"],
    ["Brazil", "French Guiana, Suriname, Guyana, Venezuela, Colombia, Peru, Bolivia, Paraguay, Argentina, Uruguay"],
    ["Chile", "Peru, Bolivia, Argentina"],
    ["Colombia", "Panama, Venezuela, Brazil, Peru, Ecuador"],
    ["Peru", "Ecuador, Colombia, Brazil, Bolivia, Chile"],
  ]),
  400: qb([
    ["France", "Spain, Andorra, Monaco, Italy, Switzerland, Germany, Luxembourg, Belgium"],
    ["Germany", "Denmark, Netherlands, Belgium, Luxembourg, France, Switzerland, Austria, Czech Republic, Poland"],
    ["Poland", "Germany, Czech Republic, Slovakia, Ukraine, Belarus, Lithuania, Russia"],
    ["Ukraine", "Russia, Belarus, Poland, Slovakia, Hungary, Romania, Moldova"],
    ["Russia", "Norway, Finland, Estonia, Latvia, Belarus, Ukraine, Georgia, Azerbaijan, Kazakhstan, China, Mongolia, North Korea, Lithuania, Poland"],
    ["China", "Mongolia, Russia, North Korea, Vietnam, Laos, Myanmar, India, Bhutan, Nepal, Pakistan, Afghanistan, Tajikistan, Kyrgyzstan, Kazakhstan"],
    ["Iran", "Iraq, Turkey, Azerbaijan, Armenia, Turkmenistan, Afghanistan, Pakistan"],
    ["Iraq", "Turkey, Iran, Kuwait, Saudi Arabia, Jordan, Syria"],
    ["Syria", "Turkey, Iraq, Jordan, Israel, Lebanon"],
    ["Lebanon", "Syria, Israel"],
    ["Switzerland", "France, Germany, Austria, Liechtenstein, Italy"],
    ["Austria", "Germany, Czech Republic, Slovakia, Hungary, Slovenia, Italy, Switzerland, Liechtenstein"],
    ["Hungary", "Austria, Slovakia, Ukraine, Romania, Serbia, Croatia, Slovenia"],
    ["Croatia", "Slovenia, Hungary, Serbia, Bosnia and Herzegovina, Montenegro"],
    ["Serbia", "Hungary, Romania, Bulgaria, North Macedonia, Kosovo, Montenegro, Bosnia and Herzegovina, Croatia"],
    ["Bulgaria", "Romania, Serbia, North Macedonia, Greece, Turkey"],
    ["Romania", "Ukraine, Moldova, Bulgaria, Serbia, Hungary"],
    ["Czech Republic", "Germany, Poland, Slovakia, Austria"],
    ["Slovakia", "Poland, Ukraine, Hungary, Austria, Czech Republic"],
    ["Belarus", "Latvia, Lithuania, Poland, Ukraine, Russia"],
    ["Lithuania", "Latvia, Belarus, Poland, Russia"],
    ["Estonia", "Latvia, Russia"],
    ["Latvia", "Estonia, Russia, Belarus, Lithuania"],
    ["Kazakhstan", "Russia, China, Kyrgyzstan, Uzbekistan, Turkmenistan"],
    ["Afghanistan", "Iran, Turkmenistan, Uzbekistan, Tajikistan, China, Pakistan"],
    ["Vietnam", "China, Laos, Cambodia"],
    ["Thailand", "Myanmar, Laos, Cambodia, Malaysia"],
    ["Malaysia", "Thailand, Indonesia, Brunei"],
    ["Indonesia", "Malaysia, Papua New Guinea, Timor-Leste"],
    ["Ethiopia", "Eritrea, Djibouti, Somalia, Kenya, South Sudan, Sudan"],
  ]),
  600: qb([
    ["Tajikistan", "Uzbekistan, Kyrgyzstan, China, Afghanistan"],
    ["Kyrgyzstan", "Kazakhstan, Uzbekistan, Tajikistan, China"],
    ["Uzbekistan", "Kazakhstan, Kyrgyzstan, Tajikistan, Afghanistan, Turkmenistan"],
    ["Turkmenistan", "Kazakhstan, Uzbekistan, Afghanistan, Iran"],
    ["Georgia", "Russia, Azerbaijan, Armenia, Turkey"],
    ["Azerbaijan", "Russia, Georgia, Armenia, Iran, Turkey"],
    ["Armenia", "Georgia, Azerbaijan, Iran, Turkey"],
    ["Bhutan", "China, India"],
    ["Nepal", "China, India"],
    ["Bangladesh", "India, Myanmar"],
    ["Myanmar", "India, Bangladesh, China, Laos, Thailand"],
    ["Laos", "Myanmar, China, Vietnam, Cambodia, Thailand"],
    ["Cambodia", "Thailand, Laos, Vietnam"],
    ["Moldova", "Romania, Ukraine"],
    ["North Macedonia", "Kosovo, Serbia, Bulgaria, Greece, Albania"],
    ["Albania", "Montenegro, Kosovo, North Macedonia, Greece"],
    ["Bosnia and Herzegovina", "Croatia, Serbia, Montenegro"],
    ["Kosovo", "Serbia, North Macedonia, Albania, Montenegro"],
    ["Slovenia", "Italy, Austria, Hungary, Croatia"],
    ["Luxembourg", "Belgium, Germany, France"],
    ["Andorra", "Spain, France"],
    ["Liechtenstein", "Switzerland, Austria"],
    ["San Marino", "Italy"],
    ["Mongolia", "Russia, China"],
    ["Jordan", "Syria, Iraq, Saudi Arabia, Israel"],
    ["Yemen", "Saudi Arabia, Oman"],
    ["Oman", "Saudi Arabia, UAE, Yemen"],
    ["Qatar", "Saudi Arabia"],
    ["Eritrea", "Sudan, Ethiopia, Djibouti"],
    ["Niger", "Algeria, Libya, Chad, Nigeria, Benin, Burkina Faso, Mali"],
  ]),
};

export default NEW_CATEGORIES_PACK_2;
