// New categories added in bulk. Shape matches RAW_BANK entries in App.jsx.
const qa = (rows) => rows.map(([q, a]) => ({ q, a }));
const who = (rows) => rows.map(([q, a, wiki]) => ({ q, a, wiki }));
const charades = (rows) => rows.map((a) => ({ q: "Act out this scenario!", a }));

const NEW_CATEGORIES_BANK = {
  // ===================== GENERAL =====================
  pop_culture: {
    label: "Pop Culture",
    icon: "\u{1F4F0}",
    color: "#EC4899",
    200: qa([
      ["Which app is famous for short dance videos?", "TikTok"],
      ["Who is Beyoncé's husband?", "Jay-Z"],
      ["Which streaming service has the red 'N' logo?", "Netflix"],
      ["Which boy band sang 'I Want It That Way'?", "Backstreet Boys"],
      ["Which Kardashian sister founded the brand 'SKIMS'?", "Kim Kardashian"],
      ["Which singer released 'Bad Guy' in 2019?", "Billie Eilish"],
      ["What is the name of the platform formerly known as Twitter?", "X"],
      ["Which famous Italian fashion brand has a Medusa logo?", "Versace"],
      ["Which video site is the largest in the world?", "YouTube"],
      ["Which app's logo is a yellow ghost on a yellow background?", "Snapchat"],
      ["Which Disney movie features Elsa and Anna?", "Frozen"],
      ["Which app uses a pink-and-white camera logo?", "Instagram"],
      ["Which singer married Justin Bieber?", "Hailey Baldwin"],
      ["Which animated franchise features a yellow sponge?", "SpongeBob SquarePants"],
      ["Who is the lead singer of Coldplay?", "Chris Martin"],
      ["Which fast food chain has golden arches?", "McDonald's"],
      ["Which game show host hosted 'Wheel of Fortune' for decades?", "Pat Sajak"],
      ["Which singer is known as 'Slim Shady'?", "Eminem"],
      ["Which Apple product is a smartphone?", "iPhone"],
      ["Which sport is Tom Brady famous for?", "American football"],
    ]),
    400: qa([
      ["Which reality show launched the Kardashians?", "Keeping Up with the Kardashians"],
      ["Who played Joey on Friends?", "Matt LeBlanc"],
      ["Which boy band did Harry Styles belong to?", "One Direction"],
      ["Who founded Apple alongside Steve Jobs?", "Steve Wozniak"],
      ["Which talk show host gave away cars to her audience?", "Oprah Winfrey"],
      ["Which actress starred in 'Pretty Woman'?", "Julia Roberts"],
      ["Which rapper released 'The Marshall Mathers LP'?", "Eminem"],
      ["What year did MTV first air?", "1981"],
      ["Which singer's real name is Stefani Germanotta?", "Lady Gaga"],
      ["Which actress played Wednesday in the 2022 Netflix series?", "Jenna Ortega"],
      ["Which YouTuber is the most-subscribed individual creator?", "MrBeast"],
      ["Which singer headlined the 2024 Super Bowl halftime show?", "Usher"],
      ["Which couple are nicknamed 'Bennifer'?", "Ben Affleck and Jennifer Lopez"],
      ["Which actress founded the production company Hello Sunshine?", "Reese Witherspoon"],
      ["Which singer wore a meat dress to the 2010 VMAs?", "Lady Gaga"],
      ["Which fashion designer founded Fenty Beauty?", "Rihanna"],
      ["Which K-pop group performed at the United Nations in 2018?", "BTS"],
      ["Which singer is dating NFL star Travis Kelce?", "Taylor Swift"],
      ["Which streaming service produced 'The Crown'?", "Netflix"],
      ["Which talk show host ended her 19-year daytime show in 2022?", "Ellen DeGeneres"],
      ["Which singer released the album '1989' in 2014?", "Taylor Swift"],
      ["Which TV show features the character Eleven with telekinetic powers?", "Stranger Things"],
      ["Which YouTuber-turned-boxer is known as 'KSI'?", "Olajide Olatunji"],
      ["Which model and actress is on the cover of British Vogue and known as 'Bella'?", "Bella Hadid"],
    ]),
    600: qa([
      ["Who was the first artist to have a music video on MTV?", "The Buggles"],
      ["Which magazine names the 'Person of the Year' annually?", "Time"],
      ["Who wrote and recorded 'Imagine' in 1971?", "John Lennon"],
      ["Which rapper founded Roc-A-Fella Records with Damon Dash?", "Jay-Z"],
      ["Who painted the Marilyn Diptych?", "Andy Warhol"],
      ["Which couple were known as 'Brangelina'?", "Brad Pitt and Angelina Jolie"],
      ["Who hosted 'The Daily Show' from 1999 to 2015?", "Jon Stewart"],
      ["Which fashion designer founded the brand YSL?", "Yves Saint Laurent"],
      ["Which TV show ended with the phrase 'Live long and prosper'?", "Star Trek"],
      ["Who created Spider-Man with Steve Ditko?", "Stan Lee"],
      ["Which actor has won the most Best Actor Oscars (3 wins)?", "Daniel Day-Lewis"],
      ["Which actor won Best Actor at the 2023 Oscars for 'The Whale'?", "Brendan Fraser"],
      ["Which 2023 film became Universal's highest-grossing animated film?", "The Super Mario Bros. Movie"],
      ["Which novel by Colleen Hoover topped 2022 bestseller lists?", "It Ends with Us"],
      ["Which Netflix documentary featured Taylor Swift in 2020?", "Miss Americana"],
      ["Which director made 'The Dark Knight'?", "Christopher Nolan"],
      ["Who founded the Met Gala fundraising tradition?", "Eleanor Lambert"],
      ["Which fashion magazine is run by Anna Wintour?", "Vogue"],
      ["Which Beatle was assassinated in 1980?", "John Lennon"],
      ["Which film won Best Animated Feature at the 2024 Oscars?", "The Boy and the Heron"],
      ["Who voices Princess Fiona in Shrek?", "Cameron Diaz"],
      ["Who wrote the 'Harry Potter' book series?", "J.K. Rowling"],
      ["Which actress holds the record for most Best Actress Oscar nominations?", "Meryl Streep"],
    ]),
  },

  technology: {
    label: "Technology",
    icon: "\u{1F4BB}",
    color: "#0EA5E9",
    200: qa([
      ["What does 'CPU' stand for?", "Central Processing Unit"],
      ["Which company makes the iPhone?", "Apple"],
      ["What does 'WWW' stand for?", "World Wide Web"],
      ["Which search engine is the most popular worldwide?", "Google"],
      ["What does 'PDF' stand for?", "Portable Document Format"],
      ["What does 'USB' stand for?", "Universal Serial Bus"],
      ["What is the brain of a computer called?", "CPU"],
      ["Which messaging app uses a green speech bubble logo and was bought by Facebook?", "WhatsApp"],
      ["What does 'Wi-Fi' allow you to do?", "Connect to the internet wirelessly"],
      ["What does 'AI' stand for?", "Artificial Intelligence"],
      ["Which company owns Instagram?", "Meta (Facebook)"],
      ["What is 'app' short for?", "Application"],
      ["Which company makes the Galaxy line of phones?", "Samsung"],
      ["What does 'ROM' stand for?", "Read-Only Memory"],
      ["What does 'RAM' stand for?", "Random Access Memory"],
      ["What is the name of Apple's voice assistant?", "Siri"],
      ["Which company makes Pixel phones?", "Google"],
      ["What is the name of the most popular video conferencing app launched in 2011 starting with 'Z'?", "Zoom"],
      ["Which device do you use to point and click on a computer screen?", "Mouse"],
      ["What is the name of Microsoft's web browser launched in 2015?", "Microsoft Edge"],
      ["What does 'GB' stand for in storage?", "Gigabyte"],
      ["Which company makes the MacBook?", "Apple"],
      ["What is the name of the famous open-source operating system kernel created by Linus Torvalds?", "Linux"],
      ["What does 'Bluetooth' connect?", "Devices wirelessly"],
      ["What does 'OS' stand for?", "Operating System"],
    ]),
    400: qa([
      ["Who founded Microsoft with Paul Allen?", "Bill Gates"],
      ["What does 'HTML' stand for?", "HyperText Markup Language"],
      ["Which company developed the Android operating system?", "Google"],
      ["Which programming language shares its name with an Indonesian island?", "Java"],
      ["What year was the first iPhone released?", "2007"],
      ["Who founded Tesla and SpaceX?", "Elon Musk"],
      ["What does 'GPU' stand for?", "Graphics Processing Unit"],
      ["What does 'IP' stand for in 'IP address'?", "Internet Protocol"],
      ["Which website did Mark Zuckerberg found in 2004?", "Facebook"],
      ["What does 'SSD' stand for?", "Solid State Drive"],
      ["What is the name of Google's web browser?", "Chrome"],
      ["What does 'VPN' stand for?", "Virtual Private Network"],
      ["Which company created the GeForce line of graphics cards?", "Nvidia"],
      ["What programming language is named after a snake?", "Python"],
      ["What does 'URL' stand for?", "Uniform Resource Locator"],
      ["What is the name of the cryptocurrency created by Satoshi Nakamoto?", "Bitcoin"],
      ["Which company developed the Mac OS?", "Apple"],
      ["What does 'LAN' stand for?", "Local Area Network"],
      ["What does 'HDD' stand for?", "Hard Disk Drive"],
      ["Which company makes the Kindle e-reader?", "Amazon"],
      ["Which programming language was developed by Brendan Eich at Netscape in 1995?", "JavaScript"],
      ["What does 'IoT' stand for?", "Internet of Things"],
      ["Which company developed the cloud platform AWS?", "Amazon"],
      ["What is the name of Microsoft's cloud platform?", "Azure"],
      ["Which company owns YouTube?", "Google"],
      ["Which Apple device launched in 2010 was the first major tablet?", "iPad"],
      ["What does 'JPG' stand for?", "Joint Photographic Experts Group"],
    ]),
    600: qa([
      ["Who is considered the inventor of the World Wide Web?", "Tim Berners-Lee"],
      ["What year was Google founded?", "1998"],
      ["Which protocol does email use to send messages?", "SMTP"],
      ["What does 'HTTP' stand for?", "HyperText Transfer Protocol"],
      ["Who co-founded Apple alongside Steve Jobs and Steve Wozniak?", "Ronald Wayne"],
      ["Which programming language was created by Guido van Rossum?", "Python"],
      ["What is the name of the first commercially successful microprocessor by Intel?", "Intel 4004"],
      ["What does 'API' stand for?", "Application Programming Interface"],
      ["Who founded Amazon?", "Jeff Bezos"],
      ["Who created the Linux kernel?", "Linus Torvalds"],
      ["In which year was Bitcoin first released?", "2009"],
      ["What does 'JSON' stand for?", "JavaScript Object Notation"],
      ["Who founded Oracle Corporation?", "Larry Ellison"],
      ["What does 'SQL' stand for?", "Structured Query Language"],
      ["Which protocol secures HTTPS connections?", "TLS"],
      ["What is the name of the version control system created by Linus Torvalds?", "Git"],
      ["Which company manufactures the H100 AI GPU?", "Nvidia"],
      ["Who founded OpenAI alongside Sam Altman?", "Elon Musk"],
      ["What is the name of the AI chatbot launched by OpenAI in November 2022?", "ChatGPT"],
      ["What is the name of Google's AI chatbot launched in 2023?", "Bard"],
      ["Who founded Dell Technologies?", "Michael Dell"],
      ["Which company developed the Unreal Engine?", "Epic Games"],
      ["Who founded Twitter alongside Jack Dorsey?", "Biz Stone, Evan Williams, and Noah Glass"],
      ["Which Apple co-founder was the first to leave the company (1976)?", "Ronald Wayne"],
      ["Which programming language was created by Bjarne Stroustrup?", "C++"],
      ["What is the name of Facebook's parent company since 2021?", "Meta"],
      ["Which company developed the React JavaScript library?", "Facebook (Meta)"],
      ["Which Intel CEO led the company through the 1990s PC boom?", "Andy Grove"],
      ["What does 'TCP' stand for in TCP/IP?", "Transmission Control Protocol"],
    ]),
  },

  // ===================== FICTION =====================
  family_guy: {
    label: "Family Guy",
    icon: "\u{1F436}",
    color: "#22C55E",
    200: qa([
      ["What is the name of the Griffin family's talking dog?", "Brian"],
      ["What is the name of the Griffin baby?", "Stewie"],
      ["What town do the Griffins live in?", "Quahog"],
      ["What is Peter Griffin's wife's name?", "Lois"],
      ["Who created Family Guy?", "Seth MacFarlane"],
      ["What is the name of Peter and Lois's daughter?", "Meg"],
      ["What state is Quahog located in?", "Rhode Island"],
      ["What is the name of Peter's older son?", "Chris"],
      ["What kind of animal is Brian?", "Dog"],
      ["In what fictional state university did Peter and Lois meet?", "Brown University"],
      ["What network airs Family Guy?", "Fox"],
      ["What is the name of the bar where Peter and his friends drink?", "The Drunken Clam"],
      ["What is the name of Peter's wheelchair-using friend?", "Joe Swanson"],
      ["What is the name of the perverted neighbor with the catchphrase 'Giggity'?", "Glenn Quagmire"],
      ["What is Quagmire's catchphrase?", "Giggity"],
      ["What is the name of Peter's African-American friend who got a spinoff?", "Cleveland Brown"],
      ["What is the name of Stewie's teddy bear?", "Rupert"],
      ["What does Stewie usually want to do to Lois (his mother)?", "Kill her"],
      ["What language can Brian speak?", "English"],
      ["What instrument does Lois teach?", "Piano"],
      ["What is the name of the news anchor on Quahog 5 News?", "Tom Tucker"],
      ["What is the name of Joe Swanson's wife?", "Bonnie"],
      ["What is Cleveland's spinoff series called?", "The Cleveland Show"],
      ["What city is Quahog modeled after?", "Providence (Rhode Island)"],
      ["Who voices Peter, Brian, and Stewie?", "Seth MacFarlane"],
      ["What kind of glasses does Peter wear?", "Round black glasses"],
    ]),
    400: qa([
      ["What is Peter's job at the Pawtucket Brewery?", "Safety inspector"],
      ["What is the name of the brewery's signature beer?", "Pawtucket Patriot Ale"],
      ["What is the name of Peter's father?", "Francis Griffin"],
      ["What is Lois's maiden name?", "Pewterschmidt"],
      ["What is the name of Lois's wealthy father?", "Carter Pewterschmidt"],
      ["What is the name of Lois's mother?", "Babs Pewterschmidt"],
      ["What is the name of the giant chicken Peter regularly fights?", "Ernie the Giant Chicken"],
      ["What is the name of Cleveland's son?", "Cleveland Brown Jr."],
      ["What is Stewie's main weapon of choice in cutaways?", "Ray gun"],
      ["What is the name of the elderly creepy neighbor voiced by Mike Henry?", "Herbert"],
      ["What is the name of the Jewish pharmacist character?", "Mort Goldman"],
      ["What is Quagmire's profession?", "Airline pilot"],
      ["What is the name of Quagmire's sister?", "Brenda"],
      ["What is the name of Brenda's abusive boyfriend?", "Jeff Fecalman"],
      ["Who voices Lois Griffin?", "Alex Borstein"],
      ["Who voices Meg Griffin?", "Mila Kunis"],
      ["What is the name of the local news co-anchor with Tom Tucker?", "Diane Simmons"],
      ["What is the name of Tom Tucker's son?", "Jake Tucker"],
      ["What is Jake Tucker's distinctive feature?", "Upside-down face"],
      ["What is the name of Peter's autistic-coded next-door neighbor with a wife and kid that has a deep voice?", "Joe Swanson"],
      ["What is Joe Swanson's profession?", "Police officer"],
      ["What is the name of Cleveland's first wife (mother of Cleveland Jr.)?", "Loretta"],
      ["What is the name of Cleveland's second wife in the spinoff?", "Donna"],
      ["What is Peter's mother's name?", "Thelma Griffin"],
      ["Which Star Wars film did Family Guy parody first?", "A New Hope"],
      ["What was the title of Family Guy's Star Wars parody special?", "Blue Harvest"],
      ["What is the name of the Catholic priest character in Quahog?", "Father John"],
      ["What is the name of the Asian reporter character?", "Tricia Takanawa"],
    ]),
    600: qa([
      ["In what year did Family Guy first premiere?", "1999"],
      ["What was Brian's novel called?", "Faster Than the Speed of Love"],
      ["What is the name of Brian's son introduced in the show?", "Dylan"],
      ["Which character briefly died and was replaced by Vinny the dog?", "Brian"],
      ["What is the name of the cleaning lady character voiced by Seth MacFarlane?", "Consuela"],
      ["What is Consuela's catchphrase?", "No, no"],
      ["What is the name of Quagmire's father, who later transitions and is named Ida?", "Dan Quagmire"],
      ["What is the name of Peter's evil twin brother in 'The Tan Aquatic with Steve Zissou'?", "Thaddeus Griffin"],
      ["What is the title of the episode where Brian dies (season 12)?", "Life of Brian"],
      ["What is the name of Stewie's half-brother (Brian's son)?", "Dylan Flannigan"],
      ["What is the title of Family Guy's Empire Strikes Back parody?", "Something, Something, Something, Dark Side"],
      ["What is the title of Family Guy's Return of the Jedi parody?", "It's a Trap!"],
      ["What was the title of Seth MacFarlane's original animated short that became Family Guy?", "The Life of Larry"],
      ["What is the name of the local TV anchor played by Adam West (the mayor)?", "Mayor Adam West"],
      ["What is the name of the rich British neighbor in 'No Chris Left Behind'?", "Buzz Killington"],
      ["What is Quagmire's full first name?", "Glenn"],
      ["Who is the dog that fills in for Brian after his death?", "Vinny"],
      ["Who voices Vinny the dog?", "Tony Sirico"],
      ["What is the name of the talk show parodied in 'Tom Tucker: The Man and His Dream'?", "Tom Tucker show"],
      ["What is Peter's favorite TV show within the show?", "Gumbel 2 Gumbel"],
      ["What is the name of the obese man Peter befriends in 'McStroke'?", "Skip"],
      ["What is the name of Peter's gay cousin?", "Jasper"],
      ["Who is the actor that voices the Greased-Up Deaf Guy?", "Seth MacFarlane"],
      ["What is the name of the rooster Peter fights in season 3's 'Da Boom'?", "Ernie the Giant Chicken"],
      ["What episode introduced Stewie's time machine?", "The Big Bang Theory"],
      ["Who voices Cleveland Brown originally?", "Mike Henry"],
      ["What network briefly cancelled Family Guy before reviving it due to DVD sales?", "Fox"],
    ]),
  },

  himym: {
    label: "How I Met Your Mother",
    icon: "\u{1F37B}",
    color: "#3B82F6",
    200: qa([
      ["Who is the main narrator of the show?", "Ted Mosby"],
      ["What is the name of Ted's best friend who loves suits?", "Barney Stinson"],
      ["Who plays Barney Stinson?", "Neil Patrick Harris"],
      ["What is Marshall's wife's name?", "Lily"],
      ["What is the name of the bar the gang hangs out at?", "MacLaren's"],
      ["What is Barney's catchphrase about something being awesome?", "Legendary"],
      ["What is Ted's profession?", "Architect"],
      ["What is the title of Barney's published rulebook?", "The Bro Code"],
      ["Who plays Ted Mosby?", "Josh Radnor"],
      ["Who plays Marshall?", "Jason Segel"],
      ["Who plays Robin?", "Cobie Smulders"],
      ["Who plays Lily?", "Alyson Hannigan"],
      ["What is Lily's profession?", "Kindergarten teacher"],
      ["What is Marshall's last name?", "Eriksen"],
      ["What state is Marshall from?", "Minnesota"],
      ["How many seasons did How I Met Your Mother run?", "9"],
      ["Who is Ted telling the story of meeting their mother to?", "His kids"],
      ["What network aired How I Met Your Mother?", "CBS"],
      ["What does Barney say when he wants Ted to change clothes?", "Suit up"],
      ["Who is the womanizer of the group?", "Barney Stinson"],
      ["What kind of journalist is Robin?", "TV news anchor"],
      ["What was Marshall's college a cappella group called?", "The Funky Bunch"],
      ["What is Ted's last name?", "Mosby"],
      ["What is Lily's maiden name?", "Aldrin"],
      ["What does Marshall call himself when bowling with the Fiero?", "Big Fudge"],
    ]),
    400: qa([
      ["What was Robin's secret pop star past identity?", "Robin Sparkles"],
      ["What is the name of Robin Sparkles' famous song?", "Let's Go to the Mall"],
      ["How many kids do Marshall and Lily have by the show's end?", "3"],
      ["What is the name of Marshall and Lily's first child?", "Marvin"],
      ["What is Marvin named after?", "Marshall's father (Marvin Eriksen)"],
      ["What bank does Barney work at for most of the series?", "Goliath National Bank"],
      ["What is the name of Ted's would-be pun-themed bar concept in season 8?", "Puzzles"],
      ["What is Ted's ex-fiancée from the pilot's name?", "Stella"],
      ["Who plays Stella?", "Sarah Chalke"],
      ["What is the name of the dermatologist Ted dates and almost marries?", "Stella Zinman"],
      ["What is Marshall's father's name?", "Marvin Eriksen Sr."],
      ["What is Lily's high school boyfriend who keeps reappearing?", "Scooter"],
      ["What is the name of Marshall's beloved car?", "The Fiero"],
      ["What is the name of Barney's half-brother?", "James Stinson"],
      ["Who is revealed to be Barney's father?", "Jerome Whittaker"],
      ["What is the name of Robin's coworker and ex who works as a doctor in season 3 onwards?", "Don Frank"],
      ["Who plays Ted's pretentious college ex who reappears as his girlfriend in season 3?", "Laura Prepon"],
      ["What is the name of Marshall's law firm?", "Honeywell and Cootes"],
      ["What footwear does Ted wear that the gang openly mocks?", "Red cowboy boots"],
      ["What is the name of Marshall's rival lawyer (the one Ted dates)?", "Brad"],
      ["What field of law does Marshall really want to practice?", "Environmental law"],
      ["What is Ted's most famous catchphrase?", "True story"],
      ["What is Barney's favorite catch-phrase number game?", "Have you met Ted?"],
      ["Who plays Robin's strict father from season 6 onward?", "Ray Wise"],
      ["What is the name of the strip club Barney frequents?", "The Lusty Leopard"],
      ["What season is Barney's catchphrase 'suit up' first used?", "Season 1"],
      ["What is the name of Lily's grandmother who appears in flashbacks?", "Lola"],
      ["Who plays Marshall's father, Marvin Sr.?", "Bill Fagerbakke"],
      ["What is the name of the wedding chapel Barney and Robin get married at?", "Farhampton Inn"],
    ]),
    600: qa([
      ["What is the name of the Mother?", "Tracy McConnell"],
      ["Who plays the Mother?", "Cristin Milioti"],
      ["What instrument does the Mother play?", "Bass guitar"],
      ["What yellow item does the Mother carry that Ted spots?", "A yellow umbrella"],
      ["How many slaps did Marshall get to give Barney in the original slap bet?", "5"],
      ["What is the name of the second Robin Sparkles song revealed?", "Sandcastles in the Sand"],
      ["Who guest starred in 'Sandcastles in the Sand' as Robin's love interest?", "James Van Der Beek"],
      ["What is the title of Robin Sparkles' grunge alter ego revealed later?", "Robin Daggers"],
      ["What is the name of Barney's mother?", "Loretta Stinson"],
      ["Who plays Barney's mother?", "Frances Conroy"],
      ["What year does the show begin (in the framing story)?", "2030"],
      ["What is the name of the eco-conscious lawyer Marshall idolizes and works for at Nicholson, Hewitt & West?", "Garrison Cootes"],
      ["What is the name of the show's creators?", "Carter Bays and Craig Thomas"],
      ["What is the name of the opening theme song's band?", "The Solids"],
      ["What is Marshall's nickname based on his last name?", "The Marshmallow"],
      ["What is the name of the play Lily directs in season 3?", "The Wedding Bride"],
      ["What is the title of the in-universe movie that mocks Ted?", "The Wedding Bride"],
      ["Who plays the Captain (Zoey's husband)?", "Kyle MacLachlan"],
      ["What is the name of Ted's main season 6 girlfriend (Zoey's friend)?", "Zoey Pierson"],
      ["Who plays Zoey?", "Jennifer Morrison"],
      ["What is the name of the building Ted designs and Zoey wants to save?", "The Arcadian"],
      ["What is the name of Marshall's father's restaurant?", "Big Fudge's"],
      ["What is the name of the location Barney and Robin's wedding takes place?", "Farhampton Inn"],
      ["Who plays Barney's father, Jerome Whittaker?", "John Lithgow"],
      ["What is the name of Ted's son?", "Luke"],
      ["What is the name of Ted's daughter?", "Penny"],
      ["How does the Mother die?", "Of an illness"],
      ["What does Ted do at the end of the series after the Mother's death?", "Pursues Robin again"],
      ["What is the name of the show's spin-off?", "How I Met Your Father"],
      ["Who stars in 'How I Met Your Father'?", "Hilary Duff"],
    ]),
  },

  modern_family: {
    label: "Modern Family",
    icon: "\u{1F46A}",
    color: "#F59E0B",
    200: qa([
      ["What is the name of the family patriarch played by Ed O'Neill?", "Jay Pritchett"],
      ["What is Jay's young Colombian wife's name?", "Gloria"],
      ["Who plays Gloria?", "Sofía Vergara"],
      ["What is the name of Gloria's son from her first marriage?", "Manny"],
      ["Who is Phil Dunphy's wife?", "Claire"],
      ["What is the name of Mitchell and Cameron's adopted daughter?", "Lily"],
      ["What is Mitchell Pritchett's partner's name?", "Cameron"],
      ["What is Jay's dog's name?", "Stella"],
      ["What city is the show set in?", "Los Angeles"],
      ["What kind of dog is Stella?", "French bulldog"],
      ["Who plays Phil Dunphy?", "Ty Burrell"],
      ["Who plays Claire Dunphy?", "Julie Bowen"],
      ["Who plays Cameron?", "Eric Stonestreet"],
      ["Who plays Mitchell?", "Jesse Tyler Ferguson"],
      ["What is Phil Dunphy's profession?", "Real estate agent"],
      ["What is the name of Phil and Claire's three children?", "Haley, Alex, and Luke"],
      ["What is the name of the eldest Dunphy child?", "Haley"],
      ["What is the name of the middle Dunphy child?", "Alex"],
      ["What is the name of the youngest Dunphy child?", "Luke"],
      ["What network aired Modern Family?", "ABC"],
      ["What style is the show filmed in?", "Mockumentary"],
      ["How many years did Modern Family run?", "11 (seasons)"],
      ["Who is the eldest Pritchett-Tucker child?", "Lily"],
      ["What is the name of Manny's biological father?", "Javier"],
      ["What is Gloria's home country?", "Colombia"],
      ["What language does Gloria speak besides English?", "Spanish"],
    ]),
    400: qa([
      ["What is Cameron's profession?", "Music teacher"],
      ["What was Cameron's previous job before teaching music?", "PE coach (football coach)"],
      ["What is Mitchell's profession?", "Lawyer"],
      ["What is the name of the baby Jay and Gloria have together?", "Joe"],
      ["What state is Cameron originally from?", "Missouri"],
      ["How many seasons of Modern Family aired?", "11"],
      ["What is the name of Haley's eventual husband?", "Dylan"],
      ["What instrument does Dylan play?", "Guitar"],
      ["What university does Alex Dunphy attend?", "Caltech"],
      ["What is the name of Cameron's clown alter-ego?", "Fizbo"],
      ["What is Claire's maiden name?", "Pritchett"],
      ["What is the name of Jay's ex-wife and mother of Claire and Mitchell?", "DeDe"],
      ["What was Jay's company called?", "Pritchett's Closets & Blinds"],
      ["What is Cameron's last name?", "Tucker"],
      ["What is Mitchell's last name?", "Pritchett"],
      ["What is the name of Phil's father?", "Frank Dunphy"],
      ["Who plays Phil's father, Frank Dunphy?", "Fred Willard"],
      ["What is Manny's biological father's name?", "Javier Delgado"],
      ["What university does Haley eventually attend?", "Community college"],
      ["What is the name of Cam's sister?", "Pameron"],
      ["What is the name of Cameron's mother?", "Barb"],
      ["What is the name of Cameron's father?", "Merle"],
      ["What is the name of Manny's grandmother (Gloria's mother)?", "Pilar"],
      ["What is Phil's university where he became a cheerleader?", "University of Wisconsin (UW)"],
      ["What hobby is Phil obsessed with that involves close-up tricks?", "Magic"],
      ["What is the name of Jay's golf course buddy and rival?", "Shorty"],
      ["What is Manny's favorite sport (older interest)?", "Fencing"],
      ["What language do Gloria and her family often speak?", "Spanish"],
      ["What does Lily call Cam to upset him in early seasons?", "Mom"],
    ]),
    600: qa([
      ["In what year did Modern Family premiere?", "2009"],
      ["In what year did Modern Family end?", "2020"],
      ["How many Emmy Awards did Modern Family win for Outstanding Comedy Series?", "5"],
      ["Who created Modern Family?", "Christopher Lloyd and Steven Levitan"],
      ["What is the name of the twins Haley has at the end of the series?", "Poppy and George"],
      ["Who is the father of Haley's twins?", "Dylan"],
      ["What is the name of Cam's twin sister played by Eric Stonestreet?", "Pameron"],
      ["What is Phil's catchphrase about being a 'cool dad'?", "I'm a cool dad"],
      ["What is the name of the soap opera Gloria appears in (in-universe)?", "Fuego"],
      ["At which California school does Manny first attend college?", "Caltech"],
      ["Who plays the older Lily Tucker-Pritchett?", "Aubrey Anderson-Emmons"],
      ["What U.S. agency does Alex Dunphy intern at in later seasons?", "NASA"],
      ["What state does the Dunphy-Pritchett family go on a dude-ranch vacation to in season 3?", "Wyoming"],
      ["Where do Mitchell and Cameron get married in season 5?", "Their backyard"],
      ["In which season do Mitchell and Cameron get married?", "5"],
      ["What is the theme of the rehearsal dinner Cam plans for his wedding?", "The Wizard of Oz"],
      ["What is the name of Phil's real-estate mentor played by Stephen Merchant?", "Tom"],
      ["Where does Haley work after being hired as Nathan Fillion's character's assistant?", "A lifestyle website"],
      ["Who plays Manny Delgado's biological father, Javier?", "Benjamin Bratt"],
      ["Who plays Cameron's overbearing mother, Barb?", "Celia Weston"],
      ["What is the name of Phil's brother?", "Wayne"],
      ["What instrument does Phil play in front of his children to embarrass them?", "Banjo"],
      ["What is the name of Gloria's hometown in Colombia?", "Barranquilla"],
      ["What instrument does Cameron play that he often brags about?", "Saxophone"],
      ["Who plays Manny Delgado?", "Rico Rodriguez"],
      ["Who plays Luke Dunphy?", "Nolan Gould"],
      ["Who plays Alex Dunphy?", "Ariel Winter"],
      ["Who plays Haley Dunphy?", "Sarah Hyland"],
    ]),
  },

  blacklist: {
    label: "The Blacklist",
    icon: "\u{1F575}",
    color: "#1F2937",
    200: qa([
      ["Who plays Raymond 'Red' Reddington?", "James Spader"],
      ["What government agency does Red work with?", "FBI"],
      ["What is the name of the FBI profiler Red insists on working with?", "Elizabeth Keen"],
      ["Who plays Elizabeth Keen?", "Megan Boone"],
      ["What is the name of the list Red helps the FBI hunt down?", "The Blacklist"],
      ["What network airs The Blacklist?", "NBC"],
      ["What hat is Red famously associated with?", "Fedora"],
      ["What is Liz's job title at the start of the show?", "FBI profiler"],
      ["What is Liz's nickname (used by Red)?", "Lizzy"],
      ["What is the name of Red's bodyguard?", "Dembe Zuma"],
      ["What is the name of Liz's first husband?", "Tom Keen"],
      ["Who plays Tom Keen?", "Ryan Eggold"],
      ["What is the name of the FBI Assistant Director who oversees the task force?", "Harold Cooper"],
      ["Who plays Harold Cooper?", "Harry Lennix"],
      ["In what year did The Blacklist premiere?", "2013"],
      ["What is Liz's daughter's name?", "Agnes"],
      ["What is the name of the FBI agent partnered with Liz played by Diego Klattenhoff?", "Donald Ressler"],
      ["What is the name of the Mossad agent on the task force?", "Samar Navabi"],
      ["What is Red's preferred drink?", "Wine"],
      ["What is Tom's secret occupation?", "Spy"],
      ["What is Red's primary occupation?", "Criminal broker"],
      ["What city is the show primarily set in?", "Washington, D.C."],
      ["Who created The Blacklist?", "Jon Bokenkamp"],
      ["How many seasons of The Blacklist aired?", "10"],
      ["Who plays Aram Mojtabai on the task force?", "Amir Arison"],
    ]),
    400: qa([
      ["What is the name of Red's bodyguard played by Hisham Tawfiq?", "Dembe Zuma"],
      ["What was Tom Keen's secret occupation?", "Spy/operative"],
      ["What is Red's cooking hobby on the show?", "Gourmet cooking"],
      ["What is Liz's biological mother's name?", "Katarina Rostova"],
      ["What nationality is Katarina Rostova?", "Russian"],
      ["What is Tom Keen's real name?", "Jacob Phelps"],
      ["What is the name of the cleaner Red employs played by Susan Blommaert?", "Mr. Kaplan"],
      ["What is the name of the show's spin-off?", "The Blacklist: Redemption"],
      ["What is the name of Liz's adoptive father?", "Sam Milhoan"],
      ["What is the name of the FBI tech analyst on the task force?", "Aram Mojtabai"],
      ["How many people are originally on the FBI Blacklist task force?", "5"],
      ["What is the name of Red's daughter that Liz turned out to be (initially believed)?", "Masha Rostova"],
      ["Who plays Dembe Zuma?", "Hisham Tawfiq"],
      ["What is the name of the prison Red frequents in the early seasons?", "Black site"],
      ["What is Red's favorite type of music?", "Jazz / classical"],
      ["What is the name of the criminal organization led by 'The Major'?", "The Major's network"],
      ["What is the name of Red's old associate played by Alan Alda?", "Alan Fitch"],
      ["What is the name of the briefcase Red guards full of secrets?", "The Fulcrum"],
      ["Who plays Samar Navabi?", "Mozhan Marnò"],
      ["Who plays Donald Ressler?", "Diego Klattenhoff"],
      ["What is the name of the task force's HQ called?", "The Post Office"],
      ["What city is the FBI 'Post Office' headquarters located in?", "Washington, D.C."],
      ["Who plays the character Mr. Kaplan?", "Susan Blommaert"],
      ["What is Red's profession before becoming a criminal (his former Navy rank)?", "Naval officer"],
      ["What is the name of Liz's sister later introduced?", "Jennifer Reddington"],
      ["Who is the lead character of the spinoff Blacklist: Redemption?", "Tom Keen"],
    ]),
    600: qa([
      ["What is the name of the leader of the Cabal known as 'The Director'?", "Peter Kotsiopolis"],
      ["What is Liz's full name?", "Elizabeth Scott Keen"],
      ["Which character dies in the season 8 finale?", "Elizabeth Keen"],
      ["How many episodes does the original Blacklist series have in total?", "218"],
      ["What is the name of Red's pilot character played in early seasons?", "Edward"],
      ["Who plays Katarina Rostova?", "Lotte Verbeek"],
      ["What is the name of the Russian agent and Liz's mother's lover?", "Ilya Koslov"],
      ["What is the title of the season 1 finale?", "Berlin: Conclusion"],
      ["What is the name of the character played by Edi Gathegi?", "Matias Solomon"],
      ["What is Matias Solomon's role?", "Mercenary working for the Cabal"],
      ["What is the name of the person Tom is hired to investigate before meeting Liz?", "Liz herself"],
      ["What is the name of Tom's adoptive mother who is also a spy?", "Susan 'Scottie' Hargrave"],
      ["Who plays Susan 'Scottie' Hargrave in the spinoff?", "Famke Janssen"],
      ["What is Tom Keen's cover job in season 1?", "Substitute teacher"],
      ["What is the name of the assassin who claims his payment in cash on shipping containers in season 1?", "The Courier"],
      ["What is the name of the character Cooper's wife?", "Charlene Cooper"],
      ["Who plays Charlene Cooper?", "Valarie Pettiford"],
      ["Who plays the older Katarina Rostova revealed in season 7?", "Laila Robins"],
      ["What is Tom's biological father's name (revealed in spinoff)?", "Howard Hargrave"],
      ["Who plays Howard Hargrave?", "Terry O'Quinn"],
      ["What is the name of the character Red's lawyer?", "Marvin Gerard"],
      ["Who plays Marvin Gerard?", "Fisher Stevens"],
      ["In which episode does Mr. Kaplan turn against Red?", "Mr. Kaplan: Conclusion"],
      ["What number on the Blacklist is the assassin known as The Freelancer?", "145"],
      ["What is the name of the task force agent introduced in later seasons played by Anya Banerjee?", "Siya Malik"],
      ["Who plays Siya Malik?", "Anya Banerjee"],
      ["What is Liz's biological grandfather's name?", "Dom Wilkinson"],
      ["Who plays Dom Wilkinson?", "Brian Dennehy"],
      ["Who plays the recurring assassin known as Garvey?", "Jonny Coyne"],
      ["What is Liz's daughter Agnes's father?", "Tom Keen"],
    ]),
  },

  arrow: {
    label: "Arrow",
    icon: "\u{1F3F9}",
    color: "#16A34A",
    200: qa([
      ["Who is the main character of Arrow?", "Oliver Queen"],
      ["Who plays Oliver Queen?", "Stephen Amell"],
      ["What city does Arrow protect?", "Star City"],
      ["What was Star City originally called?", "Starling City"],
      ["What weapon does the Arrow primarily use?", "Bow and arrow"],
      ["Who is Oliver's tech-savvy ally and love interest with blonde hair?", "Felicity Smoak"],
      ["Who plays Felicity Smoak?", "Emily Bett Rickards"],
      ["What island was Oliver stranded on before becoming Arrow?", "Lian Yu"],
      ["What network aired Arrow?", "The CW"],
      ["What is the name of Oliver's sister?", "Thea Queen"],
      ["Who is Oliver's bodyguard turned best friend?", "John Diggle"],
      ["Who plays John Diggle?", "David Ramsey"],
      ["What is Diggle's superhero alias?", "Spartan"],
      ["In what year did Arrow premiere?", "2012"],
      ["What is the name of Oliver's mother?", "Moira Queen"],
      ["What is Oliver's father's name?", "Robert Queen"],
      ["Who is the comic book character Arrow is based on?", "Green Arrow"],
      ["How many seasons of Arrow aired?", "8"],
      ["Who created Arrow (with Greg Berlanti and Andrew Kreisberg)?", "Marc Guggenheim"],
      ["What family-owned company does Oliver inherit?", "Queen Consolidated"],
      ["Who is Oliver's best friend (the other rich playboy)?", "Tommy Merlyn"],
      ["What is Tommy Merlyn's father's name?", "Malcolm Merlyn"],
      ["What organization is Malcolm Merlyn the leader of?", "League of Assassins"],
      ["What is Felicity's job at Queen Consolidated?", "IT specialist"],
      ["What weapon does the Black Canary use?", "Sonic device (Canary Cry)"],
      ["Who is Sara Lance's sister?", "Laurel Lance"],
    ]),
    400: qa([
      ["What is the name of Oliver and Felicity's son?", "William"],
      ["What is the name of the assassin who is Ra's al Ghul's daughter?", "Nyssa al Ghul"],
      ["What is the name of the League of Assassins leader?", "Ra's al Ghul"],
      ["What is Laurel Lance's vigilante alias?", "Black Canary"],
      ["Who plays Laurel Lance?", "Katie Cassidy"],
      ["Who is Laurel's father, the police detective?", "Quentin Lance"],
      ["What is Slade Wilson's villain alias?", "Deathstroke"],
      ["What is Thea's vigilante alias?", "Speedy"],
      ["Who plays Thea Queen?", "Willa Holland"],
      ["What is Roy Harper's vigilante alias?", "Arsenal"],
      ["Who plays Roy Harper?", "Colton Haynes"],
      ["What is the name of Sara Lance's vigilante alias?", "White Canary"],
      ["Who plays Sara Lance?", "Caity Lotz"],
      ["What is Diggle's wife's name?", "Lyla Michaels"],
      ["What organization does Lyla Michaels work for?", "A.R.G.U.S."],
      ["Who is the Big Bad of Season 1?", "Malcolm Merlyn"],
      ["Who is the Big Bad of Season 2?", "Slade Wilson"],
      ["Who is the Big Bad of Season 3?", "Ra's al Ghul"],
      ["Who is the Big Bad of Season 4?", "Damien Darhk"],
      ["Who plays Damien Darhk?", "Neal McDonough"],
      ["What is Malcolm Merlyn's alias?", "Dark Archer"],
      ["Who plays Malcolm Merlyn?", "John Barrowman"],
      ["What is the name of Oliver's first vigilante hideout?", "The Foundry"],
      ["What is Felicity's mother's name?", "Donna Smoak"],
      ["Who plays Donna Smoak?", "Charlotte Ross"],
      ["What is the name of Diggle's brother who was killed?", "Andy Diggle"],
      ["What is the name of the news reporter on the show?", "Susan Williams"],
      ["What island became Slade Wilson's prison after the events of Season 2?", "Lian Yu"],
      ["What is the name of Quentin Lance's wife (and Laurel's mother)?", "Dinah Lance"],
      ["What season introduces Mr. Terrific?", "Season 4"],
    ]),
    600: qa([
      ["What is Malcolm Merlyn's plan called in Season 1?", "The Undertaking"],
      ["What is the name of the Suicide Squad team Diggle joined briefly?", "Task Force X"],
      ["What is the name of the spin-off featuring time travelers?", "Legends of Tomorrow"],
      ["What is the name of the crossover event where Oliver dies?", "Crisis on Infinite Earths"],
      ["Who plays the new Black Canary in later seasons (Dinah Drake)?", "Juliana Harkavy"],
      ["What is the name of the new Mr. Terrific introduced in Season 4?", "Curtis Holt"],
      ["Who plays Curtis Holt?", "Echo Kellum"],
      ["What is the name of the villain who is Oliver's half-brother revealed in Season 6?", "Emiko Queen"],
      ["Who plays Emiko Queen?", "Sea Shimooka"],
      ["What is the name of the Arrow Cave's first nickname before becoming the Bunker?", "The Foundry"],
      ["What is the name of the show's first crossover with The Flash?", "Flash vs. Arrow"],
      ["In which episode is Tommy Merlyn killed?", "Sacrifice (Season 1 finale)"],
      ["What is Sara Lance's death scene weapon (her killer in Season 3)?", "Three arrows"],
      ["Who is revealed to have killed Sara Lance in Season 3?", "Thea Queen (under Malcolm's influence)"],
      ["What is the name of the criminal organization Emiko Queen leads?", "The Ninth Circle"],
      ["Who is Prometheus, the Season 5 villain, in his civilian identity?", "Adrian Chase"],
      ["Who plays Adrian Chase?", "Josh Segarra"],
      ["What is the name of Oliver's son's mother?", "Samantha Clayton"],
      ["What was the name of Felicity's hacker alias?", "Overwatch"],
      ["What is the name of John Diggle's daughter?", "Sara"],
      ["What is the name of the alternate Earth Diggle visits?", "Earth-2"],
      ["What is the name of Oliver's stepfather?", "Walter Steele"],
      ["Who plays Walter Steele?", "Colin Salmon"],
      ["What is the name of the future setting in the Season 7+ flash-forwards?", "Star City 2040"],
      ["What is the name of Oliver's daughter introduced in flash-forwards?", "Mia Smoak"],
      ["Who plays Mia Smoak?", "Katherine McNamara"],
      ["Who plays Tommy Merlyn?", "Colin Donnell"],
      ["What is the name of the show's final episode?", "Fadeout"],
      ["Which season does Felicity leave the show?", "Season 7"],
    ]),
  },

  // ===================== GAMING =====================
  ark_survival: {
    label: "ARK: Survival Evolved",
    icon: "\u{1F995}",
    color: "#0891B2",
    200: qa([
      ["What kind of creatures can you tame in ARK?", "Dinosaurs"],
      ["What developer created ARK: Survival Evolved?", "Studio Wildcard"],
      ["What is the basic resource you punch trees for?", "Wood"],
      ["What flying dinosaur is one of the most iconic mounts?", "Pteranodon"],
      ["What large carnivore is featured prominently on the cover?", "Tyrannosaurus Rex"],
      ["What city is Studio Wildcard headquartered in?", "Bellevue, Washington"],
      ["What food source restores hunger most reliably for early players?", "Cooked meat"],
      ["What item do you craft first to start a fire?", "Campfire"],
      ["What do you place to mark your respawn point?", "Bed"],
      ["What is the name of the first map released?", "The Island"],
      ["What is the most basic firearm in ARK?", "Simple Pistol"],
      ["What kind of armor is the most basic in ARK?", "Cloth armor"],
      ["What stat do you increase to carry more items?", "Weight"],
      ["What stat increases how much damage you do?", "Melee Damage"],
      ["What dinosaur is famous for its frill and acid spit?", "Dilophosaurus"],
      ["What animal is the most common early-game tame for berry gathering?", "Triceratops"],
      ["What is the name of the small lizard you can tame and put on your shoulder?", "Compsognathus"],
      ["What basic shelter piece do you craft first to build a hut?", "Thatch foundation"],
      ["What plant on Scorched Earth do you eat for water?", "Cactus"],
      ["What does the engram system let you do?", "Unlock crafting recipes"],
      ["How do you typically tame a carnivore?", "Knock it out and feed it meat"],
      ["What does the torpor stat measure?", "Unconsciousness level"],
      ["Which ranged weapon is the earliest available?", "Bow"],
      ["Which tool do you use to harvest meat efficiently from a corpse?", "Metal hatchet"],
      ["What is the name of the giant snail that produces cementing paste?", "Achatina"],
      ["What dinosaur is most known for its three horns?", "Triceratops"],
    ]),
    400: qa([
      ["What is the name of the giant gorilla boss on The Island?", "Megapithecus"],
      ["Which expansion map features a Norse mythology theme with wyverns?", "Ragnarok"],
      ["Which expansion is set in a futuristic alien environment?", "Extinction"],
      ["What is the name of the alpha dinosaur variant of the T-Rex?", "Alpha T-Rex"],
      ["What resource is used to craft most metal tools?", "Metal ingot"],
      ["What flying creature is large enough to carry a platform saddle?", "Quetzal"],
      ["What stat increases when you feed narcoberries to a creature?", "Torpor"],
      ["What aquatic creature is one of the largest in the game?", "Tusoteuthis"],
      ["What is the name of the small monkey-like creature you can tame?", "Mesopithecus"],
      ["What in-game material is needed to craft a saddle?", "Hide and fiber"],
      ["What is the name of the desert-themed map?", "Scorched Earth"],
      ["What is the name of the underwater/cave-themed expansion?", "Aberration"],
      ["What is the name of the giant scorpion creature?", "Pulmonoscorpius"],
      ["What is the name of the rideable creature unique to Aberration with glider abilities?", "Rock Drake"],
      ["What is the name of the giant snake creature found on Scorched Earth?", "Titanoboa"],
      ["What is the name of the boss arena on The Island for the Spider boss?", "Broodmother Lysrix"],
      ["Which fire-themed mythical creature is found on Scorched Earth?", "Phoenix"],
      ["Which armored mammal-like creature is best for collecting stone passively?", "Doedicurus"],
      ["What is the largest land carnivore tameable on The Island?", "Giganotosaurus"],
      ["What is the name of the small flying creature used for early-game flying?", "Pteranodon"],
      ["What creature in Aberration glows and can be used as a portable light?", "Bulbdog"],
      ["What deep zone on Aberration is filled with radiation?", "The Radiation Zone"],
      ["Which large theropod is the best source of prime meat?", "Tyrannosaurus Rex"],
      ["What is the name of the iconic 'big cat' creature in ARK?", "Sabertooth"],
      ["Which creature is a giant beaver capable of building dams?", "Castoroides"],
      ["What is the name of the large rideable bird flightless on The Island that can be used as a sprinter?", "Terror Bird"],
      ["What's the name of the creature you can ride to gather berries efficiently?", "Trike"],
    ]),
    600: qa([
      ["What year was ARK: Survival Evolved fully released (1.0)?", "2017"],
      ["What was the original early access release year?", "2015"],
      ["What is the name of the final boss on Genesis Part 2?", "Rockwell"],
      ["What is the name of the AI companion in Genesis Part 1?", "HLN-A"],
      ["What is the maximum wild dinosaur level on default settings?", "150"],
      ["What is the name of the Tek-tier energy resource from boss arenas?", "Element"],
      ["What is the name of the largest creature in the game, capable of carrying a mobile base?", "Titanosaur"],
      ["What is the name of the season-pass storyline expansion released in 2019?", "Genesis Part 1"],
      ["What is the name of the futuristic biome map?", "Genesis"],
      ["Which expansion features procedurally generated missions?", "Genesis Part 1"],
      ["What is the name of ARK 2's protagonist actor?", "Vin Diesel"],
      ["Who is Vin Diesel's character in ARK 2?", "Santiago"],
      ["What is the name of the developer behind ARK 2?", "Studio Wildcard"],
      ["What is the name of the engine ARK 2 is being built on?", "Unreal Engine 5"],
      ["What does a Cryopod do to a tamed creature?", "Puts it into stasis"],
      ["What is the highest tier of structure in ARK?", "Tek tier"],
      ["What is the name of the boss-fight item that the Overseer drops on The Island?", "Element"],
      ["What is the name of the strongest wyvern on Ragnarok?", "Ice Wyvern"],
      ["Which colored Wyvern shoots lightning?", "Lightning Wyvern"],
      ["Which colored Wyvern shoots fire?", "Fire Wyvern"],
      ["Which colored Wyvern shoots poison?", "Poison Wyvern"],
      ["What is the name of the boss on Aberration?", "Rockwell"],
      ["What is the name of the boss on Extinction?", "Forest Titan, Desert Titan, Ice Titan, King Titan"],
      ["What is the name of the boss on Scorched Earth?", "Manticore"],
      ["What is the name of the resource gathered from poop?", "Fertilizer"],
      ["What item is required to craft the Cryopod itself?", "Tek-tier components"],
      ["What item is placed on a redwood tree to harvest sap?", "Tree Sap Tap"],
      ["Which crab-like creature in Aberration produces organic polymer?", "Karkinos"],
      ["What is the name of the unique boss added on the Valguero map?", "The Forsaken Oasis"],
      ["What is the maximum imprint percentage on a perfectly raised baby?", "100%"],
    ]),
  },

  minecraft: {
    label: "Minecraft",
    icon: "\u{1F9F1}",
    color: "#84CC16",
    200: qa([
      ["What is the main character of Minecraft commonly called?", "Steve"],
      ["What hostile mob explodes when it gets close to you?", "Creeper"],
      ["What tool do you need to mine stone?", "Pickaxe"],
      ["What is the name of the alternate dimension full of fire and lava?", "The Nether"],
      ["What block do you mine to get diamonds?", "Diamond ore"],
      ["What animal gives you wool when sheared?", "Sheep"],
      ["How many sticks are required to craft a sword in Minecraft?", "1"],
      ["What happens when night falls in survival mode?", "Hostile mobs spawn"],
      ["What company developed Minecraft originally?", "Mojang"],
      ["What boss do you find in the End dimension?", "Ender Dragon"],
      ["Who created Minecraft?", "Markus 'Notch' Persson"],
      ["What year was Minecraft officially released (1.0)?", "2011"],
      ["What animal moos in Minecraft?", "Cow"],
      ["What animal oinks in Minecraft?", "Pig"],
      ["What hostile mob shoots arrows at you?", "Skeleton"],
      ["What food can you make from wheat?", "Bread"],
      ["What tool do you use to break dirt fastest?", "Shovel"],
      ["What tool do you use to chop wood fastest?", "Axe"],
      ["What item lights up dark areas to prevent monster spawns?", "Torch"],
      ["What sound does a creeper make right before exploding?", "A hissing/fuse sound"],
      ["What mob says 'hmmmm' and trades emeralds with you?", "Villager"],
      ["What block is used to make a crafting table?", "Wood (planks)"],
      ["What does the player do to defeat the Ender Dragon's regeneration?", "Destroy the End crystals"],
      ["What dimension is the home of Endermen?", "The End"],
      ["What block is used to build a Nether portal frame?", "Obsidian"],
      ["What item lights a Nether portal?", "Flint and steel"],
      ["What food do you get from killing a chicken?", "Chicken (raw)"],
    ]),
    400: qa([
      ["Which company bought Mojang in 2014?", "Microsoft"],
      ["How much did Microsoft pay for Mojang?", "$2.5 billion"],
      ["What item do you throw to find a stronghold?", "Eye of Ender"],
      ["What mob drops string when killed?", "Spider"],
      ["What is the name of the rare ore used to craft Netherite?", "Ancient Debris"],
      ["What is the name of the boss found in the Nether (added in 1.4)?", "Wither"],
      ["How many Wither Skeleton skulls are needed to build a Wither?", "3"],
      ["What is the name of the rare ore in the Overworld besides diamond?", "Emerald"],
      ["What is the maximum enchantment level on most Minecraft items at a table?", "30"],
      ["What is the name of the 1.13 update?", "Update Aquatic"],
      ["What is the name of the 1.16 update?", "Nether Update"],
      ["What is the name of the 1.17 update?", "Caves & Cliffs"],
      ["What is the name of the structure where you can find the End portal?", "Stronghold"],
      ["How many pieces of Netherite do you need to upgrade a full set of diamond armor and tools?", "9"],
      ["What is the name of the snowy biome friendly mob with horns added in 1.17?", "Goat"],
      ["What is the name of the underground city structure added in 1.19?", "Ancient City"],
      ["What is the name of the boss-like mob found in Ancient Cities?", "Warden"],
      ["What was the original working name of Minecraft during development?", "Cave Game"],
      ["What is the name of the floating black hostile mob that teleports?", "Enderman"],
      ["What block is used to brew potions?", "Brewing stand"],
      ["What item is required to make a brewing stand?", "Blaze rod"],
      ["What dimension contains Blazes?", "The Nether"],
      ["What is the name of the iron-block-shaped construct you can build to fight mobs?", "Iron golem"],
      ["What blocks do you need to build an iron golem?", "4 iron blocks and a carved pumpkin"],
      ["What is the name of the snow construct you can build?", "Snow golem"],
      ["What food gives the highest saturation level in vanilla Minecraft?", "Golden carrot"],
      ["Which item must be paired with fireworks to fly in Survival mode?", "Elytra"],
      ["What item allows you to glide in Survival mode?", "Elytra"],
    ]),
    600: qa([
      ["What is the name of the 1.18 update?", "Caves & Cliffs Part II"],
      ["What is the name of the 1.19 update?", "The Wild Update"],
      ["What is the name of the 1.20 update?", "Trails & Tales"],
      ["What is the name of the 1.21 update?", "Tricky Trials"],
      ["What is the maximum stack size for most items in Minecraft?", "64"],
      ["What is the maximum world height as of 1.18?", "320 blocks above bedrock"],
      ["What is the deepest Y level of the Overworld as of 1.18?", "-64"],
      ["What is the rarest natural diamond ore Y level for highest spawn?", "Y=-59"],
      ["What is the name of the new wood type added in 1.20?", "Cherry"],
      ["What is the name of the wood type added in 1.16?", "Crimson and Warped"],
      ["What item does a creeper drop when killed by a skeleton's arrow?", "A music disc"],
      ["What is the name of the music disc found only in Ancient Cities?", "Disc 5"],
      ["What is the name of the friendly cetacean mob in oceans?", "Dolphin"],
      ["Which mob can be tamed by feeding it bones?", "Wolf"],
      ["Which mob can be tamed by feeding it raw cod or salmon?", "Cat"],
      ["What is the name of the mob added in 1.19 from a vote?", "Allay"],
      ["What was the runner-up to the Allay in the mob vote?", "Glare"],
      ["What item dropped by goats in Caves & Cliffs lets you summon noises?", "Goat horn"],
      ["What is the name of the new structure added in 1.21 with trial spawners?", "Trial Chambers"],
      ["What item drops from defeating the Ender Dragon?", "Dragon egg"],
      ["How many obsidian End Crystals heal the Ender Dragon during its boss fight?", "10"],
      ["What is the name of the temporary buff effect from a Conduit?", "Conduit Power"],
      ["What is the name of the dolphin-given buff?", "Dolphin's Grace"],
      ["What block do you use to summon the Wither?", "Soul sand"],
      ["What is the maximum number of bookshelves needed for the highest enchantment table tier?", "15"],
      ["Who is the current Minecraft game director at Mojang?", "Agnes Larsson"],
      ["What is the name of the Minecraft education-focused edition?", "Minecraft: Education Edition"],
      ["What is the name of the Minecraft spinoff game by Mojang in 2020?", "Minecraft Dungeons"],
      ["What is the name of the Minecraft spinoff strategy game released in 2024?", "Minecraft Legends"],
    ]),
  },

  // ===================== WHO AM I =====================
  who_historic_figure: {
    label: "Which Historic Figure Am I?",
    icon: "\u{1F4DC}",
    color: "#A16207",
    isWhoAmI: true,
    200: who([
      ["I led India to independence through nonviolent resistance.", "Mahatma Gandhi", "Mahatma_Gandhi"],
      ["I was a Roman dictator stabbed on the Ides of March.", "Julius Caesar", "Julius_Caesar"],
      ["I painted the Mona Lisa.", "Leonardo da Vinci", "Leonardo_da_Vinci"],
      ["I formulated the theory of relativity and the equation E=mc².", "Albert Einstein", "Albert_Einstein"],
      ["I was the first U.S. President.", "George Washington", "George_Washington"],
      ["I led the Allied forces in WWII as British Prime Minister.", "Winston Churchill", "Winston_Churchill"],
      ["I was a French general who became Emperor and lost at Waterloo.", "Napoleon Bonaparte", "Napoleon"],
      ["I gave the 'I Have a Dream' speech in 1963.", "Martin Luther King Jr.", "Martin_Luther_King_Jr."],
      ["I was the queen of England during the defeat of the Spanish Armada in 1588.", "Elizabeth I", "Elizabeth_I"],
      ["I was the long-reigning queen of the British Empire in the 19th century.", "Queen Victoria", "Queen_Victoria"],
      ["I sailed across the Atlantic in 1492.", "Christopher Columbus", "Christopher_Columbus"],
      ["I was the 16th U.S. President and ended slavery.", "Abraham Lincoln", "Abraham_Lincoln"],
      ["I was an inventor known for the light bulb and phonograph.", "Thomas Edison", "Thomas_Edison"],
      ["I was a German-born theoretical physicist with wild white hair.", "Albert Einstein", "Albert_Einstein"],
      ["I was a Greek philosopher and student of Plato.", "Aristotle", "Aristotle"],
      ["I was an Italian astronomer who supported heliocentrism.", "Galileo Galilei", "Galileo_Galilei"],
      ["I was the founder of Facebook.", "Mark Zuckerberg", "Mark_Zuckerberg"],
      ["I was the third U.S. President and author of the Declaration of Independence.", "Thomas Jefferson", "Thomas_Jefferson"],
      ["I was a Spanish painter known for melting clocks.", "Salvador Dalí", "Salvador_Dal%C3%AD"],
      ["I was a Mexican painter known for self-portraits and unibrow.", "Frida Kahlo", "Frida_Kahlo"],
      ["I founded Microsoft with Paul Allen.", "Bill Gates", "Bill_Gates"],
      ["I was a German-born physicist who developed quantum theory.", "Max Planck", "Max_Planck"],
      ["I was a co-founder of Apple with Steve Wozniak.", "Steve Jobs", "Steve_Jobs"],
      ["I was a Tibetan spiritual leader awarded the Nobel Peace Prize in 1989.", "Dalai Lama", "14th_Dalai_Lama"],
      ["I was an English playwright who wrote Romeo and Juliet.", "William Shakespeare", "William_Shakespeare"],
      ["I was a Greek philosopher who drank hemlock.", "Socrates", "Socrates"],
      ["I was a Dutch painter who cut off part of my ear.", "Vincent van Gogh", "Vincent_van_Gogh"],
      ["I was the founder of modern psychoanalysis.", "Sigmund Freud", "Sigmund_Freud"],
      ["I was a Jewish girl who wrote a famous diary while hiding from Nazis.", "Anne Frank", "Anne_Frank"],
      ["I was a deaf and blind American author and activist.", "Helen Keller", "Helen_Keller"],
      ["I was the first woman to fly solo across the Atlantic.", "Amelia Earhart", "Amelia_Earhart"],
      ["I refused to give up my seat on a bus and sparked a civil rights movement.", "Rosa Parks", "Rosa_Parks"],
      ["I was a German philosopher and co-author of 'The Communist Manifesto.'", "Karl Marx", "Karl_Marx"],
      ["I was the Mongol warrior-emperor known as the conqueror of Asia.", "Kublai Khan", "Kublai_Khan"],
    ]),
    400: who([
      ["I was a Macedonian king who built an empire stretching to India.", "Alexander the Great", "Alexander_the_Great"],
      ["I discovered penicillin.", "Alexander Fleming", "Alexander_Fleming"],
      ["I was the last Tsar of Russia.", "Nicholas II", "Nicholas_II_of_Russia"],
      ["I led the Soviet Union during WWII.", "Joseph Stalin", "Joseph_Stalin"],
      ["I was a Polish-French scientist who won two Nobel Prizes for radioactivity work.", "Marie Curie", "Marie_Curie"],
      ["I formulated the laws of motion and universal gravitation.", "Isaac Newton", "Isaac_Newton"],
      ["I was the founder of the Mongol Empire.", "Genghis Khan", "Genghis_Khan"],
      ["I led the French Revolution as a Jacobin and was executed by guillotine.", "Maximilien Robespierre", "Maximilien_Robespierre"],
      ["I was a famous Egyptian queen who allied with Caesar and Mark Antony.", "Cleopatra", "Cleopatra"],
      ["I was the founder of Buddhism.", "Siddhartha Gautama", "Gautama_Buddha"],
      ["I was the Chinese revolutionary who founded the People's Republic in 1949.", "Mao Zedong", "Mao_Zedong"],
      ["I was an English physicist whose work on cosmology was renowned despite ALS.", "Stephen Hawking", "Stephen_Hawking"],
      ["I was an American jazz trumpeter known as Satchmo.", "Louis Armstrong", "Louis_Armstrong"],
      ["I was a Russian chemist who created the periodic table.", "Dmitri Mendeleev", "Dmitri_Mendeleev"],
      ["I was an Indian leader and one of the founders of the Indian National Congress.", "Jawaharlal Nehru", "Jawaharlal_Nehru"],
      ["I was a Roman emperor known as the Stoic philosopher who wrote 'Meditations.'", "Marcus Aurelius", "Marcus_Aurelius"],
      ["I was an Austrian-born American conductor and composer of musicals.", "Leonard Bernstein", "Leonard_Bernstein"],
      ["I was an English nurse who founded modern nursing during the Crimean War.", "Florence Nightingale", "Florence_Nightingale"],
      ["I was the U.S. President assassinated in Dallas in 1963.", "John F. Kennedy", "John_F._Kennedy"],
      ["I was a French scientist who proved the germ theory of disease.", "Louis Pasteur", "Louis_Pasteur"],
      ["I was the Soviet leader who introduced 'glasnost' and 'perestroika.'", "Mikhail Gorbachev", "Mikhail_Gorbachev"],
      ["I was a U.S. President during the Civil War.", "Abraham Lincoln", "Abraham_Lincoln"],
      ["I was a German-born physicist who developed the atomic bomb's design as part of the Manhattan Project.", "J. Robert Oppenheimer", "J._Robert_Oppenheimer"],
      ["I was a Romanian-born Israeli writer and Holocaust survivor who wrote 'Night.'", "Elie Wiesel", "Elie_Wiesel"],
      ["I was the Mughal emperor who built the Taj Mahal.", "Shah Jahan", "Shah_Jahan"],
      ["I was an English naturalist who proposed the theory of evolution by natural selection.", "Charles Darwin", "Charles_Darwin"],
      ["I was a French painter and sculptor, founder of cubism with Braque.", "Pablo Picasso", "Pablo_Picasso"],
      ["I was an Italian astronomer and engineer who improved the telescope.", "Galileo Galilei", "Galileo_Galilei"],
      ["I was the founder of Standard Oil and one of the wealthiest Americans of all time.", "John D. Rockefeller", "John_D._Rockefeller"],
      ["I was the first female British Prime Minister.", "Margaret Thatcher", "Margaret_Thatcher"],
      ["I was an African American civil rights activist and Muslim minister.", "Malcolm X", "Malcolm_X"],
      ["I was an Argentine revolutionary who fought alongside Fidel Castro.", "Che Guevara", "Che_Guevara"],
      ["I was an American boxer known as 'The Greatest.'", "Muhammad Ali", "Muhammad_Ali"],
      ["I was a Pakistani activist who survived being shot by the Taliban and won the Nobel Peace Prize.", "Malala Yousafzai", "Malala_Yousafzai"],
    ]),
    600: who([
      ["I was a Carthaginian general who crossed the Alps with elephants.", "Hannibal Barca", "Hannibal"],
      ["I was the Persian king who invaded Greece and was repelled at Salamis.", "Xerxes I", "Xerxes_I"],
      ["I was a Florentine political philosopher who wrote 'The Prince.'", "Niccolò Machiavelli", "Niccol%C3%B2_Machiavelli"],
      ["I was a Spanish conquistador who toppled the Aztec Empire.", "Hernán Cortés", "Hern%C3%A1n_Cort%C3%A9s"],
      ["I was a German monk whose 95 Theses sparked the Reformation.", "Martin Luther", "Martin_Luther"],
      ["I was an English physicist and chemist who pioneered electromagnetism.", "Michael Faraday", "Michael_Faraday"],
      ["I was a Soviet cosmonaut, first human in space.", "Yuri Gagarin", "Yuri_Gagarin"],
      ["I was a Polish astronomer who placed the Sun at the center of the universe.", "Nicolaus Copernicus", "Nicolaus_Copernicus"],
      ["I was an Indian emperor who built the Taj Mahal as a tomb for my wife.", "Shah Jahan", "Shah_Jahan"],
      ["I was a Roman general turned emperor, the founder of the Empire.", "Augustus", "Augustus"],
      ["I was an Italian explorer whose name appears on the American continents.", "Amerigo Vespucci", "Amerigo_Vespucci"],
      ["I was a Russian author of 'War and Peace.'", "Leo Tolstoy", "Leo_Tolstoy"],
      ["I was a French chemist and biologist who developed pasteurization.", "Louis Pasteur", "Louis_Pasteur"],
      ["I was a Hungarian-American physicist known as the 'father of the hydrogen bomb.'", "Edward Teller", "Edward_Teller"],
      ["I was a Serbian-American inventor and pioneer of alternating current.", "Nikola Tesla", "Nikola_Tesla"],
      ["I was an English mathematician who broke Nazi codes at Bletchley Park.", "Alan Turing", "Alan_Turing"],
      ["I was a Spanish painter known for 'Guernica' and surreal cubist work.", "Pablo Picasso", "Pablo_Picasso"],
      ["I was a Russian author of 'Crime and Punishment.'", "Fyodor Dostoevsky", "Fyodor_Dostoevsky"],
      ["I was a Bohemian-born Austrian composer of 'Symphony No. 9.'", "Gustav Mahler", "Gustav_Mahler"],
      ["I was a French author of 'Les Misérables.'", "Victor Hugo", "Victor_Hugo"],
      ["I was a Russian revolutionary who led the Bolsheviks to power in 1917.", "Vladimir Lenin", "Vladimir_Lenin"],
      ["I was the founder of psychoanalytic theory in Vienna.", "Sigmund Freud", "Sigmund_Freud"],
      ["I was an English author of 'A Christmas Carol.'", "Charles Dickens", "Charles_Dickens"],
      ["I was a German composer who wrote nine symphonies despite being deaf.", "Ludwig van Beethoven", "Ludwig_van_Beethoven"],
      ["I was an Austrian composer who wrote 'The Magic Flute.'", "Wolfgang Amadeus Mozart", "Wolfgang_Amadeus_Mozart"],
      ["I was the Macedonian-born Catholic nun who served in Calcutta.", "Mother Teresa", "Mother_Teresa"],
      ["I was the South African leader who became president after years in prison.", "Nelson Mandela", "Nelson_Mandela"],
      ["I was the Polish-born scientist who discovered radium.", "Marie Curie", "Marie_Curie"],
      ["I was a Roman general who said 'Veni, vidi, vici.'", "Julius Caesar", "Julius_Caesar"],
      ["I was an English author of 'Pride and Prejudice.'", "Jane Austen", "Jane_Austen"],
      ["I was the Ottoman Sultan who besieged Vienna in 1529.", "Suleiman the Magnificent", "Suleiman_the_Magnificent"],
      ["I was the Russian empress nicknamed 'the Great' who ruled in the 18th century.", "Catherine the Great", "Catherine_the_Great"],
      ["I was the Prussian king famous for militarizing and modernizing the state.", "Frederick the Great", "Frederick_the_Great"],
    ]),
  },

  who_animal: {
    label: "Which Animal Am I?",
    icon: "\u{1F43E}",
    color: "#65A30D",
    isWhoAmI: true,
    200: who([
      ["I am the king of the jungle and live in prides.", "Lion", "Lion"],
      ["I am the largest land animal on Earth.", "African elephant", "African_bush_elephant"],
      ["I have black and white stripes and live in Africa.", "Zebra", "Zebra"],
      ["I am the tallest animal on Earth.", "Giraffe", "Giraffe"],
      ["I am the largest mammal in the ocean.", "Blue whale", "Blue_whale"],
      ["I have a long trunk and large ears, and I live in Asia.", "Asian elephant", "Asian_elephant"],
      ["I jump using powerful hind legs and carry my young in a pouch.", "Kangaroo", "Kangaroo"],
      ["I have a black-and-white face and eat bamboo in China.", "Giant panda", "Giant_panda"],
      ["I am the fastest land animal.", "Cheetah", "Cheetah"],
      ["I am a large flightless bird from Africa, the heaviest of all birds.", "Ostrich", "Common_ostrich"],
      ["I am known for changing colors and having a long tongue.", "Chameleon", "Chameleon"],
      ["I live in the Arctic and have white fur.", "Polar bear", "Polar_bear"],
      ["I am known for hopping and saying 'ribbit'.", "Frog", "Frog"],
      ["I am a slow-moving reptile in trees in Asia, often green.", "Green tree python", "Green_tree_python"],
      ["I am known as 'man's best friend.'", "Dog", "Dog"],
      ["I purr and chase mice.", "Cat", "Cat"],
      ["I bray and am similar to a horse but smaller.", "Donkey", "Donkey"],
      ["I am pink and love mud baths on a farm.", "Pig", "Pig"],
      ["I lay eggs and cluck on a farm.", "Chicken", "Chicken"],
      ["I am the fastest swimmer in the ocean.", "Sailfish", "Sailfish"],
      ["I am a marine mammal known for clapping flippers and balancing balls.", "Sea lion", "Sea_lion"],
      ["I have a hard shell and walk slowly on land.", "Tortoise", "Tortoise"],
      ["I am tiny, fly, and produce honey.", "Honey bee", "Western_honey_bee"],
      ["I am a large bird of prey, the national symbol of the United States.", "Bald eagle", "Bald_eagle"],
      ["I am a black-and-white aquatic mammal nicknamed the 'killer whale.'", "Orca", "Orca"],
      ["I am a small mammal who carries my young on my back, common in Australia.", "Koala", "Koala"],
      ["I am known for my long ears and love carrots.", "Rabbit", "Rabbit"],
      ["I howl at the moon and live in packs.", "Wolf", "Wolf"],
      ["I am a waterfowl known for my 'quack' sound.", "Duck", "Duck"],
      ["I produce milk on farms and go 'moo.'", "Cow", "Cattle"],
      ["I am a woolly farm animal and often counted to fall asleep.", "Sheep", "Sheep"],
      ["I am a nocturnal bird famous for saying 'hoo.'", "Owl", "Owl"],
      ["I am a graceful white waterbird symbolizing love.", "Swan", "Swan"],
      ["I am a flightless bird that lives on icy continents.", "Penguin", "Penguin"],
    ]),
    400: who([
      ["I am the largest member of the cat family.", "Tiger", "Tiger"],
      ["I am a great ape from the rainforests of Borneo and Sumatra.", "Orangutan", "Orangutan"],
      ["I am the largest reptile alive, found in saltwater.", "Saltwater crocodile", "Saltwater_crocodile"],
      ["I am a large flightless bird from Australia, second tallest after the ostrich.", "Emu", "Emu"],
      ["I am a North American mammal known for building dams and lodges.", "Beaver", "North_American_beaver"],
      ["I am a primate famous for being humans' closest relative.", "Chimpanzee", "Chimpanzee"],
      ["I am a marsupial from Australia who eats only eucalyptus.", "Koala", "Koala"],
      ["I am the only mammal that can truly fly.", "Bat", "Bat"],
      ["I am a marine mammal known for echolocation and intelligence, often gray.", "Bottlenose dolphin", "Common_bottlenose_dolphin"],
      ["I am a large bear native to North America with a hump on my back.", "Grizzly bear", "Grizzly_bear"],
      ["I am a small fox famous for my huge ears, living in the Sahara.", "Fennec fox", "Fennec_fox"],
      ["I am a flightless bird from New Zealand and the national symbol there.", "Kiwi", "Kiwi_(bird)"],
      ["I am the heaviest snake in the world, found in South America.", "Green anaconda", "Green_anaconda"],
      ["I am a hoofed African mammal with two horns, the second largest land mammal.", "White rhinoceros", "White_rhinoceros"],
      ["I am a large ape from central Africa, larger than a chimpanzee.", "Gorilla", "Gorilla"],
      ["I am known for my striking pink color from eating shrimp.", "Flamingo", "Flamingo"],
      ["I am a marine reptile found in tropical seas with a hard shell.", "Sea turtle", "Sea_turtle"],
      ["I am a marine mammal with two long tusks living in Arctic waters.", "Walrus", "Walrus"],
      ["I am the second-largest cat in the Americas after the jaguar.", "Cougar", "Cougar"],
      ["I am a horned African antelope famous for huge spiral horns.", "Greater kudu", "Greater_kudu"],
      ["I am a small striped scavenger that 'laughs.'", "Spotted hyena", "Spotted_hyena"],
      ["I am known for diving deep and squirting ink.", "Octopus", "Octopus"],
      ["I am a large bird of prey often called the 'king of the sky.'", "Golden eagle", "Golden_eagle"],
      ["I am a slow-moving mammal that lives upside down in trees.", "Sloth", "Sloth"],
      ["I am the world's largest fish.", "Whale shark", "Whale_shark"],
      ["I am a venomous snake with a hood, famous in India.", "Indian cobra", "Indian_cobra"],
      ["I am a small Australian dog-like predator, famous for my bite force.", "Tasmanian devil", "Tasmanian_devil"],
      ["I am an African big cat known for hunting in coalitions of brothers.", "Cheetah", "Cheetah"],
      ["I am a tropical bird known for vivid plumage and mimicking speech.", "Parrot", "Parrot"],
      ["I am a giant lizard from Indonesia, the largest living lizard.", "Komodo dragon", "Komodo_dragon"],
      ["I scuttle sideways on beaches and pinch with my claws.", "Crab", "Crab"],
      ["I am a tiny ocean creature with a curled upright body.", "Seahorse", "Seahorse"],
      ["I am a clawed ocean crustacean often steamed red.", "Lobster", "Lobster"],
    ]),
    600: who([
      ["I am the only egg-laying mammal with a duck-like bill.", "Platypus", "Platypus"],
      ["I am a small Australian marsupial often called the 'happiest animal.'", "Quokka", "Quokka"],
      ["I am the largest rodent in the world.", "Capybara", "Capybara"],
      ["I am an Andean camelid prized for my soft wool.", "Vicuña", "Vicu%C3%B1a"],
      ["I am a flightless bird native to Antarctica, the largest penguin species.", "Emperor penguin", "Emperor_penguin"],
      ["I am a deep-sea cephalopod with the largest eyes of any known animal.", "Giant squid", "Giant_squid"],
      ["I am a large flightless bird from South America, similar to an ostrich.", "Greater rhea", "Greater_rhea"],
      ["I am an arboreal marsupial of Australia known for gliding between trees.", "Sugar glider", "Sugar_glider"],
      ["I am a hoofed mammal of the Arctic with broad antlers, where both sexes grow them.", "Reindeer", "Reindeer"],
      ["I am the world's largest amphibian, found in China.", "Chinese giant salamander", "Chinese_giant_salamander"],
      ["I am a small carnivore from Madagascar, the island's largest predator.", "Fossa", "Fossa_(animal)"],
      ["I am the only venomous lizard species native to the United States.", "Gila monster", "Gila_monster"],
      ["I am a small primate from Madagascar with a long striped tail.", "Ring-tailed lemur", "Ring-tailed_lemur"],
      ["I am a tiny crustacean famous for my pink color and tasty meat.", "Shrimp", "Shrimp"],
      ["I am a marine mammal often called the 'sea cow.'", "Manatee", "Manatee"],
      ["I am a small spiny mammal of Europe and Africa that curls into a ball.", "Hedgehog", "Hedgehog"],
      ["I am a large freshwater fish nicknamed for my paddle-like snout.", "American paddlefish", "American_paddlefish"],
      ["I am an arctic cetacean famous for the long single tusk of the male.", "Narwhal", "Narwhal"],
      ["I am a large dog-like canine native to the Ethiopian highlands.", "Ethiopian wolf", "Ethiopian_wolf"],
      ["I am a small African mammal famous for standing upright on guard.", "Meerkat", "Meerkat"],
      ["I am a large ape from Sumatra, critically endangered.", "Sumatran orangutan", "Sumatran_orangutan"],
      ["I am a deep-sea fish known for my bioluminescent lure.", "Anglerfish", "Anglerfish"],
      ["I am a large flightless bird from Australia covered in shaggy feathers.", "Cassowary", "Cassowary"],
      ["I am a small antelope known as the smallest in the world, found in Africa.", "Royal antelope", "Royal_antelope"],
      ["I am a striped wild horse-like equid of Central Asia.", "Przewalski's horse", "Przewalski%27s_horse"],
      ["I am a fish that can survive on land for short periods using my pectoral fins.", "Mudskipper", "Mudskipper"],
      ["I am the largest crab in the world by leg span, found in Japan.", "Japanese spider crab", "Japanese_spider_crab"],
      ["I am a small carnivorous mammal of South America with a banded tail and snout.", "Coati", "Coati"],
      ["I am a wild ox-like mammal of Southeast Asia and the world's largest bovine.", "Gaur", "Gaur"],
      ["I am a small Antarctic crustacean that forms the basis of the food chain.", "Krill", "Krill"],
      ["I am a scaly anteater, the most trafficked mammal in the world.", "Pangolin", "Pangolin"],
      ["I am a striped African relative of the giraffe with zebra-like legs.", "Okapi", "Okapi"],
      ["I am a pig-like mammal of Central America with a flexible snout.", "Tapir", "Tapir"],
    ]),
  },

  // ===================== CHARADES =====================
  charades_scenarios: {
    label: "Charades: Scenarios",
    icon: "\u{1F3AC}",
    color: "#DB2777",
    isCharades: true,
    200: charades([
      "Brushing your teeth in the morning",
      "Walking a dog on a leash",
      "Eating spaghetti",
      "Tying your shoelaces",
      "Drinking a hot cup of coffee",
      "Riding a bicycle",
      "Swimming in a pool",
      "Sleeping and snoring",
      "Sneezing loudly",
      "Painting a wall",
      "Reading a newspaper",
      "Taking a selfie",
      "Eating an ice cream cone",
      "Putting on a coat",
      "Cooking a pancake",
      "Washing your hands",
      "Combing your hair",
      "Watching TV on the couch",
      "Vacuuming the floor",
      "Tying a tie",
      "Driving a car",
      "Texting on a phone",
      "Shoveling snow",
      "Carrying heavy grocery bags",
      "Putting on makeup",
      "Eating popcorn at the movies",
      "Brushing a pet cat",
      "Blowing out birthday candles",
      "Opening a present",
      "Yawning and stretching",
      "Tying a bow",
      "Making a sandwich",
      "Pouring a glass of water",
      "Singing into a hairbrush",
      "Doing jumping jacks",
      "Swatting a fly",
      "Eating a slice of pizza",
      "Stirring a pot of soup",
    ]),
    400: charades([
      "Trying to start a stubborn lawn mower",
      "Realizing you forgot your wallet at a restaurant",
      "Sneaking past a sleeping baby",
      "Surfing a giant wave and wiping out",
      "Reacting to spicy food at a restaurant",
      "Catching a fly with chopsticks",
      "Searching for your keys in a dark room",
      "Trying to open a stuck pickle jar",
      "Walking on hot sand at the beach",
      "Reading a really sad book and crying",
      "Stuck in an elevator with a stranger",
      "Getting caught in a sudden rainstorm",
      "Putting together a complicated bookshelf",
      "Realizing you sat in chewing gum",
      "Trying not to laugh at a funeral",
      "Bargaining at a flea market",
      "Walking into a glass door",
      "Trying to take a group selfie",
      "Catching a bouquet at a wedding",
      "Sneaking food during a diet",
      "Trying to swat a mosquito at night",
      "Carrying a wedding cake across a room",
      "Receiving a surprise birthday party",
      "Trying to whisper a secret in a loud bar",
      "Tasting something that has gone bad",
      "Hailing a taxi in the rain",
      "Trying to open a child-proof bottle",
      "Realizing your zipper is down in public",
      "Burning yourself on hot pizza cheese",
      "Stepping on a Lego brick barefoot",
      "Trying to parallel park",
      "Realizing you replied-all by accident",
      "Forgetting someone's name during a hello",
      "Watching a horror movie alone",
      "Cleaning up a spilled drink quickly",
      "Trying to find your seat in a dark theater",
      "Squeezing into a crowded subway",
      "Spilling coffee on a white shirt",
      "Sneezing into your elbow during a meeting",
      "Realizing you missed the bus stop",
      "Mistaking a mannequin for a real person",
      "Tripping while going up stairs",
      "Pretending to enjoy a bad gift",
      "Discovering your phone is at 1% battery",
    ]),
    600: charades([
      "Defusing a fake bomb under pressure",
      "Negotiating with a hostage taker",
      "Performing surgery as the lights flicker",
      "Tightrope walking between two skyscrapers",
      "Sneaking out of a museum after closing time",
      "Surviving a zombie attack in a supermarket",
      "Convincing a cat to take a bath",
      "Picking a lock while hearing footsteps approach",
      "Auditioning for a Broadway musical",
      "Conducting a symphony orchestra during an earthquake",
      "Proposing marriage and being rejected",
      "Catching a runaway bride",
      "Wrestling an alligator in a swamp",
      "Climbing Mount Everest in flip-flops",
      "Saving a kitten from a burning building",
      "Discovering a winning lottery ticket in your old jeans",
      "Being stuck in traffic running late to a job interview",
      "Sneaking past a guard dog in a junkyard",
      "Trying to teach grandma how to use TikTok",
      "Performing CPR on a mannequin in front of judges",
      "Riding a mechanical bull at a rodeo",
      "Being abducted by aliens and taken to their ship",
      "Defending yourself in court without a lawyer",
      "Getting trapped in a haunted house overnight",
      "Becoming a chef on a cooking competition",
      "Bungee jumping for the first time",
      "Discovering your double in a mirror world",
      "Trying to win a hot dog eating contest",
      "Riding a unicycle through a busy market",
      "Babysitting triplets who refuse to sleep",
      "Hosting a magic show that goes wrong",
      "Surviving a shipwreck on a deserted island",
      "Performing an exorcism on a possessed laptop",
      "Hijacking a hot air balloon by accident",
      "Stuck on a roller coaster mid-loop",
      "Sneaking into a five-star restaurant in pajamas",
      "Skydiving without a parachute opening",
      "Pretending to be a museum statue when guards walk by",
      "Wrestling a python in the jungle",
      "Conducting an interview with a celebrity who hates you",
      "Stealing the crown jewels from a museum vault",
      "Being chased by paparazzi through a hotel",
      "Calming down a panicked horse in a stable",
      "Trying to fix a broken time machine",
      "Taming a lion in a circus ring",
      "Riding a runaway shopping cart down a hill",
      "Getting your tie caught in an office shredder",
      "Solving a Rubik's cube while skydiving",
      "Conducting a séance that summons something real",
      "Trying to escape from a straightjacket underwater",
      "Sneaking through laser security beams",
      "Crashing a royal wedding in disguise",
      "Trying to hold in a sneeze during a chess tournament",
      "Performing the Heimlich maneuver on a stranger",
      "Convincing a vampire to become a vegan",
      "Pretending to be invisible at a party",
      "Surviving a bear attack while camping",
      "Operating a fighter jet for the first time",
      "Pretending to be a robot to fool a sensor",
      "Negotiating peace between two warring tribes",
      "Trying to tame a wild horse on a ranch",
      "Saving a sinking lifeboat",
      "Carrying glass sculptures through a windstorm",
      "Trying to convince a judge of your alien origin",
      "Whispering a confession in a confession booth",
      "Trying to sneak a cake past airport security",
      "Tightrope walking with an umbrella over a canyon",
      "Reciting Shakespeare to a herd of cows",
      "Being chosen as Santa at the last minute",
      "Cracking a safe in under sixty seconds",
      "Pretending to be a mannequin in a shop window",
      "Climbing through an air vent in an action movie",
      "Trying to land a plane after the pilot faints",
      "Riding a hoverboard for the first time",
      "Persuading a yeti to come down from the mountain",
      "Performing on a karaoke stage with stage fright",
      "Hosting a wedding ceremony with no script",
      "Being a contestant on a survival reality show",
      "Trying to escape an escape room using only mime",
      "Auditioning to be a stunt double",
      "Convincing a dragon to give back stolen gold",
      "Being a juror trying to decide a verdict",
      "Pretending to enjoy a horror movie while terrified",
      "Stealing back your own car from a tow lot",
      "Sneaking onto a moving train",
      "Riding a wild bull at a rodeo for prize money",
      "Trying to charm a snake out of a basket",
      "Conducting a magic potion experiment that explodes",
      "Sneaking through a haunted graveyard at midnight",
      "Becoming the world's worst hairdresser by accident",
      "Trying to keep a secret from a mind reader",
      "Doing a TED talk after losing your notes",
      "Climbing the side of a cliff with only ropes",
      "Trying to win a dance battle with two left feet",
      "Performing brain surgery in a moving ambulance",
      "Trying to reach the cookie jar on the highest shelf",
      "Defending the Earth from an alien invasion",
      "Trying to outsmart a polygraph test",
      "Being a referee in a heated soccer final",
      "Sneaking past a sleeping dragon to steal an egg",
    ]),
  },
};

export default NEW_CATEGORIES_BANK;
