const qa = (pairs) => pairs.map(([q, a]) => ({ q, a }));
const charades = (items, prompt = "Scan the QR and act it out") =>
  items.map((a) => ({ q: prompt, a }));

export const QUESTION_REFINEMENT_ADDITIONS = {
  geography: {
    200: qa([]),
  },
  science: {
    200: qa([
      ["Gas humans need to breathe?", "Oxygen"],
    ]),
    600: qa([
      ["What is quantum entanglement?", "A phenomenon where linked particles affect each other across distance"],
    ]),
  },
  history: {
    200: qa([
      ["Year the Apollo 11 Moon landing happened?", "1969"],
    ]),
  },
  spider_man: {
    200: qa([
      ["What high-tech suit does Peter wear in Infinity War?", "The Iron Spider suit"],
      ["What AI glasses does Tony leave Peter in Far From Home?", "E.D.I.T.H."],
      ["What is Peter Parker's aunt's first name?", "May"],
    ]),
    400: qa([
      ["What villains does Mysterio pretend are attacking Europe?", "The Elementals"],
    ]),
    600: qa([
      ["What landmark becomes the final battlefield in No Way Home?", "The Statue of Liberty"],
      ["What machine does Kingpin use beneath Brooklyn in Into the Spider-Verse?", "A super-collider"],
    ]),
  },
  the_flash: {
    200: qa([]),
    400: qa([
      ["What icy identity does Caitlin become?", "Killer Frost"],
    ]),
    600: qa([
      ["What artificial speed drug nearly kills speedsters?", "Velocity 9"],
      ["What event names Barry the Paragon of Love?", "Crisis on Infinite Earths"],
    ]),
  },
};

export const CHARADES_HARD_OVERRIDES = {
  charades_general: charades([
    "secret agent undercover",
    "mad scientist experiment",
    "pirate finds treasure",
    "astronaut loses gravity",
    "wizard misses spell",
    "ninja dodges lasers",
    "mime in a box",
    "alien uses chopsticks",
    "robot learns emotions",
    "zombie in office",
    "villain evil laugh",
    "superhero landing pose",
    "detective crime scene",
    "movie star red carpet",
    "game show winner",
    "king loses crown",
    "chef kitchen disaster",
    "haunted house tour",
    "cowboy quick draw",
    "archaeologist opens tomb",
    "news anchor panic",
    "auction bidding war",
    "cat burglar caught",
    "lifeguard shark warning",
    "gamer rage quit",
    "dance battle",
    "invisible wall",
    "time traveler arrives",
    "magician trick fails",
    "spy changes disguise",
    "surfer wiped out",
    "teacher loses chalk",
    "chef tastes soup",
    "secret door opens",
    "pilot hits turbulence",
    "vampire hates sunlight",
    "wizard drops wand",
    "alien steals snacks",
    "mermaid on land",
    "knight fights dragon",
    "doctor bad news",
    "golfer misses putt",
    "driver road rage",
    "lifeguard saves swimmer",
    "gamer finds loot",
    "astronaut drops flag",
    "detective loses badge",
    "chef drops pasta",
    "robot needs charging",
    "vampire misses coffin",
    "ninja loses sword",
    "ghost scares lifeguard",
    "cowboy hates horses",
    "wizard sneezes sparks",
    "doctor forgets patient",
    "alien eats pizza",
    "surfer sees shark",
    "teacher fails quiz",
    "king fears mouse",
    "spy loses earpiece",
    "pilot spills coffee",
    "thief hears sirens",
    "runner trips finish",
    "magician loses rabbit",
    "mermaid learns walking",
    "farmer chases chicken",
    "artist paints ceiling",
    "judge drops hammer",
    "tourist misses train",
    "archer misses target",
    "camper sees bear",
    "scientist freezes potion",
    "driver misses exit",
    "clown loses balloon",
    "boxer dodges punch",
    "office worker panics",
    "tour guide lost",
    "firefighter drops hose",
    "cashier hates coupons",
  ]),
  charades_movies: charades(
    [
      "Whiplash",
      "Parasite",
      "Arrival",
      "Inception",
      "Memento",
      "Prisoners",
      "Dune",
      "Get Out",
      "Nope",
      "Interstellar",
      "Ex Machina",
      "The Revenant",
      "Shutter Island",
      "Gone Girl",
      "Ford v Ferrari",
      "Dunkirk",
      "The Bear",
      "Succession",
      "Mindhunter",
      "Black Mirror",
      "House of the Dragon",
      "The White Lotus",
      "The Sopranos",
      "True Detective",
      "Peaky Blinders",
      "Better Call Saul",
      "Mad Max Fury Road",
      "Blade Runner 2049",
      "The Last of Us",
      "Everything Everywhere All at Once",
      "The Truman Show",
      "The Great Gatsby",
      "Catch Me If You Can",
      "No Country for Old Men",
      "Eternal Sunshine",
      "Night at the Museum",
      "How I Met Your Mother",
      "Only Murders in the Building",
      "The Devil Wears Prada",
      "Lock, Stock",
      "Benjamin Button",
      "A Series of Unfortunate Events",
      "The Green Mile",
      "Oppenheimer",
      "Casino Royale",
      "The Social Network",
      "Spotlight",
      "Her",
      "Birdman",
      "Zodiac",
      "Heat",
      "Collateral",
      "Sicario",
      "Drive",
      "Joker",
      "Inside Man",
      "The Fighter",
      "Little Women",
      "Logan",
      "District 9",
      "Baby Driver",
      "Gone Baby Gone",
      "The Holdovers",
      "Knives Out",
      "John Wick Chapter 4",
      "Mission Impossible Fallout",
      "Dead Poets Society",
      "A Few Good Men",
      "Skyfall",
      "The Town",
      "The Bourne Ultimatum",
      "The Imitation Game",
      "The Nice Guys",
      "Hacksaw Ridge",
      "Nightcrawler",
      "Severance",
      "Mr. Robot",
      "Lupin",
      "The Americans",
      "Beef",
      "Fargo",
      "The Prestige",
    ],
    "Act this movie or show",
  ),
};
