const qa = (pairs) => pairs.map(([q, a]) => ({ q, a }));
const who = (pairs) => pairs.map(([a, wiki, q = "Guess from the image"]) => ({ q, a, wiki }));
const charades = (items, prompt = "Scan the QR and act it out") =>
  items.map((a) => ({ q: prompt, a }));

const TRIVIA_TIER_PARITY_EXPANSIONS = {
  general: {
    400: qa([
      ["What is the Roman numeral for 500?", "D"],
      ["What is a nine-sided shape called?", "Nonagon"],
      ["What does ATM stand for?", "Automated Teller Machine"],
      ["What board game uses words on a 15x15 grid?", "Scrabble"],
      ["What chess piece can jump over other pieces?", "Knight"],
      ["What does CAPTCHA try to verify?", "That you are human"],
    ]),
    600: qa([
      ["What is the Roman numeral for 900?", "CM"],
      ["What is a 12-sided shape called?", "Dodecagon"],
      ["What is the study of maps called?", "Cartography"],
      ["What does RFID stand for?", "Radio-frequency identification"],
      ["What is the longest side of a right triangle called?", "Hypotenuse"],
      ["What does ASCII stand for?", "American Standard Code for Information Interchange"],
      ["What type of number has no positive divisors besides 1 and itself?", "Prime number"],
      ["What is a polygon with 10 sides called?", "Decagon"],
      ["What instrument measures atmospheric pressure?", "Barometer"],
      ["What branch of math studies chance?", "Probability"],
      ["What does PDF stand for?", "Portable Document Format"],
      ["What is a word made from the initials of a phrase called?", "Acronym"],
    ]),
  },
  geography: {
    400: qa([
      ["Capital of Norway?", "Oslo"],
      ["Capital of Croatia?", "Zagreb"],
    ]),
    600: qa([
      ["Capital of Bolivia's constitutional capital?", "Sucre"],
      ["Capital of Kyrgyzstan?", "Bishkek"],
      ["Capital of Latvia?", "Riga"],
      ["Capital of Estonia?", "Tallinn"],
      ["Capital of Iceland?", "Reykjavik"],
      ["Capital of Paraguay?", "Asuncion"],
      ["Capital of Laos?", "Vientiane"],
      ["Capital of Madagascar?", "Antananarivo"],
      ["Capital of Tanzania?", "Dodoma"],
      ["Capital of Montenegro?", "Podgorica"],
    ]),
  },
  science: {
    400: qa([
      ["What part of the atom has a positive charge?", "Proton"],
    ]),
    600: qa([
      ["What is the study of fossils called?", "Paleontology"],
      ["What force opposes motion between surfaces?", "Friction"],
      ["What blood cells help clotting?", "Platelets"],
      ["What part of the brain controls balance?", "Cerebellum"],
      ["What is the SI unit of power?", "Watt"],
      ["What gas do red blood cells carry away from the body?", "Carbon dioxide"],
      ["What organelle contains a cell's genetic material?", "Nucleus"],
      ["What branch of biology studies insects?", "Entomology"],
      ["What process turns liquid into gas?", "Evaporation"],
      ["What is the common name for sodium bicarbonate?", "Baking soda"],
    ]),
  },
  history: {
    400: qa([
      ["What year did the Titanic sink?", "1912"],
      ["Who was the first man in space?", "Yuri Gagarin"],
      ["What empire was ruled by Suleiman the Magnificent?", "Ottoman Empire"],
      ["What year did the French Revolution begin?", "1789"],
      ["Who was the first Tudor king of England?", "Henry VII"],
      ["Which war was fought between the North and South in the United States?", "American Civil War"],
    ]),
    600: qa([
      ["What treaty ended the Thirty Years' War in 1648?", "Peace of Westphalia"],
      ["Who led the Soviet Union after Lenin?", "Joseph Stalin"],
      ["What civilization used cuneiform writing?", "Sumerians"],
      ["Which city fell to the Ottomans in 1453?", "Constantinople"],
      ["Who was the British prime minister for most of World War II?", "Winston Churchill"],
      ["What year did the Battle of Hastings happen?", "1066"],
      ["Which Chinese dynasty built much of the present Great Wall?", "Ming dynasty"],
      ["Who was the queen of Egypt allied with Julius Caesar and Mark Antony?", "Cleopatra"],
      ["What rebellion was led by Spartacus?", "Third Servile War"],
      ["Who was the first emperor of Rome?", "Augustus"],
      ["What year did India gain independence?", "1947"],
      ["What ship carried the Pilgrims to North America in 1620?", "Mayflower"],
      ["Which empire controlled present-day Peru before the Spanish conquest?", "Inca Empire"],
      ["Who wrote the Ninety-five Theses?", "Martin Luther"],
      ["Which battle in 1815 ended Napoleon's rule for good?", "Waterloo"],
      ["Who was the last tsar of Russia?", "Nicholas II"],
      ["What was the capital of the Byzantine Empire?", "Constantinople"],
    ]),
  },
  sports: {
    600: qa([
      ["What is the maximum score with one dart in standard darts?", "60"],
      ["How many points is a drop goal in rugby union?", "3"],
      ["What race opens cycling's Grand Tours season calendar?", "Giro d'Italia"],
      ["What swimming stroke is also called freestyle in races?", "Front crawl"],
      ["Which country invented table tennis?", "England"],
      ["What is a turkey in bowling?", "Three strikes in a row"],
      ["How many players are on the field for one baseball team on defense?", "9"],
      ["Which football award is given to the world's best player annually?", "Ballon d'Or"],
      ["What color jersey does the Tour de France leader wear?", "Yellow"],
      ["How many rounds are in a professional championship boxing fight?", "12"],
    ]),
  },
  music: {
    400: qa([
      ["What clef is commonly used for lower-pitched instruments?", "Bass clef"],
      ["What does a crescendo mean?", "Getting louder"],
    ]),
    600: qa([
      ["What does opus mean in classical music cataloging?", "Work"],
      ["What key has no sharps and no flats?", "C major"],
      ["What does adagio indicate?", "Slow tempo"],
      ["What is a group of three notes played together called?", "Triad"],
      ["What does pianissimo mean?", "Very soft"],
      ["What female voice type is lower than soprano?", "Alto"],
      ["What symbol cancels a sharp or flat?", "Natural"],
      ["What does a fermata tell a musician to do?", "Hold the note"],
      ["What family does the trombone belong to?", "Brass"],
      ["What is the relative minor of C major?", "A minor"],
      ["What is a piece for one performer called?", "Solo"],
      ["What does allegro usually mean?", "Fast"],
      ["What is the line system written for music called?", "Staff"],
    ]),
  },
  movies: {
    400: qa([
      ["What is the shark in Jaws nicknamed behind the scenes?", "Bruce"],
    ]),
    600: qa([
      ["What is the name of the hotel in The Shining?", "Overlook Hotel"],
      ["Which film introduced the character Furiosa?", "Mad Max: Fury Road"],
      ["What is the ship called in The Life Aquatic with Steve Zissou?", "Belafonte"],
      ["What is the name of the hotel in John Wick?", "The Continental"],
      ["Who directed Reservoir Dogs?", "Quentin Tarantino"],
      ["What is the island park called in Jurassic Park?", "Isla Nublar"],
      ["What is the name of the rabbit in Donnie Darko?", "Frank"],
      ["What is the AI in Ex Machina called?", "Ava"],
      ["What is the company in Alien that owns the Nostromo?", "Weyland-Yutani"],
    ]),
  },
  country_facts: {
    400: qa([
      ["This country is famous for fjords and the city of Bergen", "Norway"],
      ["This country has capital Bratislava and borders Austria and Hungary", "Slovakia"],
      ["This country is known for Petra and has capital Amman", "Jordan"],
      ["This country is home to Mount Kilimanjaro and Zanzibar", "Tanzania"],
      ["This country has capital Montevideo and sits between Brazil and Argentina", "Uruguay"],
      ["This country is known for the Dead Sea and has capital Jerusalem", "Israel"],
    ]),
    600: qa([
      ["This country has capital Thimphu and is famous for Gross National Happiness", "Bhutan"],
      ["This country has capital Windhoek and is known for the Namib Desert", "Namibia"],
      ["This country has capital Tbilisi and sits between Europe and Asia", "Georgia"],
      ["This country has capital Paramaribo and lies on South America's Atlantic coast", "Suriname"],
      ["This country has capital Ulaanbaatar and is known for vast steppes", "Mongolia"],
      ["This country has capital Yerevan and is one of the world's oldest Christian nations", "Armenia"],
    ]),
  },
  movie_show_emoji: {
    400: qa([
      ["🧪👨‍🏫💊", "Breaking Bad"],
      ["🕷️👨‍🎓🗽", "Spider-Man"],
      ["👑🐉🗡️", "Game of Thrones"],
    ]),
    600: qa([
      ["🧥🧠🔪", "Dexter"],
      ["🧑‍🚀🌽🪐", "Interstellar"],
    ]),
  },
  country_emoji: {
    400: qa([
      ["🦘🏏🏖️", "Australia"],
    ]),
    600: qa([
      ["🧀⌚🏔️", "Switzerland"],
    ]),
  },
  general_emoji: {
    400: qa([
      ["🔍🕵️‍♂️🧩", "Detective"],
    ]),
  },
  friends: {
    400: qa([
      ["What is Rachel's little sister called?", "Jill"],
    ]),
    600: qa([
      ["What is Monica's first kitchen job on the show?", "Chef at Iridium"],
      ["What is the name of Joey's agent?", "Estelle"],
      ["What is Ross's second wife's first name?", "Emily"],
      ["What does Chandler get trapped in on Thanksgiving by Rachel's boss?", "A box"],
    ]),
  },
  the_office: {
    400: qa([
      ["What is Dwight's family surname?", "Schrute"],
      ["What is Meredith's son's name?", "Jake"],
      ["What is Oscar's surname?", "Martinez"],
    ]),
    600: qa([
      ["What is the name of Michael's screenplay hero?", "Michael Scarn"],
      ["What is Darryl's daughter called?", "Jada"],
      ["What is Andy's a cappella college group called?", "Here Comes Treble"],
      ["What is Kelly's surname?", "Kapoor"],
      ["What is the name of Jim and Pam's son?", "Philip"],
    ]),
  },
  breaking_bad: {
    600: qa([
      ["What song does Gale sing in the lab video?", "Major Tom"],
      ["What is Todd Alquist's uncle's first name?", "Jack"],
      ["What is the name of the nursing home where Hector lives?", "Casa Tranquila"],
    ]),
  },
  stranger_things: {
    400: qa([
      ["What is Hopper's adopted daughter's name?", "Eleven"],
      ["What board game do the boys often play?", "Dungeons & Dragons"],
      ["What is Steve's job at Starcourt Mall?", "Scoops Ahoy"],
      ["What is Jonathan Byers's hobby?", "Photography"],
      ["What is the doctor's nickname used by the children?", "Papa"],
    ]),
    600: qa([
      ["What is the pizza shop employee helping Argyle called?", "Eden"],
      ["What is Max's brother's name?", "Billy"],
      ["What song does Dustin sing with Suzie over the radio?", "The NeverEnding Story"],
      ["What is the Byers' dog called in season 1?", "Chester"],
      ["What is Robin's crush at Family Video called?", "Vickie"],
      ["What newspaper does Nancy first intern at?", "Hawkins Post"],
      ["What cheerleader is Vecna's first season 4 victim?", "Chrissy Cunningham"],
      ["What California town do the Byers move to?", "Lenora Hills"],
    ]),
  },
  prison_break: {
    400: qa([
      ["What is Michael Scofield's profession before prison?", "Structural engineer"],
      ["What object contains The Company's data in later seasons?", "Scylla"],
      ["What is T-Bag's first name?", "Theodore"],
      ["What is Mahone's first name?", "Alexander"],
      ["What is Michael's wife figure called?", "Sara"],
      ["What alias does T-Bag use while working in business?", "Cole Pfeiffer"],
      ["What is Lincoln's son's nickname?", "L.J."],
      ["What state is Fox River in?", "Illinois"],
      ["What president is tied to The Company in season 1?", "Caroline Reynolds"],
      ["What is Bellick's first name?", "Brad"],
      ["What is Veronica Donovan's profession?", "Lawyer"],
      ["What country is Sona prison in?", "Panama"],
      ["What is Michael's scarred enemy from Fox River called?", "T-Bag"],
      ["What city is Ogygia prison located near?", "Sana'a"],
      ["What alias does Michael use in season 5?", "Kaniel Outis"],
      ["What is Sucre's first name?", "Fernando"],
    ]),
    600: qa([
      ["What secret service agent turns on the team in season 4?", "Don Self"],
      ["What is Gretchen Morgan's real first name?", "Emily"],
      ["What is Michael's mother's name?", "Christina Rose Scofield"],
      ["What is the name of Lincoln's son?", "L.J."],
      ["What prison is season 5 centered on?", "Ogygia"],
      ["What is T-Bag's formal surname?", "Bagwell"],
      ["What is Sara's father's name?", "Frank"],
      ["What bird-themed book helps unlock Scylla?", "Bird book"],
      ["What is Paul Kellerman's agency background?", "Secret Service"],
      ["What is Michael's second escape prison after Fox River?", "Sona"],
      ["What is Whip's relationship to T-Bag?", "Son"],
    ]),
  },
  big_bang_theory: {
    400: qa([
      ["What is Amy's surname?", "Fowler"],
      ["What is Raj's surname?", "Koothrappali"],
      ["What is Howard's surname?", "Wolowitz"],
      ["What is Penny's terrible movie title?", "Serial Ape-ist"],
      ["What is Leonard's mother's first name?", "Beverly"],
      ["What is Sheldon's favorite superhero?", "The Flash"],
      ["What is Sheldon's twin sister called?", "Missy"],
      ["What is Stuart's comic store job?", "Owner"],
    ]),
    600: qa([
      ["What is Bert's field of science?", "Geology"],
      ["What is Sheldon's favorite number?", "73"],
      ["What train hobby does Sheldon obsess over?", "Model trains"],
      ["What is Raj unable to do around women early on?", "Speak"],
      ["What is Wil Wheaton famous for within the show?", "Star Trek"],
      ["What is Penny's home state?", "Nebraska"],
      ["What is Amy's field of science?", "Neurobiology"],
      ["What is Bernadette's field of science?", "Microbiology"],
      ["What is Stuart's surname?", "Bloom"],
      ["What instrument does Amy play?", "Harp"],
      ["What is Sheldon's mother's first name?", "Mary"],
      ["What is Howard's mother's first name?", "Debbie"],
      ["What is the apartment across the hall occupied by?", "Penny"],
      ["What game store card game do the group often play?", "Magic: The Gathering"],
      ["What is Sheldon's childhood nickname from his meemaw?", "Moonpie"],
    ]),
  },
  brooklyn_99: {
    400: qa([
      ["What is Holt's first name?", "Raymond"],
      ["What is Amy's favorite kind of organization tool?", "Binders"],
      ["What is Rosa's motorcycle-riding love interest called?", "Pimento"],
      ["What is the annual contest called at the precinct?", "Halloween Heist"],
      ["What city is the precinct in?", "Brooklyn"],
      ["What is Holt's pet corgi called?", "Cheddar"],
      ["What is Boyle's ex-wife called?", "Eleanor"],
      ["What is Jake's father's first name?", "Roger"],
      ["What is Terry's surname?", "Jeffords"],
      ["What is Gina's surname?", "Linetti"],
    ]),
    600: qa([
      ["What is Amy and Jake's son's nickname?", "Mac"],
      ["What is Rosa's first name revealed to be?", "Alicia"],
      ["What is the Vulture's real surname?", "Pembroke"],
      ["What is Kevin's profession?", "Professor"],
      ["What is the Pontiac Bandit's first name?", "Doug"],
      ["What is Scully's first name?", "Norm"],
      ["What is Hitchcock's first name?", "Michael"],
      ["What is Jake's favorite movie franchise?", "Die Hard"],
      ["What is Terry's fantasy novel title?", "Skyfire"],
      ["What is Gina's dance squad called?", "Floorgasm"],
      ["What is Holt's bureaucratic rival's surname?", "Wuntch"],
      ["What is Boyle's adopted son's name?", "Nikolaj"],
      ["What is Amy's maiden surname?", "Santiago"],
    ]),
  },
  the_walking_dead: {
    400: qa([
      ["What is Daryl's brother called?", "Merle"],
      ["What prison becomes the group's base in season 3?", "West Georgia Correctional Facility"],
      ["What is Beth's surname?", "Greene"],
      ["What is the Alexandria leader's surname?", "Monroe"],
      ["What is Carol's daughter called?", "Sophia"],
      ["What is the doctor at Alexandria called?", "Denise"],
      ["What is Rick's best friend from before the outbreak?", "Shane"],
      ["What is the farm owner Hershel's surname?", "Greene"],
      ["What community is ruled by Ezekiel?", "The Kingdom"],
    ]),
    600: qa([
      ["What is Alpha's lieutenant called?", "Beta"],
      ["What is the dump community led by Jadis called?", "The Scavengers"],
      ["What is Maggie's son called?", "Hershel"],
      ["What is the villain group at the pike border called?", "The Whisperers"],
      ["What is the prison governor's real first name?", "Philip"],
      ["What is the museum worker who joins the group later called?", "Yumiko"],
      ["What city hosts the hospital arc in season 5?", "Atlanta"],
      ["What is the Oceanside leader's name?", "Natania"],
      ["What is Negan's bat called?", "Lucille"],
    ]),
  },
  suits: {
    400: qa([
      ["What is Jessica's surname?", "Pearson"],
      ["What is Mike's best friend from his old life called?", "Trevor"],
      ["What is Harvey's therapist's first name?", "Paula"],
      ["What is Rachel's father's surname?", "Zane"],
      ["What city is the firm based in?", "New York"],
    ]),
    600: qa([
      ["What is Alex Williams's role at the firm?", "Senior partner"],
      ["What is Robert Zane's profession?", "Lawyer"],
      ["What is Samantha Wheeler's role at the firm?", "Partner"],
      ["What is Louis's cat called?", "Bruno"],
      ["What college did Rachel attend?", "Columbia"],
      ["What does Louis shout when he is excited?", "You just got Litt up"],
      ["What is Donna's surname?", "Paulsen"],
      ["What is Harvey's mother's first name?", "Lily"],
    ]),
  },
  dexter: {
    400: qa([
      ["What is Dexter's surname?", "Morgan"],
      ["What is Rita's first husband's name?", "Paul"],
      ["What is Dexter's stepdaughter called?", "Astor"],
      ["What is the villain in season 4 nicknamed?", "Trinity Killer"],
      ["What city is Dexter set in?", "Miami"],
      ["What is the nickname of Dexter's kill urge?", "Dark Passenger"],
      ["What is Dexter's son called?", "Harrison"],
    ]),
    600: qa([
      ["What serial killer targets women in season 3's side arc?", "Skinner"],
      ["What killer nicknames himself with prophecy in season 6?", "Doomsday Killer"],
      ["What is Dexter's brother's surname at birth?", "Moser"],
      ["What profession does Dexter work in?", "Blood spatter analyst"],
      ["What is Arthur Mitchell's nickname?", "Trinity Killer"],
      ["What survivor does Dexter help after Jordan Chase's group?", "Lumen"],
      ["What season 8 neuropsychiatrist knows Dexter's past?", "Vogel"],
      ["What box does Dexter store his blood slides in?", "Wooden box"],
      ["What is Masuka's first name?", "Vince"],
      ["What is Dexter's mother's surname?", "Moser"],
      ["What is the vigilante label for Dexter in season 2?", "Bay Harbor Butcher"],
      ["What killer is Brian Moser better known as?", "Ice Truck Killer"],
    ]),
  },
  vikings: {
    400: qa([
      ["What is Ubbe's mother's name?", "Aslaug"],
      ["What is Harald's nickname?", "Finehair"],
      ["What is Floki's wife called?", "Helga"],
      ["What is Ragnar's red-haired son called?", "Sigurd"],
      ["What kingdom is King Ecbert from?", "Wessex"],
      ["What city do Ragnar's forces attack in France?", "Paris"],
      ["What is Bjorn's wife called later in the series?", "Gunnhild"],
      ["What monk becomes Ragnar's close friend?", "Athelstan"],
      ["What is Ivar's mother called?", "Aslaug"],
      ["What is Lagertha's title for part of the series?", "Queen"],
    ]),
    600: qa([
      ["What English kingdom is granted to Viking settlers?", "East Anglia"],
      ["What Rus prince invades Scandinavia?", "Oleg"],
      ["What river do Ragnar's forces sail up to Paris?", "Seine"],
      ["What kingdom does Ubbe dream of settling in?", "North America"],
      ["What is the ritual execution called?", "Blood eagle"],
      ["What is Ragnar's daughter called?", "Gyda"],
      ["What is Ivar's nickname?", "The Boneless"],
    ]),
  },
  the_flash: {
    400: qa([
      ["What is Barry Allen's day job?", "Forensic scientist"],
      ["What is Iris West's profession?", "Journalist"],
      ["What villain uses cold guns?", "Captain Cold"],
      ["What is Joe West's job?", "Detective"],
      ["What city does the Flash protect?", "Central City"],
      ["What is Nora West-Allen's hero name?", "XS"],
      ["What giant gorilla attacks Central City?", "Grodd"],
      ["What scientist creates the Thinking Cap arc?", "DeVoe"],
      ["What villain is also called Bloodwork?", "Ramsey Rosso"],
      ["What is Cisco's hero alias?", "Vibe"],
      ["What mirror villain traps Iris?", "Eva McCulloch"],
      ["What icy identity does Caitlin use?", "Killer Frost"],
      ["What prison houses metahumans in the city?", "Iron Heights"],
    ]),
    600: qa([
      ["What is the first metahuman Barry captures called?", "Clyde Mardon"],
      ["What villain does Savitar really turn out to be?", "Barry's time remnant"],
      ["What speedster takes the name Zoom?", "Hunter Zolomon"],
      ["What Earth is Harry Wells from?", "Earth-2"],
      ["What force opposes the Speed Force in season 7?", "Still Force"],
      ["What headline haunts Barry for years?", "Flash Vanishes in Crisis"],
      ["What is Barry and Iris's daughter from the future called?", "Nora"],
      ["What villain is also Reverse-Flash?", "Eobard Thawne"],
      ["What scientist first merges with Ronnie as Firestorm?", "Martin Stein"],
      ["What villain hunts metas with a lightning-shaped dagger scar?", "Cicada"],
      ["What AI guides Barry from the future in the lab?", "Gideon"],
    ]),
  },
  marvel: {
    600: qa([
      ["What Avengers base is destroyed in Endgame's final act?", "Avengers Compound"],
      ["What is the hidden training refuge in Doctor Strange called?", "Kamar-Taj"],
      ["What alien race does Carol Danvers fight in Captain Marvel?", "Kree"],
      ["What fake TV town traps Wanda in WandaVision?", "Westview"],
      ["What is the undersea nation in Wakanda Forever called?", "Talokan"],
      ["What authority polices timelines in Loki?", "TVA"],
      ["What prison is used for enhanced inmates in Civil War?", "The Raft"],
      ["What is Kamala Khan's superhero name?", "Ms. Marvel"],
    ]),
  },
  dc: {
    400: qa([
      ["What is Batman's real first name?", "Bruce"],
    ]),
    600: qa([
      ["What city does Shazam protect with his foster family?", "Philadelphia"],
      ["What island is Wonder Woman from?", "Themyscira"],
      ["What is Harley Quinn's surname?", "Quinzel"],
      ["What alien metal weakens Superman?", "Kryptonite"],
      ["What city is Arthur Curry tied to on land?", "Amnesty Bay"],
      ["What mercenary leads the team in The Suicide Squad?", "Bloodsport"],
      ["What villain does Robert Pattinson's Batman hunt with ciphers?", "Riddler"],
      ["What shark-headed squad member appears in The Suicide Squad?", "King Shark"],
      ["What country does Black Adam rule?", "Kahndaq"],
    ]),
  },
  star_wars: {
    600: qa([
      ["What order does Ahsoka leave during The Clone Wars?", "Jedi Order"],
      ["What is Grogu called by fans before his name is revealed?", "Baby Yoda"],
      ["What city floats above Bespin?", "Cloud City"],
      ["What desert planet is Rey from?", "Jakku"],
      ["What planet hosts the Death Star plans battle in Rogue One?", "Scarif"],
      ["What clone captain fights beside Ahsoka?", "Rex"],
    ]),
  },
  spider_man: {
    400: qa([
      ["What villain manipulates Peter with drones in Far From Home?", "Mysterio"],
      ["What high school does Peter attend in the MCU?", "Midtown School of Science and Technology"],
      ["What is Miles Morales's uncle's villain name?", "Prowler"],
      ["What newspaper employs Peter in Raimi's films?", "Daily Bugle"],
      ["What are Peter's AI glasses system called?", "E.D.I.T.H."],
      ["What villain is Adrian Toomes better known as?", "Vulture"],
      ["What animated sequel follows Into the Spider-Verse?", "Across the Spider-Verse"],
      ["What fake hero name does Peter use in Europe?", "Night Monkey"],
      ["What villain controls electricity in No Way Home?", "Electro"],
      ["What scientist becomes the Lizard?", "Curt Connors"],
      ["What black-suited rival photographer appears in Spider-Man 3?", "Eddie Brock"],
    ]),
    600: qa([
      ["What charity does Aunt May work with in No Way Home?", "FEAST"],
      ["What machine powers the collider in Into the Spider-Verse?", "Super-collider"],
      ["What is Gwen Stacy's hero persona?", "Spider-Woman"],
      ["What university does Doc Ock work at in Spider-Man 2?", "Columbia"],
      ["What villain in Homecoming is Liz's father?", "Vulture"],
      ["What is MJ's full first name in the MCU?", "Michelle"],
      ["What villain says 'the power of the sun' in Spider-Man 2?", "Doc Ock"],
      ["What monument becomes the final battle site in No Way Home?", "Statue of Liberty"],
      ["What villain's true name is Flint Marko?", "Sandman"],
      ["What animated villain absorbs portals and holes in Across the Spider-Verse?", "The Spot"],
      ["What spider-powered suit does Peter receive in Infinity War?", "Iron Spider"],
      ["What villain is Norman Osborn better known as?", "Green Goblin"],
      ["What is Miles Morales's father's first name?", "Jefferson"],
      ["What multiverse of heroes and villains collides around Miles?", "Spider-Verse"],
      ["What villain in No Way Home is Dr. Curt Connors?", "Lizard"],
    ]),
  },
  invincible: {
    400: qa([
      ["What is Mark Grayson's superhero name?", "Invincible"],
      ["What is Omni-Man's real first name?", "Nolan"],
      ["What is Mark's mother called?", "Debbie"],
      ["What fish-headed Guardians member dies to Omni-Man?", "Aquarus"],
      ["What is Atom Eve's first name?", "Samantha"],
      ["What blue alien keeps returning to Earth for help?", "Allen"],
      ["What demon detective investigates Omni-Man?", "Damien Darkblood"],
      ["What teen hero can duplicate herself?", "Dupli-Kate"],
      ["What alien empire wants Earth?", "Viltrum Empire"],
      ["What speedster hero dies in the massacre?", "Red Rush"],
      ["What is Mark's father better known as?", "Omni-Man"],
    ]),
    600: qa([
      ["What is Robot's new human-name alias?", "Rudy"],
      ["What is Monster Girl's curse side effect?", "She gets younger"],
      ["What planet does Nolan later live on with a new family?", "Thraxa"],
      ["What insectoid world does Mark help defend with Nolan?", "Thraxa"],
      ["What is the half-Viltrumite baby called?", "Oliver"],
      ["What villain builds Reanimen from corpses?", "D.A. Sinclair"],
      ["What empire does Omni-Man secretly serve?", "Viltrum Empire"],
      ["What kaiju-like parasite threat attacks Earth repeatedly?", "Sequids"],
      ["What red-armored Viltrumite woman confronts Mark later on?", "Anissa"],
      ["What is the immortal ruler of Atlantis called?", "Aquarus"],
    ]),
  },
  the_boys: {
    400: qa([
      ["What is Homelander's company called?", "Vought"],
      ["What is Hughie's surname?", "Campbell"],
      ["What is Starlight's real first name?", "Annie"],
      ["What speedster kills Robin in the pilot?", "A-Train"],
      ["What is Butcher's first name?", "Billy"],
      ["What sea-themed Seven member talks to fish?", "The Deep"],
      ["What temporary serum do the Boys use?", "Temp V"],
      ["What is Mother's Milk usually called?", "M.M."],
      ["What pageant hero joins the Seven from Iowa?", "Starlight"],
      ["What is Kimiko's nickname in the team?", "The Female"],
      ["What is Frenchie's first name?", "Serge"],
      ["What giant celebrity supe corporation runs the show?", "Vought"],
    ]),
    600: qa([
      ["What superhero reality show creates Seven candidates?", "American Hero"],
      ["What is Kimiko's surname?", "Miyashiro"],
      ["What is the main celebrity supe team called?", "The Seven"],
      ["What former supe leader returns in season 3?", "Soldier Boy"],
      ["What does Compound V create?", "Superpowers"],
      ["What supe shrinks and explodes a body from within?", "Termite"],
      ["What strategist joins Homelander in season 4?", "Sister Sage"],
      ["What is Butcher's wife called?", "Becca"],
      ["What is Ryan's father called?", "Homelander"],
      ["What media division controls supe branding?", "Vought Studios"],
      ["What is Queen Maeve's public title in the Seven?", "Warrior queen"],
      ["What church-backed supe scandal hits the Deep?", "The Church of the Collective"],
    ]),
  },
  harry_potter: {
    600: qa([
      ["What shop does Ollivander own in Diagon Alley?", "Wand shop"],
    ]),
  },
  lord_rings: {
    600: qa([
      ["What mountain range must the Fellowship cross before Moria?", "Misty Mountains"],
    ]),
  },
  disney: {
    400: qa([
      ["What toy says 'To infinity and beyond'?", "Buzz Lightyear"],
      ["What fish is Nemo's father?", "Marlin"],
      ["What city is Ratatouille set in?", "Paris"],
      ["What number is Lightning McQueen famous for?", "95"],
      ["What kingdom does Elsa rule?", "Arendelle"],
      ["What robot falls in love with EVE?", "WALL-E"],
      ["What Scottish princess is the heroine of Brave?", "Merida"],
      ["What emotion leads Riley's mind first?", "Joy"],
    ]),
    600: qa([
      ["What daycare is the main setting in Toy Story 3?", "Sunnyside"],
      ["What sea witch tricks Ariel?", "Ursula"],
      ["What town do Lightning McQueen's friends live in?", "Radiator Springs"],
      ["What is Boo's real first name in Monsters, Inc.?", "Mary"],
      ["What emperor becomes a llama?", "Kuzco"],
      ["What river spirit horse appears in Frozen II?", "Nokk"],
      ["What planet is WALL-E left to clean?", "Earth"],
      ["What giant bird carries the house in Up?", "Kevin"],
      ["What city do Riley's emotions move to?", "San Francisco"],
      ["What witch turns Merida's mother into a bear?", "The Witch"],
      ["What rat dreams of becoming a chef?", "Remy"],
    ]),
  },
  anime: {
    400: qa([
      ["What city is Eren Yeager from?", "Shiganshina"],
      ["What pirate crew does Luffy captain?", "Straw Hat Pirates"],
      ["What hidden village is Naruto from?", "Leaf Village"],
      ["What school does Deku attend?", "U.A. High"],
    ]),
    600: qa([
      ["What ship do Spike and Jet travel on?", "Bebop"],
      ["What giant robot series stars Shinji Ikari?", "Neon Genesis Evangelion"],
      ["What notebook grants Light Yagami deadly power?", "Death Note"],
      ["What brothers seek their bodies back through alchemy?", "Elric brothers"],
      ["What volleyball anime stars Hinata Shoyo?", "Haikyu!!"],
      ["What assassin family is Killua from?", "Zoldyck family"],
      ["What cursed spirit does Yuji host?", "Sukuna"],
      ["What shinigami partners with Light?", "Ryuk"],
      ["What anime follows Edward and Alphonse Elric?", "Fullmetal Alchemist"],
    ]),
  },
  dragon_ball: {
    400: qa([
      ["What is Goku's Saiyan birth name?", "Kakarot"],
      ["What company does Bulma's family run?", "Capsule Corp"],
      ["What race are Goku and Vegeta?", "Saiyans"],
      ["What attack is Goku famous for?", "Kamehameha"],
      ["What green villain absorbs androids to evolve?", "Cell"],
      ["What is Gohan's wife called?", "Videl"],
      ["What dragon grants wishes when the Dragon Balls are gathered?", "Shenron"],
      ["What tournament often decides Earth's strongest fighters?", "World Martial Arts Tournament"],
    ]),
    600: qa([
      ["What name does Vegeta call Goku by most often?", "Kakarot"],
      ["What form combines Goku and Vegeta with Potara earrings?", "Vegito"],
      ["What is Frieza's father called?", "King Cold"],
      ["What mentor raises Gohan during early Z?", "Piccolo"],
      ["What destroyer god loves pudding?", "Beerus"],
      ["What angel trains Beerus and Goku?", "Whis"],
      ["What android scientist creates Cell?", "Dr. Gero"],
      ["What is the Namekian wish dragon called?", "Porunga"],
      ["What is Trunks's mother called?", "Bulma"],
      ["What form does Gohan unlock in Super Hero?", "Beast"],
      ["What pink villain absorbs fighters in the Buu saga?", "Majin Buu"],
    ]),
  },
  one_piece_show: {
    400: qa([
      ["What is the Straw Hats' ship called?", "Going Merry"],
      ["What is Zoro's dream?", "World's greatest swordsman"],
      ["What is Nami's role on the crew?", "Navigator"],
      ["What sea does Sanji dream of finding?", "All Blue"],
      ["What is Usopp's father's name?", "Yasopp"],
      ["What is Luffy's grandfather's name?", "Garp"],
      ["What restaurant does Sanji work at first?", "Baratie"],
    ]),
    600: qa([
      ["What fish-man pirate enslaves Nami's village?", "Arlong"],
      ["What chef mentor loses a leg and trains Sanji?", "Zeff"],
      ["What clown pirate battles Luffy in Orange Town?", "Buggy"],
      ["What execution platform stands in Loguetown?", "Roger's platform"],
      ["What pirate king's full name inspires Luffy?", "Gol D. Roger"],
      ["What marine captain traps Zoro at Shells Town?", "Morgan"],
      ["What marine officer trains under Garp in the live action?", "Koby"],
      ["What map does Nami want to create?", "A map of the world"],
      ["What fighting style does Sanji use?", "Black Leg"],
      ["What sea where the story starts is called?", "East Blue"],
    ]),
  },
  solo_leveling: {
    400: qa([
      ["What is Sung Jin-Woo's original rank?", "E-rank"],
      ["What system message makes Jin-Woo stronger?", "The System"],
      ["What island raid becomes a major turning point?", "Jeju Island"],
      ["What is Jin-Woo's mother's illness called?", "Eternal slumber"],
      ["What red knight becomes one of his first elite shadows?", "Igris"],
      ["What profession are dungeon fighters called?", "Hunters"],
      ["What color rank is the strongest standard hunter rank?", "S-rank"],
      ["What is Jin-Woo's sister called?", "Jin-Ah"],
      ["What class change does Jin-Woo receive first?", "Necromancer"],
      ["What shadow ant general joins Jin-Woo after Jeju?", "Beru"],
      ["What is Jin-Woo's father called?", "Sung Il-Hwan"],
      ["What daily quest keeps rewarding Jin-Woo?", "Workout quest"],
      ["What title traps Jin-Woo in a deadly tutorial?", "Double dungeon"],
      ["What hidden stat allows Jin-Woo to keep growing?", "Level"],
    ]),
    600: qa([
      ["What true title does Jin-Woo inherit from Ashborn?", "Shadow Monarch"],
      ["What frosty enemy monarch opposes Jin-Woo?", "Frost Monarch"],
      ["What beastly enemy monarch opposes Jin-Woo?", "Beast Monarch"],
      ["What giant stone statue nearly kills Jin-Woo first?", "God Statue"],
      ["What shadow can heal allies with magic?", "Tusk"],
      ["What castle dungeon arc powers Jin-Woo up?", "Demon Castle"],
      ["What demon noble becomes Jin-Woo's ally there?", "Esil"],
      ["What Korean guild master leads the Hunters Guild?", "Choi Jong-In"],
      ["What war between rulers and monarchs drives the story?", "War of the monarchs"],
      ["What shadow soldier was once the Ant King?", "Beru"],
      ["What kingly predecessor chose Jin-Woo as successor?", "Ashborn"],
      ["What crimson knight becomes one of Jin-Woo's earliest elite shadows?", "Igris"],
    ]),
  },
  pokemon: {
    400: qa([
      ["What professor gives Ash his first Pokémon?", "Professor Oak"],
      ["What ball is red and white?", "Poké Ball"],
      ["What stone evolves Pikachu into Raichu?", "Thunder Stone"],
      ["What region does Ash start in?", "Kanto"],
      ["What sleeping giant Normal-type blocks roads?", "Snorlax"],
      ["What water starter evolves into Wartortle?", "Squirtle"],
      ["What grass starter evolves into Ivysaur?", "Bulbasaur"],
      ["What fire starter evolves into Charmeleon?", "Charmander"],
      ["What villainous trio follows Ash constantly?", "Team Rocket"],
      ["What nurse appears in almost every Pokémon Center?", "Nurse Joy"],
      ["What item heals 20 HP in many games?", "Potion"],
      ["What machine stores Pokémon digitally?", "PC"],
      ["What electric rodent is Ash's partner?", "Pikachu"],
      ["What type specialty is Misty known for?", "Water"],
      ["What professor leads Sinnoh research?", "Professor Rowan"],
      ["What role is Brock best known for?", "Gym Leader"],
    ]),
    600: qa([
      ["What item fully revives a fainted Pokémon?", "Max Revive"],
      ["What evolution item turns Eevee into Vaporeon?", "Water Stone"],
      ["What ghostly purple Pokémon is known for a grin?", "Gengar"],
      ["What dragon-like pseudo-legendary begins as Dratini?", "Dragonite"],
      ["What is Red's rival called?", "Blue"],
      ["What bird trio includes Zapdos and Moltres?", "Legendary birds"],
      ["What is the first Pokémon in the National Pokédex?", "Bulbasaur"],
      ["What orange dragon-like evolution follows Charmander?", "Charmeleon"],
      ["What ball is better for bug and water Pokémon?", "Net Ball"],
      ["What fossil Pokémon comes from the Helix Fossil?", "Omanyte"],
      ["What item prevents evolution?", "Everstone"],
      ["What plateau houses the Kanto Elite Four?", "Indigo Plateau"],
      ["What elite trainer title is Cynthia famous for?", "Champion"],
    ]),
  },
  video_games: {
    400: qa([
      ["What company makes the PlayStation?", "Sony"],
      ["What company makes the Xbox?", "Microsoft"],
      ["What plumber stars in Nintendo's flagship series?", "Mario"],
    ]),
    600: qa([
      ["What city does GTA V mainly depict?", "Los Santos"],
      ["What company publishes The Legend of Zelda?", "Nintendo"],
      ["What studio made Elden Ring?", "FromSoftware"],
      ["What franchise features Master Chief?", "Halo"],
      ["What block-building game features Endermen and creepers?", "Minecraft"],
      ["What stealth game stars Agent 47?", "Hitman"],
      ["What series features a hunter named Geralt?", "The Witcher"],
    ]),
  },
  who_footballer: {
    400: who([
      ["Ronaldinho", "Ronaldinho"],
      ["Andres Iniesta", "Andr%C3%A9s_Iniesta"],
      ["Wayne Rooney", "Wayne_Rooney"],
      ["Luis Suarez", "Luis_Su%C3%A1rez"],
      ["Robert Lewandowski", "Robert_Lewandowski"],
      ["Sergio Ramos", "Sergio_Ramos"],
      ["Xavi", "Xavi"],
      ["Andrea Pirlo", "Andrea_Pirlo"],
      ["Arjen Robben", "Arjen_Robben"],
      ["Franck Ribery", "Franck_Rib%C3%A9ry"],
      ["David Villa", "David_Villa"],
      ["Sergio Busquets", "Sergio_Busquets"],
      ["Robin van Persie", "Robin_van_Persie"],
      ["Mesut Ozil", "Mesut_%C3%96zil"],
      ["Javier Mascherano", "Javier_Mascherano"],
      ["Carlos Tevez", "Carlos_T%C3%A9vez"],
      ["Edinson Cavani", "Edinson_Cavani"],
    ]),
    600: who([
      ["Gianluigi Buffon", "Gianluigi_Buffon"],
      ["Clarence Seedorf", "Clarence_Seedorf"],
      ["Javier Zanetti", "Javier_Zanetti"],
      ["Lothar Matthaus", "Lothar_Matth%C3%A4us"],
      ["Roberto Baggio", "Roberto_Baggio"],
      ["Ruud Gullit", "Ruud_Gullit"],
      ["Gheorghe Hagi", "Gheorghe_Hagi"],
      ["Dennis Bergkamp", "Dennis_Bergkamp"],
      ["Michael Laudrup", "Michael_Laudrup"],
      ["Hristo Stoichkov", "Hristo_Stoichkov"],
      ["Pavel Nedved", "Pavel_Nedv%C4%9Bd"],
      ["Roberto Carlos", "Roberto_Carlos"],
      ["Cafu", "Cafu"],
      ["Didier Drogba", "Didier_Drogba"],
      ["Samuel Eto'o", "Samuel_Eto%27o"],
      ["Fabio Cannavaro", "Fabio_Cannavaro"],
      ["Philipp Lahm", "Philipp_Lahm"],
      ["Edgar Davids", "Edgar_Davids"],
      ["Romario", "Rom%C3%A1rio"],
      ["Garrincha", "Garrincha"],
      ["Juan Roman Riquelme", "Juan_Rom%C3%A1n_Riquelme"],
    ]),
  },
  who_tv_character: {
    400: who([
      ["Buffy Summers", "Buffy_Summers"],
    ]),
    600: who([
      ["Omar Little", "Omar_Little"],
      ["Fox Mulder", "Fox_Mulder"],
      ["Dana Scully", "Dana_Scully"],
      ["Villanelle", "Villanelle_(character)"],
      ["Adrian Monk", "Adrian_Monk"],
      ["Moira Rose", "Moira_Rose"],
      ["Veronica Mars", "Veronica_Mars"],
      ["Rust Cohle", "Rust_Cohle"],
      ["Stringer Bell", "Stringer_Bell"],
      ["Tommy Shelby", "Thomas_Shelby"],
      ["Tony Soprano", "Tony_Soprano"],
      ["Saul Berenson", "Saul_Berenson"],
      ["Bender", "Bender_(Futurama)"],
      ["Tyrion Lannister", "Tyrion_Lannister"],
      ["Leslie Knope", "Leslie_Knope"],
    ]),
  },
  who_anime_character: {
    600: who([
      ["Shinji Ikari", "Shinji_Ikari"],
      ["Sailor Moon", "Sailor_Moon"],
      ["Spike Spiegel", "Spike_Spiegel"],
      ["Vash the Stampede", "Vash_the_Stampede"],
      ["Motoko Kusanagi", "Motoko_Kusanagi"],
      ["Hisoka", "Hisoka"],
      ["Satoru Gojo", "Satoru_Gojo"],
    ]),
  },
  who_movie_character: {
    400: who([
      ["Elle Woods", "Elle_Woods"],
    ]),
    600: who([
      ["Anton Chigurh", "Anton_Chigurh"],
      ["Ferris Bueller", "Ferris_Bueller"],
      ["Tyler Durden", "Tyler_Durden"],
      ["Ellen Ripley", "Ellen_Ripley"],
      ["Mia Wallace", "Mia_Wallace"],
      ["Clarice Starling", "Clarice_Starling"],
      ["The Bride", "Beatrix_Kiddo"],
      ["Don Vito Corleone", "Vito_Corleone"],
    ]),
  },
  charades_general: {
    600: charades([
      "alien learns golf",
      "chef drops wedding cake",
      "pirate misses treasure",
      "wizard breaks wand",
      "ninja in traffic",
      "ghost needs coffee",
      "robot loses Wi-Fi",
      "cowboy on rollerblades",
      "teacher forgets lesson",
      "doctor loses patient",
      "vampire hates garlic",
      "astronaut forgets helmet",
      "superhero misses bus",
      "king loses throne",
    ]),
  },
  charades_movies: {
    600: charades([
      "The Social Network",
      "There Will Be Blood",
      "The Grand Budapest Hotel",
      "The Shawshank Redemption",
      "The Silence of the Lambs",
      "The Truman Show",
      "No Country for Old Men",
      "Eternal Sunshine",
      "A Quiet Place",
      "The Hunger Games",
      "Mission Impossible",
      "The Dark Knight",
      "The Wolf of Wall Street",
      "How I Met Your Mother",
      "Only Murders in the Building",
      "The Devil Wears Prada",
    ], "Act this movie or show"),
  },
};

export default TRIVIA_TIER_PARITY_EXPANSIONS;
