const qa = (items) => items.map(([q, a]) => ({ q, a }));
const who = (items) => items.map(([q, a, wiki]) => ({ q, a, wiki }));
const charades = (items, prompt = "Act this out") => items.map((a) => ({ q: prompt, a }));

const QUESTION_MINIMUMS = {
  the_office: {
    200: qa([
      ["What city is the Dunder Mifflin branch in?", "Scranton"],
      ["What crop does Dwight grow on his farm?", "Beets"],
      ["What was the name of Angela's cat that Dwight killed?", "Sprinkles"],
      ["What day does Stanley call the best day of the year?", "Pretzel Day"],
      ["Who briefly replaces Michael Scott after he leaves?", "Deangelo Vickers"],
      ["What is Meredith's last name?", "Palmer"],
    ]),
  },
  stranger_things: {
    200: qa([
      ["What is Hopper's first name?", "Jim"],
      ["What is Max's stepbrother's name?", "Billy Hargrove"],
      ["What ice cream shop do Steve and Robin work at?", "Scoops Ahoy"],
      ["What song helps Max fight Vecna?", "Running Up That Hill"],
      ["What California town do the Byers move to?", "Lenora Hills"],
      ["What is Robin's last name?", "Buckley"],
      ["What roller rink does Eleven get bullied at?", "Rink-O-Mania"],
      ["What newspaper does Nancy work for in season 3?", "The Hawkins Post"],
    ]),
  },
  disney: {
    200: qa([
      ["What is Jasmine's pet tiger's name?", "Rajah"],
      ["What is the snowman's name in Frozen?", "Olaf"],
      ["What is Stitch's experiment number?", "626"],
      ["Who is Belle's father?", "Maurice"],
      ["What is the name of the teacup in Beauty and the Beast?", "Chip"],
      ["Who kills Mufasa?", "Scar"],
      ["What kind of animal is Thumper?", "Rabbit"],
      ["What object does Aladdin rub to summon Genie?", "A magic lamp"],
    ]),
  },
  lord_rings: {
    200: qa([
      ["What race is Gimli?", "Dwarf"],
      ["Who calls the Ring 'my precious'?", "Gollum"],
      ["What creature does Gandalf fight in Moria?", "Balrog"],
      ["What city is defended in the big battle of Return of the King?", "Minas Tirith"],
      ["What land do Frodo and Bilbo sail to at the end?", "The Undying Lands"],
    ]),
  },
  video_games: {
    200: qa([
      ["What company makes PlayStation?", "Sony"],
      ["What exploding hostile mob is found in Minecraft?", "Creeper"],
      ["What city is BioShock set in?", "Rapture"],
      ["What battle royale by Respawn is set in the Titanfall universe?", "Apex Legends"],
      ["Who is Link usually trying to save?", "Princess Zelda"],
      ["What blocky survival game features Steve as its mascot?", "Minecraft"],
    ]),
  },
  anime: {
    200: qa([
      ["What anime follows bounty hunter Spike Spiegel?", "Cowboy Bebop"],
      ["What mecha anime stars Shinji Ikari?", "Neon Genesis Evangelion"],
      ["What energy do ninjas use in Naruto?", "Chakra"],
      ["What sport is central to Haikyuu!!?", "Volleyball"],
      ["What title does Vegeta hold?", "Prince of the Saiyans"],
      ["What is Edward Elric's brother's name?", "Alphonse Elric"],
      ["What pirate cook serves on the Straw Hats?", "Sanji"],
    ]),
  },
  country_facts: {
    200: qa([
      ["This South American country has capital Lima and is home to Machu Picchu", "Peru"],
      ["This Southeast Asian country has capital Phnom Penh and is home to Angkor Wat", "Cambodia"],
      ["This African nation known as the Land of a Thousand Hills has capital Kigali", "Rwanda"],
      ["This Gulf country has capital Muscat", "Oman"],
      ["This Baltic country with capital Tallinn is famous for digital government", "Estonia"],
      ["This Pacific island nation has capital Suva and is famous for rugby", "Fiji"],
    ]),
  },
  songs: {
    200: qa([
      ["A 1985 a-ha track with an iconic animated music video", "Take On Me by a-ha"],
      ["A 1976 Eagles song opening with 'On a dark desert highway'", "Hotel California by Eagles"],
      ["A Michael Jackson song asking 'Annie, are you okay?'", "Smooth Criminal by Michael Jackson"],
      ["A 2011 LMFAO anthem about shuffling every day", "Party Rock Anthem by LMFAO"],
      ["A 2014 Hozier hit comparing love to religion", "Take Me to Church by Hozier"],
      ["A 1995 Oasis singalong asking if you'll be somebody's wonderwall", "Wonderwall by Oasis"],
    ]),
  },
  prison_break: {
    200: qa([
      ["What is Lincoln Burrows' son's name?", "LJ Burrows"],
      ["What is T-Bag's real last name?", "Bagwell"],
      ["Who is the warden of Fox River?", "Henry Pope"],
      ["Who is the vice president tied to the conspiracy?", "Caroline Reynolds"],
      ["What alias does Michael use in Yemen?", "Kaniel Outis"],
      ["Who is Michael and Lincoln's father?", "Aldo Burrows"],
      ["What is the name of the Panamanian prison?", "Sona"],
      ["What organization drives much of the series conspiracy?", "The Company"],
      ["Who becomes Michael's wife?", "Sara Tancredi"],
      ["What is Sucre's girlfriend's name?", "Maricruz"],
      ["What is C-Note's real name?", "Benjamin Miles Franklin"],
      ["Who is the FBI agent hunting the Fox River Eight?", "Alexander Mahone"],
      ["What is T-Bag's son's nickname?", "Whip"],
      ["What is the device holding the Company's secrets called?", "Scylla"],
      ["Who is the villain known as Poseidon?", "Jacob Ness"],
      ["Where is Michael's escape plan hidden?", "In his tattoos"],
      ["What country is Ogygia prison in?", "Yemen"],
      ["What is Brad Bellick's job at Fox River?", "Correctional officer"],
      ["What lawyer and childhood friend tries to clear Lincoln's name?", "Veronica Donovan"],
      ["What alias does T-Bag use at GATE?", "Cole Pfeiffer"],
      ["What is Michael and Lincoln's mother's name?", "Christina Scofield"],
    ]),
  },
  big_bang_theory: {
    200: qa([
      ["What is Leonard's last name?", "Hofstadter"],
      ["What catchphrase does Sheldon say after jokes?", "Bazinga"],
      ["What is Raj's full first name?", "Rajesh"],
      ["What is Howard's last name?", "Wolowitz"],
      ["What is Penny's dream profession at the start?", "Actress"],
      ["What dog belongs to Raj?", "Cinnamon"],
      ["What instrument does Sheldon play during one meltdown?", "Bongos"],
      ["What school did Howard attend?", "MIT"],
      ["What does Raj need in early seasons to talk to women?", "Alcohol"],
      ["What is Howard's mother's first name?", "Debbie"],
      ["What document controls Leonard and Sheldon's apartment life?", "The Roommate Agreement"],
      ["What does Sheldon call his place on the couch?", "My spot"],
      ["What branch of physics does Sheldon study?", "Theoretical physics"],
      ["What branch of physics does Leonard study?", "Experimental physics"],
      ["What field does Raj work in?", "Astrophysics"],
      ["What field does Amy work in?", "Neurobiology"],
      ["What field does Bernadette work in?", "Microbiology"],
      ["What comic book store do the gang often visit?", "The Comic Center of Pasadena"],
      ["What is Bernadette's maiden name?", "Rostenkowski"],
      ["Who wins the Nobel Prize with Sheldon?", "Amy Farrah Fowler"],
      ["What city is the show set in?", "Pasadena"],
    ]),
  },
};

export default QUESTION_MINIMUMS;
Object.assign(QUESTION_MINIMUMS, {
  brooklyn_99: {
    200: qa([
      ["What is Amy's last name?", "Santiago"],
      ["What is Rosa's last name?", "Diaz"],
      ["What is Terry's last name?", "Jeffords"],
      ["What is Gina's last name?", "Linetti"],
      ["What is Charles's last name?", "Boyle"],
      ["What is Captain Holt's first name?", "Raymond"],
      ["Who is Hitchcock's longtime partner?", "Scully"],
      ["What is Holt and Kevin's dog called?", "Cheddar"],
      ["What annual competition does the squad play?", "The Halloween Heist"],
      ["Who is the Pontiac Bandit?", "Doug Judy"],
      ["What movie franchise is Jake obsessed with?", "Die Hard"],
      ["What food does Terry love?", "Yogurt"],
      ["What is Jake's last name?", "Peralta"],
      ["Who does Jake marry?", "Amy Santiago"],
      ["Who is Holt's husband?", "Kevin Cozner"],
      ["What alias does Jake use in Florida?", "Larry Sherbert"],
      ["What job does Rosa do after leaving the force?", "Private investigator"],
      ["What is Charles's ex-wife's name?", "Eleanor"],
      ["What is the Vulture's job?", "Detective"],
      ["Who is Jake's best friend in the precinct?", "Charles Boyle"],
      ["What is Amy obsessed with organizing?", "Binders"],
    ]),
  },
  pokemon: {
    200: qa([
      ["What type is Bulbasaur?", "Grass and Poison"],
      ["What type is Charmander?", "Fire"],
      ["What region is Ash from?", "Kanto"],
      ["Which duo chase Pikachu for Team Rocket?", "Jessie and James"],
      ["What Pokemon was created from Mew's DNA?", "Mewtwo"],
      ["What item evolves Eevee into Jolteon?", "A Thunder Stone"],
      ["What item evolves Eevee into Flareon?", "A Fire Stone"],
      ["What professor studies Pokemon in Johto?", "Professor Elm"],
      ["What sleeping Normal-type Pokemon blocks roads?", "Snorlax"],
      ["What type is Gyarados?", "Water and Flying"],
      ["What fossil Pokemon can be revived from the Helix Fossil?", "Omanyte"],
      ["What is Pikachu's evolved form?", "Raichu"],
      ["What island houses the Pokemon League in Kanto?", "Indigo Plateau"],
      ["What legendary Pokemon controls time?", "Dialga"],
      ["What legendary Pokemon controls space?", "Palkia"],
      ["What trio includes Squirtle, Charmander, and Bulbasaur?", "Kanto starters"],
      ["What type is Jigglypuff?", "Normal and Fairy"],
      ["What Pokemon is known for carrying a bone club?", "Cubone"],
      ["What ball is guaranteed to catch a Pokemon?", "Master Ball"],
      ["What Pokemon can transform into other Pokemon?", "Ditto"],
      ["What Pokemon number in the original Pokedex is Mew?", "151"],
    ]),
  },
  invincible: {
    200: qa([
      ["What is Mark Grayson's superhero name?", "Invincible"],
      ["What is Omni-Man's real first name?", "Nolan"],
      ["What is Mark's mother's name?", "Debbie Grayson"],
      ["What species are Omni-Man and Mark?", "Viltrumites"],
      ["Who is Mark's girlfriend in season 1?", "Amber Bennett"],
      ["What government agency does Cecil run?", "The Global Defense Agency"],
      ["What superhero team is massacred in episode 1?", "The Guardians of the Globe"],
      ["What is Atom Eve's first name?", "Samantha"],
      ["Who is the demon detective investigating Omni-Man?", "Damien Darkblood"],
      ["What is Robot's human original name?", "Rudy Connors"],
      ["What alien race repeatedly invades Earth with time distortion?", "The Flaxans"],
      ["Who is Mark's best friend?", "William Clockwell"],
      ["What is the name of Mark's half-brother?", "Oliver"],
      ["What is the home planet of the Viltrumites?", "Viltrum"],
      ["Who is the warrior princess-style hero on the original Guardians?", "War Woman"],
      ["What is the name of the hero who shrinks and duplicates?", "Dupli-Kate"],
      ["What is the name of the cursed young hero who turns old when she shrinks?", "Monster Girl"],
      ["What alien champion loves fighting strong opponents?", "Battle Beast"],
      ["Who is the martian-like telepath on the original Guardians?", "Martian Man"],
      ["Who is the speedster on the original Guardians?", "Red Rush"],
      ["Who is the fish-man king allied with Cecil?", "Aquarus"],
    ]),
  },
  the_boys: {
    200: qa([
      ["What is Billy Butcher's wife's name?", "Becca Butcher"],
      ["What is Starlight's surname?", "January"],
      ["What is Mother's Milk's first name?", "Marvin"],
      ["What is Kimiko often called by the Boys?", "The Female"],
      ["What company controls The Seven?", "Vought"],
      ["Who is Homelander's son?", "Ryan"],
      ["What event is the infamous superhero orgy called?", "Herogasm"],
      ["What aquatic member of The Seven talks to sea life?", "The Deep"],
      ["What speedster kills Robin in episode 1?", "A-Train"],
      ["What WWII-era supe is brought back in season 3?", "Soldier Boy"],
      ["What temporary superpower serum do Butcher and Hughie use?", "Temp V"],
      ["What is Queen Maeve's first title in the Seven?", "Queen Maeve"],
      ["What is Black Noir known for rarely doing?", "Speaking"],
      ["What is Frenchie's nationality?", "French"],
      ["What is Annie January's superhero name?", "Starlight"],
      ["What is Billy Butcher's first name?", "Billy"],
      ["What secret chemical created superheroes?", "Compound V"],
      ["What anti-supe politician becomes a major target in later seasons?", "Victoria Neuman"],
      ["What is the name of Starlight's ex-boyfriend in season 3?", "Supersonic"],
      ["What was Stormfront originally called decades earlier?", "Liberty"],
      ["What is Hughie's surname?", "Campbell"],
    ]),
  },
  the_flash: {
    200: qa([
      ["Who is Barry Allen's adoptive father figure?", "Joe West"],
      ["What is Iris West's profession for much of the series?", "Journalist"],
      ["What is Barry's father's name?", "Henry Allen"],
      ["What is the source of speedster powers called?", "The Speed Force"],
      ["What is Caitlin Snow's icy alter ego called?", "Killer Frost"],
      ["What is Cisco Ramon's superhero name?", "Vibe"],
      ["Who is Barry's season 1 nemesis?", "Reverse-Flash"],
      ["What is Barry's daughter from the future named?", "Nora West-Allen"],
      ["What timeline event happens when Barry saves his mother?", "Flashpoint"],
      ["What gorilla villain has telepathic powers?", "Gorilla Grodd"],
      ["What speedster villain is Hunter Zolomon?", "Zoom"],
      ["What speedster villain calls himself the god of speed?", "Savitar"],
      ["What is Wally West's hero name?", "Kid Flash"],
      ["What is Barry's job before becoming the Flash?", "Forensic scientist"],
      ["What city does Team Flash protect?", "Central City"],
      ["What is the name of the AI assistant in STAR Labs?", "Gideon"],
      ["What is the Thinker's real name?", "Clifford DeVoe"],
      ["What organization does Joe West work for?", "Central City Police Department"],
      ["What newspaper does Iris eventually help run?", "Central City Citizen"],
      ["What multiverse Earth is Jesse Quick from?", "Earth-2"],
      ["What lab serves as Team Flash's headquarters?", "STAR Labs"],
    ]),
  },
});
Object.assign(QUESTION_MINIMUMS, {
  the_walking_dead: {
    200: qa([
      ["What are zombies usually called in the show?", "Walkers"],
      ["What is Rick Grimes' wife named?", "Lori Grimes"],
      ["What is Rick's son's name?", "Carl Grimes"],
      ["What is Rick's daughter's name?", "Judith"],
      ["What weapon is Daryl known for?", "Crossbow"],
      ["What weapon is Michonne known for?", "Katana"],
      ["What is Glenn's wife named?", "Maggie"],
      ["What community is led by Deanna Monroe?", "Alexandria"],
      ["What community is ruled by Ezekiel?", "The Kingdom"],
      ["What community is led by Gregory and later Maggie?", "Hilltop"],
      ["What is Negan's bat called?", "Lucille"],
      ["What cannibal settlement pretends to be a sanctuary?", "Terminus"],
      ["Who leads the Whisperers?", "Alpha"],
      ["Who is Alpha's giant enforcer?", "Beta"],
      ["Who kills Alpha?", "Negan"],
      ["What was Rick's job before the apocalypse?", "Sheriff's deputy"],
      ["What prison becomes an early safe base?", "West Georgia Correctional Facility"],
      ["What farm owned by Hershel becomes a key refuge?", "Greene family farm"],
      ["What is Carol's daughter's name from early in the series?", "Sophia"],
      ["What is the name of Maggie's father?", "Hershel Greene"],
      ["What symbol is painted by the Wolves?", "W"],
    ]),
  },
  solo_leveling: {
    200: qa([
      ["What is Sung Jin-Woo's sister's name?", "Sung Jinah"],
      ["What is Sung Jin-Woo's mother's name?", "Park Kyung-Hye"],
      ["What is Jin-Woo's father's name?", "Sung Il-Hwan"],
      ["What rank is Jin-Woo at the very start?", "E-rank"],
      ["What is the name of the ant shadow soldier?", "Beru"],
      ["What knight shadow does Jin-Woo first gain from a boss?", "Igris"],
      ["What Korean hunters organization appears constantly in the story?", "The Korean Hunters Association"],
      ["What is the name of the healer S-rank hunter who notices Jin-Woo?", "Cha Hae-In"],
      ["What island raid becomes a national crisis?", "Jeju Island"],
      ["What hidden trap at the start changes Jin-Woo's life?", "The Double Dungeon"],
      ["What mysterious interface helps Jin-Woo level up?", "The System"],
      ["What job do people with powers in Solo Leveling have?", "Hunters"],
      ["What do portals full of monsters appear as?", "Gates"],
      ["What is the title of the power Jin-Woo ultimately inherits?", "Shadow Monarch"],
      ["Who was the previous Shadow Monarch?", "Ashborn"],
      ["What two cosmic factions are fighting?", "The Rulers and the Monarchs"],
      ["What item lets time be turned back near the end?", "The Cup of Reincarnation"],
      ["What is the chairman's name who believes in Jin-Woo early?", "Go Gun-Hee"],
      ["What is the name of Jin-Woo's giant orc shadow?", "Tusk"],
      ["What is the title of the strongest American hunter Jin-Woo defeats?", "Thomas Andre"],
      ["What does Jin-Woo create from fallen enemies?", "Shadow soldiers"],
    ]),
  },
  suits: {
    200: qa([
      ["What is Harvey Specter's first name?", "Harvey"],
      ["What is Mike Ross pretending to have from Harvard?", "A law degree"],
      ["What is Donna's last name?", "Paulsen"],
      ["What is Louis's last name?", "Litt"],
      ["Who is the managing partner at the start?", "Jessica Pearson"],
      ["What is Rachel's last name?", "Zane"],
      ["What is Mike's gift called?", "Photographic memory"],
      ["What law school does the firm obsess over?", "Harvard"],
      ["What is the firm's original name?", "Pearson Hardman"],
      ["Who is Rachel's father?", "Robert Zane"],
      ["Who is Louis's future wife?", "Sheila Sazs"],
      ["What unusual spa activity does Louis love?", "Mudding"],
      ["Who returns repeatedly to try to take over the firm?", "Daniel Hardman"],
      ["What role does Donna eventually become?", "COO"],
      ["What city is Suits set in?", "New York City"],
      ["Who is Harvey's secretary for most of the show?", "Donna"],
      ["What is Katrina's surname?", "Bennett"],
      ["What partner joins from a rival firm late in the series?", "Alex Williams"],
      ["What fierce name partner joins later alongside Alex?", "Samantha Wheeler"],
      ["What sentence sends Mike to prison?", "Pleading guilty to fraud"],
      ["What is Gretchen's job at the firm?", "Secretary"],
    ]),
  },
  dexter: {
    200: qa([
      ["What city is Dexter set in?", "Miami"],
      ["What department does Dexter work for?", "Miami Metro"],
      ["What does Dexter analyze?", "Blood spatter"],
      ["What is Dexter's sister named?", "Debra Morgan"],
      ["What is Dexter's adoptive father's name?", "Harry Morgan"],
      ["What does Dexter call his urge to kill?", "The Dark Passenger"],
      ["What killer is revealed to be Dexter's brother?", "The Ice Truck Killer"],
      ["What is the Ice Truck Killer's real name?", "Brian Moser"],
      ["Who is Dexter's wife?", "Rita Bennett"],
      ["Who kills Rita?", "The Trinity Killer"],
      ["What name does the FBI give Dexter's murder case?", "The Bay Harbor Butcher"],
      ["What material covers Dexter's kill room?", "Plastic wrap"],
      ["What alias does Dexter use in New Blood?", "Jim Lindsay"],
      ["Who ultimately kills Dexter in New Blood?", "Harrison"],
      ["What is Dexter's son's name?", "Harrison"],
      ["Who is the poisoner Dexter falls in love with?", "Hannah McKay"],
      ["Who is the detective who always suspects Dexter?", "Doakes"],
      ["What serial killer dominates season 4?", "Arthur Mitchell / the Trinity Killer"],
      ["Who is Dexter's lieutenant boss who later suspects him?", "LaGuerta"],
      ["What is Dexter's forensic co-worker and eventual rival detective called?", "Quinn"],
      ["What does Harry teach Dexter to follow?", "The Code"],
    ]),
  },
  vikings: {
    200: qa([
      ["What is Ragnar's first wife's name?", "Lagertha"],
      ["Who is Ragnar's eccentric boat-builder friend?", "Floki"],
      ["What monastery does Ragnar raid first?", "Lindisfarne"],
      ["What is Ragnar's brother called?", "Rollo"],
      ["Which son of Ragnar is called Ironside?", "Bjorn"],
      ["Which son of Ragnar is called the Boneless?", "Ivar"],
      ["Who is the monk who becomes close to Ragnar?", "Athelstan"],
      ["What French city do the Vikings besiege?", "Paris"],
      ["What is the Norse afterlife for warriors called?", "Valhalla"],
      ["What brutal execution is associated with Norse vengeance?", "The blood eagle"],
      ["What kingdom in England is ruled by King Ecbert?", "Wessex"],
      ["Who kills Ragnar by throwing him into a pit of snakes?", "King Aelle"],
      ["What huge invasion do Ragnar's sons launch?", "The Great Heathen Army"],
      ["What land does Floki try to settle?", "Iceland"],
      ["What city is the Vikings' home base for much of the show?", "Kattegat"],
      ["Who becomes the first Duke of Normandy?", "Rollo"],
      ["What title is given to women warriors like Lagertha?", "Shieldmaiden"],
      ["Who is Ragnar's second wife?", "Aslaug"],
      ["Who wants to unite all Norway?", "Harald Finehair"],
      ["What is the Norse public assembly called?", "The Thing"],
      ["Which son of Ragnar sails west to new lands late in the story?", "Ubbe"],
    ]),
  },
});
Object.assign(QUESTION_MINIMUMS, {
  one_piece_show: {
    200: qa([
      ["What is the name of Luffy's pirate crew?", "The Straw Hat Pirates"],
      ["What fruit gives Luffy his rubber powers?", "The Gomu Gomu no Mi"],
      ["Who is the Straw Hats' swordsman?", "Roronoa Zoro"],
      ["Who is the Straw Hats' navigator?", "Nami"],
      ["Who is the Straw Hats' cook?", "Sanji"],
      ["Who is the Straw Hats' doctor?", "Tony Tony Chopper"],
      ["Who is the Straw Hats' archaeologist?", "Nico Robin"],
      ["Who is the Straw Hats' shipwright?", "Franky"],
      ["Who is the Straw Hats' musician?", "Brook"],
      ["What dangerous sea holds the One Piece?", "The Grand Line"],
      ["What are mysterious fruits that grant powers called?", "Devil Fruits"],
      ["What power system includes Observation and Armament?", "Haki"],
      ["What title is given to the four strongest pirates?", "The Yonko"],
      ["What ship do the Straw Hats use after the Going Merry?", "The Thousand Sunny"],
      ["What is the lost century called?", "The Void Century"],
      ["What stones record the ancient history?", "Poneglyphs"],
      ["What island lies at the end of the Grand Line?", "Laugh Tale"],
      ["What hidden true model is Luffy's fruit?", "Hito Hito no Mi, Model: Nika"],
      ["What is the World Government's hidden ruler called?", "Im"],
      ["Who inspired Luffy by giving him the straw hat?", "Shanks"],
      ["What is Zoro's dream?", "To become the world's greatest swordsman"],
    ]),
  },
  dragon_ball: {
    200: qa([
      ["What race are Goku and Vegeta?", "Saiyans"],
      ["What is Goku's signature attack?", "Kamehameha"],
      ["How many Dragon Balls summon Shenron?", "7"],
      ["What is Goku's oldest son's name?", "Gohan"],
      ["What is Goku's rival prince called?", "Vegeta"],
      ["Who is the Namekian mentor of Gohan?", "Piccolo"],
      ["What galactic tyrant destroys Planet Vegeta?", "Frieza"],
      ["What android marries Krillin?", "Android 18"],
      ["What room lets fighters train for a year in a day?", "The Hyperbolic Time Chamber"],
      ["What wish-granting dragon appears on Earth?", "Shenron"],
      ["What company is run by Bulma's family?", "Capsule Corporation"],
      ["What transformation first appears against Frieza?", "Super Saiyan"],
      ["What monster holds the Cell Games?", "Cell"],
      ["What pink magical villain dominates the Buu Saga?", "Majin Buu"],
      ["What fusion dance combines two warriors?", "Fusion Dance"],
      ["What earring method also fuses two warriors?", "Potara Fusion"],
      ["What god of destruction loves food and naps?", "Beerus"],
      ["What tournament risks entire universes in Dragon Ball Super?", "The Tournament of Power"],
      ["What godly state lets Goku move without thinking?", "Ultra Instinct"],
      ["What childlike ruler can erase universes?", "Zeno"],
      ["What Saiyan power-up happens after recovering from near death?", "Zenkai boost"],
    ]),
  },
  spider_man: {
    200: qa([
      ["What is Spider-Man's real name?", "Peter Parker"],
      ["Who raised Peter after his parents died?", "Aunt May and Uncle Ben"],
      ["What newspaper does Peter work for?", "The Daily Bugle"],
      ["Who runs the Daily Bugle?", "J. Jonah Jameson"],
      ["What villain is Norman Osborn?", "The Green Goblin"],
      ["What villain is Otto Octavius?", "Doctor Octopus"],
      ["Who is Peter's red-haired love interest?", "Mary Jane Watson"],
      ["Who is Peter's first great love in comics?", "Gwen Stacy"],
      ["What borough is Peter Parker from?", "Queens"],
      ["What team of villains often unite against Spider-Man?", "The Sinister Six"],
      ["Who becomes Venom?", "Eddie Brock"],
      ["What villain is Quentin Beck?", "Mysterio"],
      ["Who is Miles Morales?", "Another Spider-Man"],
      ["Who is Aaron Davis in Spider-Man stories?", "The Prowler"],
      ["What black alien costume changes Peter's behavior?", "The symbiote suit"],
      ["What quote defines Spider-Man's life?", "With great power comes great responsibility"],
      ["Who is the futuristic Spider-Man of 2099?", "Miguel O'Hara"],
      ["What mob boss often opposes Spider-Man and Daredevil?", "Kingpin"],
      ["What device does Peter usually invent to shoot webs?", "Web-shooters"],
      ["What multiverse concept links many Spider heroes?", "The Spider-Verse"],
      ["What event is famous for the death of Gwen Stacy?", "The Night Gwen Stacy Died"],
    ]),
  },
  who_footballer: {
    200: who([
      ["Spanish midfield genius from Barcelona, won the World Cup and scored in the 2010 final", "Andres Iniesta", "Andres_Iniesta"],
      ["Spanish defender with a warrior beard, captained Real Madrid and scored huge headers", "Sergio Ramos", "Sergio_Ramos"],
      ["French striker who won the Ballon d'Or after leading Real Madrid's attack", "Karim Benzema", "Karim_Benzema"],
      ["English forward, Manchester United legend, all-time scorer for club and country for years", "Wayne Rooney", "Wayne_Rooney"],
      ["Portuguese-born Benfica legend, one of the greatest scorers ever, nicknamed the Black Panther", "Eusebio", "Eusebio"],
      ["English World Cup-winning legend, Manchester United icon, known as Sir Bobby", "Bobby Charlton", "Bobby_Charlton"],
      ["Italian playmaker with a ponytail, famous for his penalty miss in the 1994 World Cup final", "Roberto Baggio", "Roberto_Baggio"],
      ["Brazilian right-back and 2002 World Cup winner, captain of AC Milan and Brazil", "Cafu", "Cafu"],
      ["Dutch superstar with dreadlocks, Ballon d'Or winner, starred for Milan and Chelsea", "Ruud Gullit", "Ruud_Gullit"],
      ["Dutch Arsenal legend known for sublime control and elegant finishing", "Dennis Bergkamp", "Dennis_Bergkamp"],
      ["Dutch striker who scored endlessly for Manchester United and Real Madrid", "Ruud van Nistelrooy", "Ruud_van_Nistelrooy"],
      ["Spanish midfield controller turned elite coach, starred for Liverpool, Real Madrid, and Spain", "Xabi Alonso", "Xabi_Alonso"],
      ["Dutch winger famous for cutting inside onto his left foot from the right wing", "Arjen Robben", "Arjen_Robben"],
      ["Spanish holding midfielder, Barcelona icon, master of positioning and calmness", "Sergio Busquets", "Sergio_Busquets"],
    ]),
  },
  who_tv_character: {
    200: who([
      ["I am the radio psychiatrist who moved from Cheers to lead my own Seattle sitcom", "Frasier Crane", "Frasier_Crane"],
      ["I am the advertising genius at the center of Mad Men", "Don Draper", "Don_Draper"],
      ["I am the shotgun-toting stickup man from The Wire with a code of my own", "Omar Little", "Omar_Little"],
      ["I am the razor-sharp gang leader of Peaky Blinders", "Tommy Shelby", "Tommy_Shelby"],
      ["I am the detective from Law & Order: SVU played by Mariska Hargitay", "Olivia Benson", "Olivia_Benson"],
      ["Everybody lies. I am the cynical medical genius Dr. House", "Gregory House", "Gregory_House"],
      ["I am the ambitious secretary-turned-copywriter from Mad Men", "Peggy Olson", "Peggy_Olson"],
      ["I am the queen bee of Gossip Girl with impeccable fashion and schemes", "Blair Waldorf", "Blair_Waldorf"],
      ["I am the teenage private investigator from Neptune, California", "Veronica Mars", "Veronica_Mars"],
      ["I am the over-the-top matriarch with wigs and wine from Schitt's Creek", "Moira Rose", "Moira_Rose"],
      ["I am the obsessive detective with countless phobias from Monk", "Adrian Monk", "Adrian_Monk"],
    ]),
  },
  who_anime_character: {
    200: who([
      ["I am the red-coated gunman from Trigun with a giant bounty on my head", "Vash the Stampede", "Vash_the_Stampede"],
      ["I am the quiet blue-haired pilot of EVA Unit-00", "Rei Ayanami", "Rei_Ayanami"],
      ["I am the cybernetic major from Ghost in the Shell", "Motoko Kusanagi", "Motoko_Kusanagi"],
      ["It's time to duel. I solve games and wield the Millennium Puzzle", "Yugi Muto", "Yugi_Muto"],
      ["I am Yugi's rich rival who loves Blue-Eyes White Dragon", "Seto Kaiba", "Seto_Kaiba"],
      ["I am the brilliant inventor and mother of Trunks in Dragon Ball", "Bulma", "Bulma"],
      ["I am the cigarette-loving Straw Hat cook in a black suit", "Sanji", "Sanji_(One_Piece)"],
      ["I am the samurai parody hero with silver hair from Gintama", "Gintoki Sakata", "Gintoki_Sakata"],
      ["I was reincarnated as a slime and built my own nation", "Rimuru Tempest", "Rimuru_Tempest"],
      ["I am the laid-back bounty hunter from Cowboy Bebop", "Spike Spiegel", "Spike_Spiegel"],
      ["I am the fiery shrine maiden Sailor Scout with attack powers from Mars", "Sailor Mars", "Sailor_Mars"],
    ]),
  },
  who_movie_character: {
    200: who([
      ["Say hello to my little friend. I am the cocaine king of Scarface", "Tony Montana", "Tony_Montana"],
      ["You talkin' to me? I am the unstable cab driver from Taxi Driver", "Travis Bickle", "Travis_Bickle"],
      ["I click my ruby slippers and dream of returning to Kansas", "Dorothy Gale", "Dorothy_Gale"],
      ["I own a chocolate factory and love golden tickets", "Willy Wonka", "Willy_Wonka"],
      ["I fake being sick to skip school in 1980s Chicago", "Ferris Bueller", "Ferris_Bueller"],
      ["I am the Wall Street killer obsessed with Huey Lewis and business cards", "Patrick Bateman", "Patrick_Bateman"],
      ["I am the wide-eyed waitress from Paris in Amelie", "Amelie Poulain", "Amelie_Poulain"],
      ["I am the leather-clad ally of Neo in The Matrix", "Trinity", "Trinity_(The_Matrix)"],
      ["I am the lion villain with a scar and a murderous plan to take Pride Rock", "Scar", "Scar_(The_Lion_King)"],
      ["I am the survivor and mother at the heart of the Terminator films", "Sarah Connor", "Sarah_Connor_(Terminator)"],
      ["I am the split-personality anarchist of Fight Club", "Tyler Durden", "Tyler_Durden"],
    ]),
  },
});
Object.assign(QUESTION_MINIMUMS, {
  big_bang_theory: {
    ...QUESTION_MINIMUMS.big_bang_theory,
    400: [...(QUESTION_MINIMUMS.big_bang_theory?.[400] || []), ...qa([
      ["What is the name of Howard and Bernadette's daughter?", "Halley"],
      ["What is the name of Howard and Bernadette's son?", "Neil Michael"],
      ["What fantasy card game does the gang obsess over?", "Mystic Warlords of Ka'a"],
      ["What is Sheldon's mother's first name?", "Mary"],
      ["What field of science makes Bernadette wealthy?", "Pharmaceutical microbiology"],
    ])],
  },
  brooklyn_99: {
    ...QUESTION_MINIMUMS.brooklyn_99,
    400: [...(QUESTION_MINIMUMS.brooklyn_99?.[400] || []), ...qa([
      ["What borough does the Nine-Nine serve?", "Brooklyn"],
      ["What is Jake and Amy's son named?", "Mac"],
      ["What does Gina call her fanbase?", "The G-Hive"],
      ["What rank does Raymond Holt hold at the start of the series?", "Captain"],
    ])],
  },
  the_boys: {
    ...QUESTION_MINIMUMS.the_boys,
    400: [...(QUESTION_MINIMUMS.the_boys?.[400] || []), ...qa([
      ["What invisible member of the Seven does Butcher's team capture first?", "Translucent"],
      ["What university becomes the focus of Gen V and trains young supes?", "Godolkin University"],
      ["What is Queen Maeve's real name?", "Maggie Shaw"],
      ["What dog is Billy Butcher known for loving in The Boys comics?", "Terror"],
      ["What Payback member uses an explosive energy blast and red costume?", "Crimson Countess"],
    ])],
  },
  the_flash: {
    ...QUESTION_MINIMUMS.the_flash,
    400: [...(QUESTION_MINIMUMS.the_flash?.[400] || []), ...qa([
      ["What hidden STAR Labs prison holds many captured metahumans?", "The Pipeline"],
      ["Who becomes the stretchy hero Elongated Man?", "Ralph Dibny"],
      ["What is Cisco Ramon's brother named?", "Dante Ramon"],
      ["What speedster from Earth-2 becomes Barry's ally and Wally's love interest?", "Jesse Quick"],
    ])],
  },
  the_walking_dead: {
    ...QUESTION_MINIMUMS.the_walking_dead,
    400: [...(QUESTION_MINIMUMS.the_walking_dead?.[400] || []), ...qa([
      ["What tiger accompanies King Ezekiel?", "Shiva"],
      ["What scientist appears at the CDC in season 1?", "Edwin Jenner"],
      ["What is Daryl Dixon's brother's name?", "Merle Dixon"],
      ["What junkyard group is led by Jadis?", "The Scavengers"],
      ["What is the name of the Saviors' home base?", "The Sanctuary"],
    ])],
  },
  solo_leveling: {
    ...QUESTION_MINIMUMS.solo_leveling,
    400: [...(QUESTION_MINIMUMS.solo_leveling?.[400] || []), ...qa([
      ["What rank hunter is Cha Hae-In?", "S-rank"],
      ["What guild master can transform into a white tiger beast form?", "Baek Yoonho"],
      ["What Korean S-rank healer dies during the Jeju Island operation?", "Min Byung-Gyu"],
      ["What title is Jin-Woo mocked with before becoming powerful?", "The world's weakest hunter"],
    ])],
  },
  suits: {
    ...QUESTION_MINIMUMS.suits,
    400: [...(QUESTION_MINIMUMS.suits?.[400] || []), ...qa([
      ["What therapist helps Harvey confront his panic attacks?", "Paula Agard"],
      ["What exam does Mike never take before secretly practicing law?", "The bar exam"],
      ["What city does Jessica move into politics in after leaving the firm?", "Chicago"],
      ["What role does Mike eventually become legitimately after prison?", "Lawyer"],
      ["What law school does Louis constantly revere because of the firm's hiring obsession?", "Harvard Law School"],
    ])],
  },
  dexter: {
    ...QUESTION_MINIMUMS.dexter,
    400: [...(QUESTION_MINIMUMS.dexter?.[400] || []), ...qa([
      ["What are Rita's two children named?", "Astor and Cody"],
      ["What is Batista's first name?", "Angel"],
      ["What job does Dexter take after faking his death in the original finale?", "Lumberjack"],
      ["What is the name of the truck stop serial killer in New Blood?", "Kurt Caldwell"],
      ["What is Harrison's mother's name?", "Rita"],
    ])],
  },
  vikings: {
    ...QUESTION_MINIMUMS.vikings,
    400: [...(QUESTION_MINIMUMS.vikings?.[400] || []), ...qa([
      ["Which son of Ragnar struggles with faith and later converts to Christianity?", "Hvitserk"],
      ["Who is the Rus prince and major late-series villain?", "Oleg of Novgorod"],
      ["What is Bjorn's famous nickname?", "Ironside"],
      ["What title does Lagertha eventually hold after ruling Kattegat?", "Queen"],
    ])],
  },
  one_piece_show: {
    ...QUESTION_MINIMUMS.one_piece_show,
    400: [...(QUESTION_MINIMUMS.one_piece_show?.[400] || []), ...qa([
      ["Who is Luffy's grandfather and legendary Marine hero?", "Monkey D. Garp"],
      ["What prison must be infiltrated to save Ace?", "Impel Down"],
      ["Who is the fleet admiral known as Akainu?", "Sakazuki"],
      ["What sea restaurant is where Sanji first joins the crew?", "Baratie"],
    ])],
  },
  dragon_ball: {
    ...QUESTION_MINIMUMS.dragon_ball,
    400: [...(QUESTION_MINIMUMS.dragon_ball?.[400] || []), ...qa([
      ["What is Goku's Saiyan birth name?", "Kakarot"],
      ["What fusion of Goku and Vegeta uses the Potara earrings?", "Vegito"],
      ["What fusion of Goku and Vegeta uses the Fusion Dance?", "Gogeta"],
      ["What guardian originally creates Earth's Dragon Balls?", "Kami"],
    ])],
  },
  spider_man: {
    ...QUESTION_MINIMUMS.spider_man,
    400: [...(QUESTION_MINIMUMS.spider_man?.[400] || []), ...qa([
      ["What villain is Adrian Toomes?", "The Vulture"],
      ["What cat burglar often becomes Peter's ally and love interest?", "Black Cat"],
      ["What clone identity of Peter Parker is also called the Scarlet Spider?", "Ben Reilly"],
      ["What police captain is Gwen Stacy's father?", "George Stacy"],
      ["What school does Peter Parker famously attend in many versions?", "Midtown High School"],
      ["What villain identity does Mac Gargan adopt?", "Scorpion"],
    ])],
  },
  who_anime_character: {
    ...QUESTION_MINIMUMS.who_anime_character,
    400: [...(QUESTION_MINIMUMS.who_anime_character?.[400] || []), ...who([
      ["I pilot Eva Unit-01 and spend much of my story trying not to run away", "Shinji Ikari", "Shinji_Ikari"],
      ["I capture Clow Cards, skate through battles, and everyone knows me as Cardcaptor Sakura", "Sakura Kinomoto", "Sakura_Kinomoto"],
      ["I switch between martial arts chaos and cursed transformations in a Chinese training spring storyline", "Ranma Saotome", "Ranma_Saotome"],
      ["I wield Excalibur as the iconic servant of Fate/stay night", "Saber", "Saber_(Fate)"],
    ])],
  },
  who_movie_character: {
    ...QUESTION_MINIMUMS.who_movie_character,
    400: [...(QUESTION_MINIMUMS.who_movie_character?.[400] || []), ...who([
      ["I rule North Shore High, wear pink, and everyone in Mean Girls fears me", "Regina George", "Regina_George"],
      ["I am the ogre princess who can handle herself far better than any fairy-tale damsel", "Princess Fiona", "Princess_Fiona"],
      ["I am the mohawked hacker-survivor from The Girl with the Dragon Tattoo", "Lisbeth Salander", "Lisbeth_Salander"],
      ["I fake insanity, battle Nurse Ratched, and become the soul of One Flew Over the Cuckoo's Nest", "Randle McMurphy", "Randle_McMurphy"],
    ])],
  },
});
Object.assign(QUESTION_MINIMUMS, {
  charades_general: {
    200: charades([
      "putting on sunscreen at the beach",
      "trying to catch a mosquito in your room",
      "building flat-pack furniture",
      "getting shampoo in your eyes",
      "trying to unlock your phone with wet hands",
      "carrying too many grocery bags at once",
      "chasing a runaway balloon",
      "trying to untangle headphones",
      "filling a car with gas for the first time",
      "burning your tongue on hot coffee",
      "trying to fold a fitted sheet",
      "swatting at a fly during dinner",
      "painting a wall and stepping in the tray",
      "testing if rain has started outside",
      "sneaking snacks into a movie theater",
      "trying to parallel park while someone watches",
      "using chopsticks for the first time",
      "getting locked out of your house",
      "taking a group selfie that keeps failing",
      "walking on sand with shoes full of pebbles",
      "trying not to laugh in class",
      "putting in contact lenses for the first time",
      "getting your hoodie stuck while taking it off",
      "struggling to open an umbrella in the wind",
    ]),
    400: charades([
      "being the last person alive in a game of hide and seek",
      "a waiter dropping an entire tray of drinks",
      "trying to act normal after tripping in public",
      "a tourist completely lost in a new city",
      "someone realizing their mic was on the whole time",
      "winning an argument in the shower hours later",
      "getting caught singing dramatically in the car",
      "a lifeguard spotting trouble from far away",
      "trying to assemble a tent with missing instructions",
      "an airport passenger hearing final boarding call",
      "realizing your phone is slipping into the toilet",
      "a student bluffing through a presentation they didn't prepare",
      "trying to catch a glass before it falls",
      "a chef pretending the burned dish was intentional",
      "someone discovering they sat on wet paint",
      "being on hold with customer service forever",
      "trying to walk calmly after stubbing your toe",
      "someone pretending they understand modern art",
      "a referee making a dramatic bad call",
      "an office worker trying not to sneeze in silence",
      "a parent stepping on toys in the dark",
      "someone finding a spider in the shower",
      "a dog owner being pulled by an excited dog",
      "a gamer losing on the final level",
    ]),
    600: charades([
      "an alien trying to understand how humans order food",
      "a medieval knight using modern technology for the first time",
      "a superhero with powers that keep glitching",
      "a detective interrogating a very suspicious penguin",
      "a fashion model stuck in quicksand",
      "a zombie trying to fit into normal office life",
      "a dragon attempting to blow out birthday candles",
      "a secret agent whose cover is falling apart mid-mission",
      "a pirate trying to use GPS instead of a treasure map",
      "a horror movie victim hearing a strange noise upstairs",
      "a time traveler trying to explain the internet to cavemen",
      "a villain giving a speech before slipping on a banana peel",
      "a wizard whose wand only works at the worst moments",
      "an astronaut realizing something is floating loose in the station",
      "a game show host revealing the worst possible prize",
      "a movie stunt double trying to look cool after a failed jump",
      "a spy disguising themselves badly at a fancy gala",
      "a superhero team arguing about who gets the credit",
      "a treasure hunter triggering every trap in the temple",
      "a reality TV contestant overreacting to being eliminated",
      "a sorcerer summoning the wrong creature entirely",
      "a king trying to sit on a painfully uncomfortable throne",
      "a mad scientist presenting a machine that instantly explodes",
      "a heist crew realizing they forgot the actual bag for the money",
    ]),
  },
  charades_movies: {
    200: charades([
      "Jurassic Park",
      "Back to the Future",
      "Home Alone",
      "Aladdin",
      "Coco",
      "The Mask",
      "Jaws",
      "Cars",
      "Monsters, Inc.",
      "E.T. the Extra-Terrestrial",
      "The Little Mermaid",
      "Kung Fu Panda",
      "Despicable Me",
      "The Karate Kid",
      "Frozen II",
      "Wreck-It Ralph",
      "Moana",
      "Up",
      "The Jungle Book",
      "Zootopia",
      "How to Train Your Dragon",
      "Ratatouille",
      "Spider-Man: Homecoming",
      "The Lego Movie",
    ], "Act this movie or show"),
    400: charades([
      "Breaking Bad",
      "Game of Thrones",
      "Stranger Things",
      "The Office",
      "Friends",
      "The Walking Dead",
      "The Mandalorian",
      "Avatar: The Last Airbender",
      "The Lord of the Rings",
      "The Wizard of Oz",
      "Mission: Impossible",
      "The Wolf of Wall Street",
      "Shutter Island",
      "The Truman Show",
      "Mean Girls",
      "The Devil Wears Prada",
      "Doctor Strange",
      "Black Panther",
      "Deadpool",
      "The Hunger Games: Catching Fire",
      "Guardians of the Galaxy",
      "The Simpsons",
      "Brooklyn Nine-Nine",
      "Squid Game",
    ], "Act this movie or show"),
    600: charades([
      "Nope",
      "Get Out",
      "Parasite",
      "Whiplash",
      "There Will Be Blood",
      "The Grand Budapest Hotel",
      "Everything Everywhere All at Once",
      "The Banshees of Inisherin",
      "The Revenant",
      "Blade Runner 2049",
      "A Clockwork Orange",
      "Inglourious Basterds",
      "Oldboy",
      "Prisoners",
      "Arrival",
      "Memento",
      "Black Mirror",
      "True Detective",
      "Peaky Blinders",
      "Better Call Saul",
      "The Last of Us",
      "Succession",
      "House of the Dragon",
      "Mindhunter",
    ], "Act this movie or show"),
  },
});
